### ISSUE TITLE
Improve missing test count in Table A-7-2 Displays

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1019]
The table A-7-2 Outcomes appear to be correct (EVAP is correctly no longer missing), but the text message will be difficult to interpret.

32 is not the number of missing results... it is the number of accepted FMIs.  Let’s find better grammar.

One sensor was missing 1 FMI; the other, 2 FMIs.
Adding the count of missing FMIs would improve the messages below.

FAIL: 6.1.12.2.a (A7.2.a) - Engine Exhaust Sensor is missing required Test Result, 32 of: 3217:0, 3217:1, 3217:2, 3217:3, 3217:4, 3217:5, 3217:6, 3217:7, 3217:8, 3217:9, 3217:10, 3217:11, 3217:12, 3217:13, 3217:14, 3217:15, 3217:16, 3217:17, 3217:18, 3217:19, 3217:20, 3217:21, 3217:22, 3217:23, 3217:24, 3217:25, 3217:26, 3217:27, 3217:28, 3217:29, 3217:30, 3217:31
FAIL: 6.1.12.2.a (A7.2.a) - Engine Exhaust Sensor is missing required Test Result, 32 of: 3227:0, 3227:1, 3227:2, 3227:3, 3227:4, 3227:5, 3227:6, 3227:7, 3227:8, 3227:9, 3227:10, 3227:11, 3227:12, 3227:13, 3227:14, 3227:15, 3227:16, 3227:17, 3227:18, 3227:19, 3227:20, 3227:21, 3227:22, 3227:23, 3227:24, 3227:25, 3227:26, 3227:27, 3227:28, 3227:29, 3227:30, 3227:31
FAIL: 6.1.12.2.a (A7.2.a) - Fuel System Monitor is missing required Test Result, 4 of: 651:3, 651:4, 651:5, 6575:2

**Comment by gumbelmj** [comment]
We found the same issue simultaneously.  I created #1020 to fix this

**Comment by ericthomasswenson** [comment]
That should be fine ... Nice of Bob to have done the retest ... so soon.

I think I rechecked all the posted issues from Bob’s previous PSI test.  Have a look at the screen shot Bob sent.  It’s apparently related to the test 26 observation... that did get fixed.
