### ISSUE TITLE
Correct SP 2848, NAME detected as NA

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1027]
FAIL: 6.1.26.6.a - SPN 2848(ECU Name) was received as NOT AVAILABLE from Engine #1 (0)

SPN 2848 configured appropriately for Data Stream support.
Valid response received for SPN 2848 from Source Address 0(ECU)

**Comment by ericthomasswenson** [comment]
Data forwarded to J1939-84 as pictures don’t paste well.

**Comment by gumbelmj** [comment]
This issue should have been resolved with #1015 which was included in release 3.0.11. Can you re-test with the latest version and see if this issues remains?

**Comment by ericthomasswenson** [comment]
Review with 3.1

**Comment by ericthomasswenson** [comment]
J1939-84 Tool version 3.1.0 - 2022/04/12 10:03
Generated: 2022/04/12 14:46:04.1410
Log File Name: C:\CdriveSave\new j1939-84\v310 E39_2.j1939tools-84

Start Test 1.1 - Test vehicle data collection
Initial Engine Speed = 0.0 RPMs
Final Engine Speed = 0.0 RPMs
14:31:26.7552 Global Global Request for Address Claim Request
14:31:26.7598 18EAFFF9 [3] 00 EE 00 (TX)
14:31:26.7601 18EEFF00 [8] 00 00 40 05 00 00 00 00
Engine #1 (0) reported as: {
  Industry Group: Global
  Vehicle System: Non-specific System, System Instance: 0
  Function: Engine, Functional Instance: 0, ECU Instance: 0
  Manufactured by: International Truck and Engine Corporation - Engine Electronics, Identity Number: 0
  Is not arbitrary address capable.

Not queried in 6.1.26.


J1939-84 Tool version 3.0.13 - 2021/09/19 10:53
Generated: 2022/04/11 17:22:10.5883
Log File Name: C:\referenceInfo\test\Eldebrink_2022_04_11\PVE-L1\pve-L1Try2.j1939-84

16:34:17.9578 DS Request for PGN 60928 to Engine #1 (0) for SPNs 2848
16:34:17.9606 18EA00F9 [3] 00 EE 00 (TX)
16:34:17.9733 18EEFF00 [8] 08 7C 64 05 00 00 00 00
Engine #1 (0) reported as: {
  Industry Group: Global
  Vehicle System: Non-specific System, System Instance: 0
  Function: Engine, Functional Instance: 0, ECU Instance: 0
  Manufactured by: International Truck and Engine Corporation - Vehicle Electronics, Identity Number: 293896
  Is not arbitrary address capable.
}

16:36:13.2090 DS Request for PGN 60928 to Engine #1 (0) for SPNs 2848
16:36:13.2129 18EA00F9 [3] 00 EE 00 (TX)
16:36:13.2197 18EEFF00 [8] 08 7C 64 05 00 00 00 00
Engine #1 (0) reported as: {
  Industry Group: Global
  Vehicle System: Non-specific System, System Instance: 0
  Function: Engine, Functional Instance: 0, ECU Instance: 0
  Manufactured by: International Truck and Engine Corporation - Vehicle Electronics, Identity Number: 293896
  Is not arbitrary address capable.
}

**Comment by ericthomasswenson** [comment]
2848* Name of Controller Application 60928 In Table A-1 (Balloted, 3.0.13)

2848 (16) | Name of Controller Application | 60928 (SOW)

Failure not observed in 3.0.13

6.1.26 query not observed in 3.1.0

**Comment by battjt** [comment]
6.1.26 rewritten.
