### ISSUE TITLE
No Failure message for null ESN

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1028]
As observed on 3.0.9, Failure message(s) missing for a null ESN

Start Test 1.9 - Component ID: Make

13:33:49.8338 Destination Specific Component Identification Request to Engine #1 (0)
13:33:49.8363 18EA00F9 [3] EB FE 00 (TX)
13:33:49.9493 18FEEB00 [39] 44 54 44 53 43 2A 39 33 36 4E 31 36 2A 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2A 20 20 20 20 20 20 20 20 20 20 2A
Component Identification from Engine #1 (0): {
  Make: DTDSC
  Model: 936N16
  Serial: 
  Unit: 
}

Is this also addressed by #1015

**Comment by gumbelmj** [comment]
No it is not

Matt

On Jun 5, 2021, at 10:02, ericthomasswenson ***@***.***> wrote:

﻿
Start Test 1.9 - Component ID: Make

13:33:49.8338 Destination Specific Component Identification Request to Engine #1 (0)
13:33:49.8363 18EA00F9 [3] EB FE 00 (TX)
13:33:49.9493 18FEEB00 [39] 44 54 44 53 43 2A 39 33 36 4E 31 36 2A 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2A 20 20 20 20 20 20 20 20 20 20 2A
Component Identification from Engine #1 (0): {
Make: DTDSC
Model: 936N16
Serial:
Unit:
}

Is this also addressed by #1015

**Comment by ericthomasswenson** [comment]
Not worth a release by itself
