### ISSUE TITLE
SPN target missing

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1038]
Targeted SPs do not appear for some Test 1.26 and 2.17 log query displays for 3.0.12

PGN 61450 with Supported SPNs         **_<—— location for missing SP._**
07:39:25.2363 0CF00A00 [8] FF FF 00 00 FF FF FF FF
Found: Engine Gas Flow Rate from Engine #1 (0): 
  SPN  2659, Engine EGR 1 Mass Flow Rate: Not Available
  _**SPN   132, Engine Intake Air Mass Flow Rate: 0.000000 kg/h**_
  SPN  5257, Engine EGR 2 Mass Flow Rate: Not Available
  SPN 12758, Target Fresh Air Mass Flow: Not Available

WARN: 6.1.26.4.a - N.7 Provided SPN 132 is not indicated as supported by Engine #1 (0)

07:41:54.6414 DS Request for PGN 65253 to Engine #1 (0) for SPNs 
07:41:54.6437 18EA00F9 [3] E5 FE 00 (TX)
07:41:54.6507 18FEE500 [8] C5 83 03 00 7E D6 09 00
Engine Hours, Revolutions from Engine #1 (0): 
  **_SPN   247, Engine Total Hours of Operation: 11517.050000 h_**
  SPN   249, Engine Total Revolutions: 644734000.000000 r

Start Test 1.26 - Data stream support verification
Expecting the following messages:
  SPN 1213 is supported by Engine #1 (0) but will be omitted

  SPN 1220 is supported by Engine #1 (0) but will be omitted

  Req PGN 40448 from Engine #1 (0) with SPNs 4106
  Req PGN 40960 from Engine #1 (0) with SPNs 4127, 4130
  Req PGN 49408 from Engine #1 (0) with SPNs 3069, 3294, 3295, 3296
  BCT PGN 61443 from Engine #1 (0) with SPNs 91, 92
  BCT PGN 61444 from Engine #1 (0) with SPNs 190, 512, 513
  BCT PGN 61454 from Engine #1 (0) with SPNs 3216, 3217
  BCT PGN 61455 from Engine #1 (0) with SPNs 3226
  BCT PGN 61466 from Engine #1 (0) with SPNs 3464
  Req PGN 64587 from Engine #1 (0) with SPNs 7333
  Req PGN 64720 from Engine #1 (0) with SPNs 7393
  BCT PGN 64739 from Engine #1 (0) with SPNs 5541
  BCT PGN 64765 from Engine #1 (0) with SPNs 5313
  Req PGN 64782 from Engine #1 (0) with SPNs 7351
  Req PGN 64784 from Engine #1 (0) with SPNs 7353
  BCT PGN 64870 from Engine #1 (0) with SPNs 4076
  Req PGN 64878 from Engine #1 (0) with SPNs 5463
  Req PGN 64891 from Engine #1 (0) with SPNs 5466
  BCT PGN 64892 from Engine #1 (0) with SPNs 3700
  BCT PGN 64908 from Engine #1 (0) with SPNs 3609
  BCT PGN 64916 from Engine #1 (0) with SPNs 27
  BCT PGN 64923 from Engine #1 (0) with SPNs 3516
  BCT PGN 64946 from Engine #1 (0) with SPNs 3251
  BCT PGN 64947 from Engine #1 (0) with SPNs 3246
  BCT PGN 64948 from Engine #1 (0) with SPNs 3242
  Req PGN 64952 from Engine #1 (0) with SPNs 3301, 3302
  Req PGN 64962 from Engine #1 (0) with SPNs 5837
  Req PGN 64963 from Engine #1 (0) with SPNs 2623
  Req PGN 64981 from Engine #1 (0) with SPNs 2791, 5323
  BCT PGN 65110 from Engine #1 (0) with SPNs 1761
  Req PGN 65154 from Engine #1 (0) with SPNs 1413, 1414, 1415, 1416
  Req PGN 65155 from Engine #1 (0) with SPNs 1417, 1418
  BCT PGN 65174 from Engine #1 (0) with SPNs 1188, 1189
  BCT PGN 65177 from Engine #1 (0) with SPNs 1177
  BCT PGN 65178 from Engine #1 (0) with SPNs 1173
  Req PGN 65194 from Engine #1 (0) with SPNs 1692
  BCT PGN 65243 from Engine #1 (0) with SPNs 157
  BCT PGN 65247 from Engine #1 (0) with SPNs 3236
  BCT PGN 65251 from Engine #1 (0) with SPNs 539, 540, 541, 542, 543, 544
  BCT PGN 65252 from Engine #1 (0) with SPNs 1081
  **_Req PGN 65253 from Engine #1 (0) with SPNs 247_**
  BCT PGN 65262 from Engine #1 (0) with SPNs 110, 175
  BCT PGN 65263 from Engine #1 (0) with SPNs 94
  BCT PGN 65265 from Engine #1 (0) with SPNs 84
  BCT PGN 65266 from Engine #1 (0) with SPNs 51, 183
  BCT PGN 65269 from Engine #1 (0) with SPNs 108, 171
  BCT PGN 65270 from Engine #1 (0) with SPNs 102, 105
  BCT PGN 65271 from Engine #1 (0) with SPNs 158
  Req PGN 64920 from DPF Controller (85) with SPNs 5454

Step 6.1.26.1.a - Reading bus for 20 seconds

DM24 from Engine #1 (0): [
  D F T F
  a r e F
  t F s l
  a r t n  SPN — SP Name
  ----------------------
  D F   2  SPN 27 - Engine EGR 1 Valve Position
  D F   1  SPN 51 - Engine Throttle Valve 1 Position 1
  D F   2  SPN 84 - Wheel-Based Vehicle Speed
  D F   1  SPN 91 - Accelerator Pedal Position 1
  D F   1  SPN 92 - Engine Percent Load At Current Speed
  D F   1  SPN 94 - Engine Fuel Delivery Pressure
        1  SPN 96 - Fuel Level 1
    F   1  SPN 100 - Engine Oil Pressure 1
  D F T 1  SPN 102 - Engine Intake Manifold #1 Pressure
  D F   1  SPN 105 - Engine Intake Manifold 1 Temperature
  D F   1  SPN 108 - Barometric Pressure
  D F T 1  SPN 110 - Engine Coolant Temperature  **_<—- SP 132 not in DM24_**
  D F   2  SPN 157 - Engine Fuel 1 Injector Metering Rail 1 Pressure
  D F   2  SPN 158 - Key Switch Battery Potential
  D F   2  SPN 171 - Ambient Air Temperature
        1  SPN 172 - Engine Intake 1 Air Temperature
  D F   2  SPN 175 - Engine Oil Temperature 1
  D F   2  SPN 183 - Engine Fuel Rate
  D F   2  SPN 190 - Engine Speed
  **_D F   4  SPN 247 - Engine Total Hours of Operation_**

**Comment by ericthomasswenson** [comment]
Blank SPNs reflect those (relevant) PGs in Table A-1 not in DM24 response.

**Comment by battjt** [comment]
The blank SPN reflects 6.1.26.1.b:
> b. Create a second list of Table A-1 omissions from the consolidated OBD ECU DM24 response(s), excluding those SPs noted (as CI or SI) for the opposite fuel type provided by the user.

 when queried to confirm the omission of the SPN from DM24.

Consider replacing "supported" with "omitted" as shown below:

```
07:39:25.2363 0CF00A00 [8] FF FF 00 00 FF FF FF FF
Found: Engine Gas Flow Rate from Engine #1:

PGN 61450 with Supported SPNs
SPN 2659, Engine EGR 1 Mass Flow Rate: Not Available
SPN 5257, Engine EGR 2 Mass Flow Rate: Not Available
SPN 12758, Target Fresh Air Mass Flow: Not Available

PGN 61450 with Omitted SPNs 132.
SPN 132, Engine Intake Air Mass Flow Rate: 0.000000 kg/h
```

**Comment by battjt** [comment]
Please estimate effort for this change for consideration in task 8.

**Comment by karysg** [comment]
Estimate is 8 hours, starting work.
