### ISSUE TITLE
DS query for DM 19 to SA 61 was not observed. 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1046]
DS query for DM 19 to SA 61 was not observed.  V.3.0.10

Start Test 2.5 - DM19: Calibration information

07:25:16.9318 Destination Specific DM19 Request to Engine #1 (0)
07:25:16.9339 18EA00F9 [3] 00 D3 00 (TX)

// to each OBD ECU?
// query to SA 61 not in log

**Comment by ericthomasswenson** [comment]
Will retest with V3.0.12, and a different adapter

**Comment by ericthomasswenson** [comment]
The vehicle was found to violate test condition assumptions.
Correct performance will be rechecked at a later date.

**Comment by ericthomasswenson** [comment]
From 3.1.0 

End Test 2.4 - DM20: Monitor performance ratio

Start Test 2.5 - DM19: Calibration information

End Test 2.5 - DM19: Calibration information

Start Test 2.6 - DM56: Model year and certification engine family
13:44:07.7856 Destination Specific DM56 Request to Engine #1 (0)
13:44:07.7883 18EA00F9 [3] C7 FC 00 (TX)
13:44:07.7989 18E8FF00 [8] 01 FF FF FF F9 C7 FC 00
Acknowledgment from Engine #1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64711

End Test 2.6 - DM56: Model year and certification engine family

**Comment by battjt** [comment]
Can this be rejected?

**Comment by battjt** [comment]
Due to this being effected by TP Broadcast bug and "vehicle was found to violate test condition assumptions".  Development is tossing this issue back.

**Comment by ericthomasswenson** [comment]
Worked for this 3.1.4 example:

Start Test 1.7 - DM19: Calibration information
15:41:15.4585 Global DM19 Request
15:41:15.4610 18EAFFF9 [3] 00 D3 00 (TX)
15:41:15.6455 1CD3FF00 [20] 3C B4 8D A6 [35 54 32 31 34 32 30](tel:35 54 32 31 34 32 30) [30 41 30 30 30 30 30](tel:30 41 30 30 30 30 30) 30 30
DM19 from Engine #1 (0): CAL ID of 5T214200A0000000 and CVN of 0xA68DB43C

15:41:16.0715 1CD3FF3D [80] DA E8 6B 34 [33 41 73 31 62 31](tel:33 41 73 31 62 31) 4E 58 4E [32 31 30 30 30 33 31](tel:32 31 30 30 30 33 31) 72 14 4D A8 4E 4F 78 2D 53 [57 37 30 30 38](tel:57 37 30 30 38) 20 [41 54 49 31](tel:41 54 49 31) 00 72 14 4D A8 4E 4F 78 2D 53 [57 37 30 30 38](tel:57 37 30 30 38) 20 41 54 4F 31 00 3C D4 F9 EE 50 4D 53 2A 31 32 2A 33 33 30 2A [41 31 30 30](tel:41 31 30 30) 20
DM19 from Exhaust Emission Controller (61): [
  CAL ID of 3As1b1NXN2100031 and CVN of 0x346BE8DA
  CAL ID of NOx-SW7008 ATI1 and CVN of 0xA84D1472
  CAL ID of NOx-SW7008 ATO1 and CVN of 0xA84D1472
  CAL ID of PMS*12*330*A100 and CVN of 0xEEF9D43C
]

15:41:15.6245 1CD3FF01 [20] CC [50 53 82 34](tel:50 53 82 34) 4A [34 31 54 31](tel:34 31 54 31) 4E [57 35 32 34 31 33 54](tel:57 35 32 34 31 33 54) 43 4F
DM19 from Engine #2 (1): CAL ID of 4J41T1NW52413TCO and CVN of 0x825350CC

WARN: 6.1.7.3.b - Exhaust Emission Controller (61) provided more than one CAL ID and CVN pair in a single DM19 message
FAIL: 6.1.7.2.b.ii - Exhaust Emission Controller (61) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Exhaust Emission Controller (61) CAL ID not formatted correctly (contains non-printable ASCII)

15:41:16.2165 Destination Specific DM19 Request to Engine #1 (0)
15:41:16.2180 18EA00F9 [3] 00 D3 00 (TX)
15:41:16.2745 1CD3F900 [20] 3C B4 8D A6 [35 54 32 31 34 32 30](tel:35 54 32 31 34 32 30) [30 41 30 30 30 30 30](tel:30 41 30 30 30 30 30) 30 30
DM19 from Engine #1 (0): CAL ID of 5T214200A0000000 and CVN of 0xA68DB43C

15:41:16.2770 Destination Specific DM19 Request to Engine #2 (1)
15:41:16.2795 18EA01F9 [3] 00 D3 00 (TX)
15:41:16.3435 1CD3F901 [20] CC [50 53 82 34](tel:50 53 82 34) 4A [34 31 54 31](tel:34 31 54 31) 4E [57 35 32 34 31 33 54](tel:57 35 32 34 31 33 54) 43 4F
DM19 from Engine #2 (1): CAL ID of 4J41T1NW52413TCO and CVN of 0x825350CC

15:41:16.3455 Destination Specific DM19 Request to Exhaust Emission Controller (61)
15:41:16.3490 18EA3DF9 [3] 00 D3 00 (TX)
15:41:16.4805 1CD3F93D [80] DA E8 6B [34 33 41 73 31 62 31](tel:34 33 41 73 31 62 31) 4E 58 4E [32 31 30 30 30 33 31](tel:32 31 30 30 30 33 31) 72 14 4D A8 4E 4F 78 2D 53 [57 37 30 30 38 20 41](tel:57 37 30 30 38 20 41) [54 49 31 00 72 14](tel:54 49 31 00 72 14) 4D A8 4E 4F 78 2D 53 [57 37 30 30 38 20 41](tel:57 37 30 30 38 20 41) 54 4F 31 00 3C D4 F9 EE 50 4D 53 2A 31 32 2A 33 33 30 2A [41 31 30 30 20](tel:41 31 30 30 20)
DM19 from Exhaust Emission Controller (61): [
  CAL ID of 3As1b1NXN2100031 and CVN of 0x346BE8DA
  CAL ID of NOx-SW7008 ATI1 and CVN of 0xA84D1472
  CAL ID of NOx-SW7008 ATO1 and CVN of 0xA84D1472
  CAL ID of PMS*12*330*A100 and CVN of 0xEEF9D43C
]
