### ISSUE TITLE
Display FF length from DM24

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1047]
In the example, below the FF was not decoded

May the overall calculated length be displayed too

   2  SPN 3464 - Engine Throttle Actuator 1 Control Command
   1  SPN 641 - Engine Variable Geometry Turbocharger Actuator #1
   1  SPN 2795 - Engine Variable Geometry Turbocharger (VGT) 1 Actuator Position
**_Total Freeze Frame Data Length 999 bytes_**
]

**Comment by ericthomasswenson** [comment]
Start Test 3.12 - DM24: SPNs Supported

...
07:27:00.2400 Destination Specific DM24 Request to Engine #1 (0)
07:27:00.2404 18EA00F9 [3] B6 FD 00 (TX)
07:27:04.1624 18FDB600 [544] 01 02 1C 01 5C 00 1C 01 00 02 1C 01 6E 00 18 01 BE 00 1C 02 20 02 1C 01 1B 02 1C 01 1C 02 1C 01 1D 02 1C 01 1E 02 1C 01 1F 02 1C 01 E5 0C 1C 02 54 00 1C 02 6C 00 18 01 A8 00 1C 02 5B 00 1C 01 67 04 1C 02 AB 00 1C 02 46 0A 1C 02 C1 14 1C 02 C2 14 1C 02 88 0D 1C 02 81 02 1E 01 EB 0A 1E 01 BC 0D 19 00 85 05 1B 00 86 05 1B 00 87 05 1B 00 88 05 1B 00 89 05 1B 00 8A 05 1B 00 66 00 19 00 69 00 1B 00 6F 04 1B 00 A8 04 1B 00 B9 04 19 00 EF 0B 1B 00 AF 00 19 00 63 0A 19 00 90 0C 19 00 91 0C 1B 00 9A 0C 19 00 9B 0C 19 00 0C 11 1B 00 F3 10 1B 00 BB 12 1B 00 60 0F 1B 00 B7 0C 1B 00 B8 0C 1B 00 44 15 19 00 83 10 1B 00 43 11 1B 00 15 15 1B 00 C7 14 1B 00 A5 14 1B 00 A7 15 1B 00 75 16 1B 00 8B 02 1B 00 8C 02 1B 00 8D 02 1B 00 8E 02 1B 00 8F 02 1B 00 90 02 1B 00 CB 16 1B 00 C3 16 1D 00 FD 0B 1D 00 DE 0C 1D 00 D5 16 1D 00 A6 00 1D 00 BD 00 1D 00 C9 16 1D 00 A4 0C 1D 00 7E 32 1D 00 5A 15 1D 00 E6 0C 1D 00 C4 04 1D 00 74 0E 1D 00 CA FE 1D 00 B8 FD 1D 00 BA 00 1D 00 60 00 1D 00 20 0B 1D 00 4C 02 1D 00 02 02 1D 00 A2 0B 1D 00 EB 00 1D 00 F7 00 1D 00 F8 00 1D 00 EF 1A 1D 00 A5 1C 1D 00 B3 0C 1D 00 DF 0C 1D 00 E0 0C 1D 00 EC 0F 1D 00 3A 10 1D 00 87 0E 1D 00 0A 10 1D 00 75 0E 1D 00 73 0E 1D 00 76 0E 1D 00 4F 10 1D 00 E1 06 1D 00 BC 00 1D 00 10 02 1D 00 11 02 1D 00 12 02 1D 00 13 02 1D 00 9C 05 1D 00 98 04 1D 00 F9 18 1D 00 AE 0C 1D 00 08 11 1D 00 AA 0C 1D 00 0B 11 1D 00 CB 14 1D 00 AD 00 1D 00 CE 31 1D 00 B9 1C 1D 00 94 0C 1D 00 9E 0C 1D 00 65 00 1D 00 33 00 1D 00 94 04 1D 00 CF 31 1D 00 5F 04 1D 00 CD 16 1D 00 E7 0A 1D 00 C5 16 1D 00 1B 00 1D 00 40 06 1D 00 B7 00 1D 00 B2 1C 1D 00 BB 0D 1D 00 D7 0B 1D 00 9D 00 1D 00 9E 00 1D 00
DM24 from Engine #1 (0): [
  D F T F
  a r e F
  t F s l
  a r t n  SPN — SP Name
  ----------------------
  D     0  SPN 27 - Engine EGR 1 Valve Position
  D     0  SPN 51 - Engine Throttle Valve 1 Position 1
  D F   2  SPN 84 - Wheel-Based Vehicle Speed
  D F   1  SPN 91 - Accelerator Pedal Position 1
  D F   1  SPN 92 - Engine Percent Load At Current Speed
  D     0  SPN 96 - Fuel Level 1
  D     0  SPN 101 - Engine Crankcase Pressure 1
  D   T 0  SPN 102 - Engine Intake Manifold #1 Pressure
      T 0  SPN 105 - Engine Intake Manifold 1 Temperature
  D F T 1  SPN 108 - Barometric Pressure
  D F T 1  SPN 110 - Engine Coolant Temperature
  D     0  SPN 157 - Engine Fuel 1 Injector Metering Rail 1 Pressure
  D     0  SPN 158 - Key Switch Battery Potential
  D     0  SPN 166 - Engine Rated Power
  D F   2  SPN 168 - Battery Potential / Power Input 1
  D F   2  SPN 171 - Ambient Air Temperature
  D     0  SPN 173 - Engine Exhaust Temperature
  D   T 0  SPN 175 - Engine Oil Temperature 1
  D     0  SPN 183 - Engine Fuel Rate
  D     0  SPN 186 - Power Takeoff Speed
  D     0  SPN 188 - Engine Speed At Idle, Point 1
  D     0  SPN 189 - Engine Rated Speed
  D F   2  SPN 190 - Engine Speed
  D     0  SPN 235 - Engine Total Idle Hours
  D     0  SPN 247 - Engine Total Hours of Operation
  D     0  SPN 248 - Total Power Takeoff Hours
  D F   1  SPN 512 - Driver's Demand Engine - Percent Torque
  D F   1  SPN 513 - Actual Engine - Percent Torque
  D     0  SPN 514 - Nominal Friction - Percent Torque
  D     0  SPN 528 - Engine Speed At Point 2
  D     0  SPN 529 - Engine Speed At Point 3
  D     0  SPN 530 - Engine Speed At Point 4
  D     0  SPN 531 - Engine Speed At Point 5
  D F   1  SPN 539 - Engine Percent Torque At Idle, Point 1
  D F   1  SPN 540 - Engine Percent Torque At Point 2
  D F   1  SPN 541 - Engine Percent Torque At Point 3
  D F   1  SPN 542 - Engine Percent Torque At Point 4
  D F   1  SPN 543 - Engine Percent Torque At Point 5
  D F   1  SPN 544 - Engine Reference Torque
  D     0  SPN 588 - Serial Number
    F   1  SPN 641 - Engine Variable Geometry Turbocharger Actuator #1
      T 0  SPN 651 - Engine Fuel 1 Injector Cylinder 1
      T 0  SPN 652 - Engine Fuel 1 Injector Cylinder 2
      T 0  SPN 653 - Engine Fuel 1 Injector Cylinder 3
      T 0  SPN 654 - Engine Fuel 1 Injector Cylinder 4
      T 0  SPN 655 - Engine Fuel 1 Injector Cylinder 5
      T 0  SPN 656 - Engine Fuel 1 Injector Cylinder 6
  D     0  SPN 1119 - Engine Actual Exhaust 1 Oxygen
  D F   2  SPN 1127 - Engine Turbocharger 1 Boost Pressure
      T 0  SPN 1135 - Engine Oil Temperature 2
  D     0  SPN 1172 - Engine Turbocharger 1 Compressor Intake Temperature
  D     0  SPN 1176 - Engine Turbocharger 1 Compressor Intake Pressure
      T 0  SPN 1192 - Engine Turbocharger Wastegate Actuator Control Air Pressure
  D   T 0  SPN 1209 - Engine Exhaust Pressure 1
  D     0  SPN 1220 - OBD Compliance
      T 0  SPN 1413 - Engine Cylinder 1 Ignition Timing
      T 0  SPN 1414 - Engine Cylinder 2 Ignition Timing
      T 0  SPN 1415 - Engine Cylinder 3 Ignition Timing
      T 0  SPN 1416 - Engine Cylinder 4 Ignition Timing
      T 0  SPN 1417 - Engine Cylinder 5 Ignition Timing
      T 0  SPN 1418 - Engine Cylinder 6 Ignition Timing
  D     0  SPN 1436 - Engine Actual Ignition Timing
  D     0  SPN 1600 - Engine Fuel Rate (High Resolution)
  D     0  SPN 1761 - AFT 1 DEF Tank Volume
  D F   2  SPN 2630 - Engine Charge Air Cooler 1 Outlet Temperature
  D   T 0  SPN 2659 - Engine EGR 1 Mass Flow Rate
  D     0  SPN 2791 - Engine EGR 1 Valve 1 Control 1
    F   1  SPN 2795 - Engine Variable Geometry Turbocharger (VGT) 1 Actuator Position
  D     0  SPN 2848 - NAME of Controller Application (for address claimed)
  D     0  SPN 2978 - Estimated Engine Parasitic Losses - Percent Torque
  D     0  SPN 3031 - AFT 1 DEF Tank Temperature 1
      T 0  SPN 3055 - Engine Fuel System Monitor
  D     0  SPN 3069 - Distance Traveled While MIL is Activated
  D   T 0  SPN 3216 - Engine Exhaust 1 NOx 1
      T 0  SPN 3217 - Engine Exhaust 1 Percent Oxygen 1
  D     0  SPN 3220 - Engine Exhaust 1 NOx 1 Reading Stable
  D   T 0  SPN 3226 - AFT 1 Outlet NOx 1
  D   T 0  SPN 3227 - AFT 1 Outlet Percent Oxygen 1
  D     0  SPN 3230 - AFT 1 Outlet NOx 1 Reading Stable
  D     0  SPN 3236 - AFT 1 Exhaust Gas Mass Flow Rate
  D     0  SPN 3242 - AFT 1 DPF Intake Temperature
  D     0  SPN 3246 - AFT 1 DPF Outlet Temperature
  D     0  SPN 3251 - AFT 1 DPF Differential Pressure
      T 0  SPN 3255 - Engine Exhaust 2 NOx 1
      T 0  SPN 3256 - Engine Exhaust 2 Percent Oxygen 1
  D     0  SPN 3294 - Distance Since DTCs Cleared
  D     0  SPN 3295 - Minutes Run by Engine While MIL is Activated
  D     0  SPN 3296 - Time Since Diagnostic Trouble Codes Cleared
  D F   2  SPN 3301 - Time Since Engine Start
  D     0  SPN 3302 - Number of Warm-ups Since DTCs Cleared
  D F   2  SPN 3464 - Engine Throttle Actuator 1 Control Command
  D     0  SPN 3515 - AFT 1 DEF Temperature 2
  D   T 0  SPN 3516 - AFT 1 DEF Concentration
  D     0  SPN 3699 - AFT DPF Passive Regeneration Status
  D     0  SPN 3700 - AFT DPF Active Regeneration Status
  D     0  SPN 3701 - AFT DPF Status
  D     0  SPN 3702 - DPF Active Regeneration Inhibited Status
  D     0  SPN 3719 - AFT 1 DPF Soot Load Percent
      T 0  SPN 3936 - AFT DPF System
  D     0  SPN 4076 - Engine Coolant Temperature 2
  D     0  SPN 4106 - Emission-Related MIL-On DTC Count
  D     0  SPN 4154 - Actual Engine - Percent Torque (Fractional)
  D     0  SPN 4175 - DPF Active Regeneration Forced Status
      T 0  SPN 4227 - Engine Crankcase Breather Oil Separator
      T 0  SPN 4339 - AFT 1 SCR Feedback Control Status
  D     0  SPN 4360 - AFT 1 SCR Intake Temperature
  D     0  SPN 4363 - AFT 1 SCR Outlet Temperature
      T 0  SPN 4364 - AFT 1 SCR Conversion Efficiency
      T 0  SPN 4419 - AFT 2 SCR Conversion Efficiency
      T 0  SPN 4795 - AFT 1 DPF Missing
      T 0  SPN 5285 - Engine Charge Air Cooler 1 Efficiency
  D F   2  SPN 5313 - Commanded Engine Fuel Rail Pressure
  D F   2  SPN 5314 - Commanded Engine Fuel Injection Control Pressure
      T 0  SPN 5319 - AFT 1 DPF Incomplete Regeneration
  D     0  SPN 5323 - Engine Fuel Control Mode
      T 0  SPN 5397 - AFT 1 DPF Regeneration too Frequent
  D   T 0  SPN 5444 - Engine Crankcase Breather Oil Separator Speed
  D     0  SPN 5466 - AFT 1 DPF Soot Load Regeneration Threshold
      T 0  SPN 5543 - Engine Exhaust Brake Actuator Command
      T 0  SPN 5749 - Engine Exhaust Pressure 2
  D     0  SPN 5827 - AFT 1 DPF Average Distance Between Active Regenerations
  D     0  SPN 5829 - Engine EGR 1 Valve 1 Position Error
  D     0  SPN 5833 - Engine Fuel Mass Flow Rate
      T 0  SPN 5835 - AFT 1 Particulate Sensor
  D     0  SPN 5837 - Fuel Type
  D     0  SPN 5845 - Certification Engine Family Name
  D     0  SPN 6393 - Engine Fuel System 1 Total Intake Mass Air Flow Rate
  D     0  SPN 6895 - Engine Exhaust Flow Rate
  D     0  SPN 7333 - Cylinder Fuel Rate
  D     0  SPN 7346 - DEF Speed of Sound
  D     0  SPN 7353 - Engine Exhaust 1 Corrected Nox
  D     0  SPN 12750 - AFT 1 SCR 1 Engine Exhaust NOx Mass Flow
  D     0  SPN 12751 - AFT 1 SCR 1 Tailpipe NOx Mass Flow
  D     0  SPN 12926 - Nominal Friction Percent Torque (High Resolution)
  D     0  SPN 64952 - Unknown
  D     0  SPN 65226 - Unknown
]


07:27:04.1661 Destination Specific DM24 Request to Exhaust Emission Controller (61)
07:27:04.1670 18EA3DF9 [3] B6 FD 00 (TX)
07:27:04.7657 Timeout - No Response
SPs Supported in Expanded Freeze Frame from Engine #1 (0): [
  LN  SPN — SP Name
  -----------------
   1  SPN 513 - Actual Engine - Percent Torque
   1  SPN 92 - Engine Percent Load At Current Speed
   1  SPN 512 - Driver's Demand Engine - Percent Torque
   1  SPN 110 - Engine Coolant Temperature
   2  SPN 190 - Engine Speed
   1  SPN 544 - Engine Reference Torque
   1  SPN 539 - Engine Percent Torque At Idle, Point 1
   1  SPN 540 - Engine Percent Torque At Point 2
   1  SPN 541 - Engine Percent Torque At Point 3
   1  SPN 542 - Engine Percent Torque At Point 4
   1  SPN 543 - Engine Percent Torque At Point 5
   2  SPN 3301 - Time Since Engine Start
   2  SPN 84 - Wheel-Based Vehicle Speed
   1  SPN 108 - Barometric Pressure
   2  SPN 168 - Battery Potential / Power Input 1
   1  SPN 91 - Accelerator Pedal Position 1
   2  SPN 1127 - Engine Turbocharger 1 Boost Pressure
   2  SPN 171 - Ambient Air Temperature
   2  SPN 2630 - Engine Charge Air Cooler 1 Outlet Temperature
   2  SPN 5313 - Commanded Engine Fuel Rail Pressure
   2  SPN 5314 - Commanded Engine Fuel Injection Control Pressure
   2  SPN 3464 - Engine Throttle Actuator 1 Control Command
   1  SPN 641 - Engine Variable Geometry Turbocharger Actuator #1
   1  SPN 2795 - Engine Variable Geometry Turbocharger (VGT) 1 Actuator Position
]

FAIL: 6.3.12.2.b - OBD ECU Exhaust Emission Controller (61) did not provide a NACK for the DS query

End Test 3.12 - DM24: SPNs Supported

**Comment by ericthomasswenson** [comment]
Start Test 3.13 - DM25: Expanded freeze frame

07:27:04.7733 Destination Specific DM25 Request to Engine #1 (0)
07:27:04.7741 18EA00F9 [3] B7 FD 00 (TX)
07:27:04.7781 1CE8FF00 [8] 03 FF FF FF F9 B7 FD 00
Acknowledgment from Engine #1 (0): Response: Busy, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64951
07:27:04.9797 18EA00F9 [3] B7 FD 00 (TX)
07:27:04.9879 1CE8FF00 [8] 03 FF FF FF F9 B7 FD 00
Acknowledgment from Engine #1 (0): Response: Busy, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64951
07:27:05.1888 18EA00F9 [3] B7 FD 00 (TX)
07:27:05.1979 1CE8FF00 [8] 03 FF FF FF F9 B7 FD 00
Acknowledgment from Engine #1 (0): Response: Busy, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64951
07:27:05.4000 18EA00F9 [3] B7 FD 00 (TX)
07:27:06.2737 18FDB700 [117] **_26_** FF FF F0 7F 83 FF 7D 58 BD 12 69 A9 D3 D2 DE E1 10 00 00 00 C9 05 01 00 0C 00 C6 1F 23 28 0D 3C 0D 3C 88 13 00 FF 26 41 1A 05 7F 7D FF 7D 57 00 00 69 A9 D3 D2 DE 7D 00 00 00 00 C9 03 01 00 0D 00 96 28 96 28 00 0E 00 0E 00 00 00 FF 26 FF FF F1 7F 84 FF 7D 58 F5 12 69 A9 D3 D2 DE E1 01 00 00 00 C9 F3 00 00 0C 00 C6 1F B0 26 73 24 73 24 FF 7F 00 FF
DM25 from Engine #1 (0): 
Freeze Frames: [
  Freeze Frame: {
    DTC 524287:16 - Manufacturer Assignable SPN (last entry), Data Valid But Above Normal Operating Range - Moderately Severe Level
    SPN Data: 83 FF 7D 58 BD 12 69 A9 D3 D2 DE E1 10 00 00 00 C9 05 01 00 0C 00 C6 1F 23 28 0D 3C 0D 3C 88 13 00 FF
  }
  Freeze Frame: {
    DTC 6721:5 - Engine Fuel Injection Pump 2 Fuel Control Valve, Current Below Normal Or Open Circuit
    SPN Data: 7D FF 7D 57 00 00 69 A9 D3 D2 DE 7D 00 00 00 00 C9 03 01 00 0D 00 96 28 96 28 00 0E 00 0E 00 00 00 FF
  }
  Freeze Frame: {
    DTC 524287:17 - Manufacturer Assignable SPN (last entry), Data Valid But Below Normal Operating Range - Least Severe Level
    SPN Data: 84 FF 7D 58 F5 12 69 A9 D3 D2 DE E1 01 00 00 00 C9 F3 00 00 0C 00 C6 1F B0 26 73 24 73 24 FF 7F 00 FF
  }
]
// Freeze frame data not decoded … must be mis matched

07:27:06.2781 Destination Specific DM25 Request to Exhaust Emission Controller (61)
07:27:06.2785 18EA3DF9 [3] B7 FD 00 (TX)
07:27:06.2981 18FDB73D [8] 00 00 00 00 00 FF FF FF
DM25 from Exhaust Emission Controller (61): 
Freeze Frames: [
  No Freeze Frames
]

6.3.13.1.c - Received from Engine #1 (0): 

End Test 3.13 - DM25: Expanded freeze frame

**Comment by ericthomasswenson** [comment]
6.4.10 DM25: Expanded freeze frame 
6.4.10.1 Actions: 
a. DS DM25 (send Request (PGN 59904) for PGN 64951 (SPNs 3300, 1214-1215)) to each OBD ECU. 
6.4.10.2 Fail criteria: 
a. Fail if no ECU reports freeze frame data. 
b. Fail if DTC in freeze frame data does not include the DTC reported in DM12 earlier in this part. 
c. Fail if NACK not received from OBD ECUs that did not provide DM25 response.

**Comment by ericthomasswenson** [comment]
3.1.0 provides
…
   2  SPN 4331 - AFT 1 DEF Actual Dosing Quantity
   1  SPN 3703 - DPF Active Regeneration Inhibited Due to Inhibit Switch
   1  SPN 3516 - AFT 1 DEF Concentration
   1  SPN 3031 - AFT 1 DEF Tank Temperature 1
   2  SPN 5829 - Engine EGR 1 Valve 1 Position Error
   2  SPN 4360 - AFT 1 SCR Intake Temperature
   2  SPN 4363 - AFT 1 SCR Outlet Temperature
   2  SPN 4765 - AFT 1 Diesel Oxidation Catalyst Intake Temperature
   1  SPN 5837 - Fuel Type
   1  SPN 51 - Engine Throttle Valve 1 Position 1
   1  SPN 3464 - Engine Throttle Actuator 1 Control Command
]


End Test 3.12 - DM24: SPNs Supported

**Comment by battjt** [comment]
3.1.6 decodes SPN values.
```
Start Test 3.12 - DM24: SPNs Supported
...
SPs Supported in Expanded Freeze Frame from Engine #1 (0): [
LN SPN — SP Name
-----------------
1 SPN 92 - Engine Percent Load At Current Speed
1 SPN 512 - Driver&#39;s Demand Engine - Percent Torque
1 SPN 513 - Actual Engine - Percent Torque
2 SPN 544 - Engine Reference Torque
1 SPN 539 - Engine Percent Torque At Idle, Point 1
1 SPN 540 - Engine Percent Torque At Point 2
1 SPN 541 - Engine Percent Torque At Point 3
1 SPN 542 - Engine Percent Torque At Point 4
1 SPN 543 - Engine Percent Torque At Point 5
1 SPN 110 - Engine Coolant Temperature
2 SPN 175 - Engine Oil Temperature 1
2 SPN 190 - Engine Speed
...
6.3.13.1.c - Received from Engine #1 (0):
Freeze Frame: {
DTC 4227:1 - Engine Crankcase Breather Oil Separator, Data Valid But Below Normal Operational
Range - Most Severe Level - 0 times
SPN Data: 08 85 85 F7 09 A8 CE B4 DF E1 6A 66 2A 4C 21 15 00 00 00 C5 19 01 9A 93 00 01 70 60
70 60 70 60 70 60 70 60 70 60 4D 54 3A 22 26 55 26 00 00 00 00 00 28 2F 84 00 08 42 3C 4E 3C 09 35
0E 00 F9 35 0D 00 52 01 D3 39 82 82 00 87 28 01 C1 FF FA FF FA FF FA 74 65 01 00 00 1A 2A 21 27 AC
0E E5 04 01 00 00 02 01 52 1E 00 00 66 0C 14 10 0A 25 00 00 00 80 46 71 07 00 C1 35 13 35 19 35 FF
00
SPN 27, Engine EGR 1 Valve Position: 0.000 %
SPN 84, Wheel-Based Vehicle Speed: 0.000 km/h
SPN 91, Accelerator Pedal Position 1: 16.000 %
SPN 92, Engine Percent Load At Current Speed: 8.000 %
SPN 100, Engine Oil Pressure 1: 464.000 kPa
SPN 102, Engine Intake Manifold #1 Pressure: 16.000 kPa
SPN 105, Engine Intake Manifold 1 Temperature: 44.000 °C
SPN 108, Barometric Pressure: 98.500 kPa
SPN 110, Engine Coolant Temperature: 66.000 °C
SPN 132, Engine Intake Air Mass Flow Rate: 488.100 kg/h```

I see two issues:
1. the FF display should not reorder the SPNs.
2. Include the FF length in the decoding

**Comment by ericthomasswenson** [comment]
SPs Supported in Expanded Freeze Frame from Engine #1 (0): [
LN SPN — SP Name
-----------------
1 SPN 92 - Engine Percent Load At Current Speed
1 SPN 512 - Driver&#39;s Demand Engine - Percent Torque
1 SPN 513 - Actual Engine - Percent Torque
2 SPN 544 - Engine Reference Torque
1 SPN 539 - Engine Percent Torque At Idle, Point 1
1 SPN 540 - Engine Percent Torque At Point 2
1 SPN 541 - Engine Percent Torque At Point 3
1 SPN 542 - Engine Percent Torque At Point 4
1 SPN 543 - Engine Percent Torque At Point 5
1 SPN 110 - Engine Coolant Temperature
2 SPN 175 - Engine Oil Temperature 1
2 SPN 190 - Engine Speed
…
Please calculate and display Sum(LN[i]) + 4 (for DTC length)

**Comment by ericthomasswenson** [comment]
Sorting the FF SPN displays is fine. 

Please display the FF SPNs when the FF length sum matches the actual length of the data received.

e.g.
If DM25 byte 1 <> DM24 length + 5,
Then warn Length byte error.
If (DM25-payload-length mod (DM24-length +5)) = 0
Then Display FF content to DM24 layout.

Please also add FF length received to the display as shown in #1139

**Comment by ericthomasswenson** [comment]
See #1140

**Comment by battjt** [comment]
This is length calculated from DM24 displayed in DM24 decoding, not DM25 length.

**Comment by battjt** [comment]
Added "DM25 Length" to indicate actual packet length and changed frame length label to "Data Length" to indicate that it's not the whole frame, only the "SPN data" length.

**Comment by ericthomasswenson** [comment]
I look forward to seeing this.
