### ISSUE TITLE
FF False Failure in Part 8 V.3.0.10

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1048]
FF False Failure in Part 8 V.3.0.10

**_FAIL: 6.8.10.2.a - DTC(s) reported in the freeze frame by Engine #1 (0) did not include either the DTC reported in DM12 or DM23 earlier in this part_** is incorrect.
**_In fact it included both the DM12 and DM23 FFs (and three extras)_**

Start Test 8.10 - DM25: Expanded freeze frame

07:30:57.5242 Destination Specific DM25 Request to Engine #1 (0)
07:30:57.5253 18EA00F9 [3] B7 FD 00 (TX)
07:30:59.2426 18FDB700 [234] 26 FF FF F0 7F 83 FF 7D 58 CA 12 69 A9 D3 D2 DE E1 0C 00 00 00 C9 08 01 00 0C 00 A0 20 F0 26 10 3C 10 3C 88 13 00 FF 26 41 1A 05 01 7D FF 7D 57 00 00 69 A9 D3 D2 DE 7D 00 00 00 00 C9 04 01 00 0D 00 76 28 76 28 00 18 00 18 FF 7F 00 FF 26 34 04 05 01 7D FF 7D 58 00 00 69 A9 D3 D2 DE 7D 00 00 00 00 C9 00 01 00 0D 00 33 27 33 27 00 0E 00 0E 00 00 00 FF 26 30 02 13 01 7D FF 7D 58 00 00 69 A9 D3 D2 DE E1 00 00 00 00 C9 FC 00 00 0D 00 83 20 C3 26 50 3E 50 3E FF 7F 00 FF 26 01 00 A8 01 A7 FF 7D 58 00 00 69 A9 D3 D2 DE E1 00 00 00 00 C9 F0 00 00 0D 00 83 20 CA 26 06 23 06 23 FF 7F 00 FF 26 FF FF F1 7F 84 FF 7D 58 F5 12 69 A9 D3 D2 DE E1 01 00 00 00 C9 F3 00 00 0C 00 C6 1F B0 26 73 24 73 24 FF 7F 00 FF
DM25 from Engine #1 (0): 
Freeze Frames: [
  Freeze Frame: {
    DTC 524287:16 - Manufacturer Assignable SPN (last entry), Data Valid But Above Normal Operating Range - Moderately Severe Level
    SPN Data: 83 FF 7D 58 CA 12 69 A9 D3 D2 DE E1 0C 00 00 00 C9 08 01 00 0C 00 A0 20 F0 26 10 3C 10 3C 88 13 00 FF
  }
  Freeze Frame: {
    DTC **_6721:5_** - Engine Fuel Injection Pump 2 Fuel Control Valve, Current Below Normal Or Open Circuit - 1 times
    SPN Data: 7D FF 7D 57 00 00 69 A9 D3 D2 DE 7D 00 00 00 00 C9 04 01 00 0D 00 76 28 76 28 00 18 00 18 FF 7F 00 FF
  }
  Freeze Frame: {
    DTC **_1076:5_** - Engine Fuel Injection Pump 1 Fuel Control Valve, Current Below Normal Or Open Circuit - 1 times
    SPN Data: 7D FF 7D 58 00 00 69 A9 D3 D2 DE 7D 00 00 00 00 C9 00 01 00 0D 00 33 27 33 27 00 0E 00 0E 00 00 00 FF
  }
  Freeze Frame: {
    DTC 560:19 - Transmission Driveline Engaged, Received Network Data In Error - 1 times
    SPN Data: 7D FF 7D 58 00 00 69 A9 D3 D2 DE E1 00 00 00 00 C9 FC 00 00 0D 00 83 20 C3 26 50 3E 50 3E FF 7F 00 FF
  }
  Freeze Frame: {
    DTC 327681:8 - Unknown, Abnormal Frequency Or Pulse Width Or Period - 1 times
    SPN Data: A7 FF 7D 58 00 00 69 A9 D3 D2 DE E1 00 00 00 00 C9 F0 00 00 0D 00 83 20 CA 26 06 23 06 23 FF 7F 00 FF
  }
  Freeze Frame: {
    DTC 524287:17 - Manufacturer Assignable SPN (last entry), Data Valid But Below Normal Operating Range - Least Severe Level
    SPN Data: 84 FF 7D 58 F5 12 69 A9 D3 D2 DE E1 01 00 00 00 C9 F3 00 00 0C 00 C6 1F B0 26 73 24 73 24 FF 7F 00 FF
  }
]

07:30:59.2486 Destination Specific DM25 Request to Exhaust Emission Controller (61)
07:30:59.2506 18EA3DF9 [3] B7 FD 00 (TX)
07:30:59.2674 18FDB73D [8] 00 00 00 00 00 FF FF FF
DM25 from Exhaust Emission Controller (61): 
Freeze Frames: [
  No Freeze Frames
]

FAIL: 6.8.10.2.a - DTC(s) reported in the freeze frame by Engine #1 (0) did not include either the DTC reported in DM12 or DM23 earlier in this part

**Comment by ericthomasswenson** [comment]
Start Test 8.2 - DM12: Emissions related active DTCs

Attempt 1

07:30:48.6730 Global DM12 Request
07:30:48.6744 18EAFFF9 [3] D4 FE 00 (TX)
07:30:48.6754 18FED417 [8] 00 FF 00 00 00 00 FF FF
DM12 from Instrument Cluster #1 (23): MIL: off, RSL: off, AWL: off, PL: off, No DTCs
07:30:48.6758 18E8FF4C [8] 01 00 FF FF FF D4 FE 00
Acknowledgment from Communications Unit, Radio (76): Response: NACK, Group Function: 0, Address Acknowledged: 255, PGN Requested: 65236
07:30:48.7929 18FED400 [10] 43 FF 34 04 05 01 30 02 13 01
DM12 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: not supported
DTC **_1076:5_** - Engine Fuel Injection Pump 1 Fuel Control Valve, Current Below Normal Or Open Circuit - 1 times
DTC 560:19 - Transmission Driveline Engaged, Received Network Data In Error - 1 times
07:30:48.6869 18FED43D [8] 03 FF 00 00 00 00 FF FF
DM12 from Exhaust Emission Controller (61): MIL: off, RSL: off, AWL: off, PL: not supported, No DTCs
07:30:48.6879 18FED427 [8] 47 FF A8 00 01 01 FF FF
DM12 from Management Computer #1 (39): MIL: on, RSL: off, AWL: on, PL: not supported
DTC 168:1 - Battery Potential / Power Input 1, Data Valid But Below Normal Operational Range - Most Severe Level - 1 times
WARN: 6.8.2.2.a - Engine #1 (0) reported > 1 active DTC
WARN: 6.8.2.2.b - More than one ECU reported an active DTC

07:30:49.2802 Destination Specific DM12 Request to Engine #1 (0)
07:30:49.2807 18EA00F9 [3] D4 FE 00 (TX)
07:30:49.2868 1CE8FF00 [8] 03 FF FF FF F9 D4 FE 00
Acknowledgment from Engine #1 (0): Response: Busy, Group Function: 255, Address Acknowledged: 249, PGN Requested: 65236
07:30:49.4899 18EA00F9 [3] D4 FE 00 (TX)
07:30:49.6116 18FED400 [10] 43 FF 34 04 05 01 30 02 13 01
DM12 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: not supported
DTC **_1076:5_** - Engine Fuel Injection Pump 1 Fuel Control Valve, Current Below Normal Or Open Circuit - 1 times
DTC 560:19 - Transmission Driveline Engaged, Received Network Data In Error - 1 times

07:30:49.6131 Destination Specific DM12 Request to Exhaust Emission Controller (61)
07:30:49.6133 18EA3DF9 [3] D4 FE 00 (TX)
07:30:49.6269 18FED43D [8] 03 FF 00 00 00 00 FF FF
DM12 from Exhaust Emission Controller (61): MIL: off, RSL: off, AWL: off, PL: not supported, No DTCs

End Test 8.2 - DM12: Emissions related active DTCs

Start Test 8.3 - DM1: Active Diagnostic Trouble Codes (DTCs)

07:30:49.6320 Reading the bus for published DM1 messages

07:30:49.6848 18FECA03 [8] C0 FF 00 00 00 00 FF FF
DM1 from Transmission #1 (3): MIL: not supported, RSL: off, AWL: off, PL: off, No DTCs
...
07:30:50.1679 18FECA27 [18] 47 FF 94 10 04 01 BE 00 04 01 00 00 00 01 A8 00 01 01
DM1 from Management Computer #1 (39): MIL: on, RSL: off, AWL: on, PL: not supported
DTC 4244:4 - Engine Run Relay, Voltage Below Normal, Or Shorted To Low Source - 1 times
DTC 190:4 - Engine Speed, Voltage Below Normal, Or Shorted To Low Source - 1 times
DTC 168:1 - Battery Potential / Power Input 1, Data Valid But Below Normal Operational Range - Most Severe Level - 1 times

07:30:50.2173 18FECA17 [8] 00 FF 00 00 00 00 FF FF
DM1 from Instrument Cluster #1 (23): MIL: off, RSL: off, AWL: off, PL: off, No DTCs

07:30:50.2370 18FECA3D [8] 03 FF 00 00 00 00 FF FF
DM1 from Exhaust Emission Controller (61): MIL: off, RSL: off, AWL: off, PL: not supported, No DTCs
...
07:30:50.4117 18FECA00 [10] 43 FF 34 04 05 01 30 02 13 01
DM1 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: not supported
DTC 1076:5 - Engine Fuel Injection Pump 1 Fuel Control Valve, Current Below Normal Or Open Circuit - 1 times
DTC 560:19 - Transmission Driveline Engaged, Received Network Data In Error - 1 times
...
End Test 8.3 - DM1: Active Diagnostic Trouble Codes (DTCs)

Start Test 8.4 - DM23: Emission related previously active DTCs

07:30:52.6387 Global DM23 Request
07:30:52.6400 18EAFFF9 [3] B5 FD 00 (TX)
07:30:52.6423 18E8FF4C [8] 01 00 FF FF FF B5 FD 00
Acknowledgment from Communications Unit, Radio (76): Response: NACK, Group Function: 0, Address Acknowledged: 255, PGN Requested: 64949
07:30:52.6471 18FDB500 [8] 43 FF 41 1A 05 01 FF FF
DM23 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: not supported
DTC **_6721:5_** - Engine Fuel Injection Pump 2 Fuel Control Valve, Current Below Normal Or Open Circuit - 1 times
07:30:52.6572 18FDB53D [8] 03 FF 00 00 00 00 FF FF
DM23 from Exhaust Emission Controller (61): MIL: off, RSL: off, AWL: off, PL: not supported, No DTCs
07:30:52.6580 18FDB527 [8] 47 FF 00 00 00 00 FF FF
DM23 from Management Computer #1 (39): MIL: on, RSL: off, AWL: on, PL: not supported, No DTCs

End Test 8.4 - DM23: Emission related previously active DTCs

**Comment by ericthomasswenson** [comment]
Let’s discuss 

See #1095 For Similar Complaint

**Comment by ericthomasswenson** [comment]
3.1.0 Outcomes

All DM12 and DM23 DTCs were included in this FF example:
See next comment to view these displays.
No failure message was observed.

Start Test 8.10 - DM25: Expanded freeze frame
14:05:58.9238 Destination Specific DM25 Request to Engine #1 (0)
14:05:58.9270 18EA00F9 [3] B7 FD 00 (TX)
14:06:00.2253 1CFDB700 [402] 85 66 00 1F 15 00 7D 7D D7 0A 81 82 80 82 82 4E AE 26 00 00 00 00 00 00 C7 EA 00 6B 0C 00 01 00 64 00 64 00 64 00 64 00 64 00 64 3B 44 0D 00 00 F6 23 00 00 00 00 1F 00 00 00 00 00 8A 00 FF 63 FF FE 00 00 FF FE 00 00 00 00 04 00 01 00 00 C9 24 01 00 00 FB FE FA 00 FB 00 8A 04 00 00 E7 25 CE 24 12 0B 1C 04 01 00 03 02 0F EC 7D 01 00 19 19 19 19 19 19 00 00 00 80 50 11 7A 10 11 00 00 FF FE 04 FA 40 9C 85 66 00 04 01 00 7D 7D D7 0A C6 D5 B0 DD E1 4E AD 26 00 00 00 00 00 00 C7 ED 00 6B 0C 00 01 00 64 00 64 00 64 00 64 00 64 00 64 3B 44 FA 00 00 F6 23 00 00 00 00 1F 00 00 00 00 FA 8A 00 FF 63 16 30 00 00 E6 2E 00 00 00 00 A7 2E 00 00 00 CB 24 01 75 00 FB FE FA 00 FB 00 8A 04 00 00 E9 25 CD 24 DF 0A B9 03 01 00 03 02 0F EC 7D 01 00 5B 39 12 08 05 25 00 00 00 7E 33 11 7A 2C 2C 70 29 93 2E 04 FA 40 9C 85 83 10 01 01 07 84 84 D7 0A A5 D5 B0 DD E1 48 C2 25 D4 21 17 00 00 00 C7 0C 01 1B 0C 00 01 92 61 92 61 92 61 92 61 92 61 92 61 38 3D 24 9C 17 D7 23 00 00 00 00 1F 23 28 64 00 00 19 6B C7 6A CC 30 07 00 AC 31 00 00 27 01 61 36 AB AB 00 76 24 01 75 00 FB FE FA 00 FB D0 88 04 00 00 1C 26 CB 24 2A 10 F1 0B 01 00 03 02 01 EC 7D 01 00 06 29 12 08 05 25 00 00 00 7E 32 11 7A 97 2D 83 29 83 33 04 20 35 14
DM25 from Engine #1 (0): 
Freeze Frames: [
  Freeze Frame: {
    DTC 102:31 - Engine Intake Manifold #1 Pressure, Condition Exists - 21 times
    SPN Data: 00 7D 7D D7 0A 81 82 80 82 82 4E AE 26 00 00 00 00 00 00 C7 EA 00 6B 0C 00 01 00 64 00 64 00 64 00 64 00 64 00 64 3B 44 0D 00 00 F6 23 00 00 00 00 1F 00 00 00 00 00 8A 00 FF 63 FF FE 00 00 FF FE 00 00 00 00 04 00 01 00 00 C9 24 01 00 00 FB FE FA 00 FB 00 8A 04 00 00 E7 25 CE 24 12 0B 1C 04 01 00 03 02 0F EC 7D 01 00 19 19 19 19 19 19 00 00 00 80 50 11 7A 10 11 00 00 FF FE 04 FA 40 9C
  }
  Freeze Frame: {
    DTC 102:4 - Engine Intake Manifold #1 Pressure, Voltage Below Normal, Or Shorted To Low Source - 1 times
    SPN Data: 00 7D 7D D7 0A C6 D5 B0 DD E1 4E AD 26 00 00 00 00 00 00 C7 ED 00 6B 0C 00 01 00 64 00 64 00 64 00 64 00 64 00 64 3B 44 FA 00 00 F6 23 00 00 00 00 1F 00 00 00 00 FA 8A 00 FF 63 16 30 00 00 E6 2E 00 00 00 00 A7 2E 00 00 00 CB 24 01 75 00 FB FE FA 00 FB 00 8A 04 00 00 E9 25 CD 24 DF 0A B9 03 01 00 03 02 0F EC 7D 01 00 5B 39 12 08 05 25 00 00 00 7E 33 11 7A 2C 2C 70 29 93 2E 04 FA 40 9C
  }
  Freeze Frame: {
    DTC 4227:1 - Engine Crankcase Breather Oil Separator, Data Valid But Below Normal Operational Range - Most Severe Level - 1 times
    SPN Data: 07 84 84 D7 0A A5 D5 B0 DD E1 48 C2 25 D4 21 17 00 00 00 C7 0C 01 1B 0C 00 01 92 61 92 61 92 61 92 61 92 61 92 61 38 3D 24 9C 17 D7 23 00 00 00 00 1F 23 28 64 00 00 19 6B C7 6A CC 30 07 00 AC 31 00 00 27 01 61 36 AB AB 00 76 24 01 75 00 FB FE FA 00 FB D0 88 04 00 00 1C 26 CB 24 2A 10 F1 0B 01 00 03 02 01 EC 7D 01 00 06 29 12 08 05 25 00 00 00 7E 32 11 7A 97 2D 83 29 83 33 04 20 35 14
  }
]

**Comment by ericthomasswenson** [comment]
Start Test 8.2 - DM12: Emissions related active DTCs

Attempt 1
14:05:51.5429 Global DM12 Request
14:05:51.5457 18EAFFF9 [3] D4 FE 00 (TX)
14:05:51.5483 18FED417 [8] 04 FF 00 00 00 00 FF FF
DM12 from Instrument Cluster #1 (23): MIL: off, RSL: off, AWL: on, PL: off, No DTCs

14:05:51.6517 1CFED400 [10] 40 FF 66 00 1F 15 66 00 04 01
DM12 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: off
DTC 102:31 - Engine Intake Manifold #1 Pressure, Condition Exists - 21 times
DTC 102:4 - Engine Intake Manifold #1 Pressure, Voltage Below Normal, Or Shorted To Low Source - 1 times

WARN: 6.8.2.2.a - Engine #1 (0) reported > 1 active DTC
14:05:52.1478 Destination Specific DM12 Request to Engine #1 (0)
14:05:52.1512 18EA00F9 [3] D4 FE 00 (TX)
14:05:52.2045 1CFED400 [10] 40 FF 66 00 1F 15 66 00 04 01
DM12 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: off
DTC 102:31 - Engine Intake Manifold #1 Pressure, Condition Exists - 21 times
DTC 102:4 - Engine Intake Manifold #1 Pressure, Voltage Below Normal, Or Shorted To Low Source - 1 times

End Test 8.2 - DM12: Emissions related active DTCs


Start Test 8.4 - DM23: Emission related previously active DTCs
14:05:55.2150 Global DM23 Request
14:05:55.2180 18EAFFF9 [3] B5 FD 00 (TX)
14:05:55.2321 18FDB500 [8] 40 FF 83 10 01 01 FF FF
DM23 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: off
DTC 4227:1 - Engine Crankcase Breather Oil Separator, Data Valid But Below Normal Operational Range - Most Severe Level - 1 times


End Test 8.4 - DM23: Emission related previously active DTCs

**Comment by battjt** [comment]
Related to #1211 .

**Comment by ericthomasswenson** [comment]
// Pass = (There exists an X that is an element of {DM12} that is also an element of {DM25})
//        Or (There exists a Y that is an element of {DM23} that is also an element of {DM25})
// Fail = (There does not exist an X that is an element of {DM12} that is also an element of {DM25})
//       And (There does not exist an X that is an element of {DM23} that is also an element of {DM25})
