### ISSUE TITLE
Potential false failure in DM33 query for Part 9

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1049]
Potential false failure in DM33 query for Part 9

FAIL: 6.9.7.2.a - Exhaust Emission Controller (61) reported a different number of EI-AECD timers than was reported in part 2
// Responses displayed for SA 61 are consistent 
// But they are different from SA 0 response.

Start Test 9.7 - DM33: Emission increasing AECD active time

07:31:48.8525 Global DM33 Request
07:31:48.8532 18EAFFF9 [3] 00 A1 00 (TX)
07:31:48.8557 1CE8FF00 [8] 03 FF FF FF FF 00 A1 00
Acknowledgment from Engine #1 (0): Response: Busy, Group Function: 255, Address Acknowledged: 255, PGN Requested: 41216
07:31:48.9858 18A1FF3D [9] 00 00 00 00 00 00 00 00 00
DM33 Emission Increasing AECD Active Time from Exhaust Emission Controller (61): [
  EI-AECD Number = 0: Timer 1 = 0 minutes; Timer 2 = 0 minutes
]

07:31:49.4545 18EAFFF9 [3] 00 A1 00 (TX)
07:31:49.6210 18A1FF00 [18] 00 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 00
DM33 Emission Increasing AECD Active Time from Engine #1 (0): [
  EI-AECD Number = 0: Timer 1 = 0 minutes; Timer 2 = 0 minutes
  EI-AECD Number = 1: Timer 1 = 0 minutes; Timer 2 = 0 minutes
]

// Each timer needs a unique number, can’t report label value 0 three times.

07:31:49.5858 18A1FF3D [9] 00 00 00 00 00 00 00 00 00  
DM33 Emission Increasing AECD Active Time from Exhaust Emission Controller (61): [
  EI-AECD Number = 0: Timer 1 = 0 minutes; Timer 2 = 0 minutes
]
// This response appears to be excess as last query was DS to SA 00

FAIL: 6.9.7.2.a - Engine #1 (0) reported a different number of EI-AECD timers than was reported in part 2
// There were response problems in Part 2.

FAIL: 6.9.7.2.a - Exhaust Emission Controller (61) reported a different number of EI-AECD timers than was reported in part 2
// Responses displayed are consistent 

End Test 9.7 - DM33: Emission increasing AECD active time

Start Test 2.15 - DM33: Emission increasing AECD active time

07:25:30.2154 Global DM33 Request
07:25:30.2163 18EAFFF9 [3] 00 A1 00 (TX)
07:25:30.2260 1CE8FF00 [8] 03 FF FF FF FF 00 A1 00
Acknowledgment from Engine #1 (0): Response: Busy, Group Function: 255, Address Acknowledged: 255, PGN Requested: 41216
07:25:30.3462 18A1FF3D [9] 00 00 00 00 00 00 00 00 00
DM33 Emission Increasing AECD Active Time from Exhaust Emission Controller (61): [
  EI-AECD Number = 0: Timer 1 = 0 minutes; Timer 2 = 0 minutes
]

07:25:30.8219 18EAFFF9 [3] 00 A1 00 (TX)
07:25:30.8261 1CE8FF00 [8] 03 FF FF FF FF 00 A1 00
Acknowledgment from Engine #1 (0): Response: Busy, Group Function: 255, Address Acknowledged: 255, PGN Requested: 41216
07:25:30.9462 18A1FF3D [9] 00 00 00 00 00 00 00 00 00
DM33 Emission Increasing AECD Active Time from Exhaust Emission Controller (61): [
  EI-AECD Number = 0: Timer 1 = 0 minutes; Timer 2 = 0 minutes
]
// This response is allowed as query was globally addressed.

07:25:31.4221 18EA00F9 [3] 00 A1 00 (TX)
// DS Response missing?

End Test 2.15 - DM33: Emission increasing AECD active time

**Comment by ericthomasswenson** [comment]
Need expectation whether SA 0 and SA 61 are allowed to provide local counts for local EI-AECDs.   (Like test results)

EI AECD numbers need to be unique, as they are to have a unique description in the cert. application.

The criteria does not enforce this. It enforces whether the same EI AECD numbers are provided each time compared to the part 2 response. 

Part 9 criteria also check whether timers run when not required.

**Comment by ericthomasswenson** [comment]
**_#1095 segregates the numbers yet still fails._**
**_Errors in part 2 cascade into part 9, when part 2 global or DS responses go missing the part 9 queries fail._**

Here the numbers are reused, perhaps inappropriately.
The criteria doesn’t intend to punish this. 
As long as an SA reports the same timer labels each time.

**Comment by ericthomasswenson** [comment]
6.2.15 DM33: Emission Increasing Auxiliary Emission Control Device Active Time 
6.2.15.1 Actions 
a. Global DM33 [send Request (PG 59904) for PG 41216 (SPs 4124-4126)]. 
b. Create list of reported EI-AECD timers by ECU. 
6.2.15.2 Fail Criteria.  [Engines using SI technology need not respond until the 2024 engine model year.] [38]
a. Fail if no ECU responds. 
6.2.15.3 Warn Criteria 
a. Warn if only response(s) = FBh (no EI-AECDs) for EI-AECD number (byte 1). 
6.2.15.4 Actions2 
a. DS DM33 to each OBD ECU. 
6.2.15.5 Fail Criteria2 
a. Fail if any difference is detected when response data is compared to data received from global request, which is greater than 2 minutes more than the times reported from the responses received from the global request in 6.2.15.2. [39]

6.9.7 DM33: Emission Increasing Auxiliary Emission Control Device Active Time 
6.9.7.1 Actions 
a. Global DM33 [send Request (PG 59904) for PG 41216 (SPs 4124-4126)]. 
b. Create a list of ECU address + EI-AECD number + actual time (for Timer 1 and/or Timer 2) for any with non-zero timer values. 
6.9.7.2 Fail Criteria 
a. Fail if any ECU reports a different number of EI-AECD timers than was reported in part 2.  [Engines using SI technology need not respond until the 2024 engine model year]. 

6.9.23 DM33: Emission Increasing Auxiliary Emission Control Device Active Time 
6.9.23.1 Actions 
a. DS DM33 [ send Request ( PG 59904) for PG 41216 (SPs 4124-4126)] to each OBD ECU.
6.9.23.2 Fail Criteria 
a. Fail if any ECU reports a different number EI-AECDs was reported in part 2. [Engines using SI technology need not respond until the 2024 engine model year]. 
b. Compare to list of ECU a zero timer values address + observed EI-AEDC number + actual time (for Timer 1 and/or Timer 2) for any with non-zero values earlier in step 6.9. this part, and fail if any timer value is less than the value it was earlier in this part (test 6.9.7).
c. Fail if NACK not received from OBD ECU 7 s that did not provide a DM33 message.

**Comment by ericthomasswenson** [comment]
DM33 Emission Increasing AECD Active Time from 
Exhaust Emission Controller (61): [
EI-AECD Number = 0: Timer 1 = 0 minutes; Timer 2 = 0 minutes
Engine (0): [
EI-AECD Number = 0: Timer 1 = 0 minutes; Timer 2 = 0 minutes
EI-AECD Number = 1: Timer 1 = 0 minutes; Timer 2 = 0 minutes
]

**Comment by ericthomasswenson** [comment]
**_Single ECU support passes. (When the part 2 queries succeed)._**

11:53:52.0180 Destination Specific DM33 Request to Engine #1 (0)
11:53:52.0211 18EA00F9 [3] 00 A1 00 (TX)
11:53:52.1146 18A1F900 [27] 01 69 00 00 00 FF FF FF FF 05 00 00 00 00 FF FF FF FF 08 4F 00 00 00 FF FF FF FF
DM33 Emission Increasing AECD Active Time from Engine #1 (0): [
  EI-AECD Number = 1: Timer 1 = 105 minutes; Timer 2 = n/a
  EI-AECD Number = 5: Timer 1 = 0 minutes; Timer 2 = n/a
  EI-AECD Number = 8: Timer 1 = 79 minutes; Timer 2 = n/a
]

Start Test 9.7 - DM33: Emission increasing AECD active time

11:57:09.1117 Global DM33 Request
11:57:09.1154 18EAFFF9 [3] 00 A1 00 (TX)
11:57:09.3271 18A1FF00 [27] 01 69 00 00 00 FF FF FF FF 05 00 00 00 00 FF FF FF FF 08 4F 00 00 00 FF FF FF FF
DM33 Emission Increasing AECD Active Time from Engine #1 (0): [
  EI-AECD Number = 1: Timer 1 = 105 minutes; Timer 2 = n/a
  EI-AECD Number = 5: Timer 1 = 0 minutes; Timer 2 = n/a
  EI-AECD Number = 8: Timer 1 = 79 minutes; Timer 2 = n/a
]

Start Test 9.24 - DM33: Emission increasing AECD active time

11:57:55.9355 Destination Specific DM33 Request to Engine #1 (0)
11:57:55.9390 18EA00F9 [3] 00 A1 00 (TX)
11:57:56.0370 18A1F900 [27] 01 69 00 00 00 FF FF FF FF 05 00 00 00 00 FF FF FF FF 08 4F 00 00 00 FF FF FF FF
DM33 Emission Increasing AECD Active Time from Engine #1 (0): [
  EI-AECD Number = 1: Timer 1 = 105 minutes; Timer 2 = n/a
  EI-AECD Number = 5: Timer 1 = 0 minutes; Timer 2 = n/a
  EI-AECD Number = 8: Timer 1 = 79 minutes; Timer 2 = n/a
]

**Comment by ericthomasswenson** [comment]
There are a cluster of related DM33 issues that appear to be related to a common theme.

**Comment by battjt** [comment]
EIDT: we don't know what to do with this issue.

**Comment by ericthomasswenson** [comment]
No criteria changes will be made to enforce unique AECD numbers across all responding devices at this time, as there is no objective requirement from the regulator.

**Comment by ericthomasswenson** [comment]
This is believed to be a BAM message reception problem primarily.

**Comment by battjt** [comment]
So nothing for development to do?  It should be unassigned or closed.

**Comment by ericthomasswenson** [comment]
Closed as there are no apparent criteria changes
