### ISSUE TITLE
Add NOX Binning and GHG Tracking to Functions B and E, to IUMPR Tool

### ISSUE THREAD

**Issue by mmschaefer** [Equipment-and-Tool-Institute/j1939-84#1054]
From j1939-84 created by [ericthomasswenson](https://github.com/ericthomasswenson): Equipment-and-Tool-Institute/j1939-84#1053  

1. Update SAE J3162 IUMPR Tool to Java 11 using the same Java 11 version 
2. Add NOX Binning and GHG Tracking to Functions B and E, by adapting J1939-84 queries and displays.

**Comment by ericthomasswenson** [comment]
This issue is now captured in the IUMPR issues list

https://github.com/Equipment-and-Tool-Institute/iumpr/issues/84

**Comment by ericthomasswenson** [comment]
Closed in favor of IUMPR issue

**Comment by ericthomasswenson** [comment]
Closed in favor of IUMPR issue
