### ISSUE TITLE
Value observed for SP 188 Engine Idle Speed not used in Part 11 test 7

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1063]
Value observed for SP 188 Engine Idle Speed not used in Part 11 test 7.

As a result the engine idle speed timer does not increment, and the user must abort the test

Start Test 11.7 - DM20/DM28/Broadcast data: Waiting until general denominator is met
11:59:08.1993 Test Update:
          Engine Speed: 831.25 RPM
      WMA Engine Speed: 831.25 RPM
     **_Idle Engine Speed: 600.0 RPM_**
        Pedal Position: 0.0 %
  Run Time >= 1150 RPM: 0 seconds
      Run Time at Idle: 0 seconds
        Total Run Time: 2 seconds

12:00:08.1303 Test Update:
          Engine Speed: 807.0 RPM
      WMA Engine Speed: 823.6652818294498 RPM
     _**_Idle Engine Speed: 600.0 RPM_**_
        Pedal Position: 0.0 %
  Run Time >= 1150 RPM: **_0 seconds_**
      Run Time at Idle: 0 seconds
        Total Run Time: 62 seconds

**_This data was not collected using a Nexiq Link 2._**  Retries are planned with a Nexiq Link 2.

**Comment by ericthomasswenson** [comment]
PGN 65251 with Supported SPNs 544
11:08:27.8113 18FEE300 [39] 00 19 C3 20 4E DB 60 22 D9 80 25 DE 40 38 E1 20 4E FF FF 52 03 00 4B 3C 46 FA 7D DE 20 4E 86 00 FF FF FF FF FF FF FF
Found: Engine Configuration 1 from Engine #1 (0): 
  **_SPN   188, Engine Speed At Idle, Point 1:_** **_800.000000 rpm_**
  SPN   539, Engine Percent Torque At Idle, Point 1: 70.000000 %

**Comment by ericthomasswenson** [comment]
Recommend correcting this in conjunction with #982

**Comment by ericthomasswenson** [comment]
Vimal’s examples in #982 show 650 as engine idle speed … which was used as the standard.

**Comment by mmschaefer** [comment]
@ericthomasswenson - Can we get all files and logs on this, please?

**Comment by ericthomasswenson** [comment]
Logs have been provided.  See #1063 for related issue.

**Comment by ericthomasswenson** [comment]
Item 3 was suggested as the better approach.
2. I’m thinking I should add an action step: …
3. Should the proposed step say
a. Send global request (PG 59904) for EC1 (PG 65351) to obtain SP 188 Engine Idle Speed.  If SP 188 is not provided, use the value provided from Part 1 Test 26, or Part 2 test 17, when observed.  Otherwise, use 725 rpm as the default idle speed standard for test 6.7.
… instead?

**Comment by ericthomasswenson** [comment]
Review Part 11 timer performance in next release.

**Comment by battjt** [comment]
N/A was interpreted as a value and is no longer the case.

**Comment by ericthomasswenson** [comment]
WMA N no longer appears to be biased … Issue closed.

Start Test 11.7 - DM20/DM28/Broadcast data: Waiting until general denominator is met
13:58:42.0844 Test Update:
          Engine Speed: 598.5 RPM
      WMA Engine Speed: 598.5 RPM
     Idle Engine Speed: 600.0 RPM
        Pedal Position: 0.0 %
  Run Time >= 1150 RPM: 0 seconds
      Run Time at Idle: 0 seconds
        Total Run Time: 3 seconds

13:59:42.0996 Test Update:
          Engine Speed: 500.75 RPM
      WMA Engine Speed: 517.2469541885972 RPM
     Idle Engine Speed: 526.0 RPM
        Pedal Position: 0.0 %
  Run Time >= 1150 RPM: 0 seconds
      Run Time at Idle: 58 seconds
        Total Run Time: 63 seconds

14:00:42.0964 Test Update:
          Engine Speed: 500.75 RPM
      WMA Engine Speed: 500.1703334016047 RPM
     Idle Engine Speed: 500.0 RPM
        Pedal Position: 0.0 %
  Run Time >= 1150 RPM: 0 seconds
      Run Time at Idle: 116 seconds
        Total Run Time: 123 seconds

14:01:42.0933 Test Update:
          Engine Speed: 500.125 RPM
      WMA Engine Speed: 499.8130909831841 RPM
     Idle Engine Speed: 500.0 RPM
        Pedal Position: 0.0 %
  Run Time >= 1150 RPM: 0 seconds
      Run Time at Idle: 174 seconds
        Total Run Time: 183 seconds
