### ISSUE TITLE
Update SP 84 from Warn to Info 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1065]
CARB approved modification of SP 84 entries as shown in the attached image and table A-1 text.

These changes are not perceived to be material change to the level of effort for Table A-1 changes given in #820, #818, #982, #970, #971, #859, #515

![image](https://user-images.githubusercontent.com/78398059/133455579-5b277fc9-c3ce-42b8-8dfe-e30379857921.png)

[J1939-84-Table-A-1-MY24 15Sept2021.docx](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/7171010/J1939-84-Table-A-1-MY24.15Sept2021.docx)

**Comment by ericthomasswenson** [comment]
Check SP 84 warning messages provided by the next release

**Comment by battjt** [comment]
Release 3.1.5 has an updated table A-1.

**Comment by ericthomasswenson** [comment]
Completed with table A-1 changes.
