### ISSUE TITLE
DM Label Mismatch in Test 6.1.4.2.a

### ISSUE THREAD

**Issue by mmschaefer** [Equipment-and-Tool-Institute/j1939-84#1066]
Reported by field tech:
"This was found using v3.0.10
Is this a DM label mismatch?
 
DM25 should be DM24?
 
10:46:00.5773 Destination Specific DM24 Request to Exhaust Emission Controller (61)
10:46:00.5819 18EA3DF9 [3] B6 FD 00 (TX)
10:46:01.1786 Timeout - No Response
 
10:46:01.6882 Destination Specific DM24 Request to Exhaust Emission Controller (61)
10:46:01.6917 18EA3DF9 [3] B6 FD 00 (TX)
10:46:02.2918 Timeout - No Response
FAIL: 6.1.4.2.a - Retry was required to obtain **_DM25_** response from Exhaust Emission Controller (61)
 
End Test 1.4 - DM24: SPN support
 "

**Comment by ericthomasswenson** [comment]
Present as built text:
6.1.4	DM24: SP Support
6.1.4.1	Actions
a.	Destination Specific (DS) DM24 [send Request (PG 59904) for PG 64950 (SPs 3297, 4100-4103)] to each OBD ECU.  
b.	If no response [transport protocol RTS or NACK(Busy) in 220 ms], then retry DS DM24 request to the OBD ECU. (Do not attempt retry for NACKs that indicate not supported.)
c.	Create vehicle list of supported SPs for data stream.
d.	Create ECU specific list of supported SPs for test results. 
e.	Create ECU specific list of supported freeze frame SPs.
6.1.4.2	Fail Criteria 
a.	Fail if retry was required to obtain the DM24 response. 
b.	Fail if one or more minimum expected SPs for data stream not supported per Section A.1, Minimum Support Table, from the OBD ECU(s). 
c.	Fail if one or more minimum expected SPs for freeze frame not supported per Section A.2, Criteria for Freeze Frame Evaluation, from the OBD ECU(s).

**Comment by ericthomasswenson** [comment]
Joe, please add the brl label if this message text typo has been corrected.
