### ISSUE TITLE
DM21 Global Response Missed in Test 2.9

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1075]
I expect that the software saw the NACK first in Part 2.
The engine’s response was observed and reported in Part 1, followed by the NACK.

Start Test 2.9 - DM21: Diagnostic readiness 2

10:22:33.1738 Global DM21 Request
10:22:33.1781 18EAFFF9 [3] 00 C1 00 (TX)
10:22:33.1799 18E8FFE8 [8] 01 FF FF FF F9 00 C1 00
Acknowledgment from Forward Road Image Processor (232): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 49408
FAIL: 6.2.9.2.b - No ECU reported time (SPN 3295) or distance (SPN 3069) with MIL on
WARN: 6.2.9.2.e - No OBD ECU reported time (SPN 3296) for DM21

10:22:33.7786 Destination Specific DM21 Request to Engine #1 (0)
10:22:33.7813 18EA00F9 [3] 00 C1 00 (TX)
10:22:33.7848 18C1F900 [8] [00 00 00 00 00 00 01](tel:00 00 00 00 00 00 01) 00
DM21 from Engine #1 (0): [
  Distance Traveled While MIL is Activated:     0 km (0 mi)
  Time Run by Engine While MIL is Activated:    0 minutes
  Distance Since DTCs Cleared:                  0 km (0 mi)
  Time Since DTCs Cleared:                      1 minutes
]
FAIL: 6.2.9.4.b - OBD ECU Engine #1 (0) did not provide a response to Global query and did not provide a NACK for the DS query

Start Test 1.11 - DM21: Diagnostic readiness 2

10:19:55.0324 Global DM21 Request
10:19:55.0381 18EAFFF9 [3] 00 C1 00 (TX)
10:19:55.0416 18C1FF00 [8] [00 00 00 00 00 00 00](tel:00 00 00 00 00 00 00) 00
DM21 from Engine #1 (0): [
  Distance Traveled While MIL is Activated:     0 km (0 mi)
  Time Run by Engine While MIL is Activated:    0 minutes
  Distance Since DTCs Cleared:                  0 km (0 mi)
  Time Since DTCs Cleared:                      0 minutes
]
10:19:55.0504 18E8FFE8 [8] 01 FF FF FF F9 00 C1 00
Acknowledgment from Forward Road Image Processor (232): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 49408

10:19:55.6467 Destination Specific DM21 Request to Engine #1 (0)
10:19:55.6504 18EA00F9 [3] 00 C1 00 (TX)
10:19:55.6614 18C1F900 [8] [00 00 00 00 00 00 00](tel:00 00 00 00 00 00 00) 00
DM21 from Engine #1 (0): [
  Distance Traveled While MIL is Activated:     0 km (0 mi)
  Time Run by Engine While MIL is Activated:    0 minutes
  Distance Since DTCs Cleared:                  0 km (0 mi)
  Time Since DTCs Cleared:                      0 minutes
]

End Test 1.11 - DM21: Diagnostic readiness 2

**Comment by ericthomasswenson** [comment]
This pattern (seeing interfering NAC first) appears to have been repeated in Part 3.

Attempt 35

10:44:21.2291 Global DM6 Request
10:44:21.2316 18EAFFF9 [3] CF FE 00 (TX)
10:44:21.2325 18FECF17 [8] 00 FF [00 00 00 00](tel:00 00 00 00) FF FF
DM6 from Instrument Cluster #1 (23): MIL: off, RSL: off, AWL: off, PL: off, No DTCs
10:44:21.2388 18FECF00 [8] 00 FF [00 00 00 00](tel:00 00 00 00) FF FF
DM6 from Engine #1 (0): MIL: off, RSL: off, AWL: off, PL: off, No DTCs
10:44:21.2421 18E8FFE8 [8] 01 FF FF FF F9 CF FE 00
Acknowledgment from Forward Road Image Processor (232): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 65231

Attempt 36

10:44:22.8310 Global DM6 Request
10:44:22.8343 18EAFFF9 [3] CF FE 00 (TX)
10:44:22.8376 18FECF17 [8] 00 FF [00 00 00 00](tel:00 00 00 00) FF FF
DM6 from Instrument Cluster #1 (23): MIL: off, RSL: off, AWL: off, PL: off, No DTCs
10:44:22.8420 18E8FFE8 [8] 01 FF FF FF F9 CF FE 00
Acknowledgment from Forward Road Image Processor (232): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 65231
FAIL: 6.3.2.2.a - No OBD ECU supports DM6

10:44:23.4328 Destination Specific DM6 Request to Engine #1 (0)
10:44:23.4371 18EA00F9 [3] CF FE 00 (TX)
10:44:23.4487 18FECF00 [8] 00 FF [00 00 00 00](tel:00 00 00 00) FF FF
DM6 from Engine #1 (0): MIL: off, RSL: off, AWL: off, PL: off, No DTCs
FAIL: 6.3.2.5.c - OBD ECU Engine #1 (0) did not provide a response to Global query and did not provide a NACK for the DS query

End Test 3.2 - DM6: Emission related pending DTCs

**Comment by ericthomasswenson** [comment]
False failures for NACK responses are highly undesirable.
Acceptance of the engine’s positive response is indeed expected by all participants.

ETS to check example -84 text for expected nack behavior and post here.

3/10/2022 Nack handling text, J1934-84 P-18.

_F. The acknowledgement PGN provides the identification of the request in the PGN data field. The data in the field shall be matched to the data in the request **along with the address of the sender when an ACK or NACK is used to determine pass or failure outcomes**._

**Comment by ericthomasswenson** [comment]
Please provide a written description of message reception in light of interfering messages, footnote 8, and the text in F.

**Comment by battjt** [comment]
The global request logic used for all requests to global has the following intent:

1. send request to global
2. collect responses announced within 600 ms
3. if any responses are NACK 03
 3.1 send request to global
 3.2 collect responses announced within 600 ms
4. for any remaining NACK 03 responses, replace with results of a new DS request (announced within 600 ms)
5. for any remaining NACK 03 responses, replace with results of a new DS request (announced within 600 ms)

New unit tests verify this behavior.

**Comment by ericthomasswenson** [comment]
Another example of a missed response

Start Test 3.9 - DM12: Emissions related active DTCs

14:23:35.9462 Global DM12 Request
14:23:35.9476 18EAFFF9 [3] D4 FE 00 (TX)
14:23:35.9488 18FED417 [8] 04 FF 00 00 00 00 FF FF
DM12 from Instrument Cluster #1 (23): MIL: off, RSL: off, AWL: on, PL: off, No DTCs
FAIL: 6.3.9.2.d - No OBD ECU provided a DM12

14:23:36.5517 Destination Specific DM12 Request to Engine #1 (0)
14:23:36.5526 18EA00F9 [3] D4 FE 00 (TX)
14:23:36.5635 18FED400 [8] 00 FF 00 00 00 00 FF FF
DM12 from Engine #1 (0): MIL: off, RSL: off, AWL: off, PL: off, No DTCs
FAIL: 6.3.9.4.b - OBD ECU Engine #1 (0) did not provide a response to Global query and did not provide a NACK for the DS query

Start Test 4.2 - DM12: Emissions related active DTCs

Attempt 1

14:25:54.3835 Global DM12 Request
14:25:54.3857 18EAFFF9 [3] D4 FE 00 (TX)
14:25:54.3873 18FED417 [8] 04 FF 00 00 00 00 FF FF
DM12 from Instrument Cluster #1 (23): MIL: off, RSL: off, AWL: on, PL: off, No DTCs

**Comment by battjt** [comment]
Timeout has been extended to 750 ms.  Adapter evaluation is another ticket.

**Comment by battjt** [comment]
There have been mutiple changes to address this.  Is it still an issue?

**Comment by ericthomasswenson** [comment]
Let’s close this and open a new issue if it recurs.
