### ISSUE TITLE
SPN 3700 incorrect WARN - Tool Issue

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#1078]
SPN 3700 (DPF Active regeneration status) reports binary 10 (regeneration needed - automatically initiated active regeneration imminent).

Tool issue - Tool is decoding 10 binary as ERROR and issuing an incorrect WARN in Part 1 Test 26 and Part 2 Test 17.

Below is the specification for WARNING.
![image](https://user-images.githubusercontent.com/46825003/156055946-a9ea6870-188b-4d7f-9b23-3a1a719467df.png)

**Part 1 Test 26**

PGN 64892 with Supported SPNs 3700
13:34:16.6907 18FD7C00 [8] F8 FB F3 FF FF FF E3 FF
Found: DPF Control 1 from Engine #1 (0): 
  SPN  3697, DPF Lamp Command: 000
  SPN  8857, DPF Active Regeneration Availability Status: 11
  SPN  3699, AFT DPF Passive Regeneration Status: 11
  SPN  3700, AFT DPF Active Regeneration Status: 10
  SPN  3701, AFT DPF Status: 111
  SPN  3702, DPF Active Regeneration Inhibited Status: 11
  SPN  3703, DPF Active Regeneration Inhibited Due to Inhibit Switch: 00
  SPN  3704, DPF Active Regeneration Inhibited Due to Clutch Disengaged: 11
  SPN  3705, DPF Active Regeneration Inhibited Due to Service Brake Active: 11
  SPN  3706, DPF Active Regeneration Inhibited Due to PTO Active: 11
  SPN  3707, DPF Active Regeneration Inhibited Due to Accelerator Pedal Off Idle: 11
  SPN  3708, DPF Active Regeneration Inhibited Due to Out of Neutral: 11
  SPN  3709, DPF Active Regeneration Inhibited Due to Vehicle Speed Above Allowed Speed: 11
  SPN  3710, DPF Active Regeneration Inhibited Due to Parking Brake Not Set: 11
  SPN  3711, DPF Active Regeneration Inhibited Due to Low Exhaust Temperature: 11
  SPN  3712, DPF Active Regeneration Inhibited Due to System Fault Active: 11
  SPN  3713, DPF Active Regeneration Inhibited Due to System Timeout: 11
  SPN  3714, DPF Active Regeneration Inhibited Due to Temporary System Lockout: 11
  SPN  3715, DPF Active Regeneration Inhibited Due to Permanent System Lockout: 11
  SPN  3716, DPF Active Regeneration Inhibited Due to Engine Not Warmed Up: 11
  SPN  3717, DPF Active Regeneration Inhibited Due to Vehicle Speed Below Allowed Speed: 11
  SPN  3718, DPF Automatic Active Regeneration Initiation Configuration: 11
  SPN  3698, Exhaust System High Temperature Lamp Command: 000
  SPN  4175, DPF Active Regeneration Forced Status: 111
  SPN  5504, Hydrocarbon Doser Purging Enable: 11
  SPN  5629, DPF Active Regeneration Inhibited Due to Low Exhaust Pressure: 11
  SPN  3750, AFT 1 DPF Conditions Not Met for Active Regeneration: 11
  SPN 10153, DPF Active Regeneration Inhibited Due to Thresher: 11

WARN: 6.1.26.2.d - N.8 Engine #1 (0) reported value for SPN 3700 (ERROR) is implausible

**Part 2 Test 17**

PGN 64892 with Supported SPNs 3700
13:36:00.6894 18FD7C00 [8] F8 FB F3 FF FF FF E3 FF
Found: DPF Control 1 from Engine #1 (0): 
  SPN  3697, DPF Lamp Command: 000
  SPN  8857, DPF Active Regeneration Availability Status: 11
  SPN  3699, AFT DPF Passive Regeneration Status: 11
  SPN  3700, AFT DPF Active Regeneration Status: 10
  SPN  3701, AFT DPF Status: 111
  SPN  3702, DPF Active Regeneration Inhibited Status: 11
  SPN  3703, DPF Active Regeneration Inhibited Due to Inhibit Switch: 00
  SPN  3704, DPF Active Regeneration Inhibited Due to Clutch Disengaged: 11
  SPN  3705, DPF Active Regeneration Inhibited Due to Service Brake Active: 11
  SPN  3706, DPF Active Regeneration Inhibited Due to PTO Active: 11
  SPN  3707, DPF Active Regeneration Inhibited Due to Accelerator Pedal Off Idle: 11
  SPN  3708, DPF Active Regeneration Inhibited Due to Out of Neutral: 11
  SPN  3709, DPF Active Regeneration Inhibited Due to Vehicle Speed Above Allowed Speed: 11
  SPN  3710, DPF Active Regeneration Inhibited Due to Parking Brake Not Set: 11
  SPN  3711, DPF Active Regeneration Inhibited Due to Low Exhaust Temperature: 11
  SPN  3712, DPF Active Regeneration Inhibited Due to System Fault Active: 11
  SPN  3713, DPF Active Regeneration Inhibited Due to System Timeout: 11
  SPN  3714, DPF Active Regeneration Inhibited Due to Temporary System Lockout: 11
  SPN  3715, DPF Active Regeneration Inhibited Due to Permanent System Lockout: 11
  SPN  3716, DPF Active Regeneration Inhibited Due to Engine Not Warmed Up: 11
  SPN  3717, DPF Active Regeneration Inhibited Due to Vehicle Speed Below Allowed Speed: 11
  SPN  3718, DPF Automatic Active Regeneration Initiation Configuration: 11
  SPN  3698, Exhaust System High Temperature Lamp Command: 000
  SPN  4175, DPF Active Regeneration Forced Status: 111
  SPN  5504, Hydrocarbon Doser Purging Enable: 11
  SPN  5629, DPF Active Regeneration Inhibited Due to Low Exhaust Pressure: 11
  SPN  3750, AFT 1 DPF Conditions Not Met for Active Regeneration: 11
  SPN 10153, DPF Active Regeneration Inhibited Due to Thresher: 11

WARN: 6.2.17.2.b - N.8 Engine #1 (0) reported value for SPN 3700 (ERROR) is implausible

**Comment by ericthomasswenson** [comment]
The SP 3700 enumeration in J1939-84 does not map 10b to error
10b is mapped to “regeneration needed - automatically initiated active regeneration imminent”.
EMA ETSC to discuss.  
Further discussion needed.

**Comment by ericthomasswenson** [comment]
Status of 10 - Regen Imminent confirmed with EPA who will recognize this for SP 3700 in Title 40 Part 86.

Need to clarify expected handling of error status v. SPs lacking error status.

SP 3700 only observed SP thus far.

**Comment by PVEcompliance** [comment]
Title 40  Part 86.1370(d)(2) will be updated to show the same status bit meaning as defined in the J1939DA

"
00b = not active
01b = active
10b = regeneration needed - automatically initiated active regeneration imminent
11b = not available
"

**Comment by battjt** [comment]
Some enumerations like SPN 5837 have error values (FE), but SPN 3700 doesn't?  How is it specified? We could search for the word "error" in the slot definitions, but that seems error prone.

See https://github.com/Equipment-and-Tool-Institute/j1939-84/blob/release/src/org/etools/j1939tools/resources/bit-slots.csv for the current enum definitions.
The "isError" logic is here: https://github.com/Equipment-and-Tool-Institute/j1939-84/blob/802ac17efb199d47fb337a94d6d00f71818479e3/src/org/etools/j1939tools/j1939/packets/Slot.java#L180-L195

**Comment by ericthomasswenson** [comment]
Check screened value's description string for 'Error' before returning true for binary enumerations.

**Comment by battjt** [comment]
The old rule was `max_value - 1` was error.  Now, if the value has a "bit slot" definition for `max_value - 1` that does not include the word error, then the value it not an error value.

These SPN values will no longer be treated as error:
|SPN|Name|Binary|Value|
|---:|---|---:|---|
|      976 | PTO Governor State                                           |    11110 | Reserved |
|     3490 | AFT 1 Purge Air Actuator                                     |       10 | reserved for SAE assignment |
|     3543 | Engine Operating State                                       |     1110 | \<reserved\> |
|     3700 | AFT DPF Active Regeneration Status                           |       10 | regeneration needed - automatically initiated active regeneration imminent |
|     4127 | NOx NTE Control Area Status                                  |       10 | Reserved |
|     4128 | Manufacturer-specific NOx NTE Carve-out Area Status          |       10 | Reserved |
|     4129 | NOx NTE Deficiency Area Status                               |       10 | Reserved |
|     4130 | PM NTE Control Area Status                                   |       10 | Reserved |
|     4131 | Manufacturer-specific PM NTE Carve-out Area Status           |       10 | Reserved |
|     4132 | PM NTE Deficiency Area Status                                |       10 | Reserved |
|     5457 | Engine Variable Geometry Turbocharger 1 Control Mode         |       10 | SAE reserved |
|     5843 | Engine Warm-up Sequence                                      |       10 | SAE reserved |
|     7315 | Propulsion System Active                                     |       10 | SAE Reserved |

**Comment by battjt** [comment]
What about SPN 13171 DC Charging State?  Values of 13 and 14 both include the word "error".
