### ISSUE TITLE
Incorrect timing count in the J1939-84 test summary report outcome

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#1079]
The timing error count in the test summary report outcome is incorrect. When there is no timing: late responses in the report file, there is one count of timing reported. Attached the report file and j1939_84xx.log files for root cause finding
[report2468311710962679495J1939-84.txt](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/8164570/report2468311710962679495J1939-84.txt)
[j1939_8431.txt](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/8164580/j1939_8431.txt)
[j1939_8432.txt](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/8164581/j1939_8432.txt)
[j1939_8433.txt](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/8164582/j1939_8433.txt)
.

**Comment by ericthomasswenson** [comment]
Timing error count in the header was not observed in the detail report as shown in the exhibits. It is believed such errors may be improved when the response time calculations are directly shown in the log.

Recurrences in the candidate releases will be used to start an investigation

**Comment by battjt** [comment]
The timing count is not cleared immediately before the report, so the calibration request could have registered a late packet that was not reported.  The fix is to clear the timing warnings immediately before the report.

**Comment by ericthomasswenson** [comment]
Fixed in 3.1.0
