### ISSUE TITLE
Reconfiguring adapter causes multiple requests for each button press

### ISSUE THREAD

**Issue by battjt** [Equipment-and-Tool-Institute/j1939-84#1080]
Each time we reconfigured the adapter, we added another handler. If you switched from auto to 500 and back to auto, you will see 3 requests sent for each request that should be sent. Reconfiguring the adapter again, would have resulted in 4 packets sent.

Close old adapter handlers when opening new.

**Comment by ericthomasswenson** [comment]
Jacob Bosch & Vimal Muthukumar have also observed this in 3.0.13.

**Comment by ericthomasswenson** [comment]
Confirmed on bench

To be included in 1st candidate release

**Comment by ericthomasswenson** [comment]
No recent complaints that this is still an issue.
