### ISSUE TITLE
Tool flagging PGN 7424 broadcast rate

### ISSUE THREAD

**Issue by jacobbosch-cummins** [Equipment-and-Tool-Institute/j1939-84#1083]
The J1939DA lists the broadcast rate of PGN 7424 as "Engine speed dependent".  We are observing the message below on our spark ignited products.

PGN 7424 from Engine #1 (0)
09:54:39.1013 0C1DFF00 [8] 7A 66 FF FF FF FF FF FF
09:54:39.1513 0C1DFF00 [8] 7A 66 FF FF FF FF FF FF
09:54:39.2014 0C1DFF00 [8] 7A 66 FF FF FF FF FF FF
FAIL: 6.1.26 - Broadcast period of PGN 7424 (49 ms) by ECU Engine #1 (0) is less than 90% specified broadcast period of 100 ms.

Recommend disabling the diagnostic for PGNs that may have variable transmission rates.

**Comment by ericthomasswenson** [comment]
PG 7424 has no default period, assumption of 100 ms is incorrect

7424 | Engine Ignition Controller | EIC | Commanded engine ignition timing advance | 0 | 0 | 29 | DA | No | **_Engine speed dependent_**

**Comment by ericthomasswenson** [comment]
Review Table A-1 notes for period and discuss engine speed dependent 

Add comment on broadcast period to 6.1.26.2.b.

**Comment by ericthomasswenson** [comment]
PG 7424 is EIC (Engine Ignition Controller)

**Comment by ericthomasswenson** [comment]
Update text in 6.1.26, 6.2.17, and Table A.1 to suit this request to excuse engine speed dependent messages.

**Comment by ericthomasswenson** [comment]
See common request #1223

**Comment by ericthomasswenson** [comment]
6.1.26.3.b.	Fail if any parameter, **_other than those in an engine speed dependent PG_**, is not broadcast within ±10% of the specified broadcast period.  

6.2.17.3.b.	Fail if any parameter, **_other than those in an engine speed dependent PG,_** is not broadcast within ±10% of the specified broadcast period.

**Comment by ericthomasswenson** [comment]
This may be implemented prior to the completion of the draft artifact.

**Comment by ericthomasswenson** [comment]
This construct may be used for engine speed dependent content from J1939DA.

**Comment by battjt** [comment]
PgnDefinition already has a isVariableBroadcast flag. **Development**, verify that this flag is correctly interpretted for the SPNs in question. No DA parsing changes should be needed.

**Comment by karysg** [comment]
[variableRatePGNReport.csv](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/13343055/variableRatePGNReport.csv)

Attached file lists the signals that have a variable broadcast rate. Proposed fix eliminates check for these signals being broadcast at a minimum rate.

**Comment by battjt** [comment]
bi-weekly meeting Nov 17 2023: Fix all from the report.  CARB informed Nov 14 2023.

**Comment by jacobbosch-cummins** [comment]
This is still present in 3.1.25.

PGN 7424 from Engine #1 (0)
14:07:14.5443 0C1DFF00 [8] 80 68 FF FF FF FF FF FF
14:07:14.5945 0C1DFF00 [8] 80 68 FF FF FF FF FF FF
14:07:14.6443 0C1DFF00 [8] 80 68 FF FF FF FF FF FF
FAIL: 6.1.26 - Broadcast period of PGN 7424 (49 ms) by ECU Engine #1 (0) is less than 90% specified broadcast period of 100 ms.

...


PGN 7424 from Engine #1 (0)
14:09:30.8485 0C1DFF00 [8] 51 69 FF FF FF FF FF FF
14:09:30.8988 0C1DFF00 [8] 51 69 FF FF FF FF FF FF
14:09:30.9486 0C1DFF00 [8] 51 69 FF FF FF FF FF FF
FAIL: 6.2.17 - Broadcast period of PGN 7424 (49 ms) by ECU Engine #1 (0) is less than 90% specified broadcast period of 100 ms.

**Comment by jacobbosch-cummins** [comment]
It is present in 3.1.26 as well.
