### ISSUE TITLE
Table A.1 allows multiple ECUs to provide SPN 2978, but flagged by tool

### ISSUE THREAD

**Issue by jacobbosch-cummins** [Equipment-and-Tool-Institute/j1939-84#1084]
Table A.1 doesn't require a diagnostic if multiple ECUs provide SPN 2978.  Additionally, Table A.1 does require a failure if provided by a non-OBD device, but the J1939DA allows multiple ancillary devices to provide SPN 2978.

PGN 65247 with Supported SPNs 514, 2978
13:05:57.2070 18FEDF00 [8] 7D A0 28 7D 7D FF FF F0
Found: Electronic Engine Controller 3 from Engine #1 (0):
SPN 514, Nominal Friction - Percent Torque: 0.000000 %
SPN 515, Engine's Desired Operating Speed: 1300.000000 rpm
SPN 519, Engine's Desired Operating Speed Asymmetry Adjustment: 125.000000
SPN 2978, Estimated Engine Parasitic Losses - Percent Torque: 0.000000 %
SPN 3236, AFT 1 Exhaust Gas Mass Flow Rate: Not Available
SPN 3237, AFT 1 Intake Dew Point: 00
SPN 3238, AFT 1 Exhaust Dew Point: 00
SPN 3239, AFT 2 Intake Dew Point: 11
SPN 3240, AFT 2 Exhaust Dew Point: 11

PGN 65247 with Supported SPNs 514, 2978
13:05:57.2398 18FEDF4E [8] FF FF FF FF 7D FF FF FF
Found: Electronic Engine Controller 3 from Fan Drive Controller (78):
SPN 514, Nominal Friction - Percent Torque: Not Available
SPN 515, Engine's Desired Operating Speed: Not Available
SPN 519, Engine's Desired Operating Speed Asymmetry Adjustment: Not Available
SPN 2978, Estimated Engine Parasitic Losses - Percent Torque: 0.000000 %
SPN 3236, AFT 1 Exhaust Gas Mass Flow Rate: Not Available
SPN 3237, AFT 1 Intake Dew Point: 11
SPN 3238, AFT 1 Exhaust Dew Point: 11
SPN 3239, AFT 2 Intake Dew Point: 11
SPN 3240, AFT 2 Exhaust Dew Point: 11

FAIL: 6.1.26.2.e - N.6 SPN 2978 provided by non-OBD ECU Fan Drive Controller (78)
FAIL: 6.1.26.2.f - N.5 SPN 2978 provided by more than one ECU

**Comment by ericthomasswenson** [comment]
The ballot draft says: Fail for ‘Action if SPN Provided by Non-OBD Module’ and ‘Action if SPN Provided but Not Included in DM24’ 

| 2978* | Estimated Engine Parasitic Losses - Percent Torque | 65247 | BC 250 ms or RPM Dependent | Yes  | No | No | None |  N/A | **_Fail_** | **_Fail_** | > 0%  |  <= 0%  |

**Comment by ericthomasswenson** [comment]
Closed as invalid
