### ISSUE TITLE
J1939-84 User Community Communications Check

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1085]
Please leave a comment to verify your access to create comments in this GitHub repository.

In the blank comment dialog box, enter your GitHub user name and today’s date

The ability to add new issues may be assessed at a later date.

An example response is provided below.

**Comment by ericthomasswenson** [comment]
ericthomasswenson — 03/17/2022

**Comment by gumbelmj** [comment]
@gumbelmj 03/17/2022

**Comment by naroner** [comment]
naroner -- 3/18/2022 (Nathan Roner - Detroit Diesel)

**Comment by anthonyhbest** [comment]
anthonyhbest - 3/18/2022 (Anthony Best - PACCAR)

**Comment by jacobbosch-cummins** [comment]
jacobbosch-cummins - 3/18/22 (Jacob Bosch - Cummins)

**Comment by vmuthu2** [comment]
vmuthu2 - 03/18/2022 (Vimal Muthukumar - PACCAR)

**Comment by PVEcompliance** [comment]
Bob Halfman - 18mar2022

**Comment by mmschaefer** [comment]
@mmschaefer - 3/18/2022

**Comment by GovindarajKarthik** [comment]
GovindarajKarthik - 03/18/2022 ( Karthik Govindaraj - Detroit Diesel)

**Comment by DPatasky** [comment]
David Patasky - March 18th 2022.

**Comment by tgolub1** [comment]
Tom Golub -- 19 MAR 2022

**Comment by battjt** [comment]
Joe Batt - 19 MAR 2022

**Comment by markmorrisoncummins** [comment]
Mark Morrison (Cummins) - 03/21/2022

**Comment by ericthomasswenson** [comment]
All users have responded. Thank you all.

The developer’s team also responded.  

You may see Joe, Matt, and Marianne comment on your issues in the future.

**Comment by ericthomasswenson** [comment]
Everyone responded.
