### ISSUE TITLE
Tool Fails for FF when Multiple DTCs are Present

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1090]
**Tool fails FF when there is more than 1 DTC present, it appears the tool expected equal number of FF to DTCs. However this isn't required: 1971.1 (h)(4.3.3) - (4.3.3) Only one frame of data is required to be recorded. Manufacturers may choose to store additional frames provided that at least the required frame can be read by a scan tool meeting SAE J1978**

18:16:50.1241 Destination Specific DM25 Request to Exhaust Emission Controller (61)
18:16:50.1276 18EA3DF9 [3] B7 FD 00 (TX)
18:16:50.5156 18FDB73D [131] 82 **_A9 F0 F0_** 01 14 02 00 00 00 00 00 07 00 00 00 3B 32 C7 3D 50 01 FD 00 50 23 8A 24 00 00 00 16 00 00 7D 7D 80 51 80 25 00 32 A0 42 BD B3 E0 E1 D2 F2 05 00 00 00 64 00 64 00 64 00 64 00 64 00 64 00 64 9B 24 D4 00 00 88 23 32 70 94 34 60 28 54 25 E8 27 00 00 00 00 DA 03 32 00 00 00 00 00 00 00 01 07 3A 02 00 0D 74 23 00 00 60 28 E8 27 35 03 00 00 00 00 00 00 1E 01 98 1E 04 FF FF 00 00 EF 03
DM25 from Exhaust Emission Controller (61): 
Freeze Frames: [
  Freeze Frame: {
    DTC 520361:16 - Manufacturer Assignable SPN, Data Valid But Above Normal Operating Range - Moderately Severe Level - 1 times
    SPN Data: 14 02 00 00 00 00 00 07 00 00 00 3B 32 C7 3D 50 01 FD 00 50 23 8A 24 00 00 00 16 00 00 7D 7D 80 51 80 25 00 32 A0 42 BD B3 E0 E1 D2 F2 05 00 00 00 64 00 64 00 64 00 64 00 64 00 64 00 64 9B 24 D4 00 00 88 23 32 70 94 34 60 28 54 25 E8 27 00 00 00 00 DA 03 32 00 00 00 00 00 00 00 01 07 3A 02 00 0D 74 23 00 00 60 28 E8 27 35 03 00 00 00 00 00 00 1E 01 98 1E 04 FF FF 00 00 EF 03
  }
]

FAIL: 6.7.12.2.b - Exhaust Emission Controller (61) did not reported DTC in Freeze Frame data which included the DTC provided by DM23 earlier in this part

**From previous DM23:**
18:16:43.7720 Destination Specific DM23 Request to Exhaust Emission Controller (61)
18:16:43.7751 18EA3DF9 [3] B5 FD 00 (TX)
18:16:43.8171 18FDB53D [10] 03 FF **A9 F0 F0** 01 **A9 F0 E2** 01
DM23 from Exhaust Emission Controller (61): MIL: off, RSL: off, AWL: off, PL: not supported
DTC 520361:16 - Manufacturer Assignable SPN, Data Valid But Above Normal Operating Range - Moderately Severe Level - 1 times
DTC 520361:2 - Manufacturer Assignable SPN, Data Erratic, Intermittent Or Incorrect - 1 times

**Comment by ericthomasswenson** [comment]
The test procedure says implant 1 DTC and not 2.  (For both Fault A and Fault B)
Is it not possible to implant just one fault?

Which DTC of the two provided in the DM23 is to be expected in the FF?
How is the tool supposed to know?

The tool will reliably find 1 DTC in a list of FFs.

SAE J1979-73 capabilities are the test subject not J1978 capabilities
Indeed 13 CCR 1971.1 (d) and (h) are bifurcated by J1979 and J1939.

**Comment by ericthomasswenson** [comment]
Future implant methods will elicit a single DTC in the future
