### ISSUE TITLE
Tool Doesn't Handle SNA Correctly During DM29

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1092]
**The tool interprets SNA as > 0 during the parsing of the DM29 response. Our controllers don't support DM27 and will make the "All Pending DTC Count" in DM29 as SNA** 

19:04:53.4112 Global DM29 Request
19:04:53.4122 18EAFFF9 [3] 00 9E 00 (TX)
19:04:53.4146 189EFF3D [8] 00 **_FF_** 00 00 00 FF FF FF
DM29 from Exhaust Emission Controller (61): 
Emission-Related Pending DTC Count                               0
All Pending DTC Count                                **_not available_**
Emission-Related MIL-On DTC Count                                0
Emission-Related Previously MIL-On DTC Count                     0
Emission-Related Permanent DTC Count                             0
19:04:53.4187 189EFF01 [8] 00 **_FF_** 00 01 00 FF FF FF
DM29 from Engine #2 (1): 
Emission-Related Pending DTC Count                               0
All Pending DTC Count                                **_not available_**
Emission-Related MIL-On DTC Count                                0
Emission-Related Previously MIL-On DTC Count                     1
Emission-Related Permanent DTC Count                             0
**_FAIL: 6.7.10.2.a - Engine #2 (1) reported > 0 for all pending
FAIL: 6.7.10.2.a - Exhaust Emission Controller (61) reported > 0 for all pending_**

**Comment by ericthomasswenson** [comment]
Parameter Group Number: 40448 (009E0016) (DM29)
Byte: 1  Emission-related pending DTC count see 5.7.29.1 
**_Byte: 2  All pending DTC count see 5.7.29.2 (DM27 Count)_**  
Byte: 3  Emission-related MIL-On DTC count see 5.7.29.3 
Byte: 4  Emission-related previously MIL-On DTC count see 5.7.29.4 
Byte: 5  Emission-related permanent DTC count see 5.7.29.5 
Bytes: 6-8  Reserved for SAE assignment

**Comment by ericthomasswenson** [comment]
It looks like 6.7.10 didn’t get the same treatment for DM27 as other locations.

6.7.10 DM29: Regulated DTC Counts 
6.7.10.1 Actions 
a. Global DM29 [send Request (PG 59904) for PG 40448 (SPs 4104-4108)].
6.7.10.2 Fail Criteria 
**_a. Fail if any ECU reports > 0 for pending, all pending, MIL on, or permanent._** 

6.1.22 DM29: Regulated DTC Counts 6.1.22.1 Actions a. Global DM29 [send Request (PG 59904) for PG 40448 (SPNSPs 4104-4108)].
6.1.22.2 Fail Criteria 
a. For ECUs that support DM27, fail if any ECU does not report pending/all pending/MIL on/previous MIL on/permanent = 0/0/0/0/0. [27]
b. For ECUs that do not support DM27, fail if any ECU does not report pending/all pending/MIL on/previous MIL on/permanent = 0/FFh /0/0/0.  
c. For non-OBD ECUs, fail if any ECU reports pending, MIL-on, previously MIL-on or permanent DTC count greater than 0. d. Fail if no OBD ECU provides DM29.  

[27] The count of number of fault codes for “‘all pending”’ DTCs corresponds to the number of pending fault DTCs reported by DM27. If DM27 is not supported by an ECU, all DM29 responses from that ECU should report 0xFFh for the number of all pending DTCs (SPN 4105). A fail shall be noted for an ECU that does not support DM27, but does report something other than 0xFFh for SPN 4105 in a DM29 response. 

6.2.12 DM29: Regulated DTC Counts 
6.2.12.1 Actions 
a. Global DM29 [send Request (PGNPG 59904) for PGNPG 40448 (SPNSPs 4104-4108)].
6.2.12.2 Fail Criteria 
a. For OBD ECUs that did support DM27 in step 6.2.10, fail if any ECU does not report pending/all pending/MIL on/previously MIL on/permanent = 0/0/0/0/0. 
b. For OBD ECUs that did not support DM27 in step 6.2.10, fail if any ECU does not report pending/all pending/MIL on/previous MIL on/permanent = 0/FFh/0/0/0. 
c. For non-OBD ECUs, fail if any ECU reports any pending, MIL-on, previously MIL-on, or permanent DTC count that is greater than 0 
d. Fail if no OBD ECU provides DM29. 

6.3.4 DM29: Regulated DTC Counts 
6.3.4.1 Actions 
a. Global DM29 [send Request (PG 59904) forPG 40448 (SPNSPs 4104-4108)].
6.3.4.2 Fail Criteria 
a. Fail if any ECU reports > 0 for MIL on, previous MIL on, or permanent fault counts. 
b. Fail if no ECU reports > 0 emission-related pending (SPNSP 4104). 
c. Fail if any ECU reports a different number of emission-related pending DTCs than what that ECU reported in DM6 earlier in this part. 
d. For OBD ECUs that support DM27, fail if any ECU reports a lower number of all pending DTCs (SP 4105) than the number of emission-related pending DTCs. 
e. For OBD ECUs that support DM27, fail if any ECU reports a lower number of all pending DTCs than what that ECU reported in DM27 earlier in this part. 
f. For OBD ECUs that do not support DM27, fail if any ECU does not report number of all pending DTCs =FFh.  
g. For non-OBD ECUs, fail if any ECU reports pending, MIL-on, previously MIL-on or permanent DTC count greater than 0.

**Comment by ericthomasswenson** [comment]
6.5.5.2 says
e. For OBD ECUs that support DM27,
i. Fail if any ECU reports > 0; for all pending DTCs (SP 4105).
ii. Fail if any ECU reports 0xFFh, for all pending DTCs.
f. For ECUs that do not support DM27,
i. Fail if any ECU does not report number of all pending DTCs (SP 4105) = FFh.

6.6.8.2 says
f. For ECUs that support DM27, fail if any ECU reports an all pending DTC (DM27) (SPNSP 4105) count that is less than its pending DTC (DM6) count. 
g. For ECUs that do not support DM27, fail if any ECU does not report number of all pending DTCs = 0xFFh. 

6.8.8.2 says
h. For ECUs that support DM27, fail if any ECU reports > 0 for all pending DTCs (SP 4105). 
i. For ECUs that do not support DM27, fail if any ECU does not report number of all pending DTCs = 0xFFh. 

6.9.15.2 says
d. For OBD ECUs that support DM27, fail if any ECU reports > 0 for all pending DTCs (SP 4105). 
e. For OBD ECUs that do not support DM27, fail if any ECU does not report number of all pending DTCs = 0xFFh. 

6.11.4.2 says
c. For ECUs that support DM27, fail if any ECU reports > 0 for all pending DTCs (SPNSP 4105). 
d. For ECUs that do not support DM27, fail if any ECU does not report number of all pending DTCs = 0xFFh. 

6.12.5.2 Fail Criteria 
a. Fail if any ECU reports > 0 for emission-related pending, MIL-on, previous MIL on, or permanent DTC. 
b. For OBD ECUs that support DM27, fail if any ECU reports > 0 for all pending DTCs (SP 4105). 
c. For OBD ECUs that do not support DM27, fail if any ECU does not report number of all pending DTCs =FFh. 
d. Fail if no OBD ECU provides a DM29 message.

**Comment by ericthomasswenson** [comment]
Duplicates  #1181
