### ISSUE TITLE
Aggregated Table A-1 Changes

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1094]
See link to updated Table A-1 below. The 9/15/21 link is now obsolete.
The Table A-1 version from 09/15/2021 is expected to address the following individual items

#859
#970 
#971
#972
#1065 

Sept 15, 2021 Table A-1 is now obsolete.  See May 13, 2022 for revised content.
https://github.com/Equipment-and-Tool-Institute/j1939-84/files/7171010/J1939-84-Table-A-1-MY24.15Sept2021.docx

**Comment by ericthomasswenson** [comment]
Also 

https://github.com/Equipment-and-Tool-Institute/j1939-84/issues/820, https://github.com/Equipment-and-Tool-Institute/j1939-84/issues/818, https://github.com/Equipment-and-Tool-Institute/j1939-84/issues/982,

**Comment by ericthomasswenson** [comment]
Changes were not observed in 3.1.0

**Comment by ericthomasswenson** [comment]
Duplicate Rows Removed. Def This Cycle Added.

[J1939-84-Table-A-1-MY24-13May2022.docx](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/8691917/J1939-84-Table-A-1-MY24-13May2022.docx)

**Comment by ericthomasswenson** [comment]
Column 4 yes to warn change

Sept 6 Update for DEF quantity SPs and Column 4 change

[J1939-84-Table-A-1-MY24-Aug-30-2022-v1.docx](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/9539521/J1939-84-Table-A-1-MY24-Aug-30-2022-v1.docx)

**Comment by anthonyhbest** [comment]
@ericthomasswenson in the latest task5v3 documentthe SPN 84 data did not carryover the INFOs in place of the WARNs:

![image](https://user-images.githubusercontent.com/94923793/207180610-d35bdb2c-9a16-4939-8711-ebac7b74d627.png)
