### ISSUE TITLE
Disparate Timers EI-AECD Timers Not Matched in Distributed DM33 Responses

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1095]
SA 1 and SA 61 support distinct index numbers for EI-AECD timing labels.

This example where each SA provides the same response for Global and DS queries should be accepted without error, as the timer index numbers are not shared across SA 1 and SA 61.  

Where there shared index numbers, the shared timer values would have been expected to be the same.

**_SA 61 response was not observed to global query_** This May have cascaded to part 9.

—-

End Test 2.14 - DM25: Expanded freeze frame

Start Test 2.15 - DM33: Emission increasing AECD active time

14:38:49.3592 Global DM33 Request
14:38:49.3607 18EAFFF9 [3] 00 A1 00 (TX)
14:38:49.5191 18A1FF01 [18] 01 00 00 00 00 00 00 00 00 05 03 00 00 00 00 00 00 00
DM33 Emission Increasing AECD Active Time from Engine #2 (1): [
  EI-AECD Number = 1: Timer 1 = 0 minutes; Timer 2 = 0 minutes
  EI-AECD Number = 5: Timer 1 = 3 minutes; Timer 2 = 0 minutes
]

14:38:49.9713 Destination Specific DM33 Request to Engine #1 (0)
14:38:49.9747 18EA00F9 [3] 00 A1 00 (TX)
14:38:49.9811 18E8FF00 [8] 01 FF FF FF F9 00 A1 00
Acknowledgment from Engine #1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 41216

14:38:49.9817 Destination Specific DM33 Request to Engine #2 (1)
14:38:49.9838 18EA01F9 [3] 00 A1 00 (TX)
14:38:50.0492 18A1F901 [18] 01 00 00 00 00 00 00 00 00 05 03 00 00 00 00 00 00 00
DM33 Emission Increasing AECD Active Time from Engine #2 (1): [
  EI-AECD Number = 1: Timer 1 = 0 minutes; Timer 2 = 0 minutes
  EI-AECD Number = 5: Timer 1 = 3 minutes; Timer 2 = 0 minutes
]

14:38:50.0518 Destination Specific DM33 Request to Exhaust Emission Controller (61)
14:38:50.0531 18EA3DF9 [3] 00 A1 00 (TX)
14:38:50.0954 18A1F93D [27] 02 00 00 00 00 FF FF FF FF 03 00 00 00 00 FF FF FF FF 04 61 00 00 00 FF FF FF FF
DM33 Emission Increasing AECD Active Time from Exhaust Emission Controller (61): [
  EI-AECD Number = 2: Timer 1 = 0 minutes; Timer 2 = n/a
  EI-AECD Number = 3: Timer 1 = 0 minutes; Timer 2 = n/a
  EI-AECD Number = 4: Timer 1 = 97 minutes; Timer 2 = n/a
]

FAIL: 6.2.15.5.a - Exhaust Emission Controller (61) did not return timer 2 in both responses
FAIL: 6.2.15.5.a - Exhaust Emission Controller (61) did not return timer 3 in both responses
FAIL: 6.2.15.5.a - Exhaust Emission Controller (61) did not return timer 4 in both responses
FAIL: 6.2.15.5.b - OBD ECU Exhaust Emission Controller (61) did not provide a response to Global query and did not provide a NACK for the DS query

End Test 2.15 - DM33: Emission increasing AECD active time

**Comment by ericthomasswenson** [comment]
#1049 May be failing for the wrong reason.

**Comment by ericthomasswenson** [comment]
Start Test 9.7 - DM33: Emission increasing AECD active time

15:26:28.6042 Global DM33 Request
15:26:28.6057 18EAFFF9 [3] 00 A1 00 (TX)
15:26:28.8117 18A1FF3D [27] 02 00 00 00 00 FF FF FF FF 03 00 00 00 00 FF FF FF FF 04 63 00 00 00 FF FF FF FF
DM33 Emission Increasing AECD Active Time from Exhaust Emission Controller (61): [
  EI-AECD Number = 2: Timer 1 = 0 minutes; Timer 2 = n/a
  EI-AECD Number = 3: Timer 1 = 0 minutes; Timer 2 = n/a
  EI-AECD Number = 4: Timer 1 = 99 minutes; Timer 2 = n/a
]

15:26:28.8112 18A1FF01 [18] 01 00 00 00 00 00 00 00 00 05 03 00 00 00 00 00 00 00
DM33 Emission Increasing AECD Active Time from Engine #2 (1): [
  EI-AECD Number = 1: Timer 1 = 0 minutes; Timer 2 = 0 minutes
  EI-AECD Number = 5: Timer 1 = 3 minutes; Timer 2 = 0 minutes
]

FAIL: 6.9.7.2.a - Exhaust Emission Controller (61) reported a different number of EI-AECD timers than was reported in part 2
_**So the missed global query response in Part 2 resulted in this message**_ 

End Test 9.7 - DM33: Emission increasing AECD active time

15:26:42.7545 Destination Specific DM33 Request to Exhaust Emission Controller (61)
15:26:42.7564 18EA3DF9 [3] 00 A1 00 (TX)
15:26:42.8018 18A1F93D [27] 02 00 00 00 00 FF FF FF FF 03 00 00 00 00 FF FF FF FF 04 63 00 00 00 FF FF FF FF
DM33 Emission Increasing AECD Active Time from Exhaust Emission Controller (61): [
  EI-AECD Number = 2: Timer 1 = 0 minutes; Timer 2 = n/a
  EI-AECD Number = 3: Timer 1 = 0 minutes; Timer 2 = n/a
  EI-AECD Number = 4: Timer 1 = 99 minutes; Timer 2 = n/a
]

FAIL: 6.9.8.4.b - One or more than one ECU erased diagnostic information and one or more other ECUs did not erase diagnostic information

_**So the missed global query DM33 response in Part 2 resulted in this message too?**_ 

Start Test 9.24 - DM33: Emission increasing AECD active time

15:27:29.2094 Destination Specific DM33 Request to Engine #1 (0)
15:27:29.2108 18EA00F9 [3] 00 A1 00 (TX)
15:27:29.2191 18E8FF00 [8] 01 FF FF FF F9 00 A1 00
Acknowledgment from Engine #1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 41216

15:27:29.2191 Destination Specific DM33 Request to Engine #2 (1)
15:27:29.2213 18EA01F9 [3] 00 A1 00 (TX)
15:27:29.2931 18A1F901 [18] 01 00 00 00 00 00 00 00 00 05 03 00 00 00 00 00 00 00
DM33 Emission Increasing AECD Active Time from Engine #2 (1): [
  EI-AECD Number = 1: Timer 1 = 0 minutes; Timer 2 = 0 minutes
  EI-AECD Number = 5: Timer 1 = 3 minutes; Timer 2 = 0 minutes
]


15:27:29.2952 Destination Specific DM33 Request to Exhaust Emission Controller (61)
15:27:29.2968 18EA3DF9 [3] 00 A1 00 (TX)
15:27:29.3428 18A1F93D [27] 02 00 00 00 00 FF FF FF FF 03 00 00 00 00 FF FF FF FF 04 63 00 00 00 FF FF FF FF
DM33 Emission Increasing AECD Active Time from Exhaust Emission Controller (61): [
  EI-AECD Number = 2: Timer 1 = 0 minutes; Timer 2 = n/a
  EI-AECD Number = 3: Timer 1 = 0 minutes; Timer 2 = n/a
  EI-AECD Number = 4: Timer 1 = 99 minutes; Timer 2 = n/a
]

FAIL: 6.9.24.2.a - ECU Exhaust Emission Controller (61) reported a different number EI-AECD here (3) and reported (0) in part 2


_**So the missed global query DM33 response in Part 2 resulted in this message too?**_ 
_**The timer criteria passed**_ 

End Test 9.24 - DM33: Emission increasing AECD active time

**Comment by ericthomasswenson** [comment]
Need repeat with same distributed system.

**Comment by ericthomasswenson** [comment]
A potential back to back CTS experience, as more recently observed for DM19.

**Comment by ericthomasswenson** [comment]
Recheck on 3.1.5 log, as to global message reception.

No detailed criteria changes perceived at this time.

**Comment by battjt** [comment]
Review StepController.save(Packet) to verify that the DS responses are saved and not the Global reponses.

**Comment by ericthomasswenson** [comment]
No criteria changes will be made to enforce unique AECD numbers across all responding devices at this time, as there is no objective requirement from the regulator.

**Comment by battjt** [comment]
No bug?  Should this be unassigned from development?

**Comment by ericthomasswenson** [comment]
Let’s create a new issue should DM33 reception issue recur.
