### ISSUE TITLE
Consolidated DM5 Future Enhancements 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1099]
Consolidated DM5 Outcome Improvements other than Status Bit improvements for Table A-6-1 and A-6-2.

Current DM5 Issues consolidated by this issue.

https://github.com/Equipment-and-Tool-Institute/j1939-84/issues/968 
https://github.com/Equipment-and-Tool-Institute/j1939-84/issues/1032 
Reduce Severity of Non OBD Responses (with no status bit support) to Info

https://github.com/Equipment-and-Tool-Institute/j1939-84/issues/515 
Enhance OBD Device Recognition:
Add a warning message specifically for 0, FB, FC, FD, And FE.
Expand the definition of devices qualified as HD OBD ECUs (as needed)

Task 5 requires recognition of XEV/BEV, provide for 1Bh (27) now to avoid changing these tests twice.

**Comment by ericthomasswenson** [comment]
Proposed Text and Rationale (Ready for Review)

[Consolidated-DM5-Issues-n1099.docx](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/8423623/Consolidated-DM5-Issues-n1099.docx)

**Comment by ericthomasswenson** [comment]
DM5 concepts reviewed 4/15/2022.  These consolidated suggestions are ready to go.

**Comment by ericthomasswenson** [comment]
These changes in consolidated text for section 6.

**Comment by ericthomasswenson** [comment]
The following issues were closed as consolidated text superseding them is now available.

https://github.com/Equipment-and-Tool-Institute/j1939-84/issues/968
https://github.com/Equipment-and-Tool-Institute/j1939-84/issues/1032
https://github.com/Equipment-and-Tool-Institute/j1939-84/issues/515

**Comment by anthonyhbest** [comment]
Were we expecting these issues to be resolved in v3.1.4 since this issue is listed as "closed"?

**Comment by ericthomasswenson** [comment]
Blue items in The task 5 artifact may have been done early … 
This was closed in favor of the consolidated text, principally.

**Comment by anthonyhbest** [comment]
I am still encountering some of these issues in v3.1.9.  
The proposed draft text above does not appear to include the change from WARN to INFO for DM5 responses in sections 6.1.13.2.a and 6.2.2.2.a.  These sections point to "Section A.6.3.a" of the specification which still includes the wording below as of the latest draft release:
![image](https://user-images.githubusercontent.com/94923793/197067191-fce7e79a-8228-44e2-b41e-222db31df2cb.png)

**Example from v3.1.9 testing:**
12:05:31.4143 Global DM5 Request
12:05:31.4168 18EAFFF9 [3] CE FE 00 (TX)
12:05:31.4180 18FECE03 [8] 00 00 05 00 00 00 00 00
DM5 from Transmission #1 (3): _OBD Compliance: Not intended to meet OBD II requirements (5)_, Active Codes: 0, Previously Active Codes: 0

WARN: 6.1.13.2.a (A6.3.a) - Non-OBD ECU Transmission #1 (3) responded

12:07:17.9712 Global DM5 Request
12:07:17.9748 18EAFFF9 [3] CE FE 00 (TX)
12:07:17.9792 18FECE03 [8] 00 00 05 00 00 00 00 00
DM5 from Transmission #1 (3): _OBD Compliance: Not intended to meet OBD II requirements (5)_, Active Codes: 0, Previously Active Codes: 0

WARN: 6.2.2.2.a (A6.3.a) - Non-OBD ECU Transmission #1 (3) responded

**Comment by ericthomasswenson** [comment]
This issue was closed with the creation of new text in the task 5 artifact.

The change from warn to info was an omission in that artifact.

**Comment by ericthomasswenson** [comment]
6.1.13	DM5: Diagnostic Readiness 1: Monitor Readiness
6.1.13.1	Actions
a.	Global DM5 [send Request (PG 59904) for PG 65230 (SPs 1218-1223)].
b.	Display monitor readiness composite value in log for OBD ECU replies only. 
6.1.13.2	Fail/Warn Criteria
a.	Fail/warn per Section A.6, Criteria for Readiness 1 Evaluation. 
b.	Fail if no OBD ECU reports DTC counts of 0 for both active and previously active faults.
c.	Fail if no OBD ECU provides DM5 with readiness bits showing monitor support.
d.	Warn if any individual required monitor, except Continuous Component Monitoring (CCM) is supported by more than one OBD ECU.      // Delete d. Per #1151. Added strike through font format.
6.1.13.3	Actions2
a.	DS DM5 to each OBD ECU.
6.1.13.4	Fail Criteria
a.	Fail if any difference compared to data received during global request.
b.	Fail if NACK not received from OBD ECUs that did not respond to global query.
6.1.14	DM26: Diagnostic Readiness 3 
6.1.14.1	Actions
a.	Global DM26 [send Request (PG 59904) for PG 64952 (SPs [3301-3305](tel:3301-3305))].
i.	Create list by OBD ECU address of all data and current status for use later in the test. 
b.	Display monitor readiness composite value in log for OBD ECU replies only. 
6.1.14.2	Fail Criteria
a.	Fail if any response for any monitor supported in DM5 by a given ECU is reported as “0=monitor complete this cycle or not supported” in SP 3303 bits 1-4 and SP 3305 [except comprehensive components monitor (CCM)].                         // and except misfire for MY 2019+ engines.
b.	Fail if any response for each monitor not supported in DM5 by a given ECU is also reported in DM26 as “1=monitor not complete this monitoring cycle” in SP 3303 bits 5-7.
c.	Fail if any response for each monitor not supported in DM5 by a given ECU is also reported in DM26 as “0=monitor enabled for this monitoring cycle” in SP 3303 bits 1 and 2 and SP 3304.
d.	Fail if any response from an ECU indicating support for CCM monitor in DM5 reports “0=monitor disabled for rest of this cycle or not supported” in SP 3303 bit 3. 
e.	Fail if any response indicates number of warm-ups since code clear (WU-SCC) (SP 3302) is not zero. 
f.	Fail if any response indicates time since engine start (SP 3301) is not zero.
g.	Fail if no OBD ECU provides DM26.
// SOW Confirmed existing criteria. Check Unit Tests vs. confirmation analysis in SOW. 
6.1.14.3	Warn Criteria
a.	Warn if any individual required monitor, except Continuous Component Monitoring (CCM) is supported by more than one OBD ECU.
6.1.14.4	Actions
a.	DS DM26 to each OBD ECU.
6.1.14.5	Fail Criteria
a.	Fail if any difference compared to data received during global request.
b.	Fail if NACK not received from OBD ECUs that did not respond to global query.

**Comment by ericthomasswenson** [comment]
A.6	CRITERIA FOR READINESS 1 EVALUATION
Section A.6 describes criteria for evaluation of readiness bits in SPs 1221, 1222, and 1223 (bytes 4-8) of the DM5 message (PG 65320). Parallel construction can be applied to SPs 3303, 3304 and 3305 (bytes 4-8) in the DM26 message (PG 59904) which share the same assignments of monitors to bits, except for the monitor inhibit status in DM26, but operates on a smaller time scale.
1.	The response from each responding device shall be evaluated separately using a through d below:
a.	Fail if no response from an OBD ECU (ECUs that indicate 13h, 14h, 22h, or 23h for OBD compliance).
b.	Fail if any response does not report supported and complete for comprehensive components support and status (SP 1221, byte 4, bit 3 = 1 and bit 7 = 0), except when all the bits in SPs 1221, 1222, and 1223 are sent as 0 as defined in SAE J1939-73 paragraph 5.7.5.
c.	Fail if any response does not report 0 = ‘complete/not supported’ for the status bit for every unsupported monitors (i.e., any of the support bits in SP 1221, byte 4 bits 1-3, 1222 byte 5 bits 1-8, or 1222 byte 6 bits 1-5 that report 0 also report 0 in the corresponding status bit in SP 1221 and 1223).
d.	Fail if any response does not report 0 for reserved bits (SP 1221 byte 4 bits 4 and 8, SP 1222 byte 6 bits 6-8, and SP1223 byte 8 bits 6-8).
2.	All responses received from all responding OBD devices shall be combined with appropriate ‘AND/OR’ logic to create a composite vehicle readiness response: (Do not use responses from non-OBD devices to create a composite vehicle readiness response.)
a.	If one or more responses indicates 1 = supported in the support bit for a monitor, 
i.	Then the composite vehicle readiness shall indicate 1 = supported for that support bit/monitor, 
ii.	Else it shall indicate 0 = unsupported for that support bit/monitor; 
b.	If one or more responses indicates the status bit for a supported monitor is 1 = not complete, 
i.	Then the composite vehicle readiness shall indicate 1 = not complete for that status bit/monitor,
ii.	Else it shall indicate 0 = complete for that status bit/monitor). 
c.	Fail if composite vehicle readiness does not meet any of the criteria in Table A4. 
d.	Warn if any individual required monitor, except Continuous Component Monitoring (CCM) is supported by more than one OBD ECU.
**_3.	All responses received from non-OBD ECU shall be evaluated using the criteria below:  
a.	Warn if any response from non-OBD ECU received.
b.	Warn if all the monitor status and support bits in any reply from a non-OBD ECU are not all binary zeros or all binary ones._** 
SP 1222, bit 7 (Exhaust Sensor Heater Monitor Support) may appear as a 0 with a warning message, instead of a requiring a failure message in 2013 MY engines. Future engine model years (c. 2016) shall unbundle all heater monitoring support and support both bits 7 and 6. When SP 1222, bit 7 is provided as a 0 (not supported) after the 2013 engine model year, SP 1223, bit 7 (Exhaust Sensor Heater Monitor Status) shall be provided as 0 (complete). 
Specific implementations may require the immediate setting of the misfire monitor status bit to zero (complete). Refer to 13 CCR 1971.1 for such conditions. Observation of a zero (complete) for a misfire monitor status bit after fault codes have been cleared shall be marked with a warning message.
