### ISSUE TITLE
Tool doesn't Interpret Data-Stream Messages Correctly  

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1100]
**Tool is providing warnings for SP 512 & SP 91 with values that aren't received:**

Step 6.1.26.1.a - Reading bus for 20 seconds

PGN 61444 with Supported SPNs 190, 512, 513, 4154
12:42:00.0007 0CF00400 [8] 00 7D 7D 00 00 00 F0 7D
Found: Engine Speed from Engine #1 (0): 
  SPN   899, Engine Torque Mode: 0000
  SPN  4154, Actual Engine - Percent Torque (Fractional): 0.000000 %
  **SPN   512, Driver's Demand Engine - Percent Torque: 0.000000 %**
  SPN   513, Actual Engine - Percent Torque: 0.000000 %
  SPN   190, Engine Speed: 0.000000 rpm
  SPN  1483, Source Address of Controlling Device for Engine Control: 0.000000 source address
  SPN  1675, Engine Starter Mode: 0000
  SPN  2432, Engine Demand - Percent Torque: 0.000000 %

PGN 61443 with Supported SPNs 91, 92
12:42:00.0317 0CF00300 [8] DD 00 00 FF FF 0C 00 FF
Found: Electronic Engine Controller 2 from Engine #1 (0): 
  SPN   558, Accelerator Pedal 1 Low Idle Switch: 01
  SPN   559, Accelerator Pedal Kickdown Switch: 11
  SPN  1437, Road Speed Limit Status: 01
  SPN  2970, Accelerator Pedal 2 Low Idle Switch: 11
  **SPN    91, Accelerator Pedal Position 1: 0.000000 %**
  SPN    92, Engine Percent Load At Current Speed: 0.000000 %
  SPN   974, Remote Accelerator Pedal Position: Not Available
  SPN    29, Accelerator Pedal 2 Position: Not Available
  SPN  2979, Vehicle Acceleration Rate Limit Status: 00
  SPN  5021, Momentary Engine Maximum Power Enable Feedback: 11
  SPN  5399, DPF Thermal Management Active: 00
  SPN  5400, SCR Thermal Management Active: 00
  SPN  3357, Actual Maximum Available Engine - Percent Torque: 0.000000 %
  SPN  5398, Estimated Pumping - Percent Torque: Not Available

.
.
.

Step 6.2.17.1.a - Reading bus for 20 seconds

PGN 61444 with Supported SPNs 190, 512, 513, 4154
12:45:16.5246 0CF00400 [8] 30 7D 86 01 16 00 F4 85
Found: Engine Speed from Engine #1 (0): 
  SPN   899, Engine Torque Mode: 0000
  SPN  4154, Actual Engine - Percent Torque (Fractional): 0.375000 %
  **SPN   512, Driver's Demand Engine - Percent Torque: 0.000000 %**
  SPN   513, Actual Engine - Percent Torque: 9.000000 %
  SPN   190, Engine Speed: 704.125000 rpm
  SPN  1483, Source Address of Controlling Device for Engine Control: 0.000000 source address
  SPN  1675, Engine Starter Mode: 0100
  SPN  2432, Engine Demand - Percent Torque: 8.000000 %

PGN 61443 with Supported SPNs 91, 92
12:45:16.5252 0CF00300 [8] DD 00 0C FF FF 0C 8E FF
Found: Electronic Engine Controller 2 from Engine #1 (0): 
  SPN   558, Accelerator Pedal 1 Low Idle Switch: 01
  SPN   559, Accelerator Pedal Kickdown Switch: 11
  SPN  1437, Road Speed Limit Status: 01
  SPN  2970, Accelerator Pedal 2 Low Idle Switch: 11
  **SPN    91, Accelerator Pedal Position 1: 0.000000 %**
  SPN    92, Engine Percent Load At Current Speed: 12.000000 %
  SPN   974, Remote Accelerator Pedal Position: Not Available
  SPN    29, Accelerator Pedal 2 Position: Not Available
  SPN  2979, Vehicle Acceleration Rate Limit Status: 00
  SPN  5021, Momentary Engine Maximum Power Enable Feedback: 11
  SPN  5399, DPF Thermal Management Active: 00
  SPN  5400, SCR Thermal Management Active: 00
  SPN  3357, Actual Maximum Available Engine - Percent Torque: 56.800000 %
  SPN  5398, Estimated Pumping - Percent Torque: Not Available

WARN: 6.2.17.2.b - N.8 Engine #1 (0) reported value for SPN 512 (9.0) is implausible
WARN: 6.2.17.2.b - N.8 Engine #1 (0) reported value for SPN 91 (1.2000000000000002) is implausible

**Comment by ericthomasswenson** [comment]
It looks like the value for SP 92 may have been used v. SP 91 criteria

SPN 91, Accelerator Pedal Position 1: 0.000000 %
SPN 92, Engine Percent Load At Current Speed: 12.000000 %

WARN: 6.2.17.2.b - N.8 Engine (0) reported value for SPN 512 (**_9.0_**) is implausible
WARN: 6.2.17.2.b - N.8 Engine (0) reported value for SPN 91 (**_1.2000000000000002_**) is implausible

**Comment by ericthomasswenson** [comment]
These outcomes were not observed during an earlier test

     DM19 from Engine #1 (0): CAL ID of 5R203100A0000000 and CVN of 0x54CFFD57
     DM19 from Engine #2 (1): CAL ID of 4J1132S1W2215TCO and CVN of 0x1BB0FEE8
     DM19 from Exhaust Emission Controller (61): [
       CAL ID of 3Ap102N2S2100031 and CVN of 0xD452425A
       CAL ID of NOx-TR0440 ATI1 and CVN of 0x6AFFF5C0
       CAL ID of NOx-TR0440 ATO1 and CVN of 0x822BA944
       CAL ID of PMS*12*330*A100 and CVN of 0xEEF9D43C

PGN 61444 with Supported SPNs 190, 512, 513, 4154
14:35:09.9272 0CF00400 [8] 00 7D 7D 00 00 00 F0 7D
Found: Engine Speed from Engine #1 (0): 
  SPN   899, Engine Torque Mode: 0000
  SPN  4154, Actual Engine - Percent Torque (Fractional): 0.000000 %
  SPN   512, Driver's Demand Engine - Percent Torque: 0.000000 %
  SPN   513, Actual Engine - Percent Torque: 0.000000 %
  SPN   190, Engine Speed: 0.000000 rpm
  SPN  1483, Source Address of Controlling Device for Engine Control: 0.000000 source address
  SPN  1675, Engine Starter Mode: 0000
  SPN  2432, Engine Demand - Percent Torque: 0.000000 %

PGN 61443 with Supported SPNs 91, 92
14:35:09.9381 0CF00300 [8] D1 00 00 FF FF 0C 00 FF
Found: Electronic Engine Controller 2 from Engine #1 (0): 
  SPN   558, Accelerator Pedal 1 Low Idle Switch: 01
  SPN   559, Accelerator Pedal Kickdown Switch: 00
  SPN  1437, Road Speed Limit Status: 01
  SPN  2970, Accelerator Pedal 2 Low Idle Switch: 11
  SPN    91, Accelerator Pedal Position 1: 0.000000 %
  SPN    92, Engine Percent Load At Current Speed: 0.000000 %
  SPN   974, Remote Accelerator Pedal Position: Not Available
  SPN    29, Accelerator Pedal 2 Position: Not Available
  SPN  2979, Vehicle Acceleration Rate Limit Status: 00
  SPN  5021, Momentary Engine Maximum Power Enable Feedback: 11
  SPN  5399, DPF Thermal Management Active: 00
  SPN  5400, SCR Thermal Management Active: 00
  SPN  3357, Actual Maximum Available Engine - Percent Torque: 0.000000 %
  SPN  5398, Estimated Pumping - Percent Torque: Not Available

**Comment by ericthomasswenson** [comment]
Table A-1 Plausibility improvements not in A-1

Need to see a run with the A-1 changes included.

**Comment by ericthomasswenson** [comment]
Nathan, Is this still broken with the Table A-1 improvements in 3.1.4?

**Comment by battjt** [comment]
@naroner any update?

**Comment by ericthomasswenson** [comment]
Create new issue with any unresolved complaints @naroner
