### ISSUE TITLE
Task 5 Umbrella Description 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1101]
Task 5 XEV GHG Tracking. (SOW Summary)
Implement the proposed changes to the SAE J1939-84 3.0 test software to add tests for XEV PSA and HEV GHG Tracking Active 100-hour, Stored 100-hour, and Lifetime Arrays.  Provide means in the user interface to identify HEV, Plug in HEV distinctly from BEV vehicles, to support alternation of Plug in HEV and xEV queries and outcomes.

**Comment by ericthomasswenson** [comment]
Task 5 XEV GHG Tracking. (SOW Description)
Implement the proposed changes to the SAE J1939-84 3.0 test software to add tests for XEV GHG Tracking Active 100-hour, Stored 100-hour, and Lifetime Arrays.  Provide means in the user interface to distinctly identify Plug in HEV, HEV and BEV vehicles, to support alternation of Plug in HEV and xEV queries and outcomes.

Provide queries and evaluation criteria as shown in Recommended Changes to SAE J1939-84 for NOx Binning — GHG Tracking’. Create system and unit test data to exercise evaluation criteria and tabular displays. The PGs are shown in the tables below.

**_Presently Table A-1 does not provide detailed content for a BEV.  
Lines labeled for (CI) and (SI) engines shall be ignored (omitted) for a (BEV).
Lines not labeled with (CI) or (SI) shall be used in 6.1.4 and 6.1.26._** 

**_Task 8 may consider suggestions to improve the resulting outcomes._**

**Comment by ericthomasswenson** [comment]
Task 5 query and evaluation criteria text is shown in red in the attached document.

[Task 5 clarification.docx](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/8454429/Task.5.clarification.docx)

This text is provided below. The text presumes #1099 is complete.

**Comment by ericthomasswenson** [comment]
The selection between gas (SI) and diesel (CI) comes from the user interface today.
The user interface must change to accept additional selections for xEV and BEV
XEV (Hybrid) and BEV are mutually exclusive.
BEV and XEV (Hybrid) are mutually exclusive.
BEV, CI (Diesel), and SI (Spark Ignition) are mutually exclusive.

The possible combinations are

CI
SI
CI + Hybrid
SI + Hybrid (I’m not really expecting this one)
BEV

SP 6317 is assessed from the UI selection in Table A-1 (6.1.26 & 6.2.17)

**Comment by ericthomasswenson** [comment]
6.1.4.2
g. For all MY2022+ HEV and BEV drives, Fail if SP 12797 (Hybrid Lifetime Propulsion System Active Time), is not included in DM24 response. (SP 12797 is Lifetime EV Tracking Byte 1 SP)
h. For all MY2022+ Plug-in HEV drives, Fail if SP 12783 (Hybrid Lifetime Distance Traveled in Charge Depleting Operation with Engine off), is not included in DM24 response.

**Comment by ericthomasswenson** [comment]
6.1.26.19	Actions10 for MY2022+ HEV and BEV drives
a. DS request message to ECU that indicated support in DM24 for upon request SP 12797 (Hybrid Lifetime Propulsion System Active Time) for 64241 PSA Times Lifetime Hours
b. Record each value for use in Part 2.
6.1.26.20	Fail criteria10 for MY2022+ HEV and BEV drives
a. Fail PG query where no response was received.  
b. Fail PG query where any accumulator value received is greater than FAFFFFFFh.
6.1.26.21	Actions11 for MY2022+ HEV and BEV drives
a. DS request message to ECU that indicated support in DM24 for upon request SP 12797 (Hybrid Lifetime Propulsion System Active Time) for Active 100hr PSA Times and Stored 100hr PSA Times PGs:

PG       PG Label                                       PG Acronym
64242  PSA Times Stored 100 Hours        PSATS
64243  PSA Times Active 100 Hours         PSATA

b. Record each value for use in Part 2.
c. List data received in a table using lifetime, stored 100 hr, active 100hr for columns, and categories for rows.

6.1.26.22	Fail criteria11 for MY2022+ HEV and BEV drives
a. For MY2024+ HEV and BEV drives, Fail each PG query where no response was received.  
b. For MY2022-23 HEV and BEV drives, Warn each PG query, where no response was received.
c. Fail each PG query where any accumulator value received is greater than FAFFh.
6.1.26.23	Actions12 for MY2022+ Plug-in HEV DRIVES
a. DS request message to ECU that indicated support in DM24 for upon request SP 12783 (Hybrid Lifetime Distance Traveled in Charge Depleting Operation with Engine off) for PG 64244 Hybrid Charge Depleting or Increasing Operation Lifetime Hours
b. Record each value for use in Part 12.
6.1.17.24 Fail criteria12 for MY2022+ Plug-in HEV DRIVES
a. Fail PG query where no response was received.  
b. Fail PG query where any accumulator value received is greater than FAFFFFFFh.
c. Fail all values where the corresponding value received in part 1 is greater than the part 2 value.

6.1.26.24	Actions13 for MY2022+ Plug-in HEV DRIVES
a. DS request message to ECU that indicated support in DM24 for upon request SP 12783 (Hybrid Lifetime Distance Traveled in Charge Depleting Operation with Engine off) for Active 100hr Charge Depleting times and Stored 100hr PSA Charge Depleting Times PGs:

PG       PG Label                                                                                               PG Acronym
64246  Hybrid Charge Depleting or Increasing Operation Active 100 Hours    HCDIOA
64245  Hybrid Charge Depleting or Increasing Operation Stored 100 Hours   HCDIOS

b. Record each value for use in Part 2.
c. List data received in a table using lifetime, stored 100 hr, active 100hr for columns, and categories for rows.
6.1.26.25	Fail criteria13 for MY2022+ Plug-in HEV DRIVES
a. For MY2024+ Plug-in HEV DRIVES, Fail each PG query where no response was received.  
b. For MY2022-23 Plug-in HEV DRIVES, Warn each PG query, where no response was received
c. Fail each PG query where any active technology label or accumulator value received is greater than FAFFh, respectively.

**Comment by ericthomasswenson** [comment]
6.2.17.19	Actions10 for MY2022+ HEV and BEV drives
a. DS request message to ECU that indicated support in DM24 for upon request SP 12797 (Hybrid Lifetime Propulsion System Active Time) for 64241 PSA Times Lifetime Hours
b. Record each value for use in Part 12.
c. List data received in a table using lifetime, stored 100 hr, active 100hr for columns, and categories for rows.
6.2.17.20	Fail criteria10 for MY2022+ HEV and BEV drives (Where SP 12797 is supported in DM24)
a. Fail PG query where no response was received.  
b. Fail PG query where any accumulator value received is greater than FAFFFFFFh.
c. Fail all values where the corresponding value received in part 1 is greater than the part 2 value.
6.2.17.21	 Actions11 for MY2022+ HEV and BEV drives (Where SP 12797 is supported in DM24)
a. DS request message to ECU that indicated support in DM24 for upon request SP 12797 (Hybrid Lifetime Propulsion System Active Time) for Active 100hr PSA Times and Stored 100hr PSA Times PGs:
PG      PG Label                                  PG Acronym
64242 PSA Times Stored 100 Hours  PSATS 
64243 PSA Times Active 100 Hours   PSATA
b. Record each value for use in Part 12.
c. List data received in a table using lifetime, stored 100 hr, active 100hr for columns, and categories for rows.
6.2.17.22	 Fail criteria11 for MY2022+ HEV and BEV drives (Where SP 12797 is supported in DM24)
a. For MY2022+ HEV and BEV drives, Fail each PG query where no response was received.  
b. For MY2022-23 HEV and BEV drives, Warn each PG query, where no response was received.
c. Fail each PG query where any active technology label or accumulator value received is greater than FAFFh, respectively.
d. Fail all values where the corresponding value received in part 1 is greater than the part 2 value. (Where supported)
6.2.17.23	 Actions12 for MY2022+ Plug-in HEV DRIVES (Where SP 12783 is supported in DM24)
a. DS request message to ECU that indicated support in DM24 for upon request SP 12783 (Hybrid Lifetime Distance Traveled in Charge Depleting Operation with Engine off) for 64244 Hybrid Charge Depleting or Increasing Operation Lifetime Hours
b. Record each value for use in Part 12.
6.2.17.24	6.2.17.24 Fail criteria12 for MY2022+ Plug-in HEV DRIVES (Where SP 12783 is supported in DM24)
a. Fail PG query where no response was received.  
b. Fail PG query where any accumulator value received is greater than FAFFFFFFh.
c. Fail all values where the corresponding value received in part 1 is greater than the part 2 value.
6.2.17.25	Actions13 for MY2022+ Plug-in HEV DRIVES (Where SP 12783 is supported in DM24)
a. DS request message to ECU that indicated support in DM24 for upon request SP 12783 (Hybrid Lifetime Distance Traveled in Charge Depleting Operation with Engine off) for Active 100hr Charge Depleting times and Stored 100hr PSA Charge Depleting Times PGs:

PG       PG Label            PG Acronym
64246  Hybrid Charge Depleting or Increasing Operation Active 100 Hours  HCDIOA
64245  Hybrid Charge Depleting or Increasing Operation Stored 100 Hours   HCDIOS

b. Record each value for use in Part 12.
c. List data received in a table using lifetime, stored 100 hr, active 100hr for columns, and categories for rows.
6.2.17.26	Fail criteria13 for MY2022+ Plug-in HEV DRIVES (Where SP 12783 is supported in DM24)
a. For MY2024+ HEV and BEV drives, Fail each PG query where no response was received.  
b. For MY2022-23 HEV and BEV drives, Warn each PG query, where no response was received.
c. Fail each PG query where any active technology label or accumulator value received is greater than FAFFh, respectively.
d. Fail all values where the corresponding value received in part 1 is greater than the part 2 value. (Where supported)

**Comment by ericthomasswenson** [comment]
See #1107 for CARB/US checkbox for consolidated DM5 content in #1099

**Comment by ericthomasswenson** [comment]
All XEV/BEV queries included in consolidated text.

**Comment by anthonyhbest** [comment]
Looks like issue #968 was never resolved as part of this consolidation effort.  I'm still seeing these warns in version 3.1.26  Happens in part 1 and part 2 of the test.
![image](https://github.com/Equipment-and-Tool-Institute/j1939-84/assets/94923793/d77789b5-7253-40c8-b2d0-7fac36803097)
