### ISSUE TITLE
Task 6 Umbrella Description

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1103]
Task 6 Alternate Adapter Study.  
Iterate integration testing with no less than two competitive products to the NEXIQ Link-2.
Report any issues observed when compared to Link-2 performance.
Accept and analyze up to five SAE J1939-84 tool data logs provided by users for competitive TMC RP 1210 products. 
Propose maintenance activities for issues identified.

**Comment by ericthomasswenson** [comment]
ETS to define the two adapter suggestions with the User Group

**Comment by ericthomasswenson** [comment]
See #1143 for adapter selection

**Comment by ericthomasswenson** [comment]
Adapters Ordered. Peak adapter received.

**Comment by battjt** [comment]
Retest "auto baud" testing with multiple node networks.

**Comment by battjt** [comment]
Report pending.  Will be delivered as PDF with code.
