### ISSUE TITLE
CAL ID and CVN Fail criteria should not apply to non OBD ECU

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1104]
6.1.7.2 Fail Criteria 
a. Fail if total number of reported CAL IDs is < user entered value for number of emission or diagnostic critical control units (test 6.1.2).  
b. For responses from OBD ECUs: 
i. Fail if <> 1 CVN for every CAL ID.  
ii. Fail if CAL ID not formatted correctly (printable ASCII, **_padded incorrectly_**, etc.).  
iii. Fail if any received CAL ID is all FFh or any CVN is all 00h.  
iv. Fail if CVN padded incorrectly (padding shall use 00h in MSB for unused bytes). 
6.1.7.3 Warn Criteria 
a. Warn if total number of reported CAL IDs is > user entered value for number of emission or diagnostic critical control units (test 6.1.2). 
b. Warn if more than one CAL ID and CVN pair is provided in a single DM19 message.  
**_c. For responses from non-OBD_** 
   i. Warn if any non-OBD ECU provides CAL ID.
  ii. Warn if <> 1 CVN for every CAL ID.  
**_iii. Warn if CAL ID not formatted correctly (contains non-printable ASCII, padded incorrectly, etc.).  
iv. Warn if any received CAL ID is all FFh or any CVN is all 00h._**

**Comment by ericthomasswenson** [comment]
**_// SA 17 did not respond to global DM5 — Is not presumed to be an OBD ECU._**
**_// Engine messages are interleaved in the log with SA 17 messages_** 
**_// CAL IDs are allowed to to be padded with binary zeros or spaces_**
**_// Padding is allowed for both OBD and non-OBD ECUs_**
**_// The correct severity for a zero CVN from a non-OBD device is a WARN_**

Start Test 1.7 - DM19: Calibration information
14:31:50.6784 Global DM19 Request
14:31:50.6808 18EAFFF9 [3] 00 D3 00 (TX)
14:31:51.4620 1CD3FF00 [100] 
C0 08 EE 18 41 32 36 32 39 58 58 4C 5F 46 31 32 30 30 47 31 
A8 73 89 13 4E 4F 78 2D 53 41 45 31 34 61 20 41 54 49 31 **_00_** 
8C 4B F9 C9 4E 4F 78 2D 53 41 45 31 34 61 20 41 54 4F 31 **_00_**
8B 21 D2 3A 30 34 30 32 30 32 30 30 30 38 **_00 00 00 00 00 00_** 
D2 BF 0F A9 50 4D 53 31 32 33 34 31 41 31 30 31 **_00 00 00 00_**
DM19 from Engine #1 (0): [
  CAL ID of A2629XXL_F1200G1 and CVN of 0x18EE08C0
  CAL ID of NOx-SAE14a ATI1 and CVN of 0x138973A8
  CAL ID of NOx-SAE14a ATO1 and CVN of 0xC9F94B8C
  CAL ID of 0402020008 and CVN of 0x3AD2218B
  CAL ID of PMS12341A101 and CVN of 0xA90FBFD2
]

14:31:50.8697 1CD3FF11 [20] 00 00 00 00 4E 50 44 43 46 44 4E 54 00 00 00 00 00 00 00 00
DM19 from Cruise Control (17): CAL ID of NPDCFDNT and CVN of 0x00000000

WARN: 6.1.7.3.b - Engine #1 (0) provided more than one CAL ID and CVN pair in a single DM19 message
WARN: 6.1.7.3.c.i - Non-OBD ECU Cruise Control (17) provided CAL ID
_FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)_
_WARN: 6.1.7.3.c.iii - Cruise Control (17) CAL ID not formatted correctly (contains non-printable ASCII)_
**_FAIL_**: 6.1.7.3.c.iv Received CVN that is all 0x00 from Cruise Control (17)

14:31:51.4798 Destination Specific DM19 Request to Engine #1 (0)
14:31:51.4819 18EA00F9 [3] 00 D3 00 (TX)
14:31:51.8142 1CD3F900 [100] C0 08 EE 18 41 32 36 32 39 58 58 4C 5F 46 31 32 30 30 47 31 A8 73 89 13 4E 4F 78 2D 53 41 45 31 34 61 20 41 54 49 31 00 8C 4B F9 C9 4E 4F 78 2D 53 41 45 31 34 61 20 41 54 4F 31 00 8B 21 D2 3A 30 34 30 32 30 32 30 30 30 38 00 00 00 00 00 00 D2 BF 0F A9 50 4D 53 31 32 33 34 31 41 31 30 31 00 00 00 00
DM19 from Engine #1 (0): [
  CAL ID of A2629XXL_F1200G1 and CVN of 0x18EE08C0
  CAL ID of NOx-SAE14a ATI1 and CVN of 0x138973A8
  CAL ID of NOx-SAE14a ATO1 and CVN of 0xC9F94B8C
  CAL ID of 0402020008 and CVN of 0x3AD2218B
  CAL ID of PMS12341A101 and CVN of 0xA90FBFD2
]
14:31:51.8175 Destination Specific DM19 Request to Cruise Control (17)
14:31:51.8197 18EA11F9 [3] 00 D3 00 (TX)
14:31:52.0100 1CD3FF11 [20] 00 00 00 00 4E 50 44 43 46 44 4E 54 00 00 00 00 00 00 00 00
DM19 from Cruise Control (17): CAL ID of NPDCFDNT and CVN of 0x00000000

End Test 1.7 - DM19: Calibration information

**Comment by ericthomasswenson** [comment]
**_// The expected sequence is_**

Start Test 1.7 - DM19: Calibration information
14:31:50.6784 Global DM19 Request
14:31:50.6808 18EAFFF9 [3] 00 D3 00 (TX)
14:31:51.4620 1CD3FF00 [100] 
C0 08 EE 18 41 32 36 32 39 58 58 4C 5F 46 31 32 30 30 47 31 
A8 73 89 13 4E 4F 78 2D 53 41 45 31 34 61 20 41 54 49 31 00 
8C 4B F9 C9 4E 4F 78 2D 53 41 45 31 34 61 20 41 54 4F 31 00 
8B 21 D2 3A 30 34 30 32 30 32 30 30 30 38 00 00 00 00 00 00 
D2 BF 0F A9 50 4D 53 31 32 33 34 31 41 31 30 31 00 00 00 00
DM19 from Engine #1 (0): [
  CAL ID of A2629XXL_F1200G1 and CVN of 0x18EE08C0
  CAL ID of NOx-SAE14a ATI1 and CVN of 0x138973A8
  CAL ID of NOx-SAE14a ATO1 and CVN of 0xC9F94B8C
  CAL ID of 0402020008 and CVN of 0x3AD2218B
  CAL ID of PMS12341A101 and CVN of 0xA90FBFD2
]

WARN: 6.1.7.3.b - Engine #1 (0) provided more than one CAL ID and CVN pair in a single DM19 message
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)

14:31:50.8697 1CD3FF11 [20] 00 00 00 00 4E 50 44 43 46 44 4E 54 00 00 00 00 00 00 00 00
DM19 from Cruise Control (17): CAL ID of NPDCFDNT and CVN of 0x00000000

WARN: 6.1.7.3.c.i - Non-OBD ECU Cruise Control (17) provided CAL ID
WARN: 6.1.7.3.c.iii - Cruise Control (17) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.3.c.iv Received CVN that is all 0x00 from Cruise Control (17)

14:31:51.4798 Destination Specific DM19 Request to Engine #1 (0)
14:31:51.4819 18EA00F9 [3] 00 D3 00 (TX)
14:31:51.8142 1CD3F900 [100] C0 08 EE 18 41 32 36 32 39 58 58 4C 5F 46 31 32 30 30 47 31 A8 73 89 13 4E 4F 78 2D 53 41 45 31 34 61 20 41 54 49 31 00 8C 4B F9 C9 4E 4F 78 2D 53 41 45 31 34 61 20 41 54 4F 31 00 8B 21 D2 3A 30 34 30 32 30 32 30 30 30 38 00 00 00 00 00 00 D2 BF 0F A9 50 4D 53 31 32 33 34 31 41 31 30 31 00 00 00 00
DM19 from Engine #1 (0): [
  CAL ID of A2629XXL_F1200G1 and CVN of 0x18EE08C0
  CAL ID of NOx-SAE14a ATI1 and CVN of 0x138973A8
  CAL ID of NOx-SAE14a ATO1 and CVN of 0xC9F94B8C
  CAL ID of 0402020008 and CVN of 0x3AD2218B
  CAL ID of PMS12341A101 and CVN of 0xA90FBFD2
]
14:31:51.8175 Destination Specific DM19 Request to Cruise Control (17)
14:31:51.8197 18EA11F9 [3] 00 D3 00 (TX)
14:31:52.0100 1CD3FF11 [20] 00 00 00 00 4E 50 44 43 46 44 4E 54 00 00 00 00 00 00 00 00
DM19 from Cruise Control (17): CAL ID of NPDCFDNT and CVN of 0x00000000

End Test 1.7 - DM19: Calibration information

**Comment by ericthomasswenson** [comment]
The expected messages are:

WARN: 6.1.7.3.b - Engine (0) provided more than one CAL ID and CVN pair in a single DM19 message
WARN: 6.1.7.3.c.iv Received CVN that is all 0x00 from Cruise Control (17)

**Comment by battjt** [comment]
related to #156, #766, and #1120.

**Comment by ericthomasswenson** [comment]
3.1.4 Example

Start Test 1.7 - DM19: Calibration information
15:41:15.4585 Global DM19 Request
15:41:15.4610 18EAFFF9 [3] 00 D3 00 (TX)
15:41:15.6455 1CD3FF00 [20] 3C B4 8D A6 [35 54 32 31 34 32 30](tel:35 54 32 31 34 32 30) [30 41 30 30 30 30 30](tel:30 41 30 30 30 30 30) 30 30
DM19 from Engine #1 (0): CAL ID of 5T214200A0000000 and CVN of 0xA68DB43C

15:41:16.0715 1CD3FF3D [80] DA E8 6B 34 [33 41 73 31 62 31](tel:33 41 73 31 62 31) 4E 58 4E [32 31 30 30 30 33 31](tel:32 31 30 30 30 33 31) 72 14 4D A8 4E 4F 78 2D 53 [57 37 30 30 38](tel:57 37 30 30 38) 20 [41 54 49 31](tel:41 54 49 31) 00 72 14 4D A8 4E 4F 78 2D 53 [57 37 30 30 38](tel:57 37 30 30 38) 20 41 54 4F 31 00 3C D4 F9 EE 50 4D 53 2A 31 32 2A 33 33 30 2A [41 31 30 30](tel:41 31 30 30) 20
DM19 from Exhaust Emission Controller (61): [
  CAL ID of 3As1b1NXN2100031 and CVN of 0x346BE8DA
  CAL ID of NOx-SW7008 ATI1 and CVN of 0xA84D1472
  CAL ID of NOx-SW7008 ATO1 and CVN of 0xA84D1472
  CAL ID of PMS*12*330*A100 and CVN of 0xEEF9D43C
]

15:41:15.6245 1CD3FF01 [20] CC [50 53 82 34](tel:50 53 82 34) 4A [34 31 54 31](tel:34 31 54 31) 4E [57 35 32 34 31 33 54](tel:57 35 32 34 31 33 54) 43 4F
DM19 from Engine #2 (1): CAL ID of 4J41T1NW52413TCO and CVN of 0x825350CC

WARN: 6.1.7.3.b - Exhaust Emission Controller (61) provided more than one CAL ID and CVN pair in a single DM19 message
FAIL: 6.1.7.2.b.ii - Exhaust Emission Controller (61) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Exhaust Emission Controller (61) CAL ID not formatted correctly (contains non-printable ASCII)
