### ISSUE TITLE
Test 6.1.4 Should Fail 2022 MY Engine for lack of NOx Binning GHG Support.

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1106]
Test 6.1.4 should fail 2022 MY engine that does not exhibit NOx Binning or GHG tracking support.

  D       1  SPN 7353 - Engine Exhaust 1 Corrected Nox
  D   T   1  SPN 7393 - AFT 1 Particulate Sensor Current
  D       2  SPN 12750 - AFT 1 SCR 1 Engine Exhaust NOx Mass Flow
  D       2  SPN 12751 - AFT 1 SCR 1 Tailpipe NOx Mass Flow
]

**Comment by ericthomasswenson** [comment]
6.1.4.2 Fail Criteria
a.​​Fail if retry was required to obtain the DM24 response.
b.​Fail if one or more minimum expected SPs for data stream not supported per Section A.1, Minimum Support Table, from the OBD ECU(s).
c.​Fail if one or more minimum expected SPs for freeze frame not supported per Section A.2, Criteria for Freeze Frame Evaluation, from the OBD ECU(s).
**_d. For MY2022+ diesel engines, Fail if SP 12675 (NOx Tracking Engine Activity Lifetime Fuel Consumption Bin 1 - Total) is not included in DM24 response.
e. For all MY2022+ engines, Fail if SP 12730 (GHG Tracking Engine Run Time) is not included in DM24 response.
f. For all MY2022+ engines, Warn if SP 12691 (GHG Tracking Lifetime Active Technology Index) is not included in DM24 response._**
g. For all MY2022+ HEV and BEV drives, Fail if SP 12797 (Hybrid Lifetime Propulsion System Active Time), is not included in DM24 response. (SP 12797 is Lifetime EV Tracking Byte 1 SP)
h. For all MY2022+ Plug-in HEV drives, Fail if SP 12783 (Hybrid Lifetime Distance Traveled in Charge Depleting Operation with Engine off), is not included in DM24 response.

**Comment by ericthomasswenson** [comment]
SPs 12675, 12730, 12691, 12797, and 12783 were purposefully omitted from Table A-1 changes as MY criteria don’t fit the support criteria model for table A-1.
(‘22 and ‘24 are bifurcated in 13 CCR 1971.1)

**Comment by ericthomasswenson** [comment]
NOx Binning and GHG tracking are vehicle level requirements.
These would have been better stated as, from any OBD ECU.
From each OBD ECU was not intended.

6.1.4.2 Fail Criteria
a.​​Fail if retry was required to obtain the DM24 response.
b.​Fail if one or more minimum expected SPs for data stream not supported per Section A.1, Minimum Support Table, from the OBD ECU(s).
c.​Fail if one or more minimum expected SPs for freeze frame not supported per Section A.2, Criteria for Freeze Frame Evaluation, from the OBD ECU(s).
d. For MY2022+ diesel engines, Fail if SP 12675 (NOx Tracking Engine Activity Lifetime Fuel Consumption Bin 1 - Total) is not included in DM24 response, **_from any OBD ECU._**
e. For all MY2022+ engines, Fail if SP 12730 (GHG Tracking Engine Run Time) is not included in DM24 response, **from any OBD ECU.**
f. For all MY2022+ engines, Warn if SP 12691 (GHG Tracking Lifetime Active Technology Index) is not included in DM24 response, **_from any OBD ECU._**
g. For all MY2022+ HEV and BEV drives, Fail if SP 12797 (Hybrid Lifetime Propulsion System Active Time), is not included in DM24 response, **_from any OBD ECU._** (SP 12797 is Lifetime EV Tracking Byte 1 SP)
h. For all MY2022+ Plug-in HEV drives, Fail if SP 12783 (Hybrid Lifetime Distance Traveled in Charge Depleting Operation with Engine off), is not included in DM24 response, **from any OBD ECU.**

**Comment by battjt** [comment]
6.1.4.2 rewritten since bug reported.
