### ISSUE TITLE
UI Support for CARB/US ICE v BEV and International ICE

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1107]
#1099 assumes the existence of a check box for CARB/US ICE to distinguish CARB (l)(1) ICE testing from alternate uses.

When CARB/US is indicated, the criteria demand one of 4 values be provided by all OBD modules, for OBD compliance.

This permits manufacturers to run tests, for international certs, without complaints that the value doesn’t meet CARB allowed numbers.

Such a box is envisioned to be selected by default, and must be deselected for International CI and SI circumstances.

**Comment by ericthomasswenson** [comment]
See #1101 for SOW UI needs for XEVs and BEVs

**Comment by ericthomasswenson** [comment]
All section 6 changes consolidated in one document.

**Comment by battjt** [comment]
Is the Fuel Type of "Battery/electric vehicle" sufficient?
![image](https://user-images.githubusercontent.com/1972001/184158617-be0b5882-1f35-432f-aa60-306cab4aff3c.png)

**Comment by ericthomasswenson** [comment]
#1107 is about creating an escape hatch for say a Brazilian Euro VI adaption, or a China 6 off road vehicle, which won’t use 13h or 14h …

when the box is un checked failure messages for 13h 14h … are turned off. 

We need to accept Bev values with the box checked 

The box isn’t in the displayed content above…

**Comment by ericthomasswenson** [comment]
6.1.3 Provides the new criteria.

6.1.3	DM5: Diagnostic Readiness 1 
6.1.3.1	Actions 
a.	Global  DM5 [send Request (PG 59904) for PG 65230 (SP 1220, OBD Compliance)]. 
b.	Create “OBD ECU”  list (comprised of all ECUs that indicate OBD compliance values other than 0, 5, FBh, FCh, FDh, FEh, or FFh for OBD compliance) for use later in the test as the “OBD ECUs.” 
6.1.3.2	Fail Criteria
a.	Fail if no ECU reports as an OBD ECU.
b.	Fail if any ECU responds with a NACK (to DM5, PG 65230 request). 
c.	Fail if a BEV vehicle response provides a value other than 1Bh (27) for OBD compliance.
d.	Fail if any response from a function 0 device provides OBD Compliance values of 0, 5, FBh, FCh, FDh, FEh, or FFh.
e.	**_Fail if a US/CARB vehicle does not provide OBD Compliance values of 13h, 14h, 22h, or 23h._**
6.1.3.3	Warn/Info Criteria
a.		Warn if more than one ECU responds with a value for OBD compliance where the values are not identical (e.g., if one ECU reports 13h and another reports 22h, if one reports 13h and another reports 11h, or if one ECU reports 00h and another reports 14h).
b.	Warn if any response received from a non-OBD ECU provides OBD Compliance values of 0, FBh, FCh, FDh, FEh, or FFh.
c.	Info for DM5 replies from non-OBD ECUs.
// The above changes incorporate #1099

**Comment by ericthomasswenson** [comment]
e. Fail if a US/CARB vehicle does not provide OBD Compliance values of 13h, 14h, 22h, or 23h.

Should perhaps have said

e. Fail if a US/CARB **_CI or SI_** vehicle does not provide OBD Compliance values of 13h, 14h, 22h, or 23h.

**Comment by ericthomasswenson** [comment]
8/12/2023 Task 5 Artifact Updated to 

e. Fail if a vehicle with a **_US EPA/CARB CI or SI engine_** does not provide OBD Compliance values of 13h, 14h, 22h, or 23h.
