### ISSUE TITLE
Tool does not request NOx binning data for MY22 engine

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1109]
**_New to Version 3.1.0_**

**Tool does not request NOx binning data for MY22 engine:**
User Data Entry: 

Engine Model Emissions Year: 2022
Number of Emissions ECUs Expected: 3
Number of CAL IDs Expected: 6
Fuel Type: Diesel vehicle
Ignition Type: Compression
Number of Trips for Fault B Implant: 1

Vehicle Information:
VIN: 5KKMBWD17MLMS7857
Vehicle MY: 2021
Engine MY: **2022**
Cert. Engine Family: NDDXH14.8TCX 
Number of OBD ECUs Found: 0

**SA 1 supports NOx binning data SPs:**

DM24 from Engine #2 (1): [
  D F T D F
  a r e M F
  t F s 5 l
  a r t 8 n  SPN — SP Name
\------------------------
.
.
.
  **_D       4  SPN 12675 - NOx Tracking Engine Activity Lifetime Fuel Consumption Bin 1 (Total)
  D       1  SPN 12691 - GHG Tracking Lifetime Active Technology Index
  D       4  SPN 12730 - GHG Tracking Lifetime Engine Run Time_**
  D       2  SPN 12750 - AFT 1 SCR 1 Engine Exhaust NOx Mass Flow
  D       2  SPN 12751 - AFT 1 SCR 1 Tailpipe NOx Mass Flow

**Tool doesn't request NOx binning during step 1.26 (It listens for broadcast SPs and then requests SPs that are on request, but doesn't request NOx binning SPs):**

Start Test 1.26 - Data stream support verification
Expecting the following messages:
  SPN 588 is supported by Engine #1 (0) but will be omitted

  SPN 976 is supported by Engine #1 (0) but will be omitted

  BCT PGN 61443 from Engine #1 (0) with SPNs 91, 92
  BCT PGN 61444 from Engine #1 (0) with SPNs 190, 512, 513, 4154
  BCT PGN 64830 from Engine #1 (0) with SPNs 4363
  Req PGN 64878 from Engine #1 (0) with SPNs 5463
  BCT PGN 64892 from Engine #1 (0) with SPNs 3699, 3700, 3701, 3702, 3711, 3713, 4175
  Req PGN 64920 from Engine #1 (0) with SPNs 5454, 5827
  BCT PGN 64947 from Engine #1 (0) with SPNs 3246
  Req PGN 64962 from Engine #1 (0) with SPNs 5829, 5837
  Req PGN 64963 from Engine #1 (0) with SPNs 2623, 2624
  BCT PGN 64997 from Engine #1 (0) with SPNs 2595
  BCT PGN 65110 from Engine #1 (0) with SPNs 1761, 3031, 5245
  BCT PGN 65188 from Engine #1 (0) with SPNs 411
  Req PGN 65244 from Engine #1 (0) with SPNs 235
  BCT PGN 65247 from Engine #1 (0) with SPNs 514, 2978, 3236
  BCT PGN 65251 from Engine #1 (0) with SPNs 188, 528, 529, 530, 531, 539, 540, 541, 542, 543, 544
  Req PGN 65253 from Engine #1 (0) with SPNs 247
  Req PGN 65255 from Engine #1 (0) with SPNs 248
  Req PGN 65260 from Engine #1 (0) with SPNs 237
  BCT PGN 65262 from Engine #1 (0) with SPNs 110, 174, 175
  BCT PGN 65263 from Engine #1 (0) with SPNs 94, 98, 100
  BCT PGN 65265 from Engine #1 (0) with SPNs 84
  BCT PGN 65266 from Engine #1 (0) with SPNs 183
  BCT PGN 65269 from Engine #1 (0) with SPNs 108, 171
  BCT PGN 65270 from Engine #1 (0) with SPNs 102, 105, 106
  BCT PGN 65271 from Engine #1 (0) with SPNs 168
  BCT PGN 65276 from Engine #1 (0) with SPNs 96
  SPN 12675 is supported by Engine #2 (1) but will be omitted

  SPN 12691 is supported by Engine #2 (1) but will be omitted

  SPN 12730 is supported by Engine #2 (1) but will be omitted

  **Req PGN 64250 from Engine #2 (1) with SPNs 12750, 12751**
  BCT PGN 64470 from Engine #2 (1) with SPNs 8619, 8620
  Req PGN 64587 from Engine #2 (1) with SPNs 6893, 6894, 6895, 7333
  BCT PGN 64765 from Engine #2 (1) with SPNs 5313, 5314
  BCT PGN 64869 from Engine #2 (1) with SPNs 4077
  BCT PGN 64870 from Engine #2 (1) with SPNs 4193
  BCT PGN 64916 from Engine #2 (1) with SPNs 27, 5312, 5444
  BCT PGN 64929 from Engine #2 (1) with SPNs 3480, 3482
  BCT PGN 64938 from Engine #2 (1) with SPNs 2631
  Req PGN 64952 from Engine #2 (1) with SPNs 3301
  BCT PGN 64976 from Engine #2 (1) with SPNs 3563
  Req PGN 64981 from Engine #2 (1) with SPNs 2791, 5323
  BCT PGN 65129 from Engine #2 (1) with SPNs 1636, 1637, 2630
  Req PGN 65154 from Engine #2 (1) with SPNs 1413, 1414, 1415, 1416
  Req PGN 65155 from Engine #2 (1) with SPNs 1417, 1418
  Req PGN 65159 from Engine #2 (1) with SPNs 1436
  BCT PGN 65178 from Engine #2 (1) with SPNs 1172
  Req PGN 65214 from Engine #2 (1) with SPNs 5465
  BCT PGN 65243 from Engine #2 (1) with SPNs 157
  BCT PGN 65245 from Engine #2 (1) with SPNs 103
  BCT PGN 61454 from Exhaust Emission Controller (61) with SPNs 3216, 3217
  BCT PGN 61455 from Exhaust Emission Controller (61) with SPNs 3226, 3227
  BCT PGN 61475 from Exhaust Emission Controller (61) with SPNs 4331, 4334
  BCT PGN 64501 from Exhaust Emission Controller (61) with SPNs 8160, 8162
  Req PGN 64720 from Exhaust Emission Controller (61) with SPNs 7393
  Req PGN 64782 from Exhaust Emission Controller (61) with SPNs 7351
  Req PGN 64784 from Exhaust Emission Controller (61) with SPNs 7353
  BCT PGN 64800 from Exhaust Emission Controller (61) with SPNs 4765, 4766
  BCT PGN 64828 from Exhaust Emission Controller (61) with SPNs 4374
  Req PGN 64891 from Exhaust Emission Controller (61) with SPNs 3719, 5466
  BCT PGN 64908 from Exhaust Emission Controller (61) with SPNs 3609, 3610
  BCT PGN 64946 from Exhaust Emission Controller (61) with SPNs 3250
  BCT PGN 64948 from Exhaust Emission Controller (61) with SPNs 3242
  Req PGN 64952 from Exhaust Emission Controller (61) with SPNs 3301

11:47:59.5455 Destination Specific DS Request for PGN 64784 to Exhaust Emission Controller (61) for SPNs 7353 Request to Exhaust Emission Controller (61)
11:47:59.5475 18EA3DF9 [3] 10 FD 00 (TX)
11:47:59.5515 0CFD103D [8] FF FF FF FF FF 00 FB FF
AFT 1 Intake Gas NOx Sensor Correction Data 2 from Exhaust Emission Controller (61): 
  SPN  5027, Engine Exhaust 1 NOx Sensor O2 Pressure Correction: Not Available
  SPN  5028, Engine Exhaust 1 NOx Sensor NOx Pressure Correction: Not Available
  SPN  5029, Engine Exhaust 1 NOx Sensor NO2 Correction: Not Available
  SPN  5030, Engine Exhaust 1 NOx Sensor NH3 Correction: Not Available
  SPN  5718, Engine Exhaust 1 NOx Sensor Self-diagnosis Final Result: Not Available
  SPN  7353, Engine Exhaust 1 Corrected Nox: 0xFB00

11:47:59.5525 Destination Specific DS Request for PGN 64891 to Exhaust Emission Controller (61) for SPNs 3719, 5466 Request to Exhaust Emission Controller (61)
11:47:59.5555 18EA3DF9 [3] 7B FD 00 (TX)
11:47:59.5635 18FD7B3D [8] 01 FF 00 00 00 00 49 00
AFT 1 Service 1 from Exhaust Emission Controller (61): 
  SPN  3719, AFT 1 DPF Soot Load Percent: 1.000 %
  SPN  3720, AFT 1 DPF Ash Load Percent: Not Available
  SPN  3721, AFT 1 DPF Time Since Last Active Regeneration: 0.000 s
  SPN  5466, AFT 1 DPF Soot Load Regeneration Threshold: 0.183 %

11:47:59.5645 Destination Specific DS Request for PGN 64952 to Exhaust Emission Controller (61) for SPNs 3301 Request to Exhaust Emission Controller (61)
11:47:59.5665 18EA3DF9 [3] B8 FD 00 (TX)
11:47:59.5720 18FDB83D [8] 00 00 00 04 60 1C 60 1C
DM26 from Exhaust Emission Controller (61): Warm-ups: 0, Time Since Engine Start: 0 seconds
Continuously Monitored System Support/Status:
    Comprehensive component        enabled,     complete
    Fuel System                not enabled,     complete
    Misfire                    not enabled,     complete
Non-continuously Monitored System Support/Status:
    A/C system refrigerant     not enabled,     complete
    Boost pressure control sys not enabled,     complete
    Catalyst                   not enabled,     complete
    Cold start aid system      not enabled,     complete
    Diesel Particulate Filter      enabled, not complete
    EGR/VVT system             not enabled,     complete
    Evaporative system         not enabled,     complete
    Exhaust Gas Sensor             enabled, not complete
    Exhaust Gas Sensor heater      enabled, not complete
    Heated catalyst            not enabled,     complete
    NMHC converting catalyst       enabled, not complete
    NOx catalyst/adsorber          enabled, not complete
    Secondary air system       not enabled,     complete

End Test 1.26 - Data stream support verification

**Comment by battjt** [comment]
6.1.26 hsa been rewritten since bug report.  Should be fixed.

**Comment by naroner** [comment]
@ericthomasswenson This is fixed in 3.1.19
