### ISSUE TITLE
Tool is requesting DM58 for some SPs when they are not listed as supported

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1110]
**_New to Version 3.1.0_**

**Tool is requesting DM58 for some SPs when they are not listed as supported:**

**DM24 for SP 84, 157, 1761:**
DM24 from Engine #1 (0): [
  D F T D F
  a r e M F
  t F s 5 l
  a r t 8 n  SPN — SP Name
  \------------------------
  D F     2  SPN 84 - Wheel-Based Vehicle Speed

DM24 from Engine #2 (1): [
  D F T D F
  a r e M F
  t F s 5 l
  a r t 8 n  SPN — SP Name
  \------------------------
  D F T   2  SPN 157 - Engine Fuel 1 Injector Metering Rail 1 Pressure

DM24 from Exhaust Emission Controller (61): [
  D F T D F
  a r e M F
  t F s 5 l
  a r t 8 n  SPN — SP Name
  \------------------------
    F T   1  SPN 1761 - AFT 1 DEF Tank Volume

**Only happens in part 12.11:**

12:51:05.8895 Sending DM7 for DM58 to Engine #1 (0) for SPN 84
12:51:05.8965 18E300F9 [8] F5 54 00 1F FF FF FF FF (TX)
12:51:06.4935 Timeout - No Response
12:51:06.4960 18E300F9 [8] F5 54 00 1F FF FF FF FF (TX)
12:51:07.0920 Timeout - No Response
12:51:07.0950 18E300F9 [8] F5 54 00 1F FF FF FF FF (TX)
12:51:07.6940 Timeout - No Response
FAIL: 6.12.11.5.a - NACK not received for DM7 PG from OBD ECU Engine #1 (0) for spn 84
12:51:07.6950 Sending DM7 for DM58 to Engine #2 (1) for SPN 157
12:51:07.6975 18E301F9 [8] F5 9D 00 1F FF FF FF FF (TX)
12:51:08.2930 Timeout - No Response
12:51:08.2960 18E301F9 [8] F5 9D 00 1F FF FF FF FF (TX)
12:51:08.8940 Timeout - No Response
12:51:08.8965 18E301F9 [8] F5 9D 00 1F FF FF FF FF (TX)
12:51:09.4930 Timeout - No Response
FAIL: 6.12.11.5.a - NACK not received for DM7 PG from OBD ECU Engine #2 (1) for spn 157
12:51:09.4940 Sending DM7 for DM58 to Exhaust Emission Controller (61) for SPN 1761
12:51:09.4970 18E33DF9 [8] F5 E1 06 1F FF FF FF FF (TX)
12:51:10.0930 Timeout - No Response
12:51:10.0950 18E33DF9 [8] F5 E1 06 1F FF FF FF FF (TX)
12:51:10.6935 Timeout - No Response
12:51:10.6960 18E33DF9 [8] F5 E1 06 1F FF FF FF FF (TX)
12:51:11.2925 Timeout - No Response
FAIL: 6.12.11.5.a - NACK not received for DM7 PG from OBD ECU Exhaust Emission Controller (61) for spn 1761

**Comment by ericthomasswenson** [comment]
One unsupported SP for DM 58 is expected to checked.
One query for each SA is actually expected.
The NACK for an unsupported SP is also expected, and the message is correct.

There should be similar observations for parts 1 & 2.
Omissions would be bugs.

**Comment by ericthomasswenson** [comment]
Nathan, were there queries for unsupported DM58 SPs in 6.1 and 6.2

Were there queries for supported DM58 SPs in 6.1 and 6.2?

**Comment by naroner** [comment]
No, only in 6.12

**Comment by ericthomasswenson** [comment]
DM58 Support was incomplete, but checking 1 SP for each OBD ECU is intended.
