### ISSUE TITLE
Tool is failing DM24 for NOx binning SPs with a distributed system

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1111]
**_New to Version 3.1.0_**

**We only support NOx binning with SA 1, tool fails SA 0 and SA 61 for not supporting them:**

FAIL: 6.1.4.2.d - For MY2022+ diesel engines, Fail if SP 12675 (NOx Tracking Engine Activity Lifetime Fuel Consumption Bin 1 - Total)
            is not included in DM24 response from Engine #1 (0)
WARN: 6.1.4.2.e. - For all MY2022+ engines, Fail if SP 12730 (GHG Tracking Engine Run Time) is not included in DM24 response from Engine #1 (0)
WARN: 6.1.4.2.f - For all MY2022+ engines, Warn if SP 12691 (GHG Tracking Lifetime Active Technology Index) is not included in DM24 response from Engine #1 (0)
FAIL: 6.1.4.2.d - For MY2022+ diesel engines, Fail if SP 12675 (NOx Tracking Engine Activity Lifetime Fuel Consumption Bin 1 - Total)
            is not included in DM24 response from Exhaust Emission Controller (61)
WARN: 6.1.4.2.e. - For all MY2022+ engines, Fail if SP 12730 (GHG Tracking Engine Run Time) is not included in DM24 response from Exhaust Emission Controller (61)
WARN: 6.1.4.2.f - For all MY2022+ engines, Warn if SP 12691 (GHG Tracking Lifetime Active Technology Index) is not included in DM24 response from Exhaust Emission Controller (61)

End Test 1.4 - DM24: SPN support

**Proposed change:**
6.1.4.2 Fail/warn criteria:7 
a. Fail if retry was required to obtain DM24 response.   
b. Fail if one or more minimum expected SPs for data stream, excluding NOx Binning and GHG Tracking, that are not supported per section A.1, Minimum Support Table, from the OBD ECU(s).  
c. Fail if one or more minimum expected SPs for freeze frame not supported per section A.2, Criteria for Freeze Frame Evaluation, from the OBD ECU(s).
d. For MY2022+ diesel engines, Fail if SP 12675 (NOx Tracking Engine Activity Lifetime Fuel Consumption Bin 1 - Total) is not included in **_a_** DM24 response. 
e. For all MY2022+ engines, Fail if SP 12730 (GHG Tracking Engine Run Time) is not included in **_a_** DM24 response. 
f. For all MY2022+ engines, Warn if SP 12691 (GHG Tracking Lifetime Active Technology Index) is not included in **_a_** DM24 response.

**Comment by ericthomasswenson** [comment]
Only one OBD controller need support these SPs (individually)

D 4 SPN 12675 - NOx Tracking Engine Activity Lifetime Fuel Consumption Bin 1 (Total)
D 1 SPN 12691 - GHG Tracking Lifetime Active Technology Index
D 4 SPN 12730 - GHG Tracking Lifetime Engine Run Time

It doesn’t have to be the same SA

This could be a latent issue for distributed SP support in 3.0.13.

**Comment by ericthomasswenson** [comment]
See #1106. Support for these messages was not in 3.1.0.

**Comment by ericthomasswenson** [comment]
Similar for 3.1.1

Required Data Stream SPNs are not supported. SPNs: 27
Required Data Stream SPNs are not supported. SPNs: 5829
FAIL: 6.1.4.2.b - N.2 One or more SPNs for data stream is not supported
WARN: 6.1.4.2.f - SP 12691 is not included in DM24 response from Engine #1 (0)
FAIL: 6.1.4.2.d - SP 12675 is not included in DM24 response from Management Computer #1 (39)
WARN: 6.1.4.2.e - SP 12730 is not included in DM24 response from Management Computer #1 (39)
WARN: 6.1.4.2.f - SP 12691 is not included in DM24 response from Management Computer #1 (39)
FAIL: 6.1.4.2.d - SP 12675 is not included in DM24 response from Exhaust Emission Controller (61)
WARN: 6.1.4.2.e - SP 12730 is not included in DM24 response from Exhaust Emission Controller (61)
WARN: 6.1.4.2.f - SP 12691 is not included in DM24 response from Exhaust Emission Controller (61)

**Comment by ericthomasswenson** [comment]
NOx Binning and GHG tracking are vehicle level requirements. 
These would have been better stated as, _**from any OBD ECU.**_
From each OBD ECU was not intended.

6.1.4.2 Fail Criteria
a.​​Fail if retry was required to obtain the DM24 response.
b.​Fail if one or more minimum expected SPs for data stream not supported per Section A.1, Minimum Support Table, from the OBD ECU(s).
c.​Fail if one or more minimum expected SPs for freeze frame not supported per Section A.2, Criteria for Freeze Frame Evaluation, from the OBD ECU(s).
d. For MY2022+ diesel engines, Fail if SP 12675 (NOx Tracking Engine Activity Lifetime Fuel Consumption Bin 1 - Total) is not included in DM24 response, _**from any OBD ECU.**_
e. For all MY2022+ engines, Fail if SP 12730 (GHG Tracking Engine Run Time) is not included in DM24 response,  _**from any OBD ECU.**_
f. For all MY2022+ engines, Warn if SP 12691 (GHG Tracking Lifetime Active Technology Index) is not included in DM24 response, _**from any OBD ECU.**_
g. For all MY2022+ HEV and BEV drives, Fail if SP 12797 (Hybrid Lifetime Propulsion System Active Time), is not included in DM24 response, _**from any OBD ECU.**_ (SP 12797 is Lifetime EV Tracking Byte 1 SP)
h. For all MY2022+ Plug-in HEV drives, Fail if SP 12783 (Hybrid Lifetime Distance Traveled in Charge Depleting Operation with Engine off), is not included in DM24 response,  _**from any OBD ECU.**_

**Comment by ericthomasswenson** [comment]
Close in favor of #1178

6.1.4 text updated in #1178
