### ISSUE TITLE
Tool warns for PGN 65259 while the engine is running with a distributed system

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1112]
**Per CARB regulations we only support the engine serial number from one ECU (SA 0), the tool flags SA 1 and 61 for not replying when the engine is running.**
(4.8.2) All 2013 and subsequent model year engines (except for heavy-duty engines certified to the Low Emission Vehicle III exhaust emission standards defined in title 13, CCR section 1961.2) shall have the engine serial number (ESN) available in a standardized format through the standardized data link connector. Only one electronic control unit per vehicle shall report the ESN to an SAE J1978/J1939 scan tool.

Start Test 2.7 - Component ID: Make
11:49:37.5335 Destination Specific org.etools.j1939tools.j1939.packets.ComponentIdentificationPacket Request to Engine #1 (0)
11:49:37.5370 18EA00F9 [3] EB FE 00 (TX)
11:49:37.6510 1CFEEB00 [39] 44 54 44 53 43 2A 34 37 32 4E 31 39 2A 34 37 32 39 31 32 53 39 39 39 39 39 39 39 2A 20 20 20 20 20 20 20 20 20 20 2A
Component Identification from Engine #1 (0): {
  Make: DTDSC
  Model: 472N19
  Serial: 472912S9999999
  Unit: 
}

11:49:37.6530 Destination Specific org.etools.j1939tools.j1939.packets.ComponentIdentificationPacket Request to Engine #2 (1)
11:49:37.6565 18EA01F9 [3] EB FE 00 (TX)
11:49:37.6675 18E8FF01 [8] 01 FF FF FF F9 EB FE 00
Acknowledgment from Engine #2 (1): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 65259
11:49:37.6684 Destination Specific org.etools.j1939tools.j1939.packets.ComponentIdentificationPacket Request to Exhaust Emission Controller (61)
11:49:37.6705 18EA3DF9 [3] EB FE 00 (TX)
11:49:37.6805 18E8FF3D [8] 01 FF FF FF F9 EB FE 00
Acknowledgment from Exhaust Emission Controller (61): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 65259
11:49:37.6815 Global Component Identification Request
11:49:37.6845 18EAFFF9 [3] EB FE 00 (TX)
11:49:37.6880 18E8FF25 [8] 00 00 FF FF F9 EB FE 00
Acknowledgment from Off Vehicle Gateway (37): Response: ACK, Group Function: 0, Address Acknowledged: 249, PGN Requested: 65259

11:49:37.9375 1CFEEB25 [33] 44 54 4E 41 20 2A 43 65 6E 74 72 61 6C 20 47 61 74 65 57 61 79 2A 30 30 30 30 36 30 30 38 39 39 2A
Component Identification from Off Vehicle Gateway (37): {
  Make: DTNA
  Model: Central GateWay
  Serial: 0000600899
  Unit: 
}

11:49:37.7885 1CFEEBE8 [14] 44 54 4E 41 2A 43 41 4D 45 52 41 2A 2A 2A
Component Identification from Forward Road Image Processor (232): {
  Make: DTNA
  Model: CAMERA
  Serial: 
  Unit: 
}

11:49:38.0505 1CFEEB00 [39] 44 54 44 53 43 2A 34 37 32 4E 31 39 2A 34 37 32 39 31 32 53 39 39 39 39 39 39 39 2A 20 20 20 20 20 20 20 20 20 20 2A
Component Identification from Engine #1 (0): {
  Make: DTDSC
  Model: 472N19
  Serial: 472912S9999999
  Unit: 
}

11:49:37.8910 1CFEEB03 [18] 44 45 54 44 58 2A 47 32 38 31 2D 31 32 2A 20 2A 20 2A
Component Identification from Transmission #1 (3): {
  Make: DETDX
  Model: G281-12
  Serial: 
  Unit: 
}

WARN: 6.2.7.5.a - Engine #2 (1) did not support PGN 65259 with the engine running
WARN: 6.2.7.5.a - Exhaust Emission Controller (61) did not support PGN 65259 with the engine running

End Test 2.7 - Component ID: Make

**From part 1:**

Start Test 1.9 - Component ID: Make
11:47:14.6090 Destination Specific org.etools.j1939tools.j1939.packets.ComponentIdentificationPacket Request to Engine #1 (0)
11:47:14.6115 18EA00F9 [3] EB FE 00 (TX)
11:47:14.7310 1CFEEB00 [39] 44 54 44 53 43 2A 34 37 32 4E 31 39 2A 34 37 32 39 31 32 53 39 39 39 39 39 39 39 2A 20 20 20 20 20 20 20 20 20 20 2A
Component Identification from Engine #1 (0): {
  Make: DTDSC
  Model: 472N19
  Serial: 472912S9999999
  Unit: 
}

11:47:14.7345 Destination Specific org.etools.j1939tools.j1939.packets.ComponentIdentificationPacket Request to Engine #2 (1)
11:47:14.7370 18EA01F9 [3] EB FE 00 (TX)
11:47:14.7465 18E8FF01 [8] 01 FF FF FF F9 EB FE 00
Acknowledgment from Engine #2 (1): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 65259
11:47:14.7530 Destination Specific org.etools.j1939tools.j1939.packets.ComponentIdentificationPacket Request to Exhaust Emission Controller (61)
11:47:14.7555 18EA3DF9 [3] EB FE 00 (TX)
11:47:14.7670 18E8FF3D [8] 01 FF FF FF F9 EB FE 00
Acknowledgment from Exhaust Emission Controller (61): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 65259
Function 0 ECU is Engine #1 (0)
11:47:14.7755 Global Component Identification Request
11:47:14.7775 18EAFFF9 [3] EB FE 00 (TX)
11:47:15.1405 1CFEEB00 [39] 44 54 44 53 43 2A 34 37 32 4E 31 39 2A 34 37 32 39 31 32 53 39 39 39 39 39 39 39 2A 20 20 20 20 20 20 20 20 20 20 2A
Component Identification from Engine #1 (0): {
  Make: DTDSC
  Model: 472N19
  Serial: 472912S9999999
  Unit: 
}

11:47:14.7815 18E8FF25 [8] 00 00 FF FF F9 EB FE 00
Acknowledgment from Off Vehicle Gateway (37): Response: ACK, Group Function: 0, Address Acknowledged: 249, PGN Requested: 65259

11:47:15.0315 1CFEEB25 [33] 44 54 4E 41 20 2A 43 65 6E 74 72 61 6C 20 47 61 74 65 57 61 79 2A 30 30 30 30 36 30 30 38 39 39 2A
Component Identification from Off Vehicle Gateway (37): {
  Make: DTNA
  Model: Central GateWay
  Serial: 0000600899
  Unit: 
}

11:47:14.8820 1CFEEBE8 [14] 44 54 4E 41 2A 43 41 4D 45 52 41 2A 2A 2A
Component Identification from Forward Road Image Processor (232): {
  Make: DTNA
  Model: CAMERA
  Serial: 
  Unit: 
}

11:47:14.9810 1CFEEB03 [18] 44 45 54 44 58 2A 47 32 38 31 2D 31 32 2A 20 2A 20 2A
Component Identification from Transmission #1 (3): {
  Make: DETDX
  Model: G281-12
  Serial: 
  Unit: 
}

End Test 1.9 - Component ID: Make

**Perhaps we change this to Info instead of Warn?**

**Comment by ericthomasswenson** [comment]
Support for component ID is expected from OBD Devices …

Possibly this was changed from Fail to warn years ago.

NACK with 03 conditions not correct … instead of 01 … implying not supported would be better behavior.

I think info can be sold with 03h to CARB

**Comment by ericthomasswenson** [comment]
Update document text to require only responses from function 0 devices, one of which must support ESN (SPN 588).

6.2.7 Component ID: Make, Model, Serial Number Support 
6.2.7.1 Actions 
a. Destination Specific (DS) Component ID request (PG 59904) for PG 65259 (SPs 586, 587, and 588) to each OBD ECU. 

6.2.7.2 Fail Criteria 
a. Fail if any **_function 0_** device does not support PG 65259 with the engine running that supported PG 65259 with the engine off in part 1.  
b. Fail if there is any difference between the part 2 response and the part 1 response, as PG 65259 data is defined to be static values.  

6.2.7.3 Actions2 (NOTE: No warning message shall be provided for responses from non-OBD devices for PG 59904.)  
a. Global Request for Component ID request (PG 59904) for PG 65259 (SPs 586, 587, and 588). 
b. Display each positive return in the log. 

6.2.7.4 Fail Criteria2 for Function 0 
a. Fail if there is no positive response from function 0. (Global request not supported or timed out.) 
b. Fail if the global response does not match the destination specific response from function 0 **devices**.

6.2.7.5 Warn Criteria2 for OBD ECUs Other than Function 0 
a. **_Info_** if Component ID not supported for the global query in 6.2.7.3 with engine running.

**Comment by ericthomasswenson** [comment]
The current text may be harsh.  A new proposal will be needed.

The ESN must be provided with the engine running.

**Comment by ericthomasswenson** [comment]
Perhaps,

6.2.7.2 Fail Criteria
a. Fail if any OBD ECU NACKs (control byte = 1) its DS request, where the ECU supported PG 65259 in Part 1
b. Info if any OBD ECU NACKs (control byte = 2) its DS request. (2, access denied, conditions not correct - Engine running.
c. Fail if there is any difference between the part 2 response and the part 1 response from an OBD ECU, as PG 65259 data is defined to be static values.
d. Fail if no Function 0 device supports PG 65259 with the engine running.

**Comment by battjt** [comment]
How about?
a. Fail if any OBD ECU does not respond or NACKs (control byte = 1) its DS request, where the ECU supported PG 65259 in Part 1

**Comment by ericthomasswenson** [comment]
See similar request from hybrid TF Mark Stepper item 4.

**Comment by naroner** [comment]
@ericthomasswenson 

This has been partially fixed in 3.1.23, however instead of:
_"WARN: 6.2.7.5.a - Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/2 (1) did not support PGN 65259 with the engine running"_ 

I am now getting: 
_"FAIL: 6.2.7.2.c - Engine #2 (1) reported difference between the part2 response and the part 1 response"_

It appears to me that it is not counting a NACK as the same response.
