### ISSUE TITLE
Tool is not honoring NACKs when requesting DM7/DM58 for unsupported SPs

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1113]
**The tool is requesting DM7 to get DM58 for unsupported SPs, however it is not honoring the NACK that the controller responds with**

11:26:41.3086 Sending DM7 for DM58 to Engine #1 (0) for SPN 84
11:26:41.3141 18E300F9 [8] F5 54 00 1F FF FF FF FF (TX)
11:26:41.9121 Timeout - No Response
11:26:41.9146 18E300F9 [8] F5 54 00 1F FF FF FF FF (TX)
11:26:42.5111 Timeout - No Response
11:26:42.5131 18E300F9 [8] F5 54 00 1F FF FF FF FF (TX)
11:26:43.1086 Timeout - No Response
FAIL: 6.12.11.5.a - NACK not received for DM7 PG from OBD ECU Engine #1 (0) for spn 84
![image](https://user-images.githubusercontent.com/101883690/164501790-394a491c-16cd-4fc1-82b2-65680262632c.png)

11:26:43.1091 Sending DM7 for DM58 to Engine #2 (1) for SPN 157
11:26:43.1126 18E301F9 [8] F5 9D 00 1F FF FF FF FF (TX)
11:26:43.7096 Timeout - No Response
11:26:43.7121 18E301F9 [8] F5 9D 00 1F FF FF FF FF (TX)
11:26:44.3086 Timeout - No Response
11:26:44.3116 18E301F9 [8] F5 9D 00 1F FF FF FF FF (TX)
11:26:44.9076 Timeout - No Response
FAIL: 6.12.11.5.a - NACK not received for DM7 PG from OBD ECU Engine #2 (1) for spn 157
![image](https://user-images.githubusercontent.com/101883690/164501325-f1e3540b-9929-42dc-881b-1237f1db7896.png)

11:26:44.9086 Sending DM7 for DM58 to Exhaust Emission Controller (61) for SPN 1761
11:26:44.9111 18E33DF9 [8] F5 E1 06 1F FF FF FF FF (TX)
11:26:45.5071 Timeout - No Response
11:26:45.5101 18E33DF9 [8] F5 E1 06 1F FF FF FF FF (TX)
11:26:46.1066 Timeout - No Response
11:26:46.1091 18E33DF9 [8] F5 E1 06 1F FF FF FF FF (TX)
11:26:46.7046 Timeout - No Response
FAIL: 6.12.11.5.a - NACK not received for DM7 PG from OBD ECU Exhaust Emission Controller (61) for spn 1761
![image](https://user-images.githubusercontent.com/101883690/164501228-56dfcf1e-34ac-4bb4-a1c0-222ea5b42779.png)

**Comment by ericthomasswenson** [comment]
Yes your report file does not show the NACK, as it should.

Since NACK is the expected response of an SPN which does not support DM58 … two retries seems excessive.  … Had the ECU’s NACK, been observed.  I see 3 timeouts.  The retries are expected tool behavior … to try and achieve test step goals.  The requirement to NACK is in J1939-73 5.7.58.

Your logging tool shows the NACKs.

**Comment by naroner** [comment]
Based on the raw log that I took during the test the ECUs are responding with a NACK for all 3 requests, the tool just isn't seeing it.

The temp directory log file no longer logs the raw CAN trace, it only shows failures/warnings that are added.

**Comment by ericthomasswenson** [comment]
See #1114 for related log changes.

NACKs for DM7 differ slightly from NACKs for Request (00EA00h), both need to be observed.

**Comment by jacobbosch-cummins** [comment]
This was observed with Cummins when testing on 2019 and 2022 engines.  The engine controller is NACKing the request for the unsupported SPN, but the tool records it as a timeout and issues a failure.

**Comment by ericthomasswenson** [comment]
Bug confirmed by developer

**Comment by vmuthu2** [comment]
Kindly ensure that the below NACK response is also covered for DM7/DM58 response.

67.190782 1  18E300F9x Tx d 8 F5 8B 02 1F FF FF FF FF (Request)
67.195724 1  18E8FF00x Rx d 8 01 FF FF FF FF 00 E3 00 (NACK response)

**Comment by battjt** [comment]
Yes.  We were expecting a NACK for DM30, not a NACK for DM7, like this:  
```18E8FF00x Rx d 8 01 FF FF FF FF 00 A4 00```
(With EA00, the NACK contains the requested PGN, not the requesting PGN of EA00, it was assumed that a NACK for DM7 E300 likewise would include the resulting PGN A400.)

-21 says "Parameter Group Number of requested information"  Is there a section that I'm missing that better describes this?

**Comment by ericthomasswenson** [comment]
See Appendix B SAE J1939-21

DM7 is a command. The examples for command (PG CF) use CF in the response.
The PG for DM7 is E3, thus E3 should appear in the PGN field of the response.

The example says to use FF for DA in PS. I think we should also accept the sender’s DA (240).
We don’t enforce the DA field in the data. This would also be the sender’s DA (240).

For DM7 the TID defines which response. These include DM8, DM30, and DM58.
Sending E3 and the DA is a simpler answer than sending one of three PGs.

BTW … DM22 defines its own response structure… 
IF E8 is used instead, as indicated in the criteria, the PGN would be the DM22 PGN.

**Comment by ericthomasswenson** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40"><div align="center" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

  | PF | PS (GE, DA) | SA | DATA
-- | -- | -- | -- | --
1)   BROADCAST | 254 | 235 (GE) | 000 | 236912
2)   SPECIFIC REQUEST | 234 | 000 (DA) | 003 | PGN 65259
1)   RESPONSE | 254 | 235 (GE) | 000 | 236912
or |   |   |   |  
4)   NACK | 232 | 255 (DA) | 000 | 01, 255, 255, 255, DA, PGN 65259
2A) GLOBAL REQUEST | 234 | 255 (DA) | 003 | PGN 65259
1)   RESPONSE | 254 | 235 (GE) | 000 | 236912
3)   COMMAND | CF | 000 (DA) | 240 |  
1)   ACK | 232 | 255 (DA) | 000 | 00, 255, 255, 255, DA, PGN for CF
or |   |   |   |  
4)   NACK | 232 | 255 (DA) | 000 | 01, 255, 255, 255, DA, PGN for CF
or   OTHER1 |   |   |   |  
1 COMMANDs must always have a mechanism for confirming that the action was successful or not. An ACK message is not required if another means is available. This helps to minimize bus traffic. For example, a torque command to the engine can be confirmed by looking at the torque mode bits as well as the torque value coming from the engine.

</div></html>

**Comment by ericthomasswenson** [comment]
The text says

3)	COMMAND 
For some commands it may be desirable to have a specific acknowledgment that the task has been completed. When this is the case, a message can be sent back as either an ACK = COMMAND COMPLETE or a NACK = COMMAND NOT ABLE TO BE COMPLETED. The example in Figure B1 uses “CF” as the command that will be acknowledged with an ACK or NACK. 

4)	ACK 
Send the NACK message to indicate that the command or request could not be acted upon (invalid request). The NACK message contains the offending Parameter Group Number in the Data field. If the Parameter Group Number in a COMMAND or REQUEST is not recognized by the destination (addressed device), it should still NACK. If the Parameter Group Number is recognized, but the parameter(s) are not available, a normal response is sent back but with the data value(s) set to 255.

**Comment by ericthomasswenson** [comment]
The team supported the command interpretation from J1839-21

**Comment by naroner** [comment]
@ericthomasswenson This is fixed in 3.1.19
