### ISSUE TITLE
RAW CAN data no longer in TEMP log

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1114]
Is this intended?

from Nathan Roner, “The temp directory log file no longer logs the raw CAN trace, it only shows failures/warnings that are added.”

**Comment by ericthomasswenson** [comment]
Joe to reconfigure to include NACKs et.al. and provide ascii file in the style of vector .asc file.

See #1105 for additional related comments.

See #1081 for adapter error in log comment.

Adding user interface / application errors is also desired.

**Comment by ericthomasswenson** [comment]
ASC to include tp.dt tp.rts, tp.cts, tp.bam, tp.am to SAE J1939-73 Appendix C
Will not include UI messages. (In the next release) 

Java error log will no longer record packets.

**Comment by ericthomasswenson** [comment]
Raw CAN messages were observed by Bob Halfman.

**Comment by ericthomasswenson** [comment]
V. 3.1.1 ASC log loads into excel.

**Comment by battjt** [comment]
Still missing channel from Vector .asc logs.
