### ISSUE TITLE
Part 1 Step 26 is confusing

### ISSUE THREAD

**Issue by mmschaefer** [Equipment-and-Tool-Institute/j1939-84#1116]
6.1.17.24.c. Fail all values where the corresponding value received in part 1 is greater than the part 2 value.

Is this a copy paste error?  We are in Part 1 and can't yet check the value for part 2.

**Comment by ericthomasswenson** [comment]
Yes, I did the part 2 text first. Delete c. Renumber test 1.17 to test 1.26

6.1.26.24 Fail criteria12 for MY2022+ Plug-in HEV DRIVES
a. Fail PG query where no response was received.  
b. Fail PG query where any accumulator value received is greater than FAFFFFFFh.

**Comment by ericthomasswenson** [comment]
Yes, I did the part 2 text first. Delete c. Renumber test 1.17 to test 1.26

6.1.26.24 Fail criteria12 for MY2022+ Plug-in HEV DRIVES
a. Fail PG query where no response was received.
b. Fail PG query where any accumulator value received is greater than FAFFFFFFh.

**Comment by ericthomasswenson** [comment]
Complete section 6 text now provided.
