### ISSUE TITLE
File extension changed with version 3.1.0

### ISSUE THREAD

**Issue by jacobbosch-cummins** [Equipment-and-Tool-Institute/j1939-84#1117]
It was noticed that the file extension changed from ".j1939-84" to ".j1939tools-84".  If this was intentional, feel free to mark invalid or close.

**Comment by battjt** [comment]
It should be changed to .txt so that double clicking in Windows defaults to opening in Notepad.

**Comment by ericthomasswenson** [comment]
Agreed, Joe. I’m adding the bug label to keep it with things to be worked on soon.

**Comment by jacobbosch-cummins** [comment]
Noted that 3.1.2 log ends in .txt.  This can be closed I believe.

**Comment by ericthomasswenson** [comment]
See above recommendation
