### ISSUE TITLE
Extra popup for timeout on DM56

### ISSUE THREAD

**Issue by jacobbosch-cummins** [Equipment-and-Tool-Institute/j1939-84#1118]
There is a UI dialog popup for a timeout on DM56 for all engine model years tested (2016, 2019, and 2022) during part 1.  The diagnostic in the report seems to work correctly and only issues a failure for MY2024+ (tested by setting model year to 2031).

The user must interact with the dialog box to close it.

Is the popup needed?  Even for MY2024+, the failure could be logged in the report similar other message timeouts.

**Comment by ericthomasswenson** [comment]
This is a hedge on entering the wrong engine model, and needing to start the test over.

it’s perhaps more effective when DM56 is supported. (More often than it is).

Thanks for the 2031 MY exercise.

**Comment by ericthomasswenson** [comment]
Consider removal as part of task 8

**Comment by ericthomasswenson** [comment]
[image]

**Comment by ericthomasswenson** [comment]
[EngineMYpopup.pptx](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/8599623/EngineMYpopup.pptx)

**Comment by jacobbosch-cummins** [comment]
The popup no longer occurs on 3.1.3.  A failure is correctly logged on a MY24+ engine year that does not support DM56.  Recommend closing this issue.

**Comment by ericthomasswenson** [comment]
Closed as recommended
