### ISSUE TITLE
Vehicle Information header is not counting OBD ECUs

### ISSUE THREAD

**Issue by jacobbosch-cummins** [Equipment-and-Tool-Institute/j1939-84#1119]
The Vehicle Information header in version 3.1.0 is counting 0 OBD ECUs at the start of the log, but the rest of the test seems unaffected.  The User Data Entry still automatically populates with the correct number of Emissions ECUs.  This was completed on a HIL bench, so the CALIDs, VIN, and ESN are invalid.  Both tests were completed with the same HIL configuration and same engine controller calibration.

### 3.0.13:
User Data Entry: 

Engine Model Emissions Year: 2031
**Number of Emissions ECUs Expected: 1**
Number of CAL IDs Expected: 6
Fuel Type: Diesel vehicle
Ignition Type: Compression
Number of Trips for Fault B Implant: 1

Vehicle Information:
VIN: 11111111111111111
Vehicle MY: 2031
Engine MY: 2031
Cert. Engine Family: Baseline 3.0.13 - 2022 B6.7
**Number of OBD ECUs Found: 1
     Make: CMMNS, Model: 6B u21D0670000000, Serial: 00000000**
Number of CAL IDs Found: 6
     DM19 from Engine #1 (0): [
       CAL ID of LS10389.02 and CVN of 0x52ABA7EF
       CAL ID of NOx-Sensor-ATO1 and CVN of 0x42305354
       CAL ID of NOx-Sensor-ATO1 and CVN of 0x42305354
       CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
       CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
       CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
     ]

### 3.1.0:
User Data Entry: 

Engine Model Emissions Year: 2031
**Number of Emissions ECUs Expected: 1**
Number of CAL IDs Expected: 6
Fuel Type: Diesel vehicle
Ignition Type: Compression
Number of Trips for Fault B Implant: 1

Vehicle Information:
VIN: 11111111111111111
Vehicle MY: 2031
Engine MY: 2031
Cert. Engine Family: 3.1.0 - 2022 B6.7
**Number of OBD ECUs Found: 0**

Number of CAL IDs Found: 6
     DM19 from Engine #1 (0): [
       CAL ID of LS10389.02 and CVN of 0x52ABA7EF
       CAL ID of NOx-Sensor-ATO1 and CVN of 0x42305354
       CAL ID of NOx-Sensor-ATO1 and CVN of 0x42305354
       CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
       CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
       CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
     ]

**Comment by ericthomasswenson** [comment]
Jacob, a DM5 showing 14h from SA 0 would cinch the nail on this.

Looks like the list count in ‘6.1.3’ could have broken.

**Comment by jacobbosch-cummins** [comment]
Below are the DM5 responses from Part 1.3 from the respective logs.

### 3.0.13
Start Test 1.3 - DM5: Diagnostic readiness 1

11:55:52.6065 Global DM5 Request
11:55:52.6095 18EAFFF9 [3] CE FE 00 (TX)
11:55:52.6135 18FECE00 [8] 01 00 14 37 E0 1E E0 1E
DM5 from Engine #1 (0): OBD Compliance: HD OBD (20), Active Codes: 1, Previously Active Codes: 0

### 3.1.0
Start Test 1.3 - DM5: Diagnostic readiness 1
09:55:19.4040 Global DM5 Request
09:55:19.4030 18EAFFF9 [3] CE FE 00 (TX)
09:55:19.4060 18FECE00 [8] 03 00 14 37 E0 1E E0 1E
DM5 from Engine #1 (0): OBD Compliance: HD OBD (20), Active Codes: 3, Previously Active Codes: 0

**Comment by ericthomasswenson** [comment]
Present still in 3.1.3

**Comment by battjt** [comment]
Still present in 3.1.7.

**Comment by ericthomasswenson** [comment]
Yes a zero count was observed.

**Comment by markmorrisoncummins** [comment]
3.1.8 - 3.1.10 have the correct count for me.
