### ISSUE TITLE
CAL ID check failing on null byte padding

### ISSUE THREAD

**Issue by jacobbosch-cummins** [Equipment-and-Tool-Institute/j1939-84#1120]
Per J1939/73, the CAL ID component of DM19 is a fixed length of 16 bytes and is padded with 0x00.  It appears that 3.1.0 is failing CAL IDs that have padding because 0x00 is unprintable ASCII.  Additional tests were completed with CAL IDs and CVNs overridden in engine controller to check the tool's response, which seemed to confirm the theory.

### 3.0.13 with 3 invalid CAL IDs/CVNs (tool correctly flags 3 invalid CAL IDs)
11:55:54.4995 Global DM19 Request
11:55:54.5015 18EAFFF9 [3] 00 D3 00 (TX)
11:55:55.4905 18D3FF00 [120] EF A7 AB 52 4C 53 31 30 33 38 39 2E 30 32 00 00 00 00 00 00 54 53 30 42 4E 4F 78 2D 53 65 6E 73 6F 72 2D 41 54 4F 31 00 54 53 30 42 4E 4F 78 2D 53 65 6E 73 6F 72 2D 41 54 4F 31 00 00 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 00 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 00 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
DM19 from Engine #1 (0): [
  CAL ID of LS10389.02 and CVN of 0x52ABA7EF
  CAL ID of NOx-Sensor-ATO1 and CVN of 0x42305354
  CAL ID of NOx-Sensor-ATO1 and CVN of 0x42305354
  CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
  CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
  CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
]
WARN: 6.1.7.3.b - Engine #1 (0) provided more than one CAL ID and CVN pair in a single DM19 message
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.iii - Received CAL ID is all 0xFF from Engine #1 (0)
FAIL: 6.1.7.2.b.iii - Received CAL ID is all 0xFF from Engine #1 (0)
FAIL: 6.1.7.2.b.iii - Received CAL ID is all 0xFF from Engine #1 (0)
FAIL: 6.1.7.2.b.iii - Received CVN is all 0x00 from Engine #1 (0)
FAIL: 6.1.7.2.b.iii - Received CVN is all 0x00 from Engine #1 (0)
FAIL: 6.1.7.2.b.iii - Received CVN is all 0x00 from Engine #1 (0)

### 3.1.0 with 3 invalid CAL IDs/CVNs (tool incorrectly flags 6 invalid CAL IDs)
09:55:21.9140 Global DM19 Request
09:55:21.9130 18EAFFF9 [3] 00 D3 00 (TX)
09:55:22.9020 1CD3FF00 [120] EF A7 AB 52 4C 53 31 30 33 38 39 2E 30 32 00 00 00 00 00 00 54 53 30 42 4E 4F 78 2D 53 65 6E 73 6F 72 2D 41 54 4F 31 00 54 53 30 42 4E 4F 78 2D 53 65 6E 73 6F 72 2D 41 54 4F 31 00 00 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 00 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 00 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
DM19 from Engine #1 (0): [
  CAL ID of LS10389.02 and CVN of 0x52ABA7EF
  CAL ID of NOx-Sensor-ATO1 and CVN of 0x42305354
  CAL ID of NOx-Sensor-ATO1 and CVN of 0x42305354
  CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
  CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
  CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
]

WARN: 6.1.7.3.b - Engine #1 (0) provided more than one CAL ID and CVN pair in a single DM19 message
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.iii - Received CAL ID is all 0xFF from Engine #1 (0)
FAIL: 6.1.7.2.b.iii - Received CAL ID is all 0xFF from Engine #1 (0)
FAIL: 6.1.7.2.b.iii - Received CAL ID is all 0xFF from Engine #1 (0)
FAIL: 6.1.7.2.b.iii - Received CVN is all 0x00 from Engine #1 (0)
FAIL: 6.1.7.2.b.iii - Received CVN is all 0x00 from Engine #1 (0)
FAIL: 6.1.7.2.b.iii - Received CVN is all 0x00 from Engine #1 (0)

### 3.1.0 with 0 invalid CAL IDs/CVNs (tool incorrectly flags 6 CAL IDs)
15:22:03.5200 Global DM19 Request
15:22:03.5170 18EAFFF9 [3] 00 D3 00 (TX)
15:22:04.5070 1CD3FF00 [120] C2 6F 78 64 4B 57 31 30 38 36 34 2E 30 31 00 00 00 00 00 00 54 53 30 42 4E 4F 78 2D 53 65 6E 73 6F 72 2D 41 54 4F 31 00 54 53 30 42 4E 4F 78 2D 53 65 6E 73 6F 72 2D 41 54 4F 31 00 EF BE AD DE 36 37 38 39 30 00 00 00 00 00 00 00 00 00 00 00 EF BE AD DE 31 32 33 34 35 00 00 00 00 00 00 00 00 00 00 00 EF BE AD DE 41 42 43 44 45 00 00 00 00 00 00 00 00 00 00 00
DM19 from Engine #1 (0): [
  CAL ID of KW10864.01 and CVN of 0x64786FC2
  CAL ID of NOx-Sensor-ATO1 and CVN of 0x42305354
  CAL ID of NOx-Sensor-ATO1 and CVN of 0x42305354
  CAL ID of 67890 and CVN of 0xDEADBEEF
  CAL ID of 12345 and CVN of 0xDEADBEEF
  CAL ID of ABCDE and CVN of 0xDEADBEEF
]

WARN: 6.1.7.3.b - Engine #1 (0) provided more than one CAL ID and CVN pair in a single DM19 message
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)

### 3.1.0 with 0 invalid CAL IDs/CVNs.  1 CAL ID is the full 16 bytes with no null padding (tool incorrectly flags 5 CAL IDs)
15:25:32.6677 Global DM19 Request
15:25:32.6687 18EAFFF9 [3] 00 D3 00 (TX)
15:25:33.6577 1CD3FF00 [120] C2 6F 78 64 4B 57 31 30 38 36 34 2E 30 31 00 00 00 00 00 00 54 53 30 42 4E 4F 78 2D 53 65 6E 73 6F 72 2D 41 54 4F 31 00 54 53 30 42 4E 4F 78 2D 53 65 6E 73 6F 72 2D 41 54 4F 31 00 EF BE AD DE 36 37 38 39 30 00 00 00 00 00 00 00 00 00 00 00 EF BE AD DE 31 32 33 34 35 36 37 38 39 3A 3B 3C 3D 3E 3F 40 EF BE AD DE 41 42 43 44 45 00 00 00 00 00 00 00 00 00 00 00
DM19 from Engine #1 (0): [
  CAL ID of KW10864.01 and CVN of 0x64786FC2
  CAL ID of NOx-Sensor-ATO1 and CVN of 0x42305354
  CAL ID of NOx-Sensor-ATO1 and CVN of 0x42305354
  CAL ID of 67890 and CVN of 0xDEADBEEF
  CAL ID of 123456789:;<=>?@ and CVN of 0xDEADBEEF
  CAL ID of ABCDE and CVN of 0xDEADBEEF
]

WARN: 6.1.7.3.b - Engine #1 (0) provided more than one CAL ID and CVN pair in a single DM19 message
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)

**Comment by ericthomasswenson** [comment]
See #1104 for padding comments

**Comment by ericthomasswenson** [comment]
From 3.1.2 Null Padding should be accepted.

09:59:57.6355 1CD3FF00 [100] D3 F6 78 8F 52 43 4A 58 54 44 48 41 00 00 00 00 00 00 00 00 A8 73 89 13 4E 4F 78 2D 53 41 45 31 34 61 20 41 54 49 31 00 8C 4B F9 C9 4E 4F 78 2D 53 41 45 31 34 61 20 41 54 4F 31 00 FB 1B B5 8C 30 32 30 31 30 31 30 30 30 35 00 00 00 00 00 00 D0 DD E7 48 50 4D 53 31 32 33 34 31 41 32 30 31 00 00 00 00
DM19 from Engine #1 (0): [
  CAL ID of RCJXTDHA and CVN of 0x8F78F6D3
  CAL ID of NOx-SAE14a ATI1 and CVN of 0x138973A8
  CAL ID of NOx-SAE14a ATO1 and CVN of 0xC9F94B8C
  CAL ID of 0201010005 and CVN of 0x8CB51BFB
  CAL ID of PMS12341A201 and CVN of 0x48E7DDD0
]

WARN: 6.1.7.3.b - Engine #1 (0) provided more than one CAL ID and CVN pair in a single DM19 message
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)

**Comment by ericthomasswenson** [comment]
6.1.7.2	Fail Criteria
a.	Fail if total number of reported CAL IDs is < user entered value for number of emission or diagnostic critical control units (test 6.1.2). 
b.	For responses from OBD ECUs:
i.	Fail if <> 1 CVN for every CAL ID. 
ii.	Fail if CAL ID not formatted correctly (**_printable ASCII, padded incorrectly, etc_**.). 
iii.	Fail if any received CAL ID is all FFh 
iv.	Fail if or any CVN received is all 00h. 
iv.	Fail if CVN padded with 16-binary zeros (where either the 1st two bytes are both 00h or the last two bytes both 00h). Note HD OBD CVNs are required to be 32-bits.incorrectly (padding shall use 00h in MSB for unused bytes).

6.1.7.3	Warn Criteria
a.	Warn if total number of reported CAL IDs is > user entered value for number of emission or diagnostic critical control units (test 6.1.2).
b.	WarnInfo if more than one CAL ID and CVN pair is provided in a single DM19 message. 
c.     For responses from OBD ECUs, warn if 00h is observed in either the first or fourth bytes.
d.     For responses from non-OBD ECUs:
i.	Warn if any non-OBD ECU provides CAL ID. 
ii.	Warn if <> 1 CVN for every CAL ID. 
iii.	Warn if CAL ID not formatted correctly (contains non-printable ASCII, padded incorrectly, etc.). 
iv.	Warn if any received CAL ID is all FFh 
v.	Warn if any received or any CVN is all 00h. 
iv.	Warn if CVN padded incorrectly (shall use 00h in MSB for unused bytes).

**Comment by battjt** [comment]
Sent back to develoment.  Null padding is incorrectly reported in 6.1.7.2.b.ii.

**Comment by anthonyhbest** [comment]
Tested with version 3.1.6 and bug is still present:

09:53:16.3536 Global DM19 Request
09:53:16.3578 18EAFFF9 [3] 00 D3 00 (TX)
09:53:17.9224 1CD3FF00 [180] 78 3E 44 42 50 43 49 2D 4E 41 30 30 30 32 33 33 34 34 31 33 1E 27 AE 0C 44 41 46 4E 6F 58 4E 5F 30 34 34 30 41 54 49 31 8C 4B F9 C9 4E 4F 78 2D 53 41 45 31 34 61 20 41 54 4F 31 00 D0 DD E7 48 50 4D 53 31 32 33 34 31 41 32 30 31 00 00 00 00 FB 1B B5 8C 30 32 30 31 30 31 30 30 30 35 00 00 00 00 00 00 8A 6C 84 79 30 32 31 32 30 37 30 31 4E 41 00 00 00 00 00 00 E3 FD 54 A8 45 47 52 5F 4D 59 32 30 32 31 5F 30 30 30 30 31 B6 80 7A 0A 42 50 56 5F 4D 59 32 30 32 31 5F 30 30 30 30 31 28 E7 00 00 30 35 30 33 30 30 30 30 30 31 00 00 00 00 00 00
DM19 from Engine #1 (0): [
  CAL ID of PCI-NA0002334413 and CVN of 0x42443E78
  CAL ID of DAFNoXN_0440ATI1 and CVN of 0x0CAE271E
  CAL ID of NOx-SAE14a ATO1 and CVN of 0xC9F94B8C
  CAL ID of PMS12341A201 and CVN of 0x48E7DDD0
  CAL ID of 0201010005 and CVN of 0x8CB51BFB
  CAL ID of 02120701NA and CVN of 0x79846C8A
  CAL ID of EGR_MY2021_00001 and CVN of 0xA854FDE3
  CAL ID of BPV_MY2021_00001 and CVN of 0x0A7A80B6
  CAL ID of 0503000001 and CVN of 0x0000E728
]

INFO: 6.1.7.3.b - Engine #1 (0) provided more than one CAL ID and CVN pair in a single DM19 message
WARN: 6.1.7.3.c - CAL ID 0503000001       has 00h is in either the first or fourth bytes
FAIL: 6.1.7.2.b.ii - OBD ECU Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - OBD ECU Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - OBD ECU Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - OBD ECU Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.ii - OBD ECU Engine #1 (0) CAL ID not formatted correctly (contains non-printable ASCII)
FAIL: 6.1.7.2.b.v - OBD ECU Received CVN with incorrect padding from Engine #1 (0)

**Comment by battjt** [comment]
The 3.1.6 build was incorrect and missing this fix (and others).

**Comment by battjt** [comment]
Should be fixed in 3.1.7.

**Comment by battjt** [comment]
reported as still a problem in 3.1.7

**Comment by markmorrisoncummins** [comment]
This appears to be corrected. From 3.1.10:

> Start Test 1.7 - DM19: Calibration information
> 16:09:15.9252 Global DM19 Request
> 16:09:15.9276 18EAFFF9 [3] 00 D3 00 (TX)
> 16:09:16.7513 1CD3FF00 [100] 1D AB 4D D7 2A 2A 2A 2A 2A 2A 2A 20 2A 2A 00 00 00 00 00 00 A8 73 89 13 4E 4F 78 2D 53 41 45 31 34 61 20 41 54 49 31 00 7C 63 3A CD 4E 4F 58 5F 4E 5F 30 50 32 30 20 41 54 4F 31 00 FB 1B B5 8C 30 32 30 31 30 31 30 30 30 35 00 00 00 00 00 00 38 63 91 0E 30 32 31 32 30 37 30 30 31 36 00 00 00 00 00 00
> DM19 from Engine #1 (0): [
>   CAL ID of ******* ** and CVN of 0xD74DAB1D
>   CAL ID of NOx-SAE14a ATI1 and CVN of 0x138973A8
>   CAL ID of NOX_N_0P20 ATO1 and CVN of 0xCD3A637C
>   CAL ID of 0201010005 and CVN of 0x8CB51BFB
>   CAL ID of 0212070016 and CVN of 0x0E916338
> ]
> 
> INFO: 6.1.7.3.b - Engine #1 (0) provided more than one CAL ID and CVN pair in a single DM19 message
> 16:09:16.7588 Destination Specific DM19 Request to Engine #1 (0)
> 16:09:16.7606 18EA00F9 [3] 00 D3 00 (TX)
> 16:09:16.7709 1CD3F900 [100] 1D AB 4D D7 2A 2A 2A 2A 2A 2A 2A 20 2A 2A 00 00 00 00 00 00 A8 73 89 13 4E 4F 78 2D 53 41 45 31 34 61 20 41 54 49 31 00 7C 63 3A CD 4E 4F 58 5F 4E 5F 30 50 32 30 20 41 54 4F 31 00 FB 1B B5 8C 30 32 30 31 30 31 30 30 30 35 00 00 00 00 00 00 38 63 91 0E 30 32 31 32 30 37 30 30 31 36 00 00 00 00 00 00
> DM19 from Engine #1 (0): [
>   CAL ID of ******* ** and CVN of 0xD74DAB1D
>   CAL ID of NOx-SAE14a ATI1 and CVN of 0x138973A8
>   CAL ID of NOX_N_0P20 ATO1 and CVN of 0xCD3A637C
>   CAL ID of 0201010005 and CVN of 0x8CB51BFB
>   CAL ID of 0212070016 and CVN of 0x0E916338
> ]
> 
> End Test 1.7 - DM19: Calibration information
