### ISSUE TITLE
Repeated phrases in 3.1.0 report log

### ISSUE THREAD

**Issue by jacobbosch-cummins** [Equipment-and-Tool-Institute/j1939-84#1121]
There are several repeated phrases throughout the entire report log generated by 3.1.0.  Some examples are listed below, but this is not exhaustive.

"Global Global DM22 Request Request"
"Global Global Request for Address Claim Request"
"Destination Specific DS Request for PGN 60928 to Engine #1 (0) for SPNs 2848 Request to Engine #1 (0)"
"Destination Specific DS Request for PGN 64891 to Engine #1 (0) for SPNs  Request to Engine #1 (0)"
"Destination Specific Destination Specific DM22 Request to Engine #1 (0) Request to Engine #1 (0)"

**Comment by ericthomasswenson** [comment]
There is another garbled text observation in #1105

And logging omissions in #1114

**Comment by jacobbosch-cummins** [comment]
Tested with 3.1.2 and this bug was not present.  Seems to be fixed.
