### ISSUE TITLE
Invalid parsing of DM30 for single SPN in Part 1 only

### ISSUE THREAD

**Issue by jacobbosch-cummins** [Equipment-and-Tool-Institute/j1939-84#1122]
This has been noted on all of our test runs with 3.1.0 and it seems to affect all engine model years.  This only occurs during part 1.  The SLOT failure message does not occur in any other instances where DM30 is requested for SPN 3521 after part 1.

### 3.0.13
11:56:03.5845 Sending DM7 for DM30 to Engine #1 (0) for SPN 3521
11:56:03.5875 18E300F9 [8] F7 C1 0D 1F FF FF FF FF (TX)
11:56:03.6015 18A4F900 [12] F7 C1 0D 12 00 01 00 FB FF FF FF FF
DM30 from 0: SPN 3521 FMI 18 (SLOT 256) Result: Test Not Complete.

### 3.1.0
09:55:30.5150 Sending DM7 for DM30 to Engine #1 (0) for SPN 3521
09:55:30.5190 18E300F9 [8] F7 C1 0D 1F FF FF FF FF (TX)
09:55:30.5290 1CA4F900 [12] F7 C1 0D 12 00 01 00 FB FF FF FF FF
DM30 from 0: SPN 3521 FMI 18 (SLOT 256) Result: Test Not Complete.
**FAIL: 6.1.12.2.a (A.7.1.c) - #-3521 SLOT identifier for SP 3521 FMI 18 from Engine #1 (0) is invalid**

**Comment by ericthomasswenson** [comment]
256 SAEpc08 Is in the A-7-3 list.

Yet missing slot message is sent anyway

FAIL: 6.1.12.2.a (A.7.1.c) - #-3521 SLOT identifier for SP 3521 FMI 18 from Engine (0) is invalid.

Remained in 3.1.3.

**Comment by ericthomasswenson** [comment]
Investigation requested 7/8

**Comment by jacobbosch-cummins** [comment]
https://github.com/Equipment-and-Tool-Institute/j1939-84/blob/5949042f5aedf7f509e962e8da559974d231ac6b/src/org/etools/j1939tools/j1939/J1939DaRepository.java#L56

https://github.com/Equipment-and-Tool-Institute/j1939-84/blob/5949042f5aedf7f509e962e8da559974d231ac6b/src/org/etools/j1939tools/j1939/J1939DaRepository.java#L60

https://github.com/Equipment-and-Tool-Institute/j1939-84/blob/3.1.4/src/org/etools/j1939tools/resources/bit-slots.csv

These may be the cause of the issue?  Pulling in bit-slots.csv seems new for the 3.1.X branch and the findSlot method has reordered its logic to check the slots map for a negative SPN first, which is defined in the bit-slots file.

**Comment by ericthomasswenson** [comment]
Jacob, please confirm this as corrected.

**Comment by jacobbosch-cummins** [comment]
This is still present on 3.1.7.

J1939-84 Tool version 3.1.7 - 2022/10/05 21:27
Generated: 2022/10/10 13:44:06.1648

12:37:55.0398 Sending DM7 for DM30 to Engine #1 (0) for SPN 3521
12:37:55.0418 18E300F9 [8] F7 C1 0D 1F FF FF FF FF (TX)
12:37:55.0508 1CA4F900 [12] F7 C1 0D 12 00 01 00 FB FF FF FF FF
DM30 from 0: SPN 3521 FMI 18 (SLOT 256) Result: Test Not Complete.
**FAIL: 6.1.12.2.a (A.7.1.c) - #-3521 SLOT identifier for SP 3521 FMI 18 from Engine #1 (0) is invalid**

**Comment by battjt** [comment]
SPN 3521 has SLOT identifier of 89.  89 is not identified as a valid SLOT in A-7-3.

The error message needs to be cleaned up, but the SLOT is invalid, right?  This is the correct error, right?
```FAIL: 6.1.12.2.a (A.7.1.c) - #89 SLOT identifier for SP 3521 FMI 18 from Engine #1 (0) is invalid```

**Comment by jacobbosch-cummins** [comment]
12:37:55.0508 1CA4F900 [12] F7 C1 0D 12 **_00 01_** 00 FB FF FF FF FF
DM30 from 0: SPN 3521 FMI 18 **_(SLOT 256)_** Result: Test Not Complete.

The SLOT is in bytes 5-6.  It is 256 in this case, which was correctly identified by the tool.  There should be no fail message in this case.

**Comment by battjt** [comment]
I didn't realize that the SLOT was in the response.  We will quit using the SPN to lookup the SLOT in DM30 validation.

**Comment by markmorrisoncummins** [comment]
Looks fixed. From section 6.1.12 in v3.1.10:

> 10:19:35.8039 Sending DM7 for DM30 to Engine #1 (0) for SPN 3521
> 10:19:35.8060 18E300F9 [8] F7 C1 0D 1F FF FF FF FF (TX)
> 10:19:35.8157 1CA4F900 [12] F7 C1 0D 12 00 01 00 FB FF FF FF FF
> DM30 from 0: SPN 3521 FMI 18 (SLOT 256) Result: Test Not Complete.
> 
> 
> 10:19:35.8184 Sending DM7 for DM30 to Engine #1 (0) for SPN 3936
