### ISSUE TITLE
DM58 is only being requested in Part 12

### ISSUE THREAD

**Issue by jacobbosch-cummins** [Equipment-and-Tool-Institute/j1939-84#1123]
The DM7 <-> DM58 exchange is only happening in Part 12 with 3.1.0.  It is our understanding that it should also be happening in Parts 1.12 and 2.10 in addition to the exchange in 12.11.

**Comment by ericthomasswenson** [comment]
Nathan got similar results x 3.  DM 58 was omitted in Parts 1 & 2

**Comment by ericthomasswenson** [comment]
For 3.1.1, Saw DM58 query in Part 1
Anyone have eyes on Part 2 and Part 12

**Comment by ericthomasswenson** [comment]
Observed in Parts 1 and 2
