### ISSUE TITLE
DM12 DTC was not found in DM25 when present.

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1129]
DM12 DTC was not found in DM25 when present.

All related criteria were confirmed to say include, as responses containing multiple FFs are commonly seen on development vehicles.

See #1048 for related complaint.

**Comment by ericthomasswenson** [comment]
14:14:00.9548 Destination Specific DM12 Request to Engine #1 (0)
14:14:00.9578 18EA00F9 [3] D4 FE 00 (TX)
14:14:00.9680 18FED400 [8] 43 FF 41 1A 05 01 FF FF
DM12 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: not supported
**_DTC 6721:5_** - Engine Fuel Injection Pump 2 Fuel Control Valve, Current Below Normal Or Open Circuit - 1 times

14:14:00.9688 Destination Specific DM12 Request to Exhaust Emission Controller (61)
14:14:00.9717 18EA3DF9 [3] D4 FE 00 (TX)
14:14:00.9880 18FED43D [8] 03 FF 00 00 00 00 FF FF
DM12 from Exhaust Emission Controller (61): MIL: off, RSL: off, AWL: off, PL: not supported, No DTCs

Start Test 4.10 - DM25: Expanded freeze frame

14:14:06.6898 Destination Specific DM25 Request to Engine #1 (0)
14:14:06.6930 18EA00F9 [3] B7 FD 00 (TX)
14:14:10.2147 18FDB700 [484] 78 1F 00 61 02 FA 00 00 00 17 54 01 68 0E 53 CB FF 19 26 10 01 26 24 5D 26 3B 00 C0 12 C2 12 7D 88 FF 40 38 F0 19 20 1C C0 2B 40 1F A9 D3 D2 DE E1 69 0A 4C 0B 0C 4F 04 25 00 C4 62 F7 62 CA 62 D9 62 D6 62 E5 62 61 62 F0 00 00 13 3B C6 3C 00 00 60 2B F6 28 03 00 03 00 40 9C 33 07 00 00 00 00 01 00 00 F6 2C E0 27 DF 02 86 27 01 00 FF FF 78 00 74 00 04 56 04 64 04 78 FF FF F0 7F FA 00 00 00 12 52 01 3A 11 45 CB FF 4C 28 05 01 26 24 63 26 34 00 C0 12 BA 12 7D 85 FF 40 38 F0 19 20 1C C0 2B DB 2B A9 D3 D2 DE E1 69 0A 74 0B 0C 4F 04 25 00 1D 64 D5 63 E4 63 F9 63 20 64 EA 63 DC 62 F0 00 00 E9 32 96 31 00 00 A0 2B AA 29 03 00 0D 00 40 9C 34 07 00 00 00 00 01 00 00 2A 2D E0 27 EF 02 10 28 01 00 2B 15 78 00 7C 00 04 5D 04 67 04 78 41 1A 05 01 FA 00 00 00 00 01 00 5C 03 5C CB FF 66 2A 0A 01 9D 28 56 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C 00 00 40 1F A9 D3 D2 DE 7D 69 0A 3C 0B 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AB 63 F0 00 00 36 29 FF FF 40 9C 40 2B A0 28 00 00 00 00 40 9C 33 00 00 00 00 00 01 02 00 D6 2C E0 27 2A 03 00 10 00 FA FF FF D0 07 00 00 04 1D 04 2B 04 78 FF FF F1 7F FA 00 00 00 11 53 01 15 11 48 CB FF 19 28 04 01 26 24 60 26 31 00 C0 12 C1 12 7D 85 FF 40 38 F0 19 20 1C C0 2B CB 28 A9 D3 D2 DE E1 69 0A 68 0B 0C 4F 04 25 00 38 64 E4 63 D5 63 02 64 05 64 ED 63 03 63 F0 00 00 C0 32 89 31 00 00 96 2B 8A 29 03 00 0A 00 40 9C 34 06 00 00 00 00 01 00 00 2A 2D E0 27 F9 02 0A 28 01 00 52 16 78 00 70 00 04 58 04 67 04
DM25 from Engine #1 (0): 
Freeze Frames: [
  Freeze Frame: {
    DTC 196639:1 - Unknown, Data Valid But Below Normal Operational Range - Most Severe Level - 2 times
    SPN Data: FA 00 00 00 17 54 01 68 0E 53 CB FF 19 26 10 01 26 24 5D 26 3B 00 C0 12 C2 12 7D 88 FF 40 38 F0 19 20 1C C0 2B 40 1F A9 D3 D2 DE E1 69 0A 4C 0B 0C 4F 04 25 00 C4 62 F7 62 CA 62 D9 62 D6 62 E5 62 61 62 F0 00 00 13 3B C6 3C 00 00 60 2B F6 28 03 00 03 00 40 9C 33 07 00 00 00 00 01 00 00 F6 2C E0 27 DF 02 86 27 01 00 FF FF 78 00 74 00 04 56 04 64 04
  }
  Freeze Frame: {
    DTC 524287:16 - Manufacturer Assignable SPN (last entry), Data Valid But Above Normal Operating Range - Moderately Severe Level
    SPN Data: FA 00 00 00 12 52 01 3A 11 45 CB FF 4C 28 05 01 26 24 63 26 34 00 C0 12 BA 12 7D 85 FF 40 38 F0 19 20 1C C0 2B DB 2B A9 D3 D2 DE E1 69 0A 74 0B 0C 4F 04 25 00 1D 64 D5 63 E4 63 F9 63 20 64 EA 63 DC 62 F0 00 00 E9 32 96 31 00 00 A0 2B AA 29 03 00 0D 00 40 9C 34 07 00 00 00 00 01 00 00 2A 2D E0 27 EF 02 10 28 01 00 2B 15 78 00 7C 00 04 5D 04 67 04
  }
  Freeze Frame: {
    **_DTC 6721:5_** - Engine Fuel Injection Pump 2 Fuel Control Valve, Current Below Normal Or Open Circuit - 1 times
    SPN Data: FA 00 00 00 00 01 00 5C 03 5C CB FF 66 2A 0A 01 9D 28 56 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C 00 00 40 1F A9 D3 D2 DE 7D 69 0A 3C 0B 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AB 63 F0 00 00 36 29 FF FF 40 9C 40 2B A0 28 00 00 00 00 40 9C 33 00 00 00 00 00 01 02 00 D6 2C E0 27 2A 03 00 10 00 FA FF FF D0 07 00 00 04 1D 04 2B 04
  }
  Freeze Frame: {
    DTC 524287:17 - Manufacturer Assignable SPN (last entry), Data Valid But Below Normal Operating Range - Least Severe Level
    SPN Data: FA 00 00 00 11 53 01 15 11 48 CB FF 19 28 04 01 26 24 60 26 31 00 C0 12 C1 12 7D 85 FF 40 38 F0 19 20 1C C0 2B CB 28 A9 D3 D2 DE E1 69 0A 68 0B 0C 4F 04 25 00 38 64 E4 63 D5 63 02 64 05 64 ED 63 03 63 F0 00 00 C0 32 89 31 00 00 96 2B 8A 29 03 00 0A 00 40 9C 34 06 00 00 00 00 01 00 00 2A 2D E0 27 F9 02 0A 28 01 00 52 16 78 00 70 00 04 58 04 67 04
  }
]


14:14:10.2172 Destination Specific DM25 Request to Exhaust Emission Controller (61)
14:14:10.2198 18EA3DF9 [3] B7 FD 00 (TX)
14:14:10.2384 1CE8FF3D [8] 01 FF FF FF F9 B7 FD 00
Acknowledgment from Exhaust Emission Controller (61): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64951
**_FAIL: 6.4.10.2.b - Engine #1 (0) did not report DTC in freeze frame data which included the DTC reported in DM12 earlier in this part_**

**Comment by ericthomasswenson** [comment]
Also observed in 6.8.10

Start Test 8.10 - DM25: Expanded freeze frame

14:18:38.4507 Destination Specific DM25 Request to Engine #1 (0)
14:18:38.4530 18EA00F9 [3] B7 FD 00 (TX)
14:18:42.8262 18FDB700 [605] 78 1F 00 61 05 FA 00 00 00 15 53 00 7A 0D 42 CB FF 19 27 19 01 26 24 8A 26 3F 00 C0 12 C6 12 7D 86 FF 40 38 F0 19 20 1C C0 2B 40 1F A9 D3 D2 DE E1 69 0A 80 0F 0C 4F 04 25 00 F0 63 78 63 93 63 87 63 E1 63 99 63 A0 62 F0 00 00 C3 35 36 36 00 00 60 2B B6 28 03 00 03 00 40 9C 33 09 00 00 00 00 01 00 00 20 2B 90 27 DF 02 56 27 01 00 FF FF C8 00 94 00 04 56 04 62 04 78 FF FF F0 7F FA 00 00 00 17 53 02 CB 11 3D CB FF E6 27 1A 01 26 24 96 26 3E 00 C0 12 A6 12 7D 87 FF 40 38 F0 19 20 1C C0 2B D9 24 A9 D3 D2 DE E1 69 0A 00 10 0C 4F 04 25 00 A5 63 66 63 8A 63 78 63 B1 63 87 63 82 62 F0 00 00 13 35 8C 33 00 00 80 2B E0 29 03 00 08 00 40 9C 34 07 00 00 00 00 01 00 00 80 2C A0 27 DF 02 0D 28 01 00 FF FF C8 00 88 00 04 5F 04 67 04 78 41 1A 05 01 FA 00 00 00 00 01 00 5C 03 5C CB FF 66 2A 0A 01 9D 28 56 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C 00 00 40 1F A9 D3 D2 DE 7D 69 0A 3C 0B 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AB 63 F0 00 00 36 29 FF FF 40 9C 40 2B A0 28 00 00 00 00 40 9C 33 00 00 00 00 00 01 02 00 D6 2C E0 27 2A 03 00 10 00 FA FF FF D0 07 00 00 04 1D 04 2B 04 78 FF FF F1 7F FA 00 00 00 00 52 00 BB 01 43 CB FF 19 28 FE 00 26 24 9D 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C C0 2B 40 1F A9 D3 D2 DE E1 69 0A 7C 0E 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 B1 63 F0 00 00 E9 25 F3 25 00 00 60 2B CA 28 00 00 00 00 40 9C 32 01 00 00 00 00 01 00 00 56 2B A0 27 2B 03 80 3E 00 00 00 00 C8 00 00 00 04 24 04 32 04 78 34 04 05 01 FA 00 00 00 00 01 00 00 00 45 CB FF 80 28 FE 00 B3 25 80 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C 00 00 40 1F A9 D3 D2 DE 7D 69 0A 70 0F 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 B1 63 F0 00 00 23 26 FF FF 40 9C FF FF FF FF 00 00 00 00 40 9C 33 01 00 00 00 00 01 00 00 FF FF 60 27 2A 03 00 0E 00 00 FF FF 40 01 00 00 04 22 04 2B 04
DM25 from Engine #1 (0): 
Freeze Frames: [
  Freeze Frame: {
…
  }
  Freeze Frame: {
    DTC 1076:5 - Engine Fuel Injection Pump 1 Fuel Control Valve, Current Below Normal Or Open Circuit - 1 times
    SPN Data: FA 00 00 00 00 01 00 00 00 45 CB FF 80 28 FE 00 B3 25 80 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C 00 00 40 1F A9 D3 D2 DE 7D 69 0A 70 0F 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 B1 63 F0 00 00 23 26 FF FF 40 9C FF FF FF FF 00 00 00 00 40 9C 33 01 00 00 00 00 01 00 00 FF FF 60 27 2A 03 00 0E 00 00 FF FF 40 01 00 00 04 22 04 2B 04
  }
]


14:18:42.8333 Destination Specific DM25 Request to Exhaust Emission Controller (61)
14:18:42.8376 18EA3DF9 [3] B7 FD 00 (TX)
14:18:42.8501 1CE8FF3D [8] 01 FF FF FF F9 B7 FD 00
Acknowledgment from Exhaust Emission Controller (61): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64951
FAIL: 6.8.10.2.a - DTC(s) reported in the freeze frame by Engine #1 (0) did not include either the DTC reported in DM12 or DM23 earlier in this part

**Comment by ericthomasswenson** [comment]
DTC 1076 FMI 5 was deleted for 6.9.8.6

14:21:10.5884 18EA00F9 [3] B7 FD 00 (TX)
14:21:14.9588 18FDB700 [605] 78 1F 00 61 06 FA 00 00 00 00 53 00 05 00 49 CB FF CC 2B FE 00 23 24 AD 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C C0 2B 40 1F A9 D3 D2 DE E1 69 0A 28 12 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AE 63 F0 00 00 A9 26 A0 26 00 00 6A 2B 4A 28 00 00 00 00 40 9C 33 00 00 00 00 00 01 00 00 A0 2A 50 27 2B 03 70 3E 00 00 00 00 C8 00 00 00 04 1F 04 2E 04 78 FF FF F0 7F FA 00 00 00 00 53 00 00 00 48 CB FF 00 2C FC 00 23 24 B3 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C C0 2B 40 1F A9 D3 D2 DE E1 69 0A 84 12 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AE 63 F0 00 00 86 26 90 26 00 00 60 2B 20 28 00 00 00 00 40 9C 32 01 00 00 00 00 01 00 00 56 2A 40 27 2A 03 80 3E 00 00 00 00 C8 00 00 00 04 1B 04 29 04 78 41 1A 05 01 FA 00 00 00 00 01 00 5C 03 5C CB FF 66 2A 0A 01 9D 28 56 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C 00 00 40 1F A9 D3 D2 DE 7D 69 0A 3C 0B 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AB 63 F0 00 00 36 29 FF FF 40 9C 40 2B A0 28 00 00 00 00 40 9C 33 00 00 00 00 00 01 02 00 D6 2C E0 27 2A 03 00 10 00 FA FF FF D0 07 00 00 04 1D 04 2B 04 78 FF FF F1 7F FA 00 00 00 00 52 00 00 00 49 CB FF CC 2B FC 00 23 24 B0 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C C0 2B 40 1F A9 D3 D2 DE E1 69 0A 44 12 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AE 63 F0 00 00 7C 26 CC 26 00 00 6A 2B 40 28 00 00 00 00 40 9C 33 01 00 00 00 00 01 00 00 8A 2A 50 27 2A 03 80 3E 00 00 00 00 C8 00 00 00 04 1B 04 26 04 78 34 04 05 01 FA 00 00 00 00 01 00 00 00 45 CB FF 80 28 FE 00 B3 25 80 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C 00 00 40 1F A9 D3 D2 DE 7D 69 0A 70 0F 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 B1 63 F0 00 00 23 26 FF FF 40 9C FF FF FF FF 00 00 00 00 40 9C 33 01 00 00 00 00 01 00 00 FF FF 60 27 2A 03 00 0E 00 00 FF FF 40 01 00 00 04 22 04 2B 04
DM25 from Engine #1 (0): 
Freeze Frames: [
  Freeze Frame: {
    DTC 196639:1 - Unknown, Data Valid But Below Normal Operational Range - Most Severe Level - 6 times
    SPN Data: FA 00 00 00 00 53 00 05 00 49 CB FF CC 2B FE 00 23 24 AD 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C C0 2B 40 1F A9 D3 D2 DE E1 69 0A 28 12 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AE 63 F0 00 00 A9 26 A0 26 00 00 6A 2B 4A 28 00 00 00 00 40 9C 33 00 00 00 00 00 01 00 00 A0 2A 50 27 2B 03 70 3E 00 00 00 00 C8 00 00 00 04 1F 04 2E 04
  }
  Freeze Frame: {
    DTC 524287:16 - Manufacturer Assignable SPN (last entry), Data Valid But Above Normal Operating Range - Moderately Severe Level
    SPN Data: FA 00 00 00 00 53 00 00 00 48 CB FF 00 2C FC 00 23 24 B3 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C C0 2B 40 1F A9 D3 D2 DE E1 69 0A 84 12 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AE 63 F0 00 00 86 26 90 26 00 00 60 2B 20 28 00 00 00 00 40 9C 32 01 00 00 00 00 01 00 00 56 2A 40 27 2A 03 80 3E 00 00 00 00 C8 00 00 00 04 1B 04 29 04
  }
  Freeze Frame: {
    DTC 6721:5 - Engine Fuel Injection Pump 2 Fuel Control Valve, Current Below Normal Or Open Circuit - 1 times
    SPN Data: FA 00 00 00 00 01 00 5C 03 5C CB FF 66 2A 0A 01 9D 28 56 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C 00 00 40 1F A9 D3 D2 DE 7D 69 0A 3C 0B 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AB 63 F0 00 00 36 29 FF FF 40 9C 40 2B A0 28 00 00 00 00 40 9C 33 00 00 00 00 00 01 02 00 D6 2C E0 27 2A 03 00 10 00 FA FF FF D0 07 00 00 04 1D 04 2B 04
  }
  Freeze Frame: {
    DTC 524287:17 - Manufacturer Assignable SPN (last entry), Data Valid But Below Normal Operating Range - Least Severe Level
    SPN Data: FA 00 00 00 00 52 00 00 00 49 CB FF CC 2B FC 00 23 24 B0 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C C0 2B 40 1F A9 D3 D2 DE E1 69 0A 44 12 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AE 63 F0 00 00 7C 26 CC 26 00 00 6A 2B 40 28 00 00 00 00 40 9C 33 01 00 00 00 00 01 00 00 8A 2A 50 27 2A 03 80 3E 00 00 00 00 C8 00 00 00 04 1B 04 26 04
  }
  Freeze Frame: {
    _DTC 1076:5_ - Engine Fuel Injection Pump 1 Fuel Control Valve, Current Below Normal Or Open Circuit - 1 times
    SPN Data: FA 00 00 00 00 01 00 00 00 45 CB FF 80 28 FE 00 B3 25 80 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C 00 00 40 1F A9 D3 D2 DE 7D 69 0A 70 0F 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 B1 63 F0 00 00 23 26 FF FF 40 9C FF FF FF FF 00 00 00 00 40 9C 33 01 00 00 00 00 01 00 00 FF FF 60 27 2A 03 00 0E 00 00 FF FF 40 01 00 00 04 22 04 2B 04
  }
]

14:21:21.3236 Destination Specific DM25 Request to Engine #1 (0)
14:21:21.3256 18EA00F9 [3] B7 FD 00 (TX)
14:21:23.9490 18FDB700 [363] 78 1F 00 61 06 FA 00 00 00 00 53 00 05 00 49 CB FF CC 2B FE 00 23 24 AD 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C C0 2B 40 1F A9 D3 D2 DE E1 69 0A 28 12 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AE 63 F0 00 00 A9 26 A0 26 00 00 6A 2B 4A 28 00 00 00 00 40 9C 33 00 00 00 00 00 01 00 00 A0 2A 50 27 2B 03 70 3E 00 00 00 00 C8 00 00 00 04 1F 04 2E 04 78 FF FF F0 7F FA 00 00 00 00 01 00 00 00 48 CB FF 00 2C FB 00 23 24 B3 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C C0 2B 40 1F A9 D3 D2 DE E1 69 0A B0 12 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AE 63 F0 00 00 93 26 80 26 00 00 60 2B 16 28 00 00 00 00 40 9C 33 00 00 00 00 00 01 00 00 36 2A 40 27 2B 03 80 3E 00 00 0A 00 C8 00 00 00 04 22 04 26 04 78 FF FF F1 7F FA 00 00 00 00 52 00 00 00 49 CB FF CC 2B FC 00 23 24 B0 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C C0 2B 40 1F A9 D3 D2 DE E1 69 0A 44 12 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AE 63 F0 00 00 7C 26 CC 26 00 00 6A 2B 40 28 00 00 00 00 40 9C 33 01 00 00 00 00 01 00 00 8A 2A 50 27 2A 03 80 3E 00 00 00 00 C8 00 00 00 04 1B 04 26 04
DM25 from Engine #1 (0): 
Freeze Frames: [
  Freeze Frame: {
    DTC 196639:1 - Unknown, Data Valid But Below Normal Operational Range - Most Severe Level - 6 times
    SPN Data: FA 00 00 00 00 53 00 05 00 49 CB FF CC 2B FE 00 23 24 AD 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C C0 2B 40 1F A9 D3 D2 DE E1 69 0A 28 12 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AE 63 F0 00 00 A9 26 A0 26 00 00 6A 2B 4A 28 00 00 00 00 40 9C 33 00 00 00 00 00 01 00 00 A0 2A 50 27 2B 03 70 3E 00 00 00 00 C8 00 00 00 04 1F 04 2E 04
  }
  Freeze Frame: {
    DTC 524287:16 - Manufacturer Assignable SPN (last entry), Data Valid But Above Normal Operating Range - Moderately Severe Level
    SPN Data: FA 00 00 00 00 01 00 00 00 48 CB FF 00 2C FB 00 23 24 B3 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C C0 2B 40 1F A9 D3 D2 DE E1 69 0A B0 12 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AE 63 F0 00 00 93 26 80 26 00 00 60 2B 16 28 00 00 00 00 40 9C 33 00 00 00 00 00 01 00 00 36 2A 40 27 2B 03 80 3E 00 00 0A 00 C8 00 00 00 04 22 04 26 04
  }
  Freeze Frame: {
    DTC 524287:17 - Manufacturer Assignable SPN (last entry), Data Valid But Below Normal Operating Range - Least Severe Level
    SPN Data: FA 00 00 00 00 52 00 00 00 49 CB FF CC 2B FC 00 23 24 B0 26 00 00 C0 12 00 00 7D 7D FF 40 38 F0 19 20 1C C0 2B 40 1F A9 D3 D2 DE E1 69 0A 44 12 0C 4F 04 25 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AE 63 F0 00 00 7C 26 CC 26 00 00 6A 2B 40 28 00 00 00 00 40 9C 33 01 00 00 00 00 01 00 00 8A 2A 50 27 2A 03 80 3E 00 00 00 00 C8 00 00 00 04 1B 04 26 04
  }
]

FAIL: 6.9.8.6.c - Engine #1 (0) did not erase DM25 data

**Comment by ericthomasswenson** [comment]
Confirm in 3.1.3, then request for task 5 7/8

**Comment by ericthomasswenson** [comment]
Confirmed in 3.1.4

**Comment by ericthomasswenson** [comment]
Start Test 8.10 - DM25: Expanded freeze frame
08:33:22.0897 Destination Specific DM25 Request to Engine #1 (0)
08:33:22.0937 18EA00F9 [3] B7 FD 00 (TX)
08:33:22.9684 1CFDB700 [268] 85 … 07 17
DM25 from Engine #1 (0): 
Freeze Frames: [
  Freeze Frame: {
    DTC 175:3 - Engine Oil Temperature 1, Voltage Above Normal, Or Shorted To High Source - 1 times
    SPN Data: 00 7D 7D A3 0A C8 CC B1 DF E1 69 20 1D 00 00 00 00 00 00 C7 ED 00 26 03 00 01 00 64 00 64 00 64 00 64 00 64 00 64 49 58 31 00 00 13 25 00 00 00 00 1F 00 00 00 00 00 8A 00 FF 63 7C 31 00 00 23 31 00 00 00 00 37 30 00 00 00 17 26 00 47 00 FB FF FF 00 FB 00 CE 07 00 00 9A 27 F0 25 3B 0B 97 03 01 00 03 02 0F C5 74 03 00 62 1E 0D 57 [08 25 00 00 00 7F 42 11 7A 3E 2F 56 2D 20 30 04 FA 40 9C
  }
  Freeze Frame: {
    DTC 4227:1 - Engine Crankcase Breather Oil Separator, Data Valid But Below Normal Operational Range - Most Severe Level - 1 times
    SPN Data: 06 83 83 A3 0A A6 CC B1 DF E1 6A 2F 2A 28 24 11 00 00 00 C7 06 01 C2 [02 00 01 70 60 70 60 70 60 70 60 70 60 70 60 3F 4E 29 F9 1A EF 24 00 00 00 00 1F 26 2D 68 00 00 B2 70 D6 70 23 32 09 00 30 32 00 00 46 01 78 37 A3 A4 00 07 26 01 47 00 FB FF FF 00 FB 71 CC 07 00 00 A5 27 E7 25 48 11 D4 0C 01 00 03 02 01 C5 74 03 00 C2 0C 0D 57 08 25 00 00 00 7E 3F 11 7A A9 31 23 31 46 34 04 24 07 17
  }
]

FAIL: 6.8.10.2.a - DTC(s) reported in the freeze frame by Engine #1 (0) did not include either the DTC reported in DM12 or DM23 earlier in this part
// Prior Global DM23 timed out in this case. This outcome is fair for DM33, 
// as the standard was not received. 
// The standard was received for DM12, and this could have passed based on the DM12 standard.

End Test 8.10 - DM25: Expanded freeze frame

**Comment by ericthomasswenson** [comment]
Affirmed Text: **_All instances say include … for DM25 responses with more than one FF recorded, any of the recorded FFs may contain the referenced DTC, and shall pass._**

6.4.10.2	Fail Criteria
a.	Fail if no ECU reports freeze frame data.
b.	Fail if DTC in freeze frame data **_does not include the DTC reported in DM12_** earlier in this part.
c.	Fail if NACK not received from OBD ECUs that did not provide DM25 response.
// No change 

6.7.12.2	Fail Criteria
a.	Fail if no ECU reports Freeze Frame data.
b.	Fail if DTC in reported Freeze Frame data **_does not include the DTC provided by DM23_** earlier in this part.
c.	Fail if NACK not received from OBD ECUs that did not provide DM25 message.
// No change 

6.8.10.2	Fail Criteria
a.	Fail if DTC(s) reported in the freeze frame **_does not include either the DTC reported in DM12 or the DTC reported in DM23_** earlier in this part.
b.	Fail if no OBD ECU provides freeze frame data (i.e. an empty freeze frame is provided by all OBD modules). 
c.	Fail if NACK is not received from OBD ECUs that did not provide an DM25 message.  
// No Change

**Comment by battjt** [comment]
Does 6.8.10.2.a mean that the FF should include "all of the DTCs of the previous DM12 and DM23" or "only the DM12 or the DM23 but not both"?
