### ISSUE TITLE
SPN 4384 FMI 18 reported as erased when it never ran

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1130]
SPN 4384 FMI 18 test results reported as erased, when it never ran

14:10:55.4097 Sending DM7 for DM30 to Exhaust Emission Controller (61) for SPN 4384
14:10:55.4133 18E33DF9 [8] F7 20 11 1F FF FF FF FF (TX)
14:10:55.4459 18A4F93D [12] F7 20 11 12 83 01 00 FB FF FF FF FF
DM30 from 61: SPN 4384 FMI 18 (SLOT 387) Result: Test Not Complete.
WARN: 6.2.10.3.a - All test results from Exhaust Emission Controller (61) are still initialized

14:17:13.3062 Sending DM7 for DM30 to Exhaust Emission Controller (61) for SPN 4384
14:17:13.3094 18E33DF9 [8] F7 20 11 1F FF FF FF FF (TX)
14:17:13.3534 18A4F93D [12] F7 20 11 12 83 01 00 FB FF FF FF FF
DM30 from 61: SPN 4384 FMI 18 (SLOT 387) Result: Test Not Complete.

End Test 7.15 - DM7/DM30: Command non-continuously monitored test/scaled test results

14:17:23.4067 Sending DM7 for DM30 to Exhaust Emission Controller (61) for SPN 4384
14:17:23.4102 18E33DF9 [8] F7 20 11 1F FF FF FF FF (TX)
14:17:23.4538 18A4F93D [12] F7 20 11 12 83 01 00 FB FF FF FF FF
DM30 from 61: SPN 4384 FMI 18 (SLOT 387) Result: Test Not Complete.
FAIL: 6.7.16.2.a - Exhaust Emission Controller (61) erased Test Results data

**Comment by ericthomasswenson** [comment]
See #1088 for a related complaint.

**Comment by ericthomasswenson** [comment]
Also observed in 6.8.12 and 6.8.13

14:18:51.8939 Sending DM7 for DM30 to Exhaust Emission Controller (61) for SPN 4384
14:18:51.8971 18E33DF9 [8] F7 20 11 1F FF FF FF FF (TX)
14:18:51.9412 18A4F93D [12] F7 20 11 12 83 01 00 FB FF FF FF FF
DM30 from 61: SPN 4384 FMI 18 (SLOT 387) Result: Test Not Complete.
FAIL: 6.8.12.10.d - Exhaust Emission Controller (61) erased Test Results data

End Test 8.12 - DM22: Individual clear/reset of active and previously active DTC

14:19:13.2548 Sending DM7 for DM30 to Exhaust Emission Controller (61) for SPN 4384
14:19:13.2567 18E33DF9 [8] F7 20 11 1F FF FF FF FF (TX)
14:19:13.2915 18A4F93D [12] F7 20 11 12 83 01 00 FB FF FF FF FF
DM30 from 61: SPN 4384 FMI 18 (SLOT 387) Result: Test Not Complete.
FAIL: 6.8.13.4.a - Exhaust Emission Controller (61) erased Test Results data

**Comment by ericthomasswenson** [comment]
And in 6.9.3.10

14:20:52.5761 Sending DM7 for DM30 to Exhaust Emission Controller (61) for SPN 4384
14:20:52.5782 18E33DF9 [8] F7 20 11 1F FF FF FF FF (TX)
14:20:52.6241 18A4F93D [12] F7 20 11 12 83 01 00 FB FF FF FF FF
DM30 from 61: SPN 4384 FMI 18 (SLOT 387) Result: Test Not Complete.
FAIL: 6.9.3.10.d - Exhaust Emission Controller (61) erased Test Results data

**Comment by ericthomasswenson** [comment]
And in 6.9.8.2, 6..9.8.4, 6.9.8.6

14:21:05.0270 Sending DM7 for DM30 to Exhaust Emission Controller (61) for SPN 4384
14:21:05.0286 18E33DF9 [8] F7 20 11 1F FF FF FF FF (TX)
14:21:05.0725 18A4F93D [12] F7 20 11 12 83 01 00 FB FF FF FF FF
DM30 from 61: SPN 4384 FMI 18 (SLOT 387) Result: Test Not Complete.
FAIL: 6.9.8.2.a - Exhaust Emission Controller (61) erased Test Results data
FAIL: 6.9.8.2.a - Exhaust Emission Controller (61) partially erased diagnostic information
FAIL: 6.9.8.2.b - One or more than one ECU erased diagnostic information and one or more other ECUs did not erase diagnostic information

14:21:15.6164 Sending DM7 for DM30 to Exhaust Emission Controller (61) for SPN 4384
14:21:15.6188 18E33DF9 [8] F7 20 11 1F FF FF FF FF (TX)
14:21:15.6636 18A4F93D [12] F7 20 11 12 83 01 00 FB FF FF FF FF
DM30 from 61: SPN 4384 FMI 18 (SLOT 387) Result: Test Not Complete.
FAIL: 6.9.8.4.a - Exhaust Emission Controller (61) erased Test Results data
FAIL: 6.9.8.4.a - Exhaust Emission Controller (61) partially erased diagnostic information
FAIL: 6.9.8.4.b - One or more than one ECU erased diagnostic information and one or more other ECUs did not erase diagnostic information

14:21:25.3829 Sending DM7 for DM30 to Engine #1 (0) for SPN 6772
14:21:25.3852 18E300F9 [8] F7 74 1A 1F FF FF FF FF (TX)
14:21:25.4198 18A4F900 [12] F7 74 1A 0C 0C 00 00 00 00 00 FF FF
DM30 from 0: SPN 6772 FMI 12 (SLOT 12) Result: Test Passed. Min: N/A, Value: 0, Max: 0 count
FAIL: 6.9.8.6.c - Engine #1 (0) did not erase Test Results data

**Comment by ericthomasswenson** [comment]
And 6.12.9.2 and 6.12.9.4

DM30 from 61: SPN 4384 FMI 18 (SLOT 387) Result: Test Not Complete.
FAIL: 6.12.9.2.b - Exhaust Emission Controller (61) erased Test Results data
FAIL: 6.12.9.2.b - Exhaust Emission Controller (61) partially erased diagnostic information
FAIL: 6.12.9.2.c - One or more than one ECU erased diagnostic information and one or more other ECUs did not erase diagnostic information

14:42:05.2724 Sending DM7 for DM30 to Exhaust Emission Controller (61) for SPN 4384
14:42:05.2748 18E33DF9 [8] F7 20 11 1F FF FF FF FF (TX)
14:42:05.3191 18A4F93D [12] F7 20 11 12 83 01 00 FB FF FF FF FF
DM30 from 61: SPN 4384 FMI 18 (SLOT 387) Result: Test Not Complete.
FAIL: 6.12.9.4.d - One or more than one ECU erased diagnostic information and one or more other ECUs did not erase diagnostic information

**Comment by ericthomasswenson** [comment]
SP Not supported in the engine tested.

**Comment by battjt** [comment]
From A.5:
```
It also includes information that shall be initialized/reset to provide indication of the recent code clear event including:
...
   c.	Test results (and limits) initialized to indicate that monitors have not run.
```
This monitor indicates that it has not run, so it is a failure.

**Comment by ericthomasswenson** [comment]
Document draft created and emailed for review

**Comment by battjt** [comment]
New:
6.7.15.1.c collect list of initialized test results as a globally scoped list
6.7.16.2.a added.
6.7.17.2 clarification should not change code
6.8.11.1.c collect list of initialized test results overwrite 6.7.15.1.c list
6.8.13.2.c excludes 6.8.11.1.c
6.8.13.4.a excludes 6.8.11.1.c
6.9.3.10.d excludes 6.8.11.1.c
6.9.6.1.a relates to 6.8.11.1.b
6.9.8.2.a, and now b, excludes 6.8.11.1.c
6.9.8.4.b, and now c, excludes 6.8.11.1.c *artifact update expected*
6.9.8.6.c excludes 6.8.11.1.c *artifact update expected*
A.5 6.a uses global list initially created in 6.7.15.1.c

Added 6.8.12.10.d
Added 6.9.8.6 for #1039 
Added 6.9.10.2.a for #1039 
Added 6.12.10.2.b & c for #1039
Added 6.12.10.4 for #1039

**Comment by ericthomasswenson** [comment]
Implement sequentially with #1039

**Comment by ericthomasswenson** [comment]
Proposal Examples.

6.8.11.1 Actions 
a. Iterate DS DM7 with TID 247 +SPN + FMI 31 to OBD ECUs for each SP in the OBD ECU DM24 response that supports test results. 
b. Create a list of uninitialized test results by ECU address, SPN and FMI for each ECU with uninitialized test results.62 
c. **_Create a list of initialized test results by ECU address, SPN and FMI for each ECU with initialized test results._**              // proposal for #1130 

6.9.3.10 Fail Criteria4 
a. Fail if any ECU provides CLR_PA_ACK or CLR_ACT_ACK.  
b. Fail if any ECU provides J1939-21 ACK for PG 49920. 
c. Fail if any ECU provides CLR_ACT_NACK or CLR_PA_NACK with an acknowledgement code greater than > 0.  
d. Fail if any OBD ECU erases any diagnostic information, **_excusing the initialized test results collected by 6.8.11.1.c._** See Section A.5 for more information.68     // Proposal for #1130 

6. Test results a. DM7/DM30 Test Results shall report all test results with initialized results and limits (all 00h or FB00h for results and FFFFh for limits). _Test results recorded as complete in 6.1.12.1.c are excused here, as they are presumed to complete under KOEO conditions, and create a false failure here._ // proposal for #1039  

**_Note that tests not enabled by SAE J1939-84 test conditions will never be reported as complete. Tests that include vehicle speed enabling criteria will never run for a stationary tests. Certain cold start diagnostics will not be enabled under laboratory conditions, either. Accordingly, provisions shall be made to identify tests that are not complete before false deletion commands like DM22, DM3, and directly addressed DM11 are presented to the vehicle under test. This list of tests shall be excused for being detected as erased, because they did not run to completion before the stimulus was sent._** // Proposal for #1130.

**Comment by ericthomasswenson** [comment]
See footnotes in artifact that direct the number of initialized tests to be counted ... and the counts compared to assess initialized tests as deleted.

**Comment by ericthomasswenson** [comment]
From 3.1.20

07:24:01.1966 Sending DM7 for DM30 to Engine #1 (0) for SPN 5835
07:24:01.1994 18E300F9 [8] F7 CB 16 1F FF FF FF FF (TX)
07:24:01.2253 1CA4F900 [24] F7 CB 16 14 93 01 00 FB FF FF FF FF F7 CB 16 07 77 01 00 FB FF FF FF FF
DM30 from Engine #1 (0): [
  SPN 5835 FMI 7 (SLOT 375) Result: Test Not Complete.
  SPN 5835 FMI 20 (SLOT 403) Result: Test Not Complete.
]
// Prior to the planned improvements for tests that don’t run (displayed as FB00 FFFF FFFFh). 
// The test results above may be interpreted as candidates for False Positive outcomes
// Yet there is no complaint for SA-0.
