### ISSUE TITLE
SA 61 Doesn’t support a freeze frame, yet appears to fail for not providing one.

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1131]
SA 61 Doesn’t support a freeze frame, yet appears to fail for not providing one.

14:08:45.1297 Destination Specific DM24 Request to Exhaust Emission Controller (61)
14:08:45.1333 18EA3DF9 [3] B6 FD 00 (TX)
14:08:45.1609 18FDB63D [8] 20 11 1B 00 EB 10 1B 00
DM24 from Exhaust Emission Controller (61): [
…
      T 0  SPN 4331 - AFT 1 DEF Actual Dosing Quantity
      T 0  SPN 4384 - AFT 2 DEF Actual Dosing Quantity
]

Query for FF not observed in Part 1 or 2, but is observed in Part 3.

14:13:02.7347 Destination Specific DM25 Request to Exhaust Emission Controller (61)
14:13:02.7391 18EA3DF9 [3] B7 FD 00 (TX)
14:13:02.7523 1CE8FF3D [8] 01 FF FF FF F9 B7 FD 00
Acknowledgment from Exhaust Emission Controller (61): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64951

14:18:42.8333 Destination Specific DM25 Request to Exhaust Emission Controller (61)
14:18:42.8376 18EA3DF9 [3] B7 FD 00 (TX)
14:18:42.8501 1CE8FF3D [8] 01 FF FF FF F9 B7 FD 00
Acknowledgment from Exhaust Emission Controller (61): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64951
FAIL: 6.8.10.2.a - DTC(s) reported in the freeze frame by Engine #1 (0) did not include either the DTC reported in DM12 or DM23 earlier in this part

14:21:32.5302 Destination Specific DM25 Request to Exhaust Emission Controller (61)
14:21:32.5339 18EA3DF9 [3] B7 FD 00 (TX)
14:21:32.5531 1CE8FF3D [8] 01 FF FF FF F9 B7 FD 00
Acknowledgment from Exhaust Emission Controller (61): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64951
FAIL: 6.9.17.2.a - Engine #1 (0) reported other than no Freeze Frame data stored

**Comment by ericthomasswenson** [comment]
6.1.24 DM25: Expanded Freeze Frame 
6.1.24.1 Actions 
a. DS DM25 [(send Request (PG 59904) for PG 64951 (SPNS 3300, 1214-1215)]) to each OBD ECU that responded to DS DM24 with supported freeze frame SPNSPs.  
6.1.24.2 Fail Criteria 
a. Fail if any OBD ECU provides freeze frame data other than no freeze frame data stored ([i.e., bytes 1-5 = 0x00h and bytes 6-8 = 0xFFh)]. 

6.3.13.1 Actions 
a. DS DM25 [send Request (PG 59904) for PG 64951 (SPNSPs 3300, 1214-1215)] to each OBD ECU.  
b. If no response [transport protocol RTS or NACK(Busy) in 220 ms], then retry DS DM25 request to the OBD ECU. (Do not attempt retry for NACKS that indicate not supported.)
c. Translate and print in log file all received freeze frame data with data labels assuming data received in order expected by DM24 response for visual check by test log reviewer. 

6.4.10 DM25: Expanded Freeze Frame 
6.4.10.1 Actions 
a. DS DM25 [send Request (PG 59904) for PG 64951 (SPNSPs 3300, 1214-1215)] to each OBD ECU. 
6.4.10.2 Fail Criteria 
a. Fail if no ECU reports freeze frame data. 
b. Fail if DTC in freeze frame data does not include the DTC reported in DM12 earlier in this part. 
c. Fail if NACK not received from OBD ECUs that did not provide DM25 response. 

6.8.10.1 Actions 
a. DS DM25 [send Request (PG 59904) for PG 64951 (SPNS 3300, 1214, 1215)] to each OBD ECU. 
6.8.10.2 Fail Criteria 
a. Fail if DTC(s) reported in the freeze frame does not include either the DTC reported in DM12 or the DTC reported in DM23 earlier in this part 
b. Fail if no freeze frame data (i.e. an empty freeze frame) is provided.  
**_c. Fail if NACK not received from OBD that did not provide an DM25 message._**   

6.9.17 DM25: Expanded Freeze Frame 
6.9.17.1 Actions 
a. DS DM25 [send Request (PG 59904) for PG 64951 (SPNS 3300, 1214-1215)] to each OBD ECU. 
6.9.17.2 Fail Criteria 
a. Fail if any OBD ECU reports other than no Freeze Frame data stored (bytes 1-5 = 00h, 6-8= FFh). 
**_b. Fail if NACK now received from OBD ECUs that previously provided a DM25 message._** 
6.9.18 DM23: Emission Related Previously Active DTCs

**Comment by ericthomasswenson** [comment]
DM25 check for erased diagnostic info appears to be suspect by not remembering that SA 61 didn’t support FF (DM26) … The query is fine … interpreting a NACK as erased, when not supported (in the first place) appears to be the error.

**Comment by battjt** [comment]
We need clarification.  " to each OBD ECU....Fail if DTC(s) reported in the freeze frame does not include either the DTC reported in DM12 or the DTC reported in DM23 earlier in this part.".  Should there be some constraint about NACKs? Or for any modules?

**Comment by battjt** [comment]
I'm confused by the initial report.  The FAIL is for Engine #1, but the traffic in the report is for the aftertreatment module, 3Dh.

Run on 3.1.5 correctly identified the error:
```
10:59:11.1765 1CFDB700 [134] 85 61 00 1F 01 00 7D 7D A3 0A C8 9F B1 DF E1 67 1F 2A 00 00 00 00 00
00 C6 ED 00 2D 85 00 01 00 64 00 64 00 64 00 64 00 64 00 64 4C 5C 31 00 00 80 25 00 00 00 00 1F 00
00 00 00 00 DC 00 FF 63 3C 30 00 00 9C 30 00 00 00 00 A9 2E 00 00 00 A0 26 01 DE 00 FB FF FF 00 FB
00 DC 3D 00 00 BC 28 5A 26 B9 0A 45 04 01 00 03 00 0F C2 E7 58 00 CA 3A 0F 4B 09 25 00 00 00 82 41
11 7A 0F 2F 7C 2D 93 2E 04 FA 40 9C
DM25 from Engine #1 (0):
Freeze Frames: [
Freeze Frame: {
DTC 97:31 - Water In Fuel Indicator 1, Condition Exists - 1 times
SPN Data: 00 7D 7D A3 0A C8 9F B1 DF E1 67 1F 2A 00 00 00 00 00 00 C6 ED 00 2D 85 00 01 00 64
00 64 00 64 00 64 00 64 00 64 4C 5C 31 00 00 80 25 00 00 00 00 1F 00 00 00 00 00 DC 00 FF 63 3C 30
00 00 9C 30 00 00 00 00 A9 2E 00 00 00 A0 26 01 DE 00 FB FF FF 00 FB 00 DC 3D 00 00 BC 28 5A 26 B9
0A 45 04 01 00 03 00 0F C2 E7 58 00 CA 3A 0F 4B 09 25 00 00 00 82 41 11 7A 0F 2F 7C 2D 93 2E 04 FA
40 9C
}
]
FAIL: 6.9.17.2.a - Engine #1 (0) reported other than no Freeze Frame data stored
```

Run on 3.1.6 correctly did not report the error:
```14:39:51.8290 18FDB700 [8] 00 00 00 00 00 FF FF FF```

**Comment by battjt** [comment]
There have been changes since this was reported.  Please retest with 3.1.10 when available.

**Comment by battjt** [comment]
This may be the class of error testing any instead of all.  Further testing expected.

**Comment by ericthomasswenson** [comment]
13:48:18.9068 Destination Specific DM25 Request to Management Computer #1 (39)
13:48:18.9092 18EA27F9 [3] B7 FD 00 (TX)
13:48:18.9112 18E8FF27 [8] 01 FF FF FF F9 B7 FD 00
Acknowledgment from Management Computer #1 (39): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64951

Timeout are detected as erased .. this NACK was not detected as erased.
