### ISSUE TITLE
DM28 Handling in Part 11 Incorrect

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1132]
SA 61 accused for premature permanent fault erasure when starting with no permanent fault.

SA 39 response may have gotten in the way

**Comment by ericthomasswenson** [comment]
Not observed on 3.1.4 with a monolithic Engine OBD ECU.
Need review with distributed architecture.

**Comment by battjt** [comment]
Wating for confirmation that it's still a bug.

**Comment by battjt** [comment]
Marked dev complete as duplicate of #1089 .
