### ISSUE TITLE
DM1 described as Previously Active DTC … it’s an Active DTC

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1133]
DM1 described as Previously Active DTC … it’s an Active DTC

14:44:06.4738 18FECA17 [8] 04 FF 03 08 09 01 FF FF
DM1 from Instrument Cluster #1 (23): MIL: off, RSL: off, AWL: on, PL: off
DTC 2051:9 - Source Address 51 , Abnormal Update Rate - 1 times
…
14:44:06.8639 18FECA00 [8] 00 FF 00 00 00 00 FF FF
DM1 from Engine #1 (0): MIL: off, RSL: off, AWL: off, PL: off, No DTCs
FAIL: **_6.9.22.2.b_** - ECU Instrument Cluster #1 (23) reported a **_previously_** active DTC

**Comment by battjt** [comment]
6.9.23.2.b was reporting 6.9.22.2.b.
