### ISSUE TITLE
Vehicle Summary is Redundant When Only 1 Response is Received.

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1137]
Do we really need to display the same DM26 data twice?

Start Test 2.8 - DM26: Diagnostic readiness 3
13:44:08.5733 Destination Specific DM26 Request to Engine #1 (0)
13:44:08.5762 18EA00F9 [3] B8 FD 00 (TX)
13:44:08.5785 18FDB800 [8] 3E 00 00 27 E0 1E E0 1E
DM26 from Engine #1 (0): Warm-ups: 0, Time Since Engine Start: 62 seconds
Continuously Monitored System Support/Status:
    Comprehensive component        enabled,     complete
    Fuel System                    enabled, not complete
    Misfire                        enabled,     complete
Non-continuously Monitored System Support/Status:
    A/C system refrigerant     not enabled,     complete
    Boost pressure control sys     enabled, not complete
    Catalyst                   not enabled,     complete
    Cold start aid system      not enabled,     complete
    Diesel Particulate Filter      enabled, not complete
    EGR/VVT system                 enabled, not complete
    Evaporative system         not enabled,     complete
    Exhaust Gas Sensor             enabled, not complete
    Exhaust Gas Sensor heater      enabled, not complete
    Heated catalyst            not enabled,     complete
    NMHC converting catalyst       enabled, not complete
    NOx catalyst/adsorber          enabled, not complete
    Secondary air system       not enabled,     complete

Vehicle Composite of DM26:
    A/C system refrigerant     not enabled,     complete
    Boost pressure control sys     enabled, not complete
    Catalyst                   not enabled,     complete
    Cold start aid system      not enabled,     complete
    Comprehensive component        enabled,     complete
    Diesel Particulate Filter      enabled, not complete
    EGR/VVT system                 enabled, not complete
    Evaporative system         not enabled,     complete
    Exhaust Gas Sensor             enabled, not complete
    Exhaust Gas Sensor heater      enabled, not complete
    Fuel System                    enabled, not complete
    Heated catalyst            not enabled,     complete
    Misfire                        enabled,     complete
    NMHC converting catalyst       enabled, not complete
    NOx catalyst/adsorber          enabled, not complete
    Secondary air system       not enabled,     complete

**Comment by ericthomasswenson** [comment]
See #1163 for related topic.

**Comment by ericthomasswenson** [comment]
Add … when only more than one OBD ECU response is received to appropriate DM5 and DM26 query locations.

**Comment by battjt** [comment]
In the following sections, the vehicle composite will be skipped if there is < 2 responses:

1. 6.1.3
2. 6.1.13
3. 6.1.14
4. 6.2.2
5. 6.2.8
6. 6.11.10
7. 6.11.11
8. 6.12.3

This will change unit tests for each part that verify the composite and not the individual packets.  Instead I'll verify the individual packets. 

This bring up that the order of the composite is different than the individual packets.  Should that also be changed?
![image](https://github.com/Equipment-and-Tool-Institute/j1939-84/assets/1972001/3371c143-546e-4927-82fc-2cc9a35f1b7d)

**Comment by ericthomasswenson** [comment]
Display monitor readiness composite value in log for OBD ECU replies only, **_where more than one response was received._**

**Comment by ericthomasswenson** [comment]
Jacob reports seeing reduced (additional) vehicle composites for their monolithic architecture on 3.1.24.

Vehicle composites were still observed for 6.1.3 for DM5 and 6.2.8 for DM26.

**Comment by ericthomasswenson** [comment]
There are a total of six locations observed… eratta marked with #1137.
