### ISSUE TITLE
Add Received Length to FF Display

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1139]
Add Received Length (provided in byte 1) to individual FF displays

Start Test 4.10 - DM25: Expanded freeze frame
13:49:52.4978 Destination Specific DM25 Request to Engine #1 (0)
13:49:52.5023 18EA00F9 [3] B7 FD 00 (TX)
13:49:52.9528 1CFDB700 [134] **_85_** 83 10 01 01 07 84 84 D7 0A A5 D5 B0 DD E1 48 C2 25 D4 21 17 00 00 00 C7 0C 01 1B 0C 00 01 92 61 92 61 92 61 92 61 92 61 92 61 38 3D 24 9C 17 D7 23 00 00 00 00 1F 23 28 64 00 00 19 6B C7 6A CC 30 07 00 AC 31 00 00 27 01 61 36 AB AB 00 76 24 01 75 00 FB FE FA 00 FB D0 88 04 00 00 1C 26 CB 24 2A 10 F1 0B 01 00 03 02 01 EC 7D 01 00 06 29 12 08 05 25 00 00 00 7E 32 11 7A 97 2D 83 29 83 33 04 20 35 14
DM25 from Engine #1 (0): 
Freeze Frames: [
  Freeze Frame: {
    **_Length: 133_** **_<— Add length byte value here_**
    DTC 4227:1 - Engine Crankcase Breather Oil Separator, Data Valid But Below Normal Operational Range - Most Severe Level - 1 times
    SPN Data: 07 84 84 D7 0A A5 D5 B0 DD E1 48 C2 25 D4 21 17 00 00 00 C7 0C 01 1B 0C 00 01 92 61 92 61 92 61 92 61 92 61 92 61 38 3D 24 9C 17 D7 23 00 00 00 00 1F 23 28 64 00 00 19 6B C7 6A CC 30 07 00 AC 31 00 00 27 01 61 36 AB AB 00 76 24 01 75 00 FB FE FA 00 FB D0 88 04 00 00 1C 26 CB 24 2A 10 F1 0B 01 00 03 02 01 EC 7D 01 00 06 29 12 08 05 25 00 00 00 7E 32 11 7A 97 2D 83 29 83 33 04 20 35 14
  }
]

**Comment by ericthomasswenson** [comment]
Implement with  #1047

**Comment by battjt** [comment]
Currently there is a "Data Length".  Does that satisfy this requirement?
```
DM25 from Engine #1 (0): 
Packet Length: 87
Freeze Frames: [
  Freeze Frame: {
    Data Length: 82
    DTC 157:7 - Engine Fuel 1 Injector Metering Rail 1 Pressure, Mechanical System Not Responding Or Out Of Adjustment
    SPN Data: 00 01 7B 00 00 39 3A 5C 0F C4 FB 00 00 00 F1 26 00 00 00 12 7A 7D 80 65 00 00 32 00 00 00 00 84 AD 00 39 2C 30 39 FC 38 C6 35 E0 34 2C 2F 00 00 7D 7D 8A 28 A0 0F A0 0F D1 37 00 CA 28 01 A4 0D 00 A8 C3 B2 C2 C3 00 00 00 00 7E D0 07 00 7D 04 FF FA
  }
]
```
