### ISSUE TITLE
Spark Ignition DM5 Heated Catalyst Incorrectly WARNs

### ISSUE THREAD

**Issue by markmorrisoncummins** [Equipment-and-Tool-Institute/j1939-84#1142]
Table A-6-2 indicates warn if 1 for heated catalyst monitoring support. Tool is warning when heated catalyst is not supported.

Vehicle Composite of DM5:
    A/C system refrigerant     not supported,     complete
    Boost pressure control sys not supported,     complete
    Catalyst                       supported, not complete
    Cold start aid system      not supported,     complete
    Comprehensive component        supported,     complete
    Diesel Particulate Filter  not supported,     complete
    EGR/VVT system                 supported, not complete
    Evaporative system         not supported,     complete
    Exhaust Gas Sensor             supported, not complete
    Exhaust Gas Sensor heater  not supported,     complete
    Fuel System                    supported, not complete
    **Heated catalyst            not supported,     complete**
    Misfire                        supported,     complete
    NMHC converting catalyst   not supported,     complete
    NOx catalyst/adsorber      not supported,     complete
    Secondary air system       not supported,     complete

WARN: 6.1.13.2.a (A6.2.c) - Cold start aid system is not supported, complete
FAIL: 6.1.13.2.a (A6.2.c) - Composite vehicle readiness for Evaporative system did not meet the criteria of Table A4
FAIL: 6.1.13.2.a (A6.2.c) - Composite vehicle readiness for Exhaust Gas Sensor heater did not meet the criteria of Table A4
**WARN: 6.1.13.2.a (A6.2.c) - Heated catalyst is not supported, complete**

**Comment by ericthomasswenson** [comment]
Table A-6-2 Says,

Byte 5 Bit 2    Heated Catalyst monitoring support	|  must be 0, warn if 1

For similar complaints Bob speculates 
- an indexing error, or 
- Extra or omitted row

**Comment by battjt** [comment]
Verified bug.  In addition the doc has a typo:
![image](https://user-images.githubusercontent.com/1972001/199864207-3c5fa439-226a-46dd-81bd-a8890601e3ea.png)
