### ISSUE TITLE
Identify Your CAN Interface for Task 6

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1143]
Please Identify your Task 6 Preferences, as illustrated below.

Development: Navistar Nexiq Link 2 (USB / Bluetooth / WiFi)
(l)(1,3) Data Collection: Same

**Comment by vmuthu2** [comment]
PACCAR

Development: Nexiq Link 2 (USB / Bluetooth / WiFi), PEAK Adapter, Kvaser
(l)(1,3) Data Collection: Nexiq USB Link 2 (USB / Bluetooth / WiFi)

**Comment by ericthomasswenson** [comment]
Vimal, 

Could you be more specific about the Kvaser and Peak hardware models?

Eric

Sent from my iPad
…
Copied email redacted … ETs

**Comment by ericthomasswenson** [comment]
Henderick, Paul@ARB wrote:

Greetings Eric,

We've got both the Nexiq USB and ValueCAN3 interfaces.  They should be at the top of the list for -84 related testing. Haven't acquired anything new in a few years.  We also use Vector VN1610 interfaces but not for -84 testing.  …

**Comment by ericthomasswenson** [comment]
Links

https://store.intrepidcs.com/product/vcan4-2a-j1939-kit 

https://www.vector.com/int/en/products/products-a-z/libraries-drivers/rp1210-api/#c34708 
https://www.vector.com/int/en/products/products-a-z/hardware/network-interfaces/vn16xx/ 

https://www.peak-system.com/produktcd/Catalogs/PEAK-SysE.pdf p.95

https://www.kvaser.com/products-services/our-products/#/?descriptors=pc_int

**Comment by naroner** [comment]
DDC:

Development: Vector VN16X0 / Nexiq USB Link 2
Data Collection: Nexiq USB Link 2

**Comment by jacobbosch-cummins** [comment]
Cummins:

INLINE 7 (Similar to Nexiq USB Link 2)

We use PEAK PCAN-USB commonly for engineering and development work, and frequently receive requests for PCAN-USB support from our -84 tool users.  Currently, the -84 tool does not progress past Part 1 with PCAN-USB.

**Comment by ericthomasswenson** [comment]
My recommendations are:
1. Vector 16x0 
… has RP 1210 C interface software
… Provides “standard” for viewing .ASC logs with error messages.
… may permit simultaneous logging 

2. PEAK PCAN USB
… for the learning experience.

**Comment by vmuthu2** [comment]
For the PEAK adapter we use the P-CAN USB (similar to Cummins).
RP1210C drivers/information for PEAK: https://www.peak-system.com/PCAN-RP1210-C.361.0.html

Kvaser that we use during development is Kvaser Leaf Light HS v2 J1939-13 Type II

**Comment by ericthomasswenson** [comment]
4 of 4 participants agreed with the recommendations.

Additional hardware examples may be contributed as one of the 5 user submitted logs allowed in the Task 6 statement of work text.

**Comment by ericthomasswenson** [comment]
HW Received
