### ISSUE TITLE
Part 11 NOx binning changes to modify in draft

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#1153]
6.11.13.2	Fail criteria1  for MY2022+ Diesel Engines

**REMOVE** d. Fail if lifetime engine hours bin 1 (total) SPN 12593 < part 2 value + 600 seconds. **NOx sensors will not be online. We will definitely FAIL this criteria during L1 testing on production trucks.**

6.11.13.4	Fail/warn criteria2  for MY2022+ Diesel Engines

**REMOVE** e. Fail if active 100 hrs engine hours NOx Tracking Engine Activity Lifetime Engine Hours bin 1 SP 12389 12659< 600 seconds (where supported) **NOx sensors will not be online during -84 test. We will definitely FAIL this criteria during L1 testing on production trucks.**
g. Warn for all active 100 hr bin 3 through bin 16 values that are greater than their respective values for bins 3 through 16 in part 2. (Where supported)
h. Warn for all active 100 hr vehicle distance bins  => 0.25 km. (Where supported). 
**REMOVE** i. Warn for active 100 hr EOE bin 1 SPN 12355 <= 0.5 or bin 2 SPN 12356 <= 0.5 kW-hr (Where supported). **NOx sensors will not be online during -84 test and will report 0.**
**REMOVE** j. Warn for active 100hr engine out NOx bin 1 SPN 12338 = 0 or bin 2 SPN 12339  = 0. (Where supported).  **NOx sensors will not be online during -84 test and will report 0.**
**REMOVE** k. Warn for active 100hr system out NOx bin 1 SPN 12321 = 0 or bin 2 SPN 12322 = 0. (Where supported). **NOx sensors will not be online during -84 test and will report 0.**

**Comment by vmuthu2** [comment]
FALSE fails due to specification

WARN: 6.11.13.4.i - Active 100 hr EOE bin1 and bin2 received is <= 0.5kW-hr from Engine #1 (0) for SPN 12457, NOx Tracking Stored 100 Hour Engine Output Energy Bin 1 (Total): 0.000 kWh
WARN: 6.11.13.4.i - Active 100 hr EOE bin1 and bin2 received is <= 0.5kW-hr from Engine #1 (0) for SPN 12458, NOx Tracking Stored 100 Hour Engine Output Energy Bin 2 : 0.000 kWh
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12338, NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 1 (Total): 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12339, NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 2 : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12321, NOx Tracking Active 100 Hour System Out NOx Mass Bin 1 (Total): 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12322, NOx Tracking Active 100 Hour System Out NOx Mass Bin 2 : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12440, NOx Tracking Stored 100 Hour Engine Out NOx Mass Bin 1 (Total): 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12441, NOx Tracking Stored 100 Hour Engine Out NOx Mass Bin 2 : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12423, NOx Tracking Stored 100 Hour System Out NOx Mass Bin 1 (Total): 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12424, NOx Tracking Stored 100 Hour System Out NOx Mass Bin 2 : 0.000 g

**Comment by ericthomasswenson** [comment]
Looks more like the active 100 hr limits were incorrectly applied to the stored limits.

I tried to minimize stored 100 hr checks as they are will remain zero for a newly manufactured vehicle and may be populated for a field/development vehicle.

**Comment by ericthomasswenson** [comment]
Yes I assumed operating NOx sensors … no time from No NOx data is a conceptual error from a year ago.

**Comment by ericthomasswenson** [comment]
CARB wants urea injection as soon as the engine starts in the desire that 0 g / BHP is achieved. They have bristled at the notion that NOx sensors do not operate 24/7/365.

But you have a clear argument to make this a warning.

**Comment by vmuthu2** [comment]
Changing it to a WARN is not going to help. The NOx sensors will not be online. The IUMPR tool is a great place to do this check.

**Comment by ericthomasswenson** [comment]
See #1161

**Comment by ericthomasswenson** [comment]
Completed artifact conveyed to developers and users. Update pending from #1171

**Comment by ericthomasswenson** [comment]
See #1171 for implementation status.
