### ISSUE TITLE
NOx binning false fails issued by the tool

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#1154]
WARN: 6.11.13.4.i - Active 100 hr EOE bin1 and bin2 received is <= 0.5kW-hr from Engine #1 (0) for SPN 12459, NOx Tracking Stored 100 Hour Engine Output Energy Bin 3 : 0.000 kWh
WARN: 6.11.13.4.i - Active 100 hr EOE bin1 and bin2 received is <= 0.5kW-hr from Engine #1 (0) for SPN 12460, NOx Tracking Stored 100 Hour Engine Output Energy Bin 4: 0.000 kWh
WARN: 6.11.13.4.i - Active 100 hr EOE bin1 and bin2 received is <= 0.5kW-hr from Engine #1 (0) for SPN 12461, NOx Tracking Stored 100 Hour Engine Output Energy Bin 5: 0.000 kWh
WARN: 6.11.13.4.i - Active 100 hr EOE bin1 and bin2 received is <= 0.5kW-hr from Engine #1 (0) for SPN 12462, NOx Tracking Stored 100 Hour Engine Output Energy Bin 6: 0.000 kWh
WARN: 6.11.13.4.i - Active 100 hr EOE bin1 and bin2 received is <= 0.5kW-hr from Engine #1 (0) for SPN 12463, NOx Tracking Stored 100 Hour Engine Output Energy Bin 7: 0.000 kWh
WARN: 6.11.13.4.i - Active 100 hr EOE bin1 and bin2 received is <= 0.5kW-hr from Engine #1 (0) for SPN 12464, NOx Tracking Stored 100 Hour Engine Output Energy Bin 8: 0.000 kWh
WARN: 6.11.13.4.i - Active 100 hr EOE bin1 and bin2 received is <= 0.5kW-hr from Engine #1 (0) for SPN 12465, NOx Tracking Stored 100 Hour Engine Output Energy Bin 9: 0.000 kWh
WARN: 6.11.13.4.i - Active 100 hr EOE bin1 and bin2 received is <= 0.5kW-hr from Engine #1 (0) for SPN 12466, NOx Tracking Stored 100 Hour Engine Output Energy Bin 10: 0.000 kWh
WARN: 6.11.13.4.i - Active 100 hr EOE bin1 and bin2 received is <= 0.5kW-hr from Engine #1 (0) for SPN 12467, NOx Tracking Stored 100 Hour Engine Output Energy Bin 11: 0.000 kWh
WARN: 6.11.13.4.i - Active 100 hr EOE bin1 and bin2 received is <= 0.5kW-hr from Engine #1 (0) for SPN 12468, NOx Tracking Stored 100 Hour Engine Output Energy Bin 12: 0.000 kWh
WARN: 6.11.13.4.i - Active 100 hr EOE bin1 and bin2 received is <= 0.5kW-hr from Engine #1 (0) for SPN 12469, NOx Tracking Stored 100 Hour Engine Output Energy Bin 13: 0.000 kWh
WARN: 6.11.13.4.i - Active 100 hr EOE bin1 and bin2 received is <= 0.5kW-hr from Engine #1 (0) for SPN 12470, NOx Tracking Stored 100 Hour Engine Output Energy Bin 14 : 0.000 kWh
WARN: 6.11.13.4.i - Active 100 hr EOE bin1 and bin2 received is <= 0.5kW-hr from Engine #1 (0) for SPN 12471, NOx Tracking Stored 100 Hour Engine Output Energy Bin 15 (NTE BIN) : 0.000 kWh
WARN: 6.11.13.4.i - Active 100 hr EOE bin1 and bin2 received is <= 0.5kW-hr from Engine #1 (0) for SPN 12472, NOx Tracking Stored 100 Hour Engine Output Energy Bin 16 (Regen Bin) : 0.000 kWh
WARN: 6.11.13.4.i - Active 100 hr EOE bin1 and bin2 received is <= 0.5kW-hr from Engine #1 (0) for SPN 12473, NOx Tracking Stored 100 Hour Engine Output Energy Bin 17 (MIL On Bin) : 0.000 kWh
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12340, NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 3 : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12341, NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 4: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12342, NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 5: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12343, NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 6: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12344, NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 7: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12345, NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 8: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12346, NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 9: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12347, NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 10: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12348, NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 11: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12349, NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 12: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12350, NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 13: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12351, NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 14 : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12352, NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 15 (NTE BIN) : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12353, NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 16 (Regen Bin) : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12354, NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 17 (MIL On Bin) : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12323, NOx Tracking Active 100 Hour System Out NOx Mass Bin 3 : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12324, NOx Tracking Active 100 Hour System Out NOx Mass Bin 4: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12325, NOx Tracking Active 100 Hour System Out NOx Mass Bin 5: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12326, NOx Tracking Active 100 Hour System Out NOx Mass Bin 6: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12327, NOx Tracking Active 100 Hour System Out NOx Mass Bin 7: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12328, NOx Tracking Active 100 Hour System Out NOx Mass Bin 8: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12329, NOx Tracking Active 100 Hour System Out NOx Mass Bin 9: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12330, NOx Tracking Active 100 Hour System Out NOx Mass Bin 10: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12331, NOx Tracking Active 100 Hour System Out NOx Mass Bin 11: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12332, NOx Tracking Active 100 Hour System Out NOx Mass Bin 12: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12333, NOx Tracking Active 100 Hour System Out NOx Mass Bin 13: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12334, NOx Tracking Active 100 Hour System Out NOx Mass Bin 14 : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12335, NOx Tracking Active 100 Hour System Out NOx Mass Bin 15 (NTE BIN) : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12336, NOx Tracking Active 100 Hour System Out NOx Mass Bin 16 (Regen Bin) : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12337, NOx Tracking Active 100 Hour System Out NOx Mass Bin 17 (MIL On Bin) : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12442, NOx Tracking Stored 100 Hour Engine Out NOx Mass Bin 3 : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12443, NOx Tracking Stored 100 Hour Engine Out NOx Mass Bin 4: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12444, NOx Tracking Stored 100 Hour Engine Out NOx Mass Bin 5: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12445, NOx Tracking Stored 100 Hour Engine Out NOx Mass Bin 6: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12446, NOx Tracking Stored 100 Hour Engine Out NOx Mass Bin 7: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12447, NOx Tracking Stored 100 Hour Engine Out NOx Mass Bin 8: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12448, NOx Tracking Stored 100 Hour Engine Out NOx Mass Bin 9: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12449, NOx Tracking Stored 100 Hour Engine Out NOx Mass Bin 10: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12450, NOx Tracking Stored 100 Hour Engine Out NOx Mass Bin 11: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12451, NOx Tracking Stored 100 Hour Engine Out NOx Mass Bin 12: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12452, NOx Tracking Stored 100 Hour Engine Out NOx Mass Bin 13: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12453, NOx Tracking Stored 100 Hour Engine Out NOx Mass Bin 14 : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12454, NOx Tracking Stored 100 Hour Engine Out NOx Mass Bin 15 (NTE BIN) : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12455, NOx Tracking Stored 100 Hour Engine Out NOx Mass Bin 16 (Regen Bin) : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12456, NOx Tracking Stored 100 Hour Engine Out NOx Mass Bin 17 (MIL On Bin) : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12425, NOx Tracking Stored 100 Hour System Out NOx Mass Bin 3 : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12426, NOx Tracking Stored 100 Hour System Out NOx Mass Bin 4: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12427, NOx Tracking Stored 100 Hour System Out NOx Mass Bin 5: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12428, NOx Tracking Stored 100 Hour System Out NOx Mass Bin 6: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12429, NOx Tracking Stored 100 Hour System Out NOx Mass Bin 7: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12430, NOx Tracking Stored 100 Hour System Out NOx Mass Bin 8: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12431, NOx Tracking Stored 100 Hour System Out NOx Mass Bin 9: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12432, NOx Tracking Stored 100 Hour System Out NOx Mass Bin 10: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12433, NOx Tracking Stored 100 Hour System Out NOx Mass Bin 11: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12434, NOx Tracking Stored 100 Hour System Out NOx Mass Bin 12: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12435, NOx Tracking Stored 100 Hour System Out NOx Mass Bin 13: 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12436, NOx Tracking Stored 100 Hour System Out NOx Mass Bin 14 : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12437, NOx Tracking Stored 100 Hour System Out NOx Mass Bin 15 (NTE BIN) : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12438, NOx Tracking Stored 100 Hour System Out NOx Mass Bin 16 (Regen Bin) : 0.000 g
WARN: 6.11.13.4.k - Active 100 hr system out Nox bin1 and bin2 received is = 0 seconds from Engine #1 (0) for SPN 12439, NOx Tracking Stored 100 Hour System Out NOx Mass Bin 17 (MIL On Bin) : 0.000 g

**Comment by anthonyhbest** [comment]
This issue appears to be resolved in v3.1.3.

**Comment by ericthomasswenson** [comment]
TY Anthony.

**Comment by ericthomasswenson** [comment]
Corrected in 3.1.3
