### ISSUE TITLE
GHG Tracking Stop-Start Technology 

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#1155]
Stop Start counts SPN 12711    SPN 12726    SPN 12741
Stop Start Engine Run Time SPN 12712    SPN 12727    SPN 12742

The above 6 SPNs can report "Not Available". Not all trucks are equipped with start stop systems. An exclusion list must be added in Part 1 Test 26, Part 2 Test 17 and Part 11 Test 13 for the >FAFFh evaluation for the above 6 SPNs.

**Comment by ericthomasswenson** [comment]
Please copy the engine response and the tool’s error message.

I can accept an explanation that the customer’s transmission equipment governs use of these    technologies. 

[Reporting as 0000 0000 0000 would pass the test as written (a j1979 like approach)].

We would need to add text to Appendix D too.

**Comment by vmuthu2** [comment]
09:30:02.4118 Destination Specific GHGTS Request to Engine #1 (0)
09:30:02.4152 18EA00F9 [3] FD FA 00 (TX)
09:30:02.4663 1CFAFD00 [28] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 FF
GHG Tracking Stored 100 Hour Array Data from Engine #1 (0): 
  SPN 12715, GHG Tracking Stored 100 Hour Engine Run Time: 0.000 s
  SPN 12716, GHG Tracking Stored 100 Hour Vehicle Distance: 0.000 km
  SPN 12717, GHG Tracking Stored 100 Hour Vehicle Fuel Consumption: 0.000 l
  SPN 12718, GHG Tracking Stored 100 Hour Engine Fuel Consumption: 0.000 l
  SPN 12719, GHG Tracking Stored 100 Hour Engine Output Energy: 0.000 kWh
  SPN 12720, GHG Tracking Stored 100 Hour Positive Kinetic Energy Numerator: 0.000 km²/h²
  SPN 12721, GHG Tracking Stored 100 Hour Urban Speed Run Time: 0.000 s
  SPN 12722, GHG Tracking Stored 100 Hour Idle Run Time: 0.000 s
  SPN 12723, GHG Tracking Stored 100 Hour Engine Idle Fuel Consumption: 0.000 l
  SPN 12724, GHG Tracking Stored 100 Hour Engine Power Take Off Run Time: 0.000 s
  SPN 12725, GHG Tracking Stored 100 Hour Engine Power Take Off Fuel Consumption: 0.000 l
  SPN 12726, GHG Tracking Stored 100 Hour Automatic Engine Shutdown Technology Activation Count: 0.000 count
  SPN 12727, GHG Tracking Stored 100 Hour Stop-Start Technology Run Time: Not Available

09:30:02.4711 GHG Tracking Arrays from Engine #1 (0)
|-------------------------+-------------+-------------+-------------|
|                         |    Active   |    Stored   |             |
|                         |   100 Hour  |   100 Hour  |   Lifetime  |
|-------------------------+-------------+-------------+-------------|
| Engine Run Time, s      |           0 |           0 |          43 |
| Vehicle Dist., km       |           0 |           0 |           0 |
| Vehicle Fuel, l         |           0 |           0 |           4 |
| Engine Fuel, l          |           0 |           0 |           4 |
| Eng.Out.Energy, kW-hr   |           0 |           0 |           5 |
| PKE Numerator           |           0 |           0 |           0 |
| Urban Speed Run Time, s |           0 |           0 |           0 |
| Idle Run Time, s        |           0 |           0 |          43 |
| Engine Idle Fuel, l     |           0 |           0 |           4 |
| PTO Run Time, s         |           0 |           0 |           0 |
| PTO Fuel Consumption, l |           0 |           0 |           0 |
| AES Shutdown Count      |           0 |           0 |           0 |
| Stop-Start Run Time, s  |         N/A |         N/A |         N/A |
|-------------------------+-------------+-------------+-------------|

FAIL: 6.1.26.14.c - Bin value received is greater than 0xFAFF from Engine #1 (0) for SPN 12712, GHG Tracking Active 100 Hour Stop-Start Technology Run Time: Not Available
FAIL: 6.1.26.14.c - Bin value received is greater than 0xFAFF from Engine #1 (0) for SPN 12727, GHG Tracking Stored 100 Hour Stop-Start Technology Run Time: Not Available

**Comment by ericthomasswenson** [comment]
The optional GHG tracking content would consist of

PTO Run Time, s 
PTO Fuel Consumption, l 
AES Shutdown Count

In addition to

Stop-Start Run Time, s 

For active technology tracking 

The label would still need to FAh or less.
It was generally expected that only supported technologies would be reported.

**Comment by ericthomasswenson** [comment]
For both use FB00 to FEFFh as the range of invalid values

**Comment by ericthomasswenson** [comment]
6.11.13.5	Actions3 for MY2022+ Diesel Engines

a. DS request messages to ECU that indicated support in DM24 for upon request SP 12730 (GHG Tracking Engine Run Time) for PG 64252 GHG Tracking Lifetime Array Data.

6.11.13.6 Fail criteria1  for MY2022+ Diesel Engines

a. For all MY2022+ engines, Fail PG query where no response was received.  
b. Fail PG query where any bin value received is greater than FAFFh.
c. Fail all values where the corresponding value received in part 2 is greater than the part 11 value. 
d. Fail if lifetime engine hours SPN 12730 < 600 seconds. (Where supported).

**Comment by ericthomasswenson** [comment]
Consolidated 6.11.13 Improvements updated to July 8, 2022

[Inactive NOx Sensor Proposal.docx](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/9087452/Inactive.NOx.Sensor.Proposal.docx)

[GHG Reference SPs.docx](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/9051060/GHG.Reference.SPs.docx)

[NOx Binning Reference SP.docx](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/9051063/NOx.Binning.Reference.SP.docx)

See #1161

**Comment by ericthomasswenson** [comment]
Completed Artifact conveyed.  Update pending from #1171
