### ISSUE TITLE
6.11.13.2.e Fail criteria incorrectly implemented in v3.1.3

### ISSUE THREAD

**Issue by anthonyhbest** [Equipment-and-Tool-Institute/j1939-84#1158]
Text from Task 5 document:
6.11.13.2	Fail criteria1  for MY2022+ Diesel Engines
e. Fail if lifetime engine activity engine hours bin 1 (total) SPN 12659 < part 2 value + 600 seconds. 

Fail message received in v3.1.3:
**WARN**: 6.11.13.2.e - Lifetime engine activity engine hours bin 1 (total) SP 12659 is **>** part 2 value + 600 seconds

Tool is issuing a WARN instead of a FAIL but also looking for values **greater than** part 2 + 600 seconds instead of the required **less than** part 2 + 600 seconds

**Comment by ericthomasswenson** [comment]
Anthony please copy the response data too.

**Comment by ericthomasswenson** [comment]
6.11.13.2	Fail criteria1  for MY2022+ Diesel Engines

a. Fail each PG query where no response was received.  
b. Fail each PG query where any bin value received is greater than FAFFFFFFh.  
c. Fail all values where the corresponding value received in part 2 is greater than the part 12 value.
d. Fail if lifetime engine hours bin 1 (total) SPN 12593 < part 2 value + 600 seconds. 
e. Fail if lifetime engine activity engine hours bin 1 (total) SPN 12659 < part 2 value + 600 seconds.

**Comment by ericthomasswenson** [comment]
For Vimal’s NOx sensor comment

6.11.13.2	Fail criteria1  for MY2022+ Diesel Engines

a. Fail each PG query where no response was received.  
b. Fail each PG query where any bin value received is greater than FAFFFFFFh.  
c. Fail all values where the corresponding value received in part 2 is greater than the part 12 value.
d. **_Warn_** if lifetime engine hours bin 1 (total) SPN 12593 **_<_** part 2 value + 600 seconds. 
e. Fail if lifetime engine activity engine hours bin 1 (total) SPN 12659 **_<_** part 2 value + 600 seconds. 

(Info preferred to warning).

**Comment by anthonyhbest** [comment]
**Response data from section 11.13.2:**
10:15:03.9124 Destination Specific NTEHEA Request to Engine #1 (0)
10:15:03.9157 18EA00F9 [3] 03 FB 00 (TX)
10:15:04.0177 1CFB0300 [68] A4 0D 00 00 A4 0D 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 60 02 00 00
NOx Tracking Engine Activity Lifetime Engine Run Time Bins from Engine #1 (0): 
  SPN 12659, NOx Tracking Engine Activity Lifetime Engine Run Time Bin 1 (Total): 3492.000 s
  SPN 12660, NOx Tracking Engine Activity Lifetime Engine Run Time Bin 2 : 3492.000 s
  SPN 12661, NOx Tracking Engine Activity Lifetime Engine Run Time Bin 3 : 0.000 s
  SPN 12662, NOx Tracking Engine Activity Lifetime Engine Run Time Bin 4: 0.000 s
  SPN 12663, NOx Tracking Engine Activity Lifetime Engine Run Time Bin 5: 0.000 s
  SPN 12664, NOx Tracking Engine Activity Lifetime Engine Run Time Bin 6: 0.000 s
  SPN 12665, NOx Tracking Engine Activity Lifetime Engine Run Time Bin 7: 0.000 s
  SPN 12666, NOx Tracking Engine Activity Lifetime Engine Run Time Bin 8: 0.000 s
  SPN 12667, NOx Tracking Engine Activity Lifetime Engine Run Time Bin 9: 0.000 s
  SPN 12668, NOx Tracking Engine Activity Lifetime Engine Run Time Bin 10: 0.000 s
  SPN 12669, NOx Tracking Engine Activity Lifetime Engine Run Time Bin 11: 0.000 s
  SPN 12670, NOx Tracking Engine Activity Lifetime Engine Run Time Bin 12: 0.000 s
  SPN 12671, NOx Tracking Engine Activity Lifetime Engine Run Time Bin 13: 0.000 s
  SPN 12672, NOx Tracking Engine Activity Lifetime Engine Run Time Bin 14 : 0.000 s
  SPN 12673, NOx Tracking Engine Activity Lifetime Engine Run Time Bin 15 (NTE BIN): 0.000 s
  SPN 12674, NOx Tracking Engine Activity Lifetime Engine Run Time Bin 16 (Regen Bin) : 0.000 s
  SPN 12714, NOx Tracking Engine Activity Lifetime Engine Run Time Bin 17 (MIL On Bin): 608.000 s

**Comment by ericthomasswenson** [comment]
See #1161

**Comment by ericthomasswenson** [comment]
Documentation change consolidated in #1161
