### ISSUE TITLE
Missing label on GHG Active Tech Tracker

### ISSUE THREAD

**Issue by jacobbosch-cummins** [Equipment-and-Tool-Institute/j1939-84#1159]
"Unknown FA (250)" should be labeled "Mfg Defined Active Technology 1 (250)".

Green House Gas Lifetime Active Technology Tracking from Engine #1 (0): 
  Active Technology:  Predictive Cruise Control (6), Time = 0.000 s, Vehicle Distance = 0.000 m
  **Active Technology:  Unknown FA (250), Time = 0.000 s, Vehicle Distance = 0.000 m**
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Auto Neutral (7), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Mfg Defined Active Technology 4 (247), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Mfg Defined Active Technology 8 (243), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Vehicle Speed Limiting Technology (5), Time = 0.000 s, Vehicle Distance = 0.000 m

**Comment by ericthomasswenson** [comment]
The enumerated values are not provided in J1939DA Parameter Notes
They are captured in Appendix D.



Standardized GHG Active Technology Enumeration | Manufacturer Defined GHG Active Technology Enumeration
-- | --
0, SAE/ISO Reserved | 243, Manufacturer Defined Active Technology 8
1, [Engine Controlled] Waste Heat Recovery | 244, Manufacturer Defined Active Technology 7
2, Cylinder Deactivation | 245, Manufacturer Defined Active Technology 6
3, [Engine Controlled] Active Aerodynamics | 246, Manufacturer Defined Active Technology 5
4, [Engine Participating] Intelligent Control | 247, Manufacturer Defined Active Technology 4
5, [Engine Controlled] Vehicle Speed Limiting Technology | 248, Manufacturer Defined Active Technology 3
6, [Engine Controlled] Predictive Cruise Control | 249, Manufacturer Defined Active Technology 2
7, [Engine Controlled] Auto Neutral | 250 (FAh), Manufacturer Defined Active Technology 1
8-242, SAE/ISO Reserved | 251-255, SAE/ISO Reserved

<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

**Comment by ericthomasswenson** [comment]
Labels appear in 3.1.4

15:42:12.1135 Destination Specific GHGTTA Request to Engine #2 (1)
15:42:12.1160 18EA01F9 [3] 00 FB 00 (TX)
15:42:12.1830 1CFB0001 [16] FA 00 00 00 00 F9 00 00 00 00F8 00 00 00 00 00
Green House Gas Active 100 Hour Active Technology Tracking from Engine #2 (1): 
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0.000 s, Vehicle Distance = 0.000 km

**Comment by ericthomasswenson** [comment]
Enumeration is now displayed in 3.1.4
