### ISSUE TITLE
Incorrect wording on 6.7.2.2.c diagnostic

### ISSUE THREAD

**Issue by jacobbosch-cummins** [Equipment-and-Tool-Institute/j1939-84#1160]
The tool correctly diagnoses a failure on 6.7.2.2.c (MIL was on due to an active emissions related fault), but the wording for the diagnostic is inverted.  The description should indicate the failure is caused by the MIL being on (or flashing).  Diagnostic is correctly described in the J1939-84 document.

Start Test 7.2 - DM23: Emission related previously active DTCs
15:31:59.5799 Destination Specific DM23 Request to Engine #1 (0)
15:31:59.5809 18EA00F9 [3] B5 FD 00 (TX)
15:31:59.5909 18FDB500 [8] 43 FF B9 04 04 01 FF FF
DM23 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: not supported
DTC 1209:4 - Engine Exhaust Pressure 1, Voltage Below Normal, Or Shorted To Low Source - 1 times
FAIL: 6.7.2.2.b - OBD ECU Engine #1 (0) reported a different DTCs from the DM12 DTCs
**FAIL: 6.7.2.2.c - OBD ECU Engine #1 (0) reported MIL off and not flashing**

**Comment by ericthomasswenson** [comment]
Cross check artifact text then tag as bug.

43 in byte one is Mil On and not flashing.
