### ISSUE TITLE
Vehicle composites for DM5, DM26 omit Continuous Monitors

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1163]
Vehicle composites for DM5, DM26 omit Continuous Monitors

14:51:59.8106 18FECE17 [8] 01 00 05 00 00 00 00 00
DM5 from Instrument Cluster #1 (23): OBD Compliance: Not intended to meet OBD II requirements (5), Active Codes: 1, Previously Active Codes: 0
_**Continuously Monitored System Support/Status:
    Comprehensive component    not supported,     complete
    Fuel System                not supported,     complete
    Misfire                    not supported,     complete**_
Non-continuously Monitored System Support/Status:
    A/C system refrigerant     not supported,     complete
    Boost pressure control sys not supported,     complete
    Catalyst                   not supported,     complete
    Cold start aid system      not supported,     complete
    Diesel Particulate Filter  not supported,     complete
    EGR/VVT system             not supported,     complete
    Evaporative system         not supported,     complete
    Exhaust Gas Sensor         not supported,     complete
    Exhaust Gas Sensor heater  not supported,     complete
    Heated catalyst            not supported,     complete
    NMHC converting catalyst   not supported,     complete
    NOx catalyst/adsorber      not supported,     complete
    Secondary air system       not supported,     complete

Vehicle Composite of DM5:
    A/C system refrigerant     not supported,     complete
    Boost pressure control sys     supported, not complete
    Catalyst                   not supported,     complete
    Cold start aid system      not supported,     complete
    Comprehensive component        supported,     complete
    Diesel Particulate Filter      supported, not complete
    EGR/VVT system                 supported, not complete
    Evaporative system         not supported,     complete
    Exhaust Gas Sensor             supported, not complete
    Exhaust Gas Sensor heater      supported, not complete
    Fuel System                    supported, not complete
    Heated catalyst            not supported,     complete
    Misfire                        supported,     complete
    NMHC converting catalyst       supported, not complete
    NOx catalyst/adsorber          supported, not complete
    Secondary air system       not supported,     complete

INFO: 6.1.13.2.a (A6.2.c) - Misfire is supported, complete
WARN: 6.1.13.2.a (A6.3.a) - Non-OBD ECU Transmission #1 (3) responded
WARN: 6.1.13.2.a (A6.3.a) - Non-OBD ECU Instrument Cluster #1 (23) responded
WARN: 6.1.13.2.a (A6.3.a) - Non-OBD ECU Passenger-Operator Climate Control #1 (25) responded
WARN: 6.1.13.2.a (A6.3.a) - Non-OBD ECU Forward Road Image Processor (232) responded

Start Test 1.14 - DM26: Diagnostic readiness 3
14:52:00.4088 Global DM26 Request
14:52:00.4128 18EAFFF9 [3] B8 FD 00 (TX)
14:52:00.4185 18FDB800 [8] 00 00 00 27 E0 1E E0 1E
DM26 from Engine #1 (0): Warm-ups: 0, Time Since Engine Start: 0 seconds
**_Continuously Monitored System Support/Status:
    Comprehensive component        enabled,     complete
    Fuel System                    enabled, not complete
    Misfire                        enabled,     complete_**
Non-continuously Monitored System Support/Status:
    A/C system refrigerant     not enabled,     complete
    Boost pressure control sys     enabled, not complete
    Catalyst                   not enabled,     complete
    Cold start aid system      not enabled,     complete
    Diesel Particulate Filter      enabled, not complete
    EGR/VVT system                 enabled, not complete
    Evaporative system         not enabled,     complete
    Exhaust Gas Sensor             enabled, not complete
    Exhaust Gas Sensor heater      enabled, not complete
    Heated catalyst            not enabled,     complete
    NMHC converting catalyst       enabled, not complete
    NOx catalyst/adsorber          enabled, not complete
    Secondary air system       not enabled,     complete

Vehicle Composite of DM26:
    A/C system refrigerant     not enabled,     complete
    Boost pressure control sys     enabled, not complete
    Catalyst                   not enabled,     complete
    Cold start aid system      not enabled,     complete
    Comprehensive component        enabled,     complete
    Diesel Particulate Filter      enabled, not complete
    EGR/VVT system                 enabled, not complete
    Evaporative system         not enabled,     complete
    Exhaust Gas Sensor             enabled, not complete
    Exhaust Gas Sensor heater      enabled, not complete
    Fuel System                    enabled, not complete
    Heated catalyst            not enabled,     complete
    Misfire                        enabled,     complete
    NMHC converting catalyst       enabled, not complete
    NOx catalyst/adsorber          enabled, not complete
    Secondary air system       not enabled,     complete

FAIL: 6.1.14.2.a - Engine #1 (0) response for a monitor Misfire in DM5 is reported as supported and is reported as complete/not supported DM26 response

**Comment by ericthomasswenson** [comment]
The individual device displays and vehicle composite displays need to be provided using the same format. Ideally using the same order as the bits are presented in DM5 and DM26. 

Hence the device format is preferred for the vehicle composite. IE.

Continuously Monitored System Support/Status:
Comprehensive component not supported, complete
Fuel System not supported, complete
Misfire not supported, complete
Non-continuously Monitored System Support/Status:
A/C system refrigerant not supported, complete
Boost pressure control sys not supported, complete
Catalyst not supported, complete
Cold start aid system not supported, complete
Diesel Particulate Filter not supported, complete
EGR/VVT system not supported, complete
Evaporative system not supported, complete
Exhaust Gas Sensor not supported, complete
Exhaust Gas Sensor heater not supported, complete
Heated catalyst not supported, complete
NMHC converting catalyst not supported, complete
NOx catalyst/adsorber not supported, complete
Secondary air system not supported, complete

4 of 4 user organizations agree.

**Comment by battjt** [comment]
1. continuous monitors are missing from composite
2. order needs to be consistent

**Comment by ericthomasswenson** [comment]
Actually the vehicle composite sorts the continuous and non continuous in a single list.

This makes for extra review work to match across the disparate orderings
