### ISSUE TITLE
spn should say SPN in DM58 Error message

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1165]
spn should say SPN in DM58 error message.

FAIL: 6.2.10.7.a - NACK not received for DM7 PG from OBD ECU Engine #1 (0) for **_spn_** 102

End Test 2.10 - DM7/DM30: Command Non-continuously Monitored Test/Scaled Test Results

**Comment by battjt** [comment]
Some places the tool uses no spn/SPN/SP label:
"6.2.17.24.c - Value received from " + module.getModuleName() + " for " + spn + "  in part 1 was greater than part 2 value"

Sometimes "SP" :
"6.1.12.4.c - Unused bytes in DM58 are not padded with FFh in the response from " + module.getModuleName() + " for **SP** " + spn

And sometimes "SPN":
"6.11.13.6.d - Lifetime engine hours **SPN** " + spn.getId() + " received is < 600 seconds from " + module.getModuleName()

Preference?

**Comment by ericthomasswenson** [comment]
SPN is the most recent flavor … the pendulum swung back … lower case was the larger issue.

**Comment by ericthomasswenson** [comment]
Complete
