### ISSUE TITLE
Example 2nd Chance Performance 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1166]
BCT PGN 61450 from Engine #1 (0) with SPNs 132
  BCT PGN 61454 from Engine #1 (0) with SPNs 3216, 3217
  BCT PGN 61455 from Engine #1 (0) with SPNs 3226
  BCT PGN 61466 from Engine #1 (0) with SPNs 3464
…

PGN 61454 with Supported SPNs 3216, 3217
14:53:59.4671 18F00E00 [8] 00 FB FF FF FF FF FF FF
Found: AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000 

FAIL: 6.2.17.2.a - SPN 3217 was received as NOT AVAILABLE from Engine #1 (0)
…

14:54:19.7483 Destination Specific for PGN 61454 for SPNs 3217 Request to Engine #1 (0)
14:54:19.7510 18EA00F9 [3] 0E F0 00 (TX)
14:54:19.7550 18E8FF00 [8] 01 FF FF FF F9 0E F0 00
Acknowledgment from Engine #1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 61454
FAIL: 6.2.17.5.b - No DS response for PGN 61454 from Engine #1 (0)
WARN: 6.2.17.5.b - Global request was required for PGN 61454 for broadcast SPNs 3216, 3217

14:54:19.7580 Global PGN 61454 for SPNs 3216, 3217 Request
14:54:19.7621 18EAFFF9 [3] 0E F0 00 (TX)
14:54:19.7668 18F00E00 [8] 00 FB FF FF FF FF FF FF
AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000

**Comment by ericthomasswenson** [comment]
Not sure DS then Global Request for NA data in SPN 3217 is exactly correct … for further review

**Comment by ericthomasswenson** [comment]
Confirmed in 3.1.4. Whereas 3217 was received as NA in the broadcast It should not be requested in for on request data. This creates multiple late responses from the broadcast data. Table A-1 messages in broadcast data section suffice as the outcome for SP3217.

**Comment by ericthomasswenson** [comment]
PGN 61454 with Supported SPNs 3216, 3217
08:09:29.6300 18F00E00 [8] 00 FB FF FF FF FF FF FF
Found: AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000 

FAIL: 6.1.26.2.a - SPN 3217 was received as NOT AVAILABLE from Engine #1 (0)
…

08:09:49.8482 Destination Specific for PGN 61454 for SPNs 3217 Request to Engine #1 (0)
08:09:49.8522 18EA00F9 [3] 0E F0 00 (TX)
08:09:49.8558 18E8FF00 [8] 01 FF FF FF F9 0E F0 00
Acknowledgment from Engine #1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 61454
FAIL: 6.1.26.6.b - No DS response for PGN 61454 from Engine #1 (0)

08:09:49.8586 Global PGN 61454 for SPNs 3216, 3217 Request
08:09:49.8618 18EAFFF9 [3] 0E F0 00 (TX)
08:09:49.8770 18F00E00 [8] 00 FB FF FF FF FF FF FF
AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000 
// SPN 3217 was received as NA in broadcast message… this is an excess query

08:09:49.9276 18F00E00 [8] 00 FB FF FF FF FF FF FF
AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000 


08:09:49.9770 18F00E00 [8] 00 FB FF FF FF FF FF FF
AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000 


08:09:50.0276 18F00E00 [8] 00 FB FF FF FF FF FF FF
AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000 


08:09:50.0770 18F00E00 [8] 00 FB FF FF FF FF FF FF
AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000 


08:09:50.1276 18F00E00 [8] 00 FB FF FF FF FF FF FF
AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000 


08:09:50.1770 18F00E00 [8] 00 FB FF FF FF FF FF FF
AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000 


08:09:50.2276 18F00E00 [8] 00 FB FF FF FF FF FF FF
AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000 


08:09:50.2770 18F00E00 [8] 00 FB FF FF FF FF FF FF
AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000 


08:09:50.3276 18F00E00 [8] 00 FB FF FF FF FF FF FF
AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000 


08:09:50.3770 18F00E00 [8] 00 FB FF FF FF FF FF FF
AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000 


08:09:50.4276 18F00E00 [8] 00 FB FF FF FF FF FF FF
AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000 


08:09:50.4770 18F00E00 [8] 00 FB FF FF FF FF FF FF
AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000 


08:09:50.5276 18F00E00 [8] 00 FB FF FF FF FF FF FF
AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000 


08:09:50.5770 18F00E00 [8] 00 FB FF FF FF FF FF FF
AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Not Available
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: Not available
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000 


TIMING: Late response -  08:09:50.0770 18F00E00 [8] 00 FB FF FF FF FF FF FF
TIMING: Late response -  08:09:50.1276 18F00E00 [8] 00 FB FF FF FF FF FF FF
TIMING: Late response -  08:09:50.1770 18F00E00 [8] 00 FB FF FF FF FF FF FF
TIMING: Late response -  08:09:50.2276 18F00E00 [8] 00 FB FF FF FF FF FF FF
TIMING: Late response -  08:09:50.2770 18F00E00 [8] 00 FB FF FF FF FF FF FF
TIMING: Late response -  08:09:50.3276 18F00E00 [8] 00 FB FF FF FF FF FF FF
TIMING: Late response -  08:09:50.3770 18F00E00 [8] 00 FB FF FF FF FF FF FF
TIMING: Late response -  08:09:50.4276 18F00E00 [8] 00 FB FF FF FF FF FF FF
TIMING: Late response -  08:09:50.4770 18F00E00 [8] 00 FB FF FF FF FF FF FF
TIMING: Late response -  08:09:50.5276 18F00E00 [8] 00 FB FF FF FF FF FF FF
TIMING: Late response -  08:09:50.5770 18F00E00 [8] 00 FB FF FF FF FF FF FF
// These messages are excess as F00E should not have been in the on request list in the first place

**Comment by ericthomasswenson** [comment]
6.1.26.5 Actions3
a.​DS messages to the ECU(s) that indicated support in DM24 for upon request SPs and broadcast SPs that were not observed in step 1 from both lists. [_**SPs that were observed as ‘not available’ in broadcast data from a particular ECU need not be queried**_ — the data evaluation from the broadcast data suffices]. Where a PG from a particular OBD ECU contains more than one SP (to be evaluated), that PG need only be queried one time].
b.​If no response/no valid data for any SP requested in 6.1.25.3.a, send global message to request that SP(s).
// Splitting the setup (Actions1) from the monitoring (Actions2) kept the test steps from 6.1.26.1 to 6.1.26.6.
// Checking for omitted broadcast SPs in a. is the “second chance concept”.  Such SPs failed 6.1.26.4.a.
// This (a.) provides evidence of support for undesirable circumstances (e.g. two OBD ECUs providing the same PG).
// Both supported and unsupported SPs in Table A-1 are queried (in a.) to check for omitted DM24 support bit settings.
// These changes increase the value of tests on development engines, by being more thorough with DM24 support bits.

**Comment by ericthomasswenson** [comment]
[SecondChanceClarification3.docx](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/9398317/SecondChanceClarification3.docx)

**Comment by ericthomasswenson** [comment]
Table A-1 additions not yet displayed.

Messages from Table A-1 not expected from DM24:           // This is the Second (consolidated) list
 Req PGN 40448 from Engine #1 (0) less SPNs 4106             // Show unsupported SPs only here
 Req PGN 40960 from Engine #1 (0) less SPNs 4127, 4130           // Show a PG in both lists
 BCT PGN 61444 from Engine #1 (0) less SPNs 190, 512, 513, 2432   // But query it once,
 BCT PGN 61450 from Engine #1 (0) less SPNs 132                   // if it is not broadcast.
 BCT PGN 61454 from Engine #1 (0) less SPNs 3216, 3217
 BCT PGN 64908 from Engine #1 (0) less SPNs 3610
 BCT PGN 64916 from Engine #1 (0) less SPNs 27, 5444
 Req PGN 64920 from Engine #1 (0) less SPNs 5454
 BCT PGN 64923 from Engine #1 (0) less SPNs 3516
 Req PGN 65214 from Engine #1 (0) less SPNs 166
…
 
Step 6.1.26.2.a - Reading bus for 20 seconds

**Comment by ericthomasswenson** [comment]
White space requests not yet implemented 

**_FAIL: 6.1.26.4.a SPN 12345, not observed in 20 seconds. // Let’s put the missing broadcast SPs here_**
 
**_Step 6.1.26.2.c Observed Broadcast Periods                    // Add heading for observed periods_**
 
PGN 61443 from Engine #1 (0)
13:41:28.0015 0CF00300 [8] D1 00 00 FF FF FF 65 FF
13:41:28.0512 0CF00300 [8] D1 00 00 FF FF FF 65 FF
13:41:28.1015 0CF00300 [8] D1 00 00 FF FF FF 65 FF
 
…

PGN 61454 from Engine #1 (0)
13:41:28.0050 18F00E00 [8] 00 FB FE FA FF FF FF FF
13:41:28.0532 18F00E00 [8] 00 FB FE FA FF FF FF FF
13:41:28.1050 18F00E00 [8] 00 FB FE FA FF FF FF FF …
 
**_**Step 6.1.26.5 Destination Specific Requests                  // Add heading for DS Queries**_**
 
13:41:48.2142 DS Request for PGN 40448 to Engine #1 (0) for SPNs 4106
13:41:48.2168 18EA00F9 [3] 00 9E 00 (TX)
13:41:48.2224 189EF900 [8] 00 00 00 00 00 FF FF FF
DM29 from Engine #1 (0):
Emission-Related Pending DTC Count                               0
All Pending DTC Count                                            0
Emission-Related MIL-On DTC Count                                0
Emission-Related Previously MIL-On DTC Count                     0
Emission-Related Permanent DTC Count                             0

**Comment by battjt** [comment]
6.1.26 has been rewritten.  Retest.
