### ISSUE TITLE
Tools Temp Folder ASCII Log Isn't Able to be Opened in CANalyzer Without Modification

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1169]
**The ASCII log file stored in the temp directory isn't able to be opened in CANalyzer without adding the following line to the start of the file:**
base hex  timestamps absolute

**To look like this:**
base hex  timestamps absolute
0.001001 1  0CF00203x Rx d 8 CC 00 00 FF FF 00 00 FF
0.001001 1  0CF00400x Rx d 8 00 7D 7D 00 00 00 F0 7D
0.001501 1  0CF00300x Rx d 8 D1 00 00 FF FF 0C 00 FF
0.002501 1  18F00E3Dx Rx d 8 00 FB 00 FB FF FF FF FF
0.003501 1  18EAFFF9x Tx d 3 EC FE 00
0.011001 1  0CF00203x Rx d 8 CC 00 00 FF FF 00 00 FF

**Comment by ericthomasswenson** [comment]
Joe Batt to add missing header for next release.

**Comment by ericthomasswenson** [comment]
Jacob, loaded an .ASC log in CANALYZER.
