### ISSUE TITLE
SPN 12704 Resolution is 1kW-hr

### ISSUE THREAD

**Issue by anthonyhbest** [Equipment-and-Tool-Institute/j1939-84#1170]
The resolution of SPN 12704 is 1 kW-hr per the J1939DA:  
![image](https://user-images.githubusercontent.com/94923793/180571074-40855f4b-f23d-40a7-abe5-e3681755a74b.png)

As shown in the 6.11.13.8 Fail criteria below **section g**, the test is looking for an increase of 0.5 kW-hr to occur.  
![image](https://user-images.githubusercontent.com/94923793/180570842-e96aec36-621c-418b-b978-39866abd48f8.png)

The DM11 in the end of Part 9 will reset SPN 12704 to 0 kW-hr and the engine will only have ~ 10 minutes of base idle and 5 minutes of idle >1150 rpm by the time SPN 12704 is checked in part 11.  While it may be possible on high horsepower engines to produce 1 kW-hr in those conditions, a low horsepower engine will not produce 1 kW-hr.

**Comment by ericthomasswenson** [comment]
EoE proposed corrections are shown in #1171
