### ISSUE TITLE
Resolve conflict between 6.11.13.4.d and .g

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1171]
Resolve conflict between 6.11.13.4.d and .g

As written .d and .g both apply to active 100 Hr NOx Binning Arrays.

This would result in two messages for active array elements.

Qualify .d as stored 100 Hr array elements only.

**Comment by ericthomasswenson** [comment]
6.11.13.4	Fail/warn criteria2  for MY2022+ Diesel Engines

a. For all MY2024+ Diesel engines, Fail each PG query where no response was received.  
b. For all MY2022-23 Diesel engines, Warn each PG query where no response was received.
c. Fail each PG query where any bin value received is greater than FAFFh. (Use FAFFFFFFh for NOx values).  
d. Fail all values in **_100-hr stored arrays_** where the corresponding value received in part 2 is greater than the part 11 value. (Where supported)
e. Info if active 100 hrs engine hours bin 1 SP 12389 < 60 seconds (where supported)
f. Info, if stored 100 hrs engine hours > 0 seconds (where supported)
g. Warn for all active 100 hr bin 3 through bin 16 values that are less than their respective values for bins 3 through 16 in part 2. (Where supported)
h. Warn for all active 100 hr vehicle distance bins  => 0.25 km. (Where supported).
i. Info for active 100 hr EOE bin 1 SPN 12355 <= **_1.0_** kW-hr or bin 2 SPN 12356 <= **_1.0_** kW-hr (Where supported).
j. Info for active 100hr engine out NOx bin 1 SPN 12338 = 0 or bin 2 SPN 12339  = 0. (Where supported).
k. Info for active 100hr system out NOx bin 1 SPN 12321 = 0 or bin 2 SPN 12322 = 0. (Where supported).

6.11.13.5	Actions3 for MY2022+ Diesel Engines

a. DS request messages to ECU that indicated support in DM24 for upon request SP 12730 (GHG Tracking Engine Run Time) for PG 64252 GHG Tracking Lifetime Array Data.

6.11.13.6	Fail criteria1  for MY2022+ Diesel Engines

a. For all MY2022+ engines, Fail PG query where no response was received.  
b. Fail PG query where any bin value received is greater than FAFFFFFFh and less than FFFFFFFFh.
c. Fail all values where the corresponding value received in part 2 is greater than the part 11 value. 
d. Fail if lifetime engine hours SPN 12730 < 600 seconds. (Where supported).

6.11.13.7	Actions4 for MY2022+ Diesel Engines

a. DS request message to ECU that indicated support in DM24 for upon request SP 12730 GHG Tracking Engine Run Time for each 100hr GHG tracking PG 

PG	PG Label	PG Acronym 
64254	GHG Tracking Active 100 Hour Array Data	 GHGTA
64253	GHG Tracking Stored 100 Hour Array Data	GHGTS

b. List data received in a table using lifetime, stored 100 hr, active 100hr for columns, and categories for rows.

6.11.13.8	Fail criteria4 for MY2022+ Diesel Engines

a. For all MY2024+ engines, Fail each PG query where no response was received.  
b. For all MY2022-23 engines, Warn each PG query where no response was received.
c. Fail each PG query where any bin value received is greater than FAFFh and less than FFFFh (Use FAFFFFFFh and less than FFFFFFFFh for 32-bit SPNs 12705 and 12720).
d. Fail all values where the corresponding value received in part 2 is greater than the part 11 value. (Where supported)
e. Fail if active 100 hrs engine hours SPN 12700 < 600 seconds. (where supported)
f. Warn for all active 100 hr vehicle distance SPN 12701 => 0.25 km. (Where supported).
g. Warn for active 100 hr EOE SPN 12704 <= **_1.0_** kW-hr (where supported)

**Comment by anthonyhbest** [comment]
As stated in #1170 there are engines that will not produce 1.0 kW-hr in 6.11.13.8.g.  For example, a 265kW (355HP) engine will only produce ~0.5 kW-hr of energy between the code clear in part 9 and the EoE check in part 11.

**Comment by ericthomasswenson** [comment]
Eric,
We will accept the change of 11.13.8.g from “Warn for active 100 hr EOE SPN 12704 <= 1.0 kW-hr (where supported)” to “**_Info_**, if active 100 hr EOE SPN 12704 **_>_** 1 kW-hr”.
 
Your back of an envelope calculation was very close to data I collected on a test truck using our lowest engine rating.  I produced 0.87kW-hr between the code clear in part 9 and the check in part 11.  (With defroster on and HVAC fan speed on high)

**Comment by anthonyhbest** [comment]
Still seeing a FAIL in parts **1.26.12.b, 2.17.12.b, 2.17.14.c, 11.13.6.b, 11.13.8.c** related to SPNs 12742, 12712 and 12727 (Lifetime/Active/Stored Stop-Start Technology Run Time) Bin values.  With this having a BRL label I expected those issues to be resolved.  These would have been captured by issue #1155.

**Comment by battjt** [comment]
What was the expected outcome?  Do you have a report showing what the response was?  We can include your data in the unit tests if we have it.

**Comment by anthonyhbest** [comment]
My understanding of the discussion of issue #1155 was that our response to these SPNs would be accepted.  Here is an example of the failure for SPN 12742, if you need a full log file I can email one.  

![image](https://user-images.githubusercontent.com/94923793/213236525-31408015-a468-4bed-9c42-5f91d5d48b0b.png)

**Comment by battjt** [comment]
We have improved the error message to better understand why the failure is being reported.  I suspect it is that FF 00 00 00 is being reported for N/A, but the tool is testing for FF FF FF FF.

**Comment by anthonyhbest** [comment]
You are correct Joe, our software is reporting either FF 00 or FF 00 00 00 for those SPNs.  According to J1939-71, shown below, our software is responding with a valid 'Not Available' for these SPNs.  

@ericthomasswenson, are you saying 'Not Available' is not an acceptable response for these SPNs?

![image](https://user-images.githubusercontent.com/94923793/218154463-87bba256-a10d-4338-a560-4eae7d6546fb.png)

**Comment by ericthomasswenson** [comment]
Interpretation of the transport packet is that FFh was padded for 3 bytes and FF000000h was sent as the value. Send FFFFFFFFh (or FFFFh) as the long standing practice for SAE J1939-71 Table 1.  @anthonyhbest

**Comment by ericthomasswenson** [comment]
Joe, is this ready to close?

**Comment by battjt** [comment]
yes.

**Comment by ericthomasswenson** [comment]
Won’t fix FF00h et. al. As acceptable representations of ‘Not Available’
