### ISSUE TITLE
Implement A.6 Changes in Task 5 artifact

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1174]
Implement A.6 Changes in Task 5 artifact In Tables A-6-1 and A-6-2

**Comment by ericthomasswenson** [comment]
Document completion issues were closed. Use this issue to track implementation.

**Comment by battjt** [comment]
Pending documentation clarification for misfire.

**Comment by battjt** [comment]
This needs cleaned up:
```shall = 1 after code clear, warn if 0
fail if 0, for 2013-2018MY engines
warn if 0, for 2019MY+ engines
info if 0, after engine runs.
```

**Comment by battjt** [comment]
Bob reports warn and info were corrected, but further clarification needed.

**Comment by ericthomasswenson** [comment]
DM5/DM26 bit performance appears improved. Bob and Eric will dig deeper.

**Comment by ericthomasswenson** [comment]
These additional items are exceptions from the default expectation of =1
> This needs cleaned up:
> 
> ```
> fail if 0, for 2013-2018MY engines
> warn if 0, for 2019MY+ engines
> info if 0, after engine runs.
> ```
