### ISSUE TITLE
Incorrect WARN issued by v3.1.4 of test tool for Part 6.2.17.10.d

### ISSUE THREAD

**Issue by anthonyhbest** [Equipment-and-Tool-Institute/j1939-84#1177]
Tool is incorrectly implementing the warn criteria for part 6.2.17.10.d.  The draft of the specification says: 
![image](https://user-images.githubusercontent.com/94923793/184712598-922e525a-0243-4926-a73e-cb827b3ffd5c.png)

But the tool is issuing a WARN for all values checked as part of 6.2.17.10.d that are greater than 0, in this case, I had a total of 95 incorrect WARNs on this test.  Example below:
![image](https://user-images.githubusercontent.com/94923793/184712816-3077c75e-bc3b-495a-8ff5-3645e5bb58eb.png)

Part 1 Bin 1 Value:
![image](https://user-images.githubusercontent.com/94923793/184719716-8ec5e48d-ebb8-4788-845d-05640987ba21.png)
Part 2 Bin 1 Value:
![image](https://user-images.githubusercontent.com/94923793/184719870-1132e054-ad7c-4629-b02d-710547405fa7.png)

**Comment by ericthomasswenson** [comment]
Please post the Part 1 Bin 1 value too, Anthony, to fully establish the expected pass.

**Comment by anthonyhbest** [comment]
Attached are excerpts from the test log showing Bin 1 values, Bin 2 values and the associated WARN messages from the tool:


[Issue1177_Part6-2-17-10-d_WARN.txt](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/9383974/Issue1177_Part6-2-17-10-d_WARN.txt)

**Comment by battjt** [comment]
Known bug listed as deficiency in 3.1.4 and corrected oin 3.1.5.

**Comment by ericthomasswenson** [comment]
Email Response: Known bug listed as deficiency in 3.1.4 and corrected in 3.1.5.

**Comment by battjt** [comment]
Sorry.  I incorrectly added that comment, then removed it.  I don't know how to retract the email.

**Comment by ericthomasswenson** [comment]
Errant comments deleted.

**Comment by ericthomasswenson** [comment]
In progress
