### ISSUE TITLE
NOx Binning / GHG Tracking Is a vehicle requirement, not an every device requirement 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1178]
…
  D F     2  SPN 8620 - Engine Exhaust Manifold Absolute Pressure 2
  **_D       4  SPN 12675 - NOx Tracking Engine Activity Lifetime Fuel Consumption Bin 1 (Total)
  D       1  SPN 12691 - GHG Tracking Lifetime Active Technology Index
  D       4  SPN 12730 - GHG Tracking Lifetime Engine Run Time_**
  D       2  SPN 12750 - AFT 1 SCR 1 Engine Exhaust NOx Mass Flow
  D       2  SPN 12751 - AFT 1 SCR 1 Tailpipe NOx Mass Flow
      T   0  SPN 521075 - Manufacturer Assignable SPN

  D F     2  SPN 8162 - AFT 1 DOC Intake to DPF Outlet Delta Pressure
    F     2  SPN 8619 - Engine Exhaust Manifold Absolute Pressure 1
    F     2  SPN 8620 - Engine Exhaust Manifold Absolute Pressure 2
      T   0  SPN 520348 - Manufacturer Assignable SPN
      T   0  SPN 520349 - Manufacturer Assignable SPN
      T   0  SPN 520353 - Manufacturer Assignable SPN
      T   0  SPN 520355 - Manufacturer Assignable SPN
      T   0  SPN 520372 - Manufacturer Assignable SPN
]

Required Data Stream SPNs are not supported. SPNs: 166
Required Data Stream SPNs are not supported. SPNs: 12748
Required Data Stream SPNs are not supported. SPNs: 3516, 3518, 7346
FAIL: 6.1.4.2.b - N.2 One or more SPNs for data stream is not supported
**_FAIL: 6.1.4.2.d - SP 12675 is not included in DM24 response from Engine #1 (0)
FAIL: 6.1.4.2.e - SP 12730 is not included in DM24 response from Engine #1 (0)
WARN: 6.1.4.2.f - SP 12691 is not included in DM24 response from Engine #1 (0)
FAIL: 6.1.4.2.d - SP 12675 is not included in DM24 response from Exhaust Emission Controller (61)
FAIL: 6.1.4.2.e - SP 12730 is not included in DM24 response from Exhaust Emission Controller (61)
WARN: 6.1.4.2.f - SP 12691 is not included in DM24 response from Exhaust Emission Controller (61)_**

// NOx Binning / GHG Tracking Is a vehicle requirement, not an every device requirement

**Comment by naroner** [comment]
This was already reported in #1111

**Comment by ericthomasswenson** [comment]
Improve to say “one of the DM24” for NOX binning lead SPs.

**Comment by ericthomasswenson** [comment]
Updated Text

6.1.4.2	Fail Criteria 
a.		Fail if retry was required to obtain the DM24 response. 
b.	Fail the expected SPs for data stream support, that are not supported by the OBD ECUs DM24 responses as described by Table A-1 column “Fail if SPN not supported in DM24”. Fail if one or more minimum expected SPs for data stream not supported per Section A.1, Minimum Support Table, from the OBD ECU(s).  
**_Note: For distributed systems, mandated SPNs must appear in at least one DM21 response, most commonly from the SA that provides the data stream content. The SA that supports DM25, may list freeze frame SPNs that are supported by other SAs for data stream content._** 
c.	Fail if one or more minimum expected SPs for freeze frame not supported per Section A.2, Criteria for Freeze Frame Evaluation, from the OBD ECU(s).
d. For MY2022+ diesel engines, Fail if SP 12675 (NOx Tracking Engine Activity Lifetime Fuel Consumption Bin 1 - Total) is not included **_in at least one_** DM24 response.
e. For all MY2022+ engines, Fail if SP 12730 (GHG Tracking Engine Run Time) is not included **_in at least one_** DM24 response.
f. For all MY2022+ engines, **_Warn_** if SP 12691 (GHG Tracking Lifetime Active Technology Index) is not included **_in at least one_** DM24 response.
g. For all MY2022+ HEV and BEV drives, Fail if SP 12797 (Hybrid Lifetime Propulsion System Active Time), is not included **_in at least one_**  DM24 response. (SP 12797 is Lifetime EV Tracking Byte 1 SP)
h. For all MY2022+ Plug-in HEV drives, Fail if SP 12783 (Hybrid Lifetime Distance Traveled in Charge Depleting Operation with Engine off), is not included **_in at least one_** DM24 response.
6.1.4.3	Warn/Info Criteria
a.	Warn/Info as described by Table A-1 column “Warn/Info if SP not supported in DM24”
b.	Warn/Info as described by Table A-1 column “Warn/Info if more than 1 SP supported” in DM24
