### ISSUE TITLE
6.1.13.2.a 6.1.13.2 Duplicate Warning Exh. Gas Sensor Support

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1179]
Another 6.1.13 Table A-6 duplication example

WARN: 6.1.13.2.a (A6.2.d) - Exhaust Gas Sensor is supported by more than one OBD ECU
WARN: 6.1.13.2.d - Required monitor Exhaust Gas Sensor is supported by more than one OBD ECU

Also in 6.2.2.2

WARN: 6.2.2.2.a (A6.2.d) - Exhaust Gas Sensor is supported by more than one OBD ECU
WARN: 6.2.2.2.c - Required monitor Exhaust Gas Sensor is supported by more than one OBD ECU

**Comment by ericthomasswenson** [comment]
See #1151  “Delete d. Per #1151 “ Should work for Exhaust Gas Sensor too

**Comment by battjt** [comment]
6.2.2.2.c still exists in the document.

**Comment by ericthomasswenson** [comment]
6.1.13.2.d and 6.2.2.2.c Formatted in strikethrough and commented.
