### ISSUE TITLE
Excess categories in Active Technology Display

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1180]
Excess categories in Active Technology Display

 | SAE/ISO Reserved            
 | Waste Heat Recovery       

are excess.  NAs are incorrect.

15:42:12.0105 Destination Specific GHGTTL Request to Engine #2 (1)
15:42:12.0135 18EA01F9 [3] 01 FB 00 (TX)
15:42:12.1030 1CFB0101 [28] FA 2A 00 00 00 00 00 00 00F9 00 00 00 00 00 00 00 00 F8 19 01 00 00 00 00 00 00 00
Green House Gas Lifetime Active Technology Tracking from Engine #2 (1): 
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 42.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 281.000 s, Vehicle Distance = 0.000 m

15:42:12.1135 Destination Specific GHGTTA Request to Engine #2 (1)
15:42:12.1160 18EA01F9 [3] 00 FB 00 (TX)
15:42:12.1830 1CFB0001 [16] FA 00 00 00 00 F9 00 00 00 00 F8 00 00 00 00 00
Green House Gas Active 100 Hour Active Technology Tracking from Engine #2 (1): 
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0.000 s, Vehicle Distance = 0.000 km

15:42:12.1845 Destination Specific GHGTTS Request to Engine #2 (1)
15:42:12.1880 18EA01F9 [3] FF FA 00 (TX)
15:42:12.2630 1CFAFF01 [16] FA 00 00 00 00 F9 00 00 00 00 F8 00 00 00 00 00
Green House Gas Stored 100 Hour Active Technology Tracking from Engine #2 (1): 
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0.000 s, Vehicle Distance = 0.000 km

15:42:12.2650 GHG Active Technology Arrays from Engine #2 (1)
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|
|                                     |    Active   |    Active   |    Stored   |    Stored   |             |             |
| Index                               |   100 Hour  |   100 Hour  |   100 Hour  |   100 Hour  |   Lifetime  |   Lifetime  |
| Description                         |    Time, m  |   Dist, km  |    Time, m  |   Dist, km  |    Time, m  |   Dist, km  |
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|
 | SAE/ISO Reserved                    |         N/A |         N/A |         N/A |         N/A |  69,625,446 |           0 |
 | Waste Heat Recovery                 |         N/A |         N/A |         N/A |         N/A |           0 |           0 |
| Mfg Defined Active Technology 3     |           0 |           0 |           0 |           0 |         N/A |         N/A |
| Mfg Defined Active Technology 2     |           0 |           0 |           0 |           0 |         N/A |         N/A |
| Mfg Defined Active Technology 1     |           0 |           0 |           0 |           0 |           1 |           0 |
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|

**Comment by battjt** [comment]
May have been fixed in 6.1.26 rewrite.  More investigation required.

**Comment by ericthomasswenson** [comment]
Check in 3.1.5

**Comment by battjt** [comment]
Bug was due to incorrect parsing of lifetime values (4 bytes intsead of 2 bytes like other values)
