### ISSUE TITLE
NA is the correct count for unsupported All Pending (DM27)

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1181]
NA is the correct count for unsupported All Pending (DM27)

Start Test 7.8 - DM27: All Pending DTCs
16:07:20.4290 Global DM27 Request
16:07:20.4320 18EAFFF9 [3] 82 FD 00 (TX)
16:07:21.3770 Timeout - No Response
16:07:21.3795 Destination Specific DM27 Request to Engine #1 (0)
16:07:21.3820 18EA00F9 [3] 82 FD 00 (TX)
16:07:21.3870 18E8FF00 [8] 01 FF FF FF F9 82 FD 00
Acknowledgment from Engine #1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64898
16:07:21.3880 Destination Specific DM27 Request to Engine #2 (1)
16:07:21.3890 18EA01F9 [3] 82 FD 00 (TX)
16:07:21.3960 18E8FF01 [8] 01 FF FF FF F9 82 FD 00
Acknowledgment from Engine #2 (1): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64898
16:07:21.3970 Destination Specific DM27 Request to Exhaust Emission Controller (61)
16:07:21.3990 18EA3DF9 [3] 82 FD 00 (TX)
16:07:21.4110 18E8FF3D [8] 01 FF FF FF F9 82 FD 00
Acknowledgment from Exhaust Emission Controller (61): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64898

End Test 7.8 - DM27: All Pending DTCs

Start Test 7.9 - DM28: Permanent DTCs
16:07:21.4130 Destination Specific DM28 Request to Engine #1 (0)
16:07:21.4150 18EA00F9 [3] 80 FD 00 (TX)
16:07:21.4170 18E8FF00 [8] 01 FF FF FF F9 80 FD 00
Acknowledgment from Engine #1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64896
16:07:21.4170 Destination Specific DM28 Request to Engine #2 (1)
16:07:21.4210 18EA01F9 [3] 80 FD 00 (TX)
16:07:21.4355 18FD8001 [8] 03 FF [00 00 00 00](tel:00 00 00 00) FF FF
DM28 from Engine #2 (1): MIL: off, RSL: off, AWL: off, PL: not supported, No DTCs
16:07:21.4355 Destination Specific DM28 Request to Exhaust Emission Controller (61)
16:07:21.4375 18EA3DF9 [3] 80 FD 00 (TX)
16:07:21.4455 18FD803D [8] 03 FF [00 00 00 00](tel:00 00 00 00) FF FF
DM28 from Exhaust Emission Controller (61): MIL: off, RSL: off, AWL: off, PL: not supported, No DTCs

End Test 7.9 - DM28: Permanent DTCs

Start Test 7.10 - DM29: Regulated DTC counts
16:07:21.4490 Global DM29 Request
16:07:21.4515 18EAFFF9 [3] 00 9E 00 (TX)
16:07:21.4565 189EFF01 [8] 00 FF 00 01 00 FF FF FF
DM29 from Engine #2 (1): 
Emission-Related Pending DTC Count                               0
All Pending DTC Count                                not available
Emission-Related MIL-On DTC Count                                0
Emission-Related Previously MIL-On DTC Count                     1
Emission-Related Permanent DTC Count                             0

16:07:21.4575 18E8FF3D [8] 03 FF FF FF F9 00 9E 00
Acknowledgment from Exhaust Emission Controller (61): Response: Busy, Group Function: 255, Address Acknowledged: 249, PGN Requested: 40448

16:07:22.3790 18EAFFF9 [3] 00 9E 00 (TX)
16:07:22.3840 189EFF3D [8] 00 FF 00 00 00 FF FF FF
DM29 from Exhaust Emission Controller (61): 
Emission-Related Pending DTC Count                               0
All Pending DTC Count                                not available
Emission-Related MIL-On DTC Count                                0
Emission-Related Previously MIL-On DTC Count                     0
Emission-Related Permanent DTC Count                             0

16:07:22.3840 189EFF01 [8] 00 FF 00 01 00 FF FF FF
DM29 from Engine #2 (1): 
Emission-Related Pending DTC Count                               0
All Pending DTC Count                                not available
Emission-Related MIL-On DTC Count                                0
Emission-Related Previously MIL-On DTC Count                     1
Emission-Related Permanent DTC Count                             0

FAIL: 6.7.10.2.a - Engine #2 (1) reported > 0 for all pending
FAIL: 6.7.10.2.a - Exhaust Emission Controller (61) reported > 0 for all pending

End Test 7.10 - DM29: Regulated DTC counts

**Comment by naroner** [comment]
This was already reported in #1092

**Comment by ericthomasswenson** [comment]
Reported again as #1252
