### ISSUE TITLE
Test Results Comparison — Counts Differ

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1182]
Test Results Comparison — Counts Differ

Engine #2 (1) Test Results:
SPN 157 FMI 18 (SLOT 393) Result: Test Not Complete.
SPN 157 FMI 16 (SLOT 393) Result: Test Not Complete.
SPN 157 FMI 10 (SLOT 350) Result: Test Not Complete.
SPN 164 FMI 2 (SLOT 350) Result: Test Not Complete.
SPN 636 FMI 15 (SLOT 365) Result: Test Not Complete.
SPN 651 FMI 4 (SLOT 57) Result: Test Not Complete.
SPN 651 FMI 3 (SLOT 57) Result: Test Not Complete.
SPN 652 FMI 4 (SLOT 57) Result: Test Not Complete.
SPN 652 FMI 3 (SLOT 57) Result: Test Not Complete.
SPN 653 FMI 4 (SLOT 57) Result: Test Not Complete.
——
SPN 653 FMI 3 (SLOT 57) Result: Test Not Complete.
SPN 654 FMI 4 (SLOT 57) Result: Test Not Complete.
SPN 654 FMI 3 (SLOT 57) Result: Test Not Complete.
SPN 655 FMI 4 (SLOT 57) Result: Test Not Complete.
SPN 655 FMI 3 (SLOT 57) Result: Test Not Complete.
SPN 656 FMI 4 (SLOT 57) Result: Test Not Complete.
SPN 656 FMI 3 (SLOT 57) Result: Test Not Complete.
SPN 1322 FMI 11 (SLOT 208) Result: Test Not Complete.
SPN 1322 FMI 12 (SLOT 12) Result: Test Not Complete.
SPN 1322 FMI 9 (SLOT 12) Result: Test Not Complete.
——
SPN 1322 FMI 10 (SLOT 208) Result: Test Not Complete.
SPN 1323 FMI 10 (SLOT 12) Result: Test Not Complete.
SPN 1324 FMI 10 (SLOT 12) Result: Test Not Complete.
SPN 1325 FMI 10 (SLOT 12) Result: Test Not Complete.
SPN 1326 FMI 11 (SLOT 208) Result: Test Not Complete.
SPN 1326 FMI 10 (SLOT 12) Result: Test Not Complete.
SPN 1327 FMI 11 (SLOT 208) Result: Test Not Complete.
SPN 1327 FMI 10 (SLOT 12) Result: Test Not Complete.
SPN 1328 FMI 11 (SLOT 208) Result: Test Not Complete.
SPN 1328 FMI 10 (SLOT 12) Result: Test Not Complete.
——
SPN 1636 FMI 16 (SLOT 416) Result: Test Not Complete.
SPN 2659 FMI 18 (SLOT 318) Result: Test Not Complete.
SPN 2659 FMI 0 (SLOT 318) Result: Test Not Complete.
SPN 3058 FMI 10 (SLOT 32) Result: Test Not Complete.
SPN 3058 FMI 9 (SLOT 394) Result: Test Not Complete.
SPN 3216 FMI 21 (SLOT 236) Result: Test Not Complete.
SPN 3216 FMI 2 (SLOT 360) Result: Test Not Complete.
SPN 3563 FMI 18 (SLOT 318) Result: Test Not Complete.
SPN 3563 FMI 16 (SLOT 318) Result: Test Not Complete.
SPN 3659 FMI 4 (SLOT 57) Result: Test Not Complete.
——
SPN 3659 FMI 3 (SLOT 57) Result: Test Not Complete.
SPN 3660 FMI 4 (SLOT 57) Result: Test Not Complete.
SPN 3660 FMI 3 (SLOT 57) Result: Test Not Complete.
SPN 3661 FMI 4 (SLOT 57) Result: Test Not Complete.
SPN 3661 FMI 3 (SLOT 57) Result: Test Not Complete.
SPN 3662 FMI 4 (SLOT 57) Result: Test Not Complete.
SPN 3662 FMI 3 (SLOT 57) Result: Test Not Complete.
SPN 3663 FMI 4 (SLOT 57) Result: Test Not Complete.
SPN 3663 FMI 3 (SLOT 57) Result: Test Not Complete.
SPN 3664 FMI 4 (SLOT 57) Result: Test Not Complete.
——
SPN 3664 FMI 3 (SLOT 57) Result: Test Not Complete.
SPN 4752 FMI 17 (SLOT 68) Result: Test Not Complete.
SPN 5357 FMI 16 (SLOT 318) Result: Test Not Complete.
SPN 5357 FMI 18 (SLOT 318) Result: Test Not Complete.
SPN 5358 FMI 0 (SLOT 318) Result: Test Not Complete.
SPN 5358 FMI 1 (SLOT 318) Result: Test Not Complete.
SPN 5359 FMI 0 (SLOT 318) Result: Test Not Complete.
SPN 5359 FMI 1 (SLOT 318) Result: Test Not Complete.
SPN 5360 FMI 0 (SLOT 318) Result: Test Not Complete.
SPN 5360 FMI 1 (SLOT 318) Result: Test Not Complete.
——
SPN 5361 FMI 0 (SLOT 318) Result: Test Not Complete.
SPN 5361 FMI 1 (SLOT 318) Result: Test Not Complete.
SPN 5362 FMI 0 (SLOT 318) Result: Test Not Complete.
SPN 5362 FMI 1 (SLOT 318) Result: Test Not Complete.
SPN 5363 FMI 0 (SLOT 318) Result: Test Not Complete.
SPN 5363 FMI 1 (SLOT 318) Result: Test Not Complete.
SPN 521075 FMI 4 (SLOT 57) Result: Test Not Complete.
SPN 521075 FMI 3 (SLOT 57) Result: Test Not Complete.
SPN 521076 FMI 4 (SLOT 57) Result: Test Not Complete.
SPN 521076 FMI 3 (SLOT 57) Result: Test Not Complete.
——
SPN 521077 FMI 4 (SLOT 57) Result: Test Not Complete.
SPN 521077 FMI 3 (SLOT 57) Result: Test Not Complete.
SPN 521078 FMI 4 (SLOT 57) Result: Test Not Complete.
SPN 521078 FMI 3 (SLOT 57) Result: Test Not Complete.
SPN 521079 FMI 4 (SLOT 57) Result: Test Not Complete.
SPN 521079 FMI 3 (SLOT 57) Result: Test Not Complete.
SPN 521080 FMI 4 (SLOT 57) Result: Test Not Complete.
SPN 521080 FMI 3 (SLOT 57) Result: Test Not Complete.
SPN 521173 FMI 20 (SLOT 360) Result: Test Not Complete.
SPN 521173 FMI 21 (SLOT 360) Result: Test Not Complete.
—— 80

Exhaust Emission Controller (61) Test Results:
SPN 1761 FMI 18 (SLOT 30) Result: Test Passed. Min: 7.5, Value: 87.95, Max: N/A %
SPN 3056 FMI 2 (SLOT 32) Result: Test Not Complete.
SPN 3056 FMI 2 (SLOT 32) Result: Test Not Complete.
SPN 3057 FMI 2 (SLOT 32) Result: Test Not Complete.
SPN 3057 FMI 2 (SLOT 32) Result: Test Not Complete.
SPN 3216 FMI 21 (SLOT 295) Result: Test Not Complete.
SPN 3216 FMI 20 (SLOT 295) Result: Test Not Complete.
SPN 3216 FMI 10 (SLOT 12) Result: Test Not Complete.
SPN 3217 FMI 2 (SLOT 32) Result: Test Not Complete.
——
SPN 3217 FMI 2 (SLOT 32) Result: Test Not Complete.
SPN 3223 FMI 7 (SLOT 208) Result: Test Not Complete.
SPN 3226 FMI 21 (SLOT 236) Result: Test Not Complete.
SPN 3226 FMI 20 (SLOT 236) Result: Test Not Complete.
SPN 3226 FMI 10 (SLOT 12) Result: Test Not Complete.
SPN 3227 FMI 2 (SLOT 32) Result: Test Not Complete.
SPN 3227 FMI 2 (SLOT 32) Result: Test Not Complete.
SPN 3238 FMI 2 (SLOT 208) Result: Test Not Complete.
SPN 3516 FMI 1 (SLOT 32) Result: Test Not Complete.
SPN 3556 FMI 0 (SLOT 68) Result: Test Not Complete.
——
SPN 3556 FMI 1 (SLOT 68) Result: Test Not Complete.
SPN 3711 FMI 31 (SLOT 68) Result: Test Not Complete.
SPN 3711 FMI 31 (SLOT 68) Result: Test Not Complete.
SPN 3713 FMI 31 (SLOT 68) Result: Test Not Complete.
SPN 3713 FMI 31 (SLOT 68) Result: Test Not Complete.
SPN 3936 FMI 18 (SLOT 32) Result: Test Not Complete.
SPN 4331 FMI 18 (SLOT 32) Result: Test Not Complete.
SPN 4364 FMI 17 (SLOT 32) Result: Test Not Complete.
SPN 5018 FMI 18 (SLOT 251) Result: Test Not Complete.
SPN 5397 FMI 31 (SLOT 238) Result: Test Not Complete.
——
SPN 5713 FMI 21 (SLOT 295) Result: Test Not Complete.
SPN 5713 FMI 20 (SLOT 295) Result: Test Not Complete.
SPN 5714 FMI 21 (SLOT 295) Result: Test Not Complete.
SPN 5714 FMI 20 (SLOT 295) Result: Test Not Complete.
SPN 5741 FMI 12 (SLOT 403) Result: Test Not Complete.
SPN 5747 FMI 12 (SLOT 290) Result: Test Not Complete.
SPN 520348 FMI 14 (SLOT 295) Result: Test Not Complete.
SPN 520349 FMI 14 (SLOT 318) Result: Test Not Complete.
SPN 520353 FMI 17 (SLOT 68) Result: Test Not Complete.
SPN 520355 FMI 21 (SLOT 295) Result: Test Not Complete.
——
SPN 520355 FMI 20 (SLOT 295) Result: Test Not Complete.
SPN 520372 FMI 16 (SLOT 318) Result: Test Not Complete.
—— 42
FAIL: 6.1.12.2.a (A7.2.a) - Injector Quantity (High Flow) or Injector Timing is missing required Test Result, 1 of: 651:7, 651:16, 5358:16, 1413:16
FAIL: 6.1.12.2.a (A7.2.a) - Injector Quantity (Low Flow) or Injector Timing is missing required Test Result, 1 of: 651:7, 651:18, 5358:18, 1413:18
FAIL: 6.1.12.2.a (A7.2.a) - % of misfire is missing required Test Result, 1 of: 1323:31
FAIL: 6.1.12.2.a (A7.2.a) - % of misfire is missing required Test Result, 1 of: 1324:31
FAIL: 6.1.12.2.a (A7.2.a) - % of misfire is missing required Test Result, 1 of: 1325:31
FAIL: 6.1.12.2.a (A7.2.a) - % of misfire is missing required Test Result, 1 of: 1326:31
FAIL: 6.1.12.2.a (A7.2.a) - Cooler performance is missing required Test Result, 1 of: 4752:1, 4752:18

Start Test 7.15 - DM7/DM30: Command non-continuously monitored test/scaled test results

16:07:23.8430 Sending DM7 for DM30 to Engine #1 (0) for SPN 5846
16:07:23.8465 18E300F9 [8] F6 D6 16 1F FF FF FF FF (TX)
16:07:24.5915 Timeout - No Response
16:07:24.5950 18E300F9 [8] F6 D6 16 1F FF FF FF FF (TX)
16:07:25.3405 Timeout - No Response
16:07:25.3435 18E300F9 [8] F6 D6 16 1F FF FF FF FF (TX)
16:07:26.0890 Timeout - No Response

16:07:26.0925 Sending DM7 for DM30 to Engine #2 (1) for SPN 5846
16:07:26.0945 18E301F9 [8] F6 D6 16 1F FF FF FF FF (TX)
16:07:28.9230 1CA4F901 [960] F6 9D 00 12 89 01 24 71 FF FF 12 5B F6 9D 00 10 89 01 24 71 7D 87 FF FF F6 9D 00 0A 5E 01 41 7D A4 88 FF FF F6 A4 00 02 5E 01 41 7D FF FF 5C 71 F6 7C 02 0F 6D 01 F4 7C 80 7F 00 7B F6 8B 02 04 39 00 0C 00 FF FF 06 00 F6 8B 02 03 39 00 0C 00 14 00 FF FF F6 8C 02 04 39 00 0B 00 FF FF 06 00 F6 8C 02 03 39 00 0B 00 14 00 FF FF F6 8D 02 04 39 00 0B 00 FF FF 06 00 F6 8D 02 03 39 00 0B 00 14 00 FF FF F6 8E 02 04 39 00 0B 00 FF FF 06 00 F6 8E 02 03 39 00 0B 00 14 00 FF FF F6 8F 02 04 39 00 0C 00 FF FF 06 00 F6 8F 02 03 39 00 0C 00 14 00 FF FF F6 90 02 04 39 00 0B 00 FF FF 06 00 F6 90 02 03 39 00 0B 00 14 00 FF FF F6 2A 05 0B D0 00 00 FB FF FF FF FF F6 2A 05 0C 0C 00 00 FB FF FF FF FF F6 2A 05 09 0C 00 00 FB FF FF FF FF F6 2A 05 0A D0 00 00 FB FF FF FF FF F6 2B 05 0A 0C 00 00 FB FF FF FF FF F6 2C 05 0A 0C 00 00 FB FF FF FF FF F6 2D 05 0A 0C 00 00 FB FF FF FF FF F6 2E 05 0B D0 00 00 FB FF FF FF FF F6 2E 05 0A 0C 00 00 FB FF FF FF FF F6 2F 05 0B D0 00 00 FB FF FF FF FF F6 2F 05 0A 0C 00 00 FB FF FF FF FF F6 30 05 0B D0 00 00 FB FF FF FF FF F6 30 05 0A 0C 00 00 FB FF FF FF FF F6 64 06 10 A0 01 00 FB FF FF FF FF F6 63 0A 12 3E 01 00 FB FF FF FF FF F6 63 0A 00 3E 01 00 FB FF FF FF FF F6 F2 0B 0A 20 00 00 FB FF FF FF FF F6 F2 0B 09 8A 01 00 FB FF FF FF FF F6 90 0C 15 EC 00 00 FB FF FF FF FF F6 90 0C 02 68 01 00 FB FF FF FF FF F6 EB 0D 12 3E 01 00 FB FF FF FF FF F6 EB 0D 10 3E 01 00 FB FF FF FF FF F6 4B 0E 04 39 00 21 00 FF FF 0C 00 F6 4B 0E 03 39 00 21 00 32 00 FF FF F6 4C 0E 04 39 00 2C 00 FF FF 0C 00 F6 4C 0E 03 39 00 2C 00 32 00 FF FF F6 4D 0E 04 39 00 1F 00 FF FF 0C 00 F6 4D 0E 03 39 00 1F 00 32 00 FF FF F6 4E 0E 04 39 00 27 00 FF FF 0C 00 F6 4E 0E 03 39 00 27 00 32 00 FF FF F6 4F 0E 04 39 00 1F 00 FF FF 0C 00 F6 4F 0E 03 39 00 1F 00 32 00 FF FF F6 50 0E 04 39 00 2B 00 FF FF 0C 00 F6 50 0E 03 39 00 2B 00 32 00 FF FF F6 90 12 11 44 00 00 FB FF FF FF FF F6 ED 14 10 3E 01 00 FB FF FF FF FF F6 ED 14 12 3E 01 00 FB FF FF FF FF F6 EE 14 00 3E 01 00 FB FF FF FF FF F6 EE 14 01 3E 01 00 FB FF FF FF FF F6 EF 14 00 3E 01 00 FB FF FF FF FF F6 EF 14 01 3E 01 00 FB FF FF FF FF F6 F0 14 00 3E 01 00 FB FF FF FF FF F6 F0 14 01 3E 01 00 FB FF FF FF FF F6 F1 14 00 3E 01 00 FB FF FF FF FF F6 F1 14 01 3E 01 00 FB FF FF FF FF F6 F2 14 00 3E 01 00 FB FF FF FF FF F6 F2 14 01 3E 01 00 FB FF FF FF FF F6 F3 14 00 3E 01 00 FB FF FF FF FF F6 F3 14 01 3E 01 00 FB FF FF FF FF F6 73 F3 E4 39 00 99 19 00 00 06 00 F6 73 F3 E3 39 00 00 00 14 00 00 00 F6 74 F3 E4 39 00 99 19 00 00 06 00 F6 74 F3 E3 39 00 00 00 14 00 00 00 F6 75 F3 E4 39 00 99 19 00 00 06 00 F6 75 F3 E3 39 00 00 00 14 00 00 00 F6 76 F3 E4 39 00 99 19 00 00 06 00 F6 76 F3 E3 39 00 00 00 14 00 00 00 F6 77 F3 E4 39 00 99 19 00 00 06 00 F6 77 F3 E3 39 00 00 00 14 00 00 00 F6 78 F3 E4 39 00 99 19 00 00 06  00 F6 78 F3 E3 39 00 00 00 14 00 00 00 F6 D5 F3 F4 68 01 00 FB FF FF FF FF F6 D5 F3 F5 68 01 00 FB FF FF FF FF
DM30 from 1: [
  SPN 157 FMI 10 (SLOT 350) Result: Test Passed. Min: N/A, Value: 3.25, Max: 149 l/h
  SPN 157 FMI 16 (SLOT 393) Result: Test Passed. Min: N/A, Value: -0.127, Max: 19.998 MPa
  SPN 157 FMI 18 (SLOT 393) Result: Test Passed. Min: -20.001, Value: -0.127, Max: N/A MPa
  SPN 164 FMI 2 (SLOT 350) Result: Test Passed. Min: -149, Value: 3.25, Max: N/A l/h
  SPN 636 FMI 15 (SLOT 365) Result: Test Passed. Min: -4, Value: -0.094, Max: 5 deg
  SPN 651 FMI 3 (SLOT 57) Result: Test Passed. Min: N/A, Value: 0.12, Max: 0.2 ms
  SPN 651 FMI 4 (SLOT 57) Result: Test Passed. Min: 0.06, Value: 0.12, Max: N/A ms
  SPN 652 FMI 3 (SLOT 57) Result: Test Passed. Min: N/A, Value: 0.11, Max: 0.2 ms
  SPN 652 FMI 4 (SLOT 57) Result: Test Passed. Min: 0.06, Value: 0.11, Max: N/A ms
  SPN 653 FMI 3 (SLOT 57) Result: Test Passed. Min: N/A, Value: 0.11, Max: 0.2 ms
——
  SPN 653 FMI 4 (SLOT 57) Result: Test Passed. Min: 0.06, Value: 0.11, Max: N/A ms
  SPN 654 FMI 3 (SLOT 57) Result: Test Passed. Min: N/A, Value: 0.11, Max: 0.2 ms
  SPN 654 FMI 4 (SLOT 57) Result: Test Passed. Min: 0.06, Value: 0.11, Max: N/A ms
  SPN 655 FMI 3 (SLOT 57) Result: Test Passed. Min: N/A, Value: 0.12, Max: 0.2 ms
  SPN 655 FMI 4 (SLOT 57) Result: Test Passed. Min: 0.06, Value: 0.12, Max: N/A ms
  SPN 656 FMI 3 (SLOT 57) Result: Test Passed. Min: N/A, Value: 0.11, Max: 0.2 ms
  SPN 656 FMI 4 (SLOT 57) Result: Test Passed. Min: 0.06, Value: 0.11, Max: N/A ms
  SPN 1322 FMI 9 (SLOT 12) Result: Test Not Complete.
  SPN 1322 FMI 10 (SLOT 208) Result: Test Not Complete.
  SPN 1322 FMI 11 (SLOT 208) Result: Test Not Complete.
——
  SPN 1322 FMI 12 (SLOT 12) Result: Test Not Complete.
  SPN 1323 FMI 10 (SLOT 12) Result: Test Not Complete.
  SPN 1324 FMI 10 (SLOT 12) Result: Test Not Complete.
  SPN 1325 FMI 10 (SLOT 12) Result: Test Not Complete.
  SPN 1326 FMI 10 (SLOT 12) Result: Test Not Complete.
  SPN 1326 FMI 11 (SLOT 208) Result: Test Not Complete.
  SPN 1327 FMI 10 (SLOT 12) Result: Test Not Complete.
  SPN 1327 FMI 11 (SLOT 208) Result: Test Not Complete.
  SPN 1328 FMI 10 (SLOT 12) Result: Test Not Complete.
  SPN 1328 FMI 11 (SLOT 208) Result: Test Not Complete.
——
  SPN 1636 FMI 16 (SLOT 416) Result: Test Not Complete.
  SPN 2659 FMI 0 (SLOT 318) Result: Test Not Complete.
  SPN 2659 FMI 18 (SLOT 318) Result: Test Not Complete.
  SPN 3058 FMI 9 (SLOT 394) Result: Test Not Complete.
  SPN 3058 FMI 10 (SLOT 32) Result: Test Not Complete.
  SPN 3216 FMI 2 (SLOT 360) Result: Test Not Complete.
  SPN 3216 FMI 21 (SLOT 236) Result: Test Not Complete.
  SPN 3563 FMI 16 (SLOT 318) Result: Test Not Complete.
  SPN 3563 FMI 18 (SLOT 318) Result: Test Not Complete.
  SPN 3659 FMI 3 (SLOT 57) Result: Test Passed. Min: N/A, Value: 0.33, Max: 0.5 ms
——
  SPN 3659 FMI 4 (SLOT 57) Result: Test Passed. Min: 0.12, Value: 0.33, Max: N/A ms
  SPN 3660 FMI 3 (SLOT 57) Result: Test Passed. Min: N/A, Value: 0.44, Max: 0.5 ms
  SPN 3660 FMI 4 (SLOT 57) Result: Test Passed. Min: 0.12, Value: 0.44, Max: N/A ms
  SPN 3661 FMI 3 (SLOT 57) Result: Test Passed. Min: N/A, Value: 0.31, Max: 0.5 ms
  SPN 3661 FMI 4 (SLOT 57) Result: Test Passed. Min: 0.12, Value: 0.31, Max: N/A ms
  SPN 3662 FMI 3 (SLOT 57) Result: Test Passed. Min: N/A, Value: 0.39, Max: 0.5 ms
  SPN 3662 FMI 4 (SLOT 57) Result: Test Passed. Min: 0.12, Value: 0.39, Max: N/A ms
  SPN 3663 FMI 3 (SLOT 57) Result: Test Passed. Min: N/A, Value: 0.31, Max: 0.5 ms
  SPN 3663 FMI 4 (SLOT 57) Result: Test Passed. Min: 0.12, Value: 0.31, Max: N/A ms
  SPN 3664 FMI 3 (SLOT 57) Result: Test Passed. Min: N/A, Value: 0.43, Max: 0.5 ms
——
  SPN 3664 FMI 4 (SLOT 57) Result: Test Passed. Min: 0.12, Value: 0.43, Max: N/A ms
  SPN 4752 FMI 17 (SLOT 68) Result: Test Not Complete.
  SPN 5357 FMI 16 (SLOT 318) Result: Test Not Complete.
  SPN 5357 FMI 18 (SLOT 318) Result: Test Not Complete.
  SPN 5358 FMI 0 (SLOT 318) Result: Test Not Complete.
  SPN 5358 FMI 1 (SLOT 318) Result: Test Not Complete.
  SPN 5359 FMI 0 (SLOT 318) Result: Test Not Complete.
  SPN 5359 FMI 1 (SLOT 318) Result: Test Not Complete.
  SPN 5360 FMI 0 (SLOT 318) Result: Test Not Complete.
  SPN 5360 FMI 1 (SLOT 318) Result: Test Not Complete.
——
  SPN 5361 FMI 0 (SLOT 318) Result: Test Not Complete.
  SPN 5361 FMI 1 (SLOT 318) Result: Test Not Complete.
  SPN 5362 FMI 0 (SLOT 318) Result: Test Not Complete.
  SPN 5362 FMI 1 (SLOT 318) Result: Test Not Complete.
  SPN 5363 FMI 0 (SLOT 318) Result: Test Not Complete.
  SPN 5363 FMI 1 (SLOT 318) Result: Test Not Complete.
  SPN 521075 FMI 3 (SLOT 57) Result: Test Passed. Min: 0, Value: 0, Max: 0.2 ms
  SPN 521075 FMI 4 (SLOT 57) Result: Test Failed. Min: 0.06, Value: 65.53, Max: 0 ms
  SPN 521076 FMI 3 (SLOT 57) Result: Test Passed. Min: 0, Value: 0, Max: 0.2 ms
  SPN 521076 FMI 4 (SLOT 57) Result: Test Failed. Min: 0.06, Value: 65.53, Max: 0 ms
——
  SPN 521077 FMI 3 (SLOT 57) Result: Test Passed. Min: 0, Value: 0, Max: 0.2 ms
  SPN 521077 FMI 4 (SLOT 57) Result: Test Failed. Min: 0.06, Value: 65.53, Max: 0 ms
  SPN 521078 FMI 3 (SLOT 57) Result: Test Passed. Min: 0, Value: 0, Max: 0.2 ms
  SPN 521078 FMI 4 (SLOT 57) Result: Test Failed. Min: 0.06, Value: 65.53, Max: 0 ms
  SPN 521079 FMI 3 (SLOT 57) Result: Test Passed. Min: 0, Value: 0, Max: 0.2 ms
  SPN 521079 FMI 4 (SLOT 57) Result: Test Failed. Min: 0.06, Value: 65.53, Max: 0 ms
  SPN 521080 FMI 3 (SLOT 57) Result: Test Passed. Min: 0, Value: 0, Max: 0.2 ms
  SPN 521080 FMI 4 (SLOT 57) Result: Test Failed. Min: 0.06, Value: 65.53, Max: 0 ms
  SPN 521173 FMI 20 (SLOT 360) Result: Test Not Complete.
  SPN 521173 FMI 21 (SLOT 360) Result: Test Not Complete.
—— 80
]

16:07:28.9370 Sending DM7 for DM30 to Exhaust Emission Controller (61) for SPN 5846
16:07:28.9390 18E33DF9 [8] F6 D6 16 1F FF FF FF FF (TX)
16:07:29.5420 1CA4F93D [420] F6 9A 0C 15 EC 00 00 FB FF FF FF FF F6 9A 0C 14 EC 00 00 FB FF FF FF FF F6 F0 0B [02 20 00 00](tel:02 20 00 00) FB FF FF FF FF F6 F1 0B [02 20 00 00](tel:02 20 00 00) FB FF FF FF FF F6 E4 0D 00 44 00 00 FB FF FF FF FF F6 E4 0D 01 44 00 00 FB FF FF FF FF F6 15 15 1F EE 00 00 FB FF FF FF FF F6 60 0F [12 20 00 00](tel:12 20 00 00) FB FF FF FF FF F6 7F 0E 1F 44 00 00 FB FF FF FF FF F6 81 0E 1F 44 00 00 FB FF FF FF FF F6 9A 13 12 FB 00 00 FB FF FF FF FF F6 E1 06 12 1E 00 6C 89 FF FF B8 0B F6 97 0C 07 D0 00 00 FB FF FF FF FF F6 A6 0C 02 D0 00 00 FB FF FF FF FF F6 EB [10 12 20 00 00](tel:10 12 20 00 00) FB FF FF FF FF F6 BC 0D 01 [20 00 30 75](tel:20 00 30 75) FF FF 00 00 F6 90 0C [15 27 01 00](tel:15 27 01 00) FB FF FF FF FF F6 90 0C [14 27 01 00](tel:14 27 01 00) FB FF FF FF FF F6 A3 F0 F5 27 01 00 FB FF FF FF FF F6 A3 F0 F4 27 01 00 FB FF FF FF FF F6 91 0C [02 20 00 00](tel:02 20 00 00) FB FF FF FF FF F6 9B 0C [02 20 00 00](tel:02 20 00 00) FB FF FF FF FF F6 9A 0C 0A 0C 00 00 FB FF FF FF FF F6 90 0C 0A 0C 00 00 FB FF FF FF FF F6 B4 F0 F0 3E 01 00 FB FF FF FF FF F6 73 16 0C 22 01 00 FB FF FF FF FF F6 9D F0 EE 3E 01 00 FB FF FF FF FF F6 6D 16 0C 93 01 00 FB FF FF FF FF F6 A1 F0 F1 44 00 00 FB FF FF FF FF F6 9C F0 EE 27 01 00 FB FF FF FF FF F6 0C [11 11 20 00 00](tel:11 11 20 00 00) FB FF FF FF FF F6 [52 16 15 27 01 00](tel:52 16 15 27 01 00) FB FF FF FF FF F6 [52 16 14 27 01 00](tel:52 16 14 27 01 00) FB FF FF FF FF F6 [51 16 15 27 01 00](tel:51 16 15 27 01 00) FB FF FF FF FF F6 [51 16 14 27 01 00](tel:51 16 14 27 01 00) FB FF FF FF FF
DM30 from 61: [
  SPN 1761 FMI 18 (SLOT 30) Result: Test Passed. Min: 7.5, Value: 87.95, Max: N/A %
  SPN 3056 FMI 2 (SLOT 32) Result: Test Not Complete.
  SPN 3057 FMI 2 (SLOT 32) Result: Test Not Complete.
  SPN 3216 FMI 10 (SLOT 12) Result: Test Not Complete.
  SPN 3216 FMI 20 (SLOT 295) Result: Test Not Complete.
  SPN 3216 FMI 21 (SLOT 295) Result: Test Not Complete.
  SPN 3217 FMI 2 (SLOT 32) Result: Test Not Complete.
  SPN 3223 FMI 7 (SLOT 208) Result: Test Not Complete.
  SPN 3226 FMI 10 (SLOT 12) Result: Test Not Complete.
  SPN 3226 FMI 20 (SLOT 236) Result: Test Not Complete.
——
  SPN 3226 FMI 21 (SLOT 236) Result: Test Not Complete.
  SPN 3227 FMI 2 (SLOT 32) Result: Test Not Complete.
  SPN 3238 FMI 2 (SLOT 208) Result: Test Not Complete.
  SPN 3516 FMI 1 (SLOT 32) Result: Test Passed. Min: 0, Value: 30, Max: N/A
  SPN 3556 FMI 0 (SLOT 68) Result: Test Not Complete.
  SPN 3556 FMI 1 (SLOT 68) Result: Test Not Complete.
  SPN 3711 FMI 31 (SLOT 68) Result: Test Not Complete.
  SPN 3713 FMI 31 (SLOT 68) Result: Test Not Complete.
  SPN 3936 FMI 18 (SLOT 32) Result: Test Not Complete.
  SPN 4331 FMI 18 (SLOT 32) Result: Test Not Complete.
——
  SPN 4364 FMI 17 (SLOT 32) Result: Test Not Complete.
  SPN 5018 FMI 18 (SLOT 251) Result: Test Not Complete.
  SPN 5397 FMI 31 (SLOT 238) Result: Test Not Complete.
  SPN 5713 FMI 20 (SLOT 295) Result: Test Not Complete.
  SPN 5713 FMI 21 (SLOT 295) Result: Test Not Complete.
  SPN 5714 FMI 20 (SLOT 295) Result: Test Not Complete.
  SPN 5714 FMI 21 (SLOT 295) Result: Test Not Complete.
  SPN 5741 FMI 12 (SLOT 403) Result: Test Not Complete.
  SPN 5747 FMI 12 (SLOT 290) Result: Test Not Complete.
  SPN 520348 FMI 14 (SLOT 295) Result: Test Not Complete.
——
  SPN 520349 FMI 14 (SLOT 318) Result: Test Not Complete.
  SPN 520353 FMI 17 (SLOT 68) Result: Test Not Complete.
  SPN 520355 FMI 20 (SLOT 295) Result: Test Not Complete.
  SPN 520355 FMI 21 (SLOT 295) Result: Test Not Complete.
  SPN 520372 FMI 16 (SLOT 318) Result: Test Not Complete.
—— 35
]
FAIL: 6.7.15.2.a - Difference in tests results reported from Exhaust Emission Controller (61) compared to list created in part 1

End Test 7.15 - DM7/DM30: Command non-continuously monitored test/scaled test results

**Comment by naroner** [comment]
This was a calibration issue on our HiL during testing, it isn't a tool issue.

**Comment by ericthomasswenson** [comment]
Not a tool issue
