### ISSUE TITLE
Change Warn for Missing Active Technology Arrays to Info

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1185]
Change ‘warn’ to ‘info’ for unsupported Active Technology Arrays. Prioritize with other Task 8 suggestions. This recommendation will be discussed with CARB. 

The time to make this observation for the current statement of work passed, when it was reviewed with CARB in May 2021.

Anthony Best will update the comments with the existing warnings and artifact paragraphs.

**Comment by anthonyhbest** [comment]
Warn present in the latest tool release for active technology support by the engine ECU.  Active technologies may not be present on the vehicle or may be controlled by ECUs other than the engine ECU.  Suggest changing this to "Info".
Message from J1939-84 Tool version 3.1.4:
WARN:   6.1.4.2.f - SP 12691 is not included in DM24 response from Engine #1 (0)

Recommended J1939-84 specification update:
![image](https://user-images.githubusercontent.com/94923793/188234128-b6b9ad54-ac04-4d36-b301-9e79eb02cc3d.png)

For reference, CCR 1971.1:
![image](https://user-images.githubusercontent.com/94923793/188234145-98d309fc-83c3-4ada-b205-7bc0193e9057.png)
