### ISSUE TITLE
Tool Throws a Failure for Alternate MIL Off

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1186]
**A third party controller on one of our trucks is using "Alternate MIL Off" instead of the convention off, the tools isn't recognizing this as a valid MIL off:**

12:18:27.1351 18FECA2F [8] 00 00 00 00 00 00 FF FF
DM1 from Suspension - System Controller #1 (47): MIL: alternate off, RSL: alternate off, AWL: alternate off, PL: alternate off, No DTCs

FAIL: 6.1.15.2.c - Non-OBD ECU Suspension - System Controller #1 (47) did not report MIL off or not supported

**Comment by ericthomasswenson** [comment]
Yes, please see #957 for prior observation and explanation.
