### ISSUE TITLE
Task 5 Artifact Update

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1190]
6.2.17.1 was garbled. Corrections shown below

The following improvements were made to the task 5 artifact 

6.2.17 KOER Data Stream Verification 
6.2.17.1 Actions1 
a. Create a consolidated list of expected SPs and PGs for the OBD ECU DM24 response(s) given in **_6.1.4, where the data stream support bit (SPN 4101) defined in SAE J1939-73 5.7.24 is 0. 
//  There is no technical change here … the value 0 is defined in J1939-73 5.7.24. 
b. Create a second list of Table A-1 omissions from the consolidated OBD ECU DM24 response(s), excluding those SPs noted (as CI or SI) for the opposite fuel type provided by the user. 
c. Omit the following SPNs (588, 976, 1213, 1220, 12675, 12691, 12730, 12783, 12797) which are included in the lists. Display a list of the omitted SPs in the report.                 
  // This change complete with 3.1.0-B 
d. Display the completed lists of supported SPs and unsupported SPs (as ‘broadcast’ or ‘upon request’), that follow from the vehicle DM24 composite._**

6.2.17.5 Actions3 
a. DS messages to the ECU(s) that indicated support in DM24 for upon request SPs and broadcast SPs that were not observed in step 1 from both lists. **_[SPs that were observed as ‘not available’ in broadcast data from a particular ECU need not be queried — the data evaluation from the broadcast data suffices. Where a PG from a particular OBD ECU contains more than one SP (to be evaluated), that PG need only be queried one time]._**

a. Fail if any response for each monitor not supported in DM5 by a given ECU **_from 6.2.2.3_** is also reported in DM26 as “1=monitor not complete this monitoring cycle” in SP 3303 bits 5-7.

Deleted extra table print in 6.2.17 as was deleted in 6.1.26.
c. List data received in a table using lifetime, stored 100 hr, active 100hr for columns, and categories for rows.

**Comment by battjt** [comment]
Will verify that the code matches VERSION 9.

**Comment by ericthomasswenson** [comment]
Addition errata now pending from 3.1.6 and 3.1.7 reviews

**Comment by battjt** [comment]
Verified error in the code.

> SPs that were observed as ‘not available’ in broadcast data from a particular ECU need not be queried

**Comment by battjt** [comment]
Bob verified bug and will report examples from version 3.1.13 logs.

**Comment by ericthomasswenson** [comment]
Closed in favor of #1221. Task 5 artifact believed to be complete for 6.1.26 and 6.2.17.
