### ISSUE TITLE
New DM19 diagnostic is ambiguous

### ISSUE THREAD

**Issue by jacobbosch-cummins** [Equipment-and-Tool-Institute/j1939-84#1192]
In 3.1.5, we observe a new warning.  The CAL ID/CVN pairs in question are non-production and you can see from the raw bytes in the DM19 that the CAL IDs are all FFh and the CVNs are all 00h.  We expect to see some diagnostics issued due to the invalid CVN, but it is not clear to me what this new warning is diagnosing since the CAL ID is all FFh.  Is it checking the associated CVN for 00h in the first or fourth bytes?

"WARN: 6.1.7.3.c - CAL ID ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ has 00h is in either the first or fourth bytes"

Start Test 1.7 - DM19: Calibration information
16:19:00.8215 Global DM19 Request
16:19:00.8242 18EAFFF9 [3] 00 D3 00 (TX)
16:19:01.8121 1CD3FF00 [120] C2 6F E9 12 4B 57 31 30 38 36 34 2E 30 31 00 00 00 00 00 00 54 53 30 42 4E 4F 78 2D 53 65 6E 73 6F 72 2D 41 54 4F 31 00 54 53 30 42 4E 4F 78 2D 53 65 6E 73 6F 72 2D 41 54 4F 31 00 00 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 00 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 00 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
DM19 from Engine #1 (0): [
  CAL ID of KW10864.01 and CVN of 0x12E96FC2
  CAL ID of NOx-Sensor-ATO1 and CVN of 0x42305354
  CAL ID of NOx-Sensor-ATO1 and CVN of 0x42305354
  CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
  CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
  CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
]

INFO: 6.1.7.3.b - Engine #1 (0) provided more than one CAL ID and CVN pair in a single DM19 message
**WARN: 6.1.7.3.c - CAL ID ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ has 00h is in either the first or fourth bytes
WARN: 6.1.7.3.c - CAL ID ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ has 00h is in either the first or fourth bytes
WARN: 6.1.7.3.c - CAL ID ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ has 00h is in either the first or fourth bytes**

**Comment by battjt** [comment]
Yes. The requirements say "For responses from OBD ECUs, warn if 00h is observed in either the first or fourth bytes."

You should have also had a "6.1.7.2.b.iv - OBD ECU Received CVN is all 0x00 from Engine #1 (0)"

I think the tool is working as specifid.

**Comment by battjt** [comment]
There is no work for development.  This should be reassigned.

**Comment by ericthomasswenson** [comment]
Depending on justification, either the 1st or 4th byte is correct.
Right justified 24-bit values will have 00h in the first byte.
Left justified 24-bit values will have 00h in the 4th byte.
Left justified 24-bit data is incorrect as the MSB should be 00h.
Little endian presentation puts the MSB in the fourth byte.

**Comment by jacobbosch-cummins** [comment]
I believe the diagnostic is detecting as expected, my issue was with the warning message.  The message issued doesn't reference the CVN.  As written, the message looks like the diagnostic is checking the CALID for 00h in the first or fourth bytes.

**Comment by battjt** [comment]
Better?
**WARN: 6.1.7.3.c - CAL ID ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ has CVN 0xHHHHHHHH which has 00h in either the first or fourth bytes**

**Comment by jacobbosch-cummins** [comment]
Yes, I vote in favor of the amended warning message.

**Comment by markmorrisoncummins** [comment]
I see the improved warning message in 3.1.10:

> Start Test 1.7 - DM19: Calibration information
> 10:19:27.0177 Global DM19 Request
> 10:19:27.0204 18EAFFF9 [3] 00 D3 00 (TX)
> 10:19:28.0112 1CD3FF00 [120] C2 6F E9 12 4B 57 31 30 38 36 34 2E 30 31 00 00 00 00 00 00 54 53 30 42 4E 4F 78 2D 53 65 6E 73 6F 72 2D 41 54 4F 31 00 54 53 30 42 4E 4F 78 2D 53 65 6E 73 6F 72 2D 41 54 4F 31 00 00 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 00 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 00 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
> DM19 from Engine #1 (0): [
>   CAL ID of KW10864.01 and CVN of 0x12E96FC2
>   CAL ID of NOx-Sensor-ATO1 and CVN of 0x42305354
>   CAL ID of NOx-Sensor-ATO1 and CVN of 0x42305354
>   CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
>   CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
>   CAL ID of ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ and CVN of 0x00000000
> ]
> 
> INFO: 6.1.7.3.b - Engine #1 (0) provided more than one CAL ID and CVN pair in a single DM19 message
> WARN: 6.1.7.3.c - CAL ID ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ has CVN 0x00000000 which has 00h in either the first or fourth bytes
> WARN: 6.1.7.3.c - CAL ID ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ has CVN 0x00000000 which has 00h in either the first or fourth bytes
> WARN: 6.1.7.3.c - CAL ID ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ has CVN 0x00000000 which has 00h in either the first or fourth bytes
