### ISSUE TITLE
SP 588 Length needs to be updated in section 6.1.9.3.a

### ISSUE THREAD

**Issue by anthonyhbest** [Equipment-and-Tool-Institute/j1939-84#1193]
Per closed issue #967 please update section 6.1.9.3.a to match the appendix.
Issue #967 resolution:
![image](https://user-images.githubusercontent.com/94923793/194112291-f528d4db-c545-45ac-8b32-05db0c1a94b7.png)
![image](https://user-images.githubusercontent.com/94923793/194112377-1c89660e-e33c-4ed9-9457-c7ecea19cd58.png)

Appendix A has been updated in the latest draft proposal, but section 6.1.9.3 wording was not updated to match.  The following WARN seen in 3.1.6 release should be an INFO:

![image](https://user-images.githubusercontent.com/94923793/194112150-0d20bbca-c1f0-45e5-a9c7-90cfd96fdba2.png)

**Comment by ericthomasswenson** [comment]
I’ll change eight to six

6.1.9.3	Warn Criteria for OBD ECUs
a.	Warn if the serial number field (SP 588) from any function 0 device is less than _**six**_ characters long.

**Comment by ericthomasswenson** [comment]
This was a error of omission … Appendix A-1 says 
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40"><div align="center" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

aa * b * A12345  –  ending delimiter missing | Pass [6 character, 5 numeric digit serial number example]
-- | --


</div></html>
