### ISSUE TITLE
DM33 ECU responds with control byte = 3

### ISSUE THREAD

**Issue by anthonyhbest** [Equipment-and-Tool-Institute/j1939-84#1194]
Propose to remove 6.7.16.4.c and 6.8.13.2.c 
"c.	Warn if any OBD ECU NACKs with control byte = 3"

Control byte = 3 is a valid response from an ECU when the ECU is already in a transport protocol session.  
This will always happen when there is a transport protocol session initialized when EC1 is broadcasted.  EC1 is broadcast every 5s and on change.

**Comment by ericthomasswenson** [comment]
See #1201 … this warning is to be corrected.
Busy responses suggest an ECM would clear DTCs.

**Comment by ericthomasswenson** [comment]
DM3 is a clear faults command … the response does use TP.
