### ISSUE TITLE
V3.1.7 hangs up at 1.26.2.c

### ISSUE THREAD

**Issue by anthonyhbest** [Equipment-and-Tool-Institute/j1939-84#1197]
Tool proceeds until 1.26.2.c then after "reading bus for x seconds" gets to 0, tool hangs and will not proceed.
![image](https://user-images.githubusercontent.com/94923793/194372555-4aee567c-1758-4484-8cc0-512179ecd515.png)
Starting the engine will trigger the tool to move on, but then issues the following error message:
![image](https://user-images.githubusercontent.com/94923793/194374202-5d45a3c4-76e0-4c65-8dfc-77bdae3cd3ad.png)
Tool then hangs again at "reading bus for 0 seconds" in part 2.17.1.c
Keying off triggers the tool to move on but issues numerous failures.
Log file:
[j1939-84-gc.txt](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/9727095/j1939-84-gc.txt)

**Comment by battjt** [comment]
%TEMP%\j1939_840.log  (or any j1939_*.log file that was modified at about the time you made this run that crashed) will have the important information for us to understand what crashed.  Can you zip those and send them to j1939-84@soliddesign.net ?  

The ASC file would let us try to reproduce it, but for this type of error, it likely will not help.

**Comment by battjt** [comment]
It may be that your truck produces more traffic than the other test trucks.  I have increased the amount of memory allocated for this (from 128 MB to 256 MB) for the next release.

**Comment by anthonyhbest** [comment]
Files sent as requested.

**Comment by ericthomasswenson** [comment]
Bob Has seen similar errors including the pop-up … cycling the key … hit the App with a hammer.

**Comment by battjt** [comment]
We expect this to be related to the memory configuration.  We changed the setting from 128MB to 256 MB for the 3.1.8 release.

**Comment by anthonyhbest** [comment]
Still having the issue with v3.1.8 and confirmed across multiple vehicles.

**Comment by battjt** [comment]
Addressd with release 3.1.9.

**Comment by anthonyhbest** [comment]
Have not seen the issue return in v3.1.9

**Comment by ericthomasswenson** [comment]
Reported as resolved in 3.1.9
