### ISSUE TITLE
DM12 not found in DM28 when present

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1203]
From 3.1.7.

Start Test 8.2 - DM12: Emissions related active DTCs

Attempt 1
08:51:33.0947 Global DM12 Request
08:51:33.0969 18EAFFF9 [3] D4 FE 00 (TX)
08:51:33.0983 18FED417 [8] 00 FF 00 00 00 00 FF FF
DM12 from Instrument Cluster #1 (23): MIL: off, RSL: off, AWL: off, PL: off, No DTCs

08:51:33.1032 18FED400 [8] 40 FF **_66 00 04 01_** FF FF
DM12 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: off
DTC 102:4 - Engine Intake Manifold #1 Pressure, Voltage Below Normal, Or Shorted To Low Source - 1 times

08:51:33.8494 Destination Specific DM12 Request to Engine #1 (0)
08:51:33.8524 18EA00F9 [3] D4 FE 00 (TX)
08:51:33.8529 18FED400 [8] 40 FF **_66 00 04 01_** FF FF
DM12 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: off
DTC 102:4 - Engine Intake Manifold #1 Pressure, Voltage Below Normal, Or Shorted To Low Source - 1 times
…

Start Test 8.7 - DM28: Permanent DTCs
08:51:39.1438 Global DM28 Request
08:51:39.1462 18EAFFF9 [3] 80 FD 00 (TX)
08:51:39.2725 1CFD8000 [14] 40 FF BC 0D 13 01 E1 06 13 01 **_66 00 04 01_**
DM28 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: off
DTC 3516:19 - AFT 1 DEF Concentration, Received Network Data In Error - 1 times
DTC 1761:19 - AFT 1 DEF Tank Volume, Received Network Data In Error - 1 times
DTC 102:4 - Engine Intake Manifold #1 Pressure, Voltage Below Normal, Or Shorted To Low Source - 1 times

**_FAIL: 6.8.7.2.b - Engine #1 (0) permanent DTC does not match DM12 DTC from earlier in test 6.8.2_**
WARN: 6.8.7.3.b - Engine #1 (0) reported more than one permanent DTC

**Comment by ericthomasswenson** [comment]
Also

Start Test 5.2 - DM12: Emission-related active DTCs

08:38:20.9035 Global DM12 Request
08:38:20.9050 18EAFFF9 [3] D4 FE 00 (TX)
08:38:20.9060 18FED417 [8] 00 FF 00 00 00 00 FF FF
DM12 from Instrument Cluster #1 (23): MIL: off, RSL: off, AWL: off, PL: off, No DTCs

08:38:20.9101 18FED400 [8] 40 FF **_83 10 01 01_** FF FF
DM12 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: off
DTC 4227:1 - Engine Crankcase Breather Oil Separator, Data Valid But Below Normal Operational Range - Most Severe Level - 1 times

End Test 5.2 - DM12: Emission-related active DTCs

Start Test 5.3 - DM1: Active DTCs
… 
08:38:22.0006 18FECA00 [8] 40 FF **_83 10 01_** 01 FF FF
DM1 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: off
DTC 4227:1 - Engine Crankcase Breather Oil Separator, Data Valid But Below Normal Operational Range - Most Severe Level - 1 times

…
08:38:22.3346 18FECA03 [8] F3 FF 7F 02 0B 02 FF FF
DM1 from Transmission #1 (3): MIL: not supported, RSL: not supported, AWL: off, PL: not supported
DTC 639:11 - J1939 Network #1, Primary Vehicle Network, Root Cause Not Known - 2 times

End Test 5.3 - DM1: Active DTCs

Start Test 5.4 - DM28: Permanent DTCs
08:38:24.6635 Destination Specific DM28 Request to Engine #1 (0)
08:38:24.6672 18EA00F9 [3] 80 FD 00 (TX)
08:38:24.7395 1CFD8000 [14] 40 FF BC 0D 13 01 E1 06 13 01 **_83 10 01_** 01 
DM28 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: off
DTC 3516:19 - AFT 1 DEF Concentration, Received Network Data In Error - 1 times
DTC 1761:19 - AFT 1 DEF Tank Volume, Received Network Data In Error - 1 times
DTC 4227:1 - Engine Crankcase Breather Oil Separator, Data Valid But Below Normal Operational Range - Most Severe Level - 1 times
FAIL: 6.5.4.2.c - Engine #1 (0) permanent DTC (3516:19) does not match DM12 active DTC from earlier in this part
FAIL: 6.5.4.2.c - Engine #1 (0) permanent DTC (1761:19) does not match DM12 active DTC from earlier in this part

End Test 5.4 - DM28: Permanent DTCs

Start Test 6.3 - DM12: Emissions related active DTCs
08:42:43.5811 Destination Specific DM12 Request to Engine #1 (0)
08:42:43.5836 18EA00F9 [3] D4 FE 00 (TX)
08:42:43.5906 18FED400 [8] 40 FF [83 10 01 01](tel:83 10 01 01) FF FF
DM12 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: off
DTC 4227:1 - Engine Crankcase Breather Oil Separator, Data Valid But Below Normal Operational Range - Most Severe Level - 1 times
…

Start Test 6.7 - DM28: Permanent DTCs
08:42:47.0546 Destination Specific DM28 Request to Engine #1 (0)
08:42:47.0571 18EA00F9 [3] 80 FD 00 (TX)
08:42:47.1302 1CFD8000 [14] 40 FF BC 0D 13 01 E1 [06 13 01 83 10 01 01](tel:06 13 01 83 10 01 01)
DM28 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: off
DTC 3516:19 - AFT 1 DEF Concentration, Received Network Data In Error - 1 times
DTC 1761:19 - AFT 1 DEF Tank Volume, Received Network Data In Error - 1 times
DTC 4227:1 - Engine Crankcase Breather Oil Separator, Data Valid But Below Normal Operational Range - Most Severe Level - 1 times

…
Start Test 7.2 - DM23: Emission related previously active DTCs
08:46:52.5851 Destination Specific DM23 Request to Engine #1 (0)
08:46:52.5875 18EA00F9 [3] B5 FD 00 (TX)
08:46:52.5904 18FDB500 [8] 00 FF [83 10 01 01](tel:83 10 01 01) FF FF
DM23 from Engine #1 (0): MIL: off, RSL: off, AWL: off, PL: off
DTC 4227:1 - Engine Crankcase Breather Oil Separator, Data Valid But Below Normal Operational Range - Most Severe Level - 1 times

Start Test 7.9 - DM28: Permanent DTCs
08:46:58.6622 Destination Specific DM28 Request to Engine #1 (0)
08:46:58.6647 18EA00F9 [3] 80 FD 00 (TX)
08:46:58.7402 1CFD8000 [10] 00 FF BC 0D 13 01 E1 06 13 01
DM28 from Engine #1 (0): MIL: off, RSL: off, AWL: off, PL: off
DTC 3516:19 - AFT 1 DEF Concentration, Received Network Data In Error - 1 times
DTC 1761:19 - AFT 1 DEF Tank Volume, Received Network Data In Error - 1 times
FAIL: 6.7.9.2.a - Engine #1 (0) reported a permanent DTC

End Test 7.9 - DM28: Permanent DTCs

**Comment by ericthomasswenson** [comment]
6.5.4	DM28: Permanent DTCs
6.5.4.1	Actions
a.	DS DM28 [send Request (PG 59904) for PG 64896 (SPs 1213-1215, 3038, 1706)] to each OBD ECU.
6.5.4.2	Fail Criteria
a.	Fail if no ECU reports a permanent DTC.
b.	Fail if any ECU reports a different MIL status than it did for DM12 response earlier in this part.
**_c.	Fail if permanent DTC does not match DM12 active DTC from earlier in this part._**
d.	Fail if NACK not received from OBD ECUs that did not provide a DM28 message.
6.5.5	DM29: Regulated DTC Counts
6.5.5.1	Actions
a.	Global DM29 [send Request (PG 59904) for PG 40448 (SPs [4104-4108](tel:4104-4108))].

6.6.7	DM28: Permanent DTCs
6.6.7.1	Actions
a.	DS DM28 [send Request (PG 59904) for PG 64896 (SPs 1213-1215, 3038, 1706)] to each OBD ECU.
6.6.7.2	Fail Criteria
a.	Fail if no ECU reports permanent DTC present.
**_b.	Fail if permanent DTC provided does not match DM12 active DTC._**
c.	Fail if no ECU reports MIL on. 
d.	Fail if NACK not received from OBD ECUs that did not provide a DM28 message.

**Comment by ericthomasswenson** [comment]
DTC is present but not apparently credited. All non matching perm faults fail.

**Comment by battjt** [comment]
The tool compares the results of DM28 and the results of a previous DM12, finds the results different and reports the error.  "match" was assumed to mean "equal".

Instead of 
> 6.8.7.2.b. Fail if permanent DTC does not match DM12 DTC from earlier in test 6.8.2.

Should it be?

> 6.8.7.2.b. Fail if permanent DTC does not contain DM12 DTC from earlier in test 6.8.2.

**Comment by ericthomasswenson** [comment]
Yes Joe that’s what I was thinking.

Failing because the vehicle started with an excess permanent faults is one thing.
But let’s not make it appear that the diagnostic executive failed to record the permanent fault as required.

**Comment by ericthomasswenson** [comment]
6.5.4 DM28: Permanent DTCs
6.5.4.1 Actions
a. DS DM28 [send Request (PG 59904) for PG 64896 (SPs 1213-1215, 3038, 1706)] to each OBD ECU.
6.5.4.2 Fail Criteria
a. Fail if no ECU reports a permanent DTC.
b. Fail if any ECU reports a different MIL status than it did for DM12 response earlier in this part.
**_c. Fail if DM12 active DTC is not included in DM28 permanent DTCs provided in DM28 response._**
d. Fail if NACK not received from OBD ECUs that did not provide a DM28 message.

6.6.7 DM28: Permanent DTCs
6.6.7.1 Actions
a. DS DM28 [send Request (PG 59904) for PG 64896 (SPs 1213-1215, 3038, 1706)] to each OBD ECU.
6.6.7.2 Fail Criteria
a. Fail if no ECU reports permanent DTC present.
b. **_c. Fail if DM12 active DTC is not included in DM28 permanent DTCs provided in DM28 response._**
c. Fail if no ECU reports MIL on.
d. Fail if NACK not received from OBD ECUs that did not provide a DM28 message.

**Comment by ericthomasswenson** [comment]
Changed text

6.5.4.2	Fail Criteria
a.	Fail if no ECU reports a permanent DTC.
b.	Fail if any ECU reports a different MIL status than it did for DM12 response earlier in this part.
c.	Fail if permanent DTC **_response from the SA reporting a DM12 active DTC does not include the DM12 active DTC that the SA reported_** from earlier in this part.
d.	Fail if NACK not received from OBD ECUs that did not provide a DM28 message.

6.6.7.2	Fail Criteria
a.	Fail if no ECU reports permanent DTC present.
b.	Fail if permanent DTC **_response from the SA reporting a DM12 active DTC does not include the DM12 active DTC that the SA reported earlier in this part._** 
c.	Fail if no ECU reports MIL on. 
d.	Fail if NACK not received from OBD ECUs that did not provide a DM28 message.

6.8.7.2	Fail Criteria
a.	Fail if no OBD ECU reports a permanent DTC.
b.	Fail if permanent DTC **_from the SA reporting a DM12 active DTC does not include the DM12 active DTC that the SA reported earlier in this part in_** test 6.8.2. 
c.	Fail if any ECU reporting different MIL status than DM12 response earlier in test 6.8.2. 

6.9.12.3	Warn Criteria
a.	Warn if permanent DTC **_response from the SA reporting a DM12 active DTC does not include the DM12 active DTC that the SA reported earlier in this part in test 6.9.2._**

6.11.9.2	Fail Criteria
a.	Fail if no ECU reports a permanent DTC.
b.	Fail if the permanent **_DTCs reported are not the same DTCs_** _**that were**_ reported in DM28 in part 10.
**_// This can be implemented as a string comparison using the part 10 response. 
// This text change (to plural subject) may be a clarification with no code changes required_** 
c.	Fail if NACK not received from OBD ECUs that did not provide a DM28 message.

**Comment by ericthomasswenson** [comment]
Some instances of “number” for DM29 criteria were replaced with “count” as an editorial improvement. No technical change is intended.

**Comment by battjt** [comment]
**previous comment deleted**

Not all implementations were equivalent, but all are being modified to match updated requirements.
