### ISSUE TITLE
Update tool to reflect most recent J1939DA

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1204]
There are some newer 2024 MY SPs that are missing.

**Comment by battjt** [comment]
Wait until at least January 2023 version for these new SPs.

**Comment by ericthomasswenson** [comment]
Q4 Published DA is believed to be complete.

**Comment by ericthomasswenson** [comment]
Joe, you can start this immediately, if convenient.

**Comment by battjt** [comment]
Updated to J1939DA_JAN23.  Does this need updated again?
