### ISSUE TITLE
Update Misfire Criteria for 2019+ MY Engines

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1205]
6.1.14.2 Fail Criteria
a. Fail if any response for any monitor supported in DM5 by a given ECU is reported as “0=monitor complete this cycle or not supported” in SP 3303 bits 1-4 and SP 3305 [except comprehensive components monitor (CCM)].

Should have been adjusted for misfire monitoring too 2019+MY Engines

6.1.14.2 Fail Criteria
a. Fail if any response for any monitor supported in DM5 by a given ECU is reported as “0=monitor complete this cycle or not supported” in SP 3303 bits 1-4 and SP 3305 [except comprehensive components monitor (CCM) and Misfire Monitoring for 2019+ MY engines].

**Comment by ericthomasswenson** [comment]
Don’t wait for artifact update, beforehand.

**Comment by battjt** [comment]
Fixed in Release 3.1.8. a5ade28786be5fb81efc557bc548acb2f0e7d2d8
