### ISSUE TITLE
6.7.16.4.c Incorrect Warn issued by the tool

### ISSUE THREAD

**Issue by anthonyhbest** [Equipment-and-Tool-Institute/j1939-84#1206]
Version 3.1.6 and 3.1.7 of the tool are issuing an incorrect warn at part 6.7.16.4.c based on the specification:
![image](https://user-images.githubusercontent.com/94923793/195937611-03077a35-aef6-44b7-90d0-d21878480630.png)

This seems to be coded incorrectly in the tool as the tool is issuing a WARN but the ECU responded with control byte = 1.

![image](https://user-images.githubusercontent.com/94923793/195937874-aea8b11f-2735-45fd-825e-a29d8e85b4c2.png)

**Comment by battjt** [comment]
Same error also found in 6.8.13.2.c.  We will review all NACK comparisons.

**Comment by ericthomasswenson** [comment]
See #1199, The transposition of b. and c. should take care this.

Interceding NACK messages may be creating this failure.

Transposition documented in v2 artifact.
