### ISSUE TITLE
Tool Issues Warning for SPN 12744 not In DM24 for Diesel Engines

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1208]
**Should the issue a warning for diesel engines? Perhaps it should be changed to Info for Diesel and Warn for Gasoline** 

Required Data Stream SPNs are not supported. SPNs: 12748
Required Data Stream SPNs are not supported. SPNs: 3516, 3518, 7346
FAIL: 6.1.4.2.b - N.2 One or more SPNs for data stream is not supported
FAIL: 6.1.4.2.d - SP 12675 is not included in DM24 response from Engine #1 (0)
FAIL: 6.1.4.2.e - SP 12730 is not included in DM24 response from Engine #1 (0)
WARN: 6.1.4.2.f - SP 12691 is not included in DM24 response from Engine #1 (0)
FAIL: 6.1.4.2.d - SP 12675 is not included in DM24 response from Exhaust Emission Controller (61)
FAIL: 6.1.4.2.e - SP 12730 is not included in DM24 response from Exhaust Emission Controller (61)
WARN: 6.1.4.2.f - SP 12691 is not included in DM24 response from Exhaust Emission Controller (61)
Required Data Stream SPNs are not supported. SPNs: 132
Required Data Stream SPNs are not supported. SPNs: 245, 917
Required Data Stream SPNs are not supported. SPNs: 2659
**_Required Data Stream SPNs are not supported. SPNs: 12744_**
Required Data Stream SPNs are not supported. SPNs: 3516, 3518, 7346
WARN: 6.1.4.3.a - SPN not supported in DM24
Required Data Stream SPNs are not supported. SPNs: 74
Required Data Stream SPNs are not supported. SPNs: 101
INFO: 6.1.4.3.a - SPN not supported in DM24
More than one of the SPNs are reported as supported. SPNs: 110, 1637, 4076, 4193
INFO: 6.1.4.3.b - More than 1 SPN supported

**Comment by ericthomasswenson** [comment]
12744 is not in the requirements artifact. But is in the SOW source for SI

Joe will search for the constant “12744” in the Java code.

**Comment by battjt** [comment]
Found in Table A1 artifact.
