### ISSUE TITLE
Tool Appears to be Incorrectly Issuing a Failure for SPN 12694

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1209]
**Tool is issuing a failure saying SPN 12694 is > 0 for active 100 hour array when the value is broadcast as 0**

13:59:58.7820 Destination Specific GHGTTL Request to Engine #2 (1)
13:59:58.7850 18EA01F9 [3] 01 FB 00 (TX)
13:59:58.8735 1CFB0101 [28] FA 00 00 00 00 00 00 00 00 F9 00 00 00 00 00 00 00 00 F8 00 00 00 00 00 00 00 00 00
Green House Gas Lifetime Active Technology Tracking from Engine #2 (1): 
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0.000 s, Vehicle Distance = 0.000 m

13:59:58.8810 Destination Specific GHGTTA Request to Engine #2 (1)
13:59:58.8825 18EA01F9 [3] 00 FB 00 (TX)
13:59:58.9535 1CFB0001 [16] FA 00 00 00 00 F9 00 00 00 00 F8 00 00 00 00 00
Green House Gas Active 100 Hour Active Technology Tracking from Engine #2 (1): 
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0.000 s, Vehicle Distance = 0.000 km

13:59:58.9545 Destination Specific GHGTTS Request to Engine #2 (1)
13:59:58.9570 18EA01F9 [3] FF FA 00 (TX)
13:59:59.0335 1CFAFF01 [16] FA 00 00 00 00 F9 00 00 00 00 F8 00 00 00 00 00
Green House Gas Stored 100 Hour Active Technology Tracking from Engine #2 (1): 
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0.000 s, Vehicle Distance = 0.000 km

13:59:59.0355 GHG Active Technology Arrays from Engine #2 (1)
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|
|                                     |    Active   |    Active   |    Stored   |    Stored   |             |             |
| Index                               |   100 Hour  |   100 Hour  |   100 Hour  |   100 Hour  |   Lifetime  |   Lifetime  |
| Description                         |    Time, m  |   Dist, km  |    Time, m  |   Dist, km  |    Time, m  |   Dist, km  |
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|
| SAE/ISO Reserved                    |         N/A |         N/A |         N/A |         N/A |  69,625,446 |           0 |
| Mfg Defined Active Technology 3     |           0 |           0 |           0 |           0 |         N/A |         N/A |
| Mfg Defined Active Technology 2     |           0 |           0 |           0 |           0 |         N/A |         N/A |
| Mfg Defined Active Technology 1     |           0 |           0 |           0 |           0 |           0 |           0 |
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|

FAIL: 6.1.26.18.g - Active 100 hr array value received was greater than zero from Engine #2 (1) for SPN SPN 12694, GHG Tracking Active 100 Hour Active Technology Index: Mfg Defined Active Technology 1

**Comment by ericthomasswenson** [comment]
Layouts for 16 and 32 bit fields were crossed up.

**Comment by naroner** [comment]
@ericthomasswenson This is still an issue in 3.1.19

15:28:13.3886 Destination Specific GHGTTL Request to Engine #2 (1)
15:28:13.3921 18EA01F9 [3] 01 FB 00 (TX)
15:28:13.4951 1CFB0101 [28] FA 00 00 00 00 00 00 00 00 F9 00 00 00 00 00 00 00 00 F8 82 01 00 00 00 00 00 00 00
Green House Gas Lifetime Active Technology Tracking from Engine #2 (1): 
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 386.000 s, Vehicle Distance = 0.000 m

15:28:13.4971 Destination Specific GHGTTS Request to Engine #2 (1)
15:28:13.4981 18EA01F9 [3] FF FA 00 (TX)
15:28:13.5766 1CFAFF01 [16] FA 00 00 00 00 F9 00 00 00 00 F8 00 00 00 00 00
Green House Gas Stored 100 Hour Active Technology Tracking from Engine #2 (1): 
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0.000 s, Vehicle Distance = 0.000 km

15:28:13.5786 Destination Specific GHGTTA Request to Engine #2 (1)
15:28:13.5806 18EA01F9 [3] 00 FB 00 (TX)
15:28:13.6466 1CFB0001 [16] FA 00 00 00 00 F9 00 00 00 00 F8 00 00 00 00 00
Green House Gas Active 100 Hour Active Technology Tracking from Engine #2 (1): 
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0.000 s, Vehicle Distance = 0.000 km

FAIL: Section A.5.C - Value received from Engine #2 (1) is greater than 0 for SPN 12694, GHG Tracking Active 100 Hour Active Technology Index: Mfg Defined Active Technology 1

**Comment by battjt** [comment]
Developer incorrectly included active technology index SPN when comparing values to zero.
