### ISSUE TITLE
Tool Issues a Warning for Multiple Permanent DTCs on a Distributed System when Only 1 is Present

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1210]
14:25:20.5210 Global DM28 Request
14:25:20.5230 18EAFFF9 [3] 80 FD 00 (TX)
14:25:20.5285 18FD803D [8] 03 FF 00 00 00 00 FF FF
DM28 from Exhaust Emission Controller (61): MIL: off, RSL: off, AWL: off, PL: not supported, No DTCs

14:25:20.5320 18FD8001 [8] 47 FF EB 0D 04 01 FF FF
DM28 from Engine #2 (1): MIL: on, RSL: off, AWL: on, PL: not supported
DTC 3563:4 - Engine Intake Manifold #1 Absolute Pressure, Voltage Below Normal, Or Shorted To Low Source - 1 times

WARN: 6.8.7.3.a - More than on ECU reported a permanent DTC

**Comment by battjt** [comment]
Found it.  Will be fixed in next release.

**Comment by naroner** [comment]
@ericthomasswenson This is fixed in 3.1.19
