### ISSUE TITLE
Tool Failing for NACK sent before Request

### ISSUE THREAD

**Issue by anthonyhbest** [Equipment-and-Tool-Institute/j1939-84#1215]
Tool fails for a NACK response in DM58, but the timestamp for the NACK is before the request message is sent out:

![image](https://user-images.githubusercontent.com/94923793/205176793-b761fea6-1603-46ab-94da-8f3b365b972f.png)

ASC Log:
![image](https://user-images.githubusercontent.com/94923793/205177393-f5bc332f-40b3-4bc9-bd2a-8086ba5c8325.png)

**Comment by ericthomasswenson** [comment]
Joe, will check the log.

**Comment by battjt** [comment]
Can I get the complete log?  What is the ECM NACKing at 49.176164?

**Comment by anthonyhbest** [comment]
@battjt Are you looking for the full test report or the full .asc log?

**Comment by battjt** [comment]
The .asc log.

The process the tool uses for each request is:
1. start collecting all packets
2. send request
3. search collection for response or appropriate NACK until timeout.
4. stop collecting
5. report results
6. repeat

It is possible that the tool picked up the NACK to the previous request as the NACK for this request (essentially the NACK for the previous request was received between steps 1 and 2), but that points to an error in the previous request.  I'm interested in why that NACK wasn't processed during the previous request sequence.

A processing step that we can put in is to ignore all packets collected up to the request.  This change would only ignore this NACK, which may be covering up another error.

**Comment by anthonyhbest** [comment]
.asc log provided today.

**Comment by battjt** [comment]
The change will take a lot of effort to work for requests that require TP, but I don't know of any that are used in -84.

I was able to implement this change for requests that do not require TP.  The response may require TP.

The response stream is filtered for responses after the sent packet echoed back from the adapter.

Unsolicited NACKs may still interfere with the test, but will be less likely.
