### ISSUE TITLE
Excessive penalty for remote diagnostics using source address F9

### ISSUE THREAD

**Issue by anthonyhbest** [Equipment-and-Tool-Institute/j1939-84#1218]
Tool now has numerous pop-ups now due to a remote diagnostics device operating on SA F9: 
![image](https://user-images.githubusercontent.com/94923793/211933197-df57ca16-c7d2-4582-bb02-ad724d586758.png)

These pop-ups appear to be stalling the tool, which results in mass failures for whole sections of the test where the tool does not collect the data provided by the truck.  In just parts 1 and 2 alone I had exceeded 130 failures.  I know we have discussed the root cause of this issue in the past, and there should be some penalty for the remote diagnostics device communicating using SA F9.  However, this behavior and subsequent penalty, at least upon initial review, seem excessive for the situation.

**Comment by battjt** [comment]
We will need to audit the communication layer to understand any changes needed to support shared addresses.  It was not an expected condition.

Destination specific TP is not possible for two devices sharing a single address.  One possibility would be to only display this error when TP control messages are observed.

Should we log the other device's traffic in the report?  Do we know that it isn't clearing faults or starting tests?  Do we care?

Can we get a CAN log?  I'm interested in what the address claim negotiation looks like in this case.  I don't need the whole log.

**Comment by battjt** [comment]
Options to be discussed 1/20/2023:
1. Only record in report
2. Only show popup once
3. Don't have popup interrupt test
4. Periodically query DM5 as a heartbeat to demonstrate tool is attached for telematics modules

Development will report back with description of tool address claim procedure.

**Comment by ericthomasswenson** [comment]
From 1/202023 User Development Discussion:

Item 1 — Always show the perceived excess query in the logs (report and .ASC)
Item 2 — Display the popup once, upon the first occurrence of excess SA F9. Allow user to Abort or continue. The existing abort button in the UI may provide this function.
Item 3 — Complete the current response window data collection, where practical. The tool may continue with next test step once the current response window closes.
Item 4 — Accepted as heuristic improvement. Use a global DM5 query for the heartbeat concept not less than every 10 seconds and not more than 30 seconds.

**Comment by battjt** [comment]
1. Fixed (it was missing from the on-screen report)
2. First detection of an imposter results in a popup that does not pause data collection.  If it did pause data collection during a query, it may cause failures.
3. The popup does not pause data collection, so this request doesn't make sense.  The user can cancel at anytime.
4. Adding DM5 polling is a new ticket: #1222
