### ISSUE TITLE
Verify 6.1.26 and 6.2.17 Behavior for 3.1.13

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1221]
Retire #1190 as the document changes are confirmed to be complete

Confirm 3.1.13 6.1.26 and 6.1.17 meet the artifact in all respects. 

Overall general performance is reported as much improved.

**Comment by ericthomasswenson** [comment]
BCT PGN 65217 from Engine #1 (0) with SPNs 917
——

PGN 65217 with Supported SPNs 917
13:28:50.0066 18FEC100 [8] FF FF FF FF 00 3B 0B 00
Found: High Resolution Vehicle Distance from Engine #1 (0): 
  SPN   917, Total Vehicle Distance (High Resolution): Not Available
  SPN   918, Trip Distance (High Resolution): 3680000,000 m

FAIL: 6.1.26.3.a - N.1 SPN 917 was received as NOT AVAILABLE from Engine #1 (0)
——

13:29:10.9426 Destination Specific for PGN 65217 for SPNs 917 Request to Engine #1 (0)
13:29:10.9444 18EA00F9 [3] C1 FE 00 (TX)
13:29:10.9516 1CE8FF00 [8] 01 FF FF FF F9 C1 FE 00
Acknowledgment from Engine #1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 65217
FAIL: 6.1.26.6.a - No DS response for PGN 65217 from Engine #1 (0)

**Comment by ericthomasswenson** [comment]
Need REQ use case example too

**Comment by battjt** [comment]
Create a unit test to verify that broadcast N/A information is not requested DS.
