### ISSUE TITLE
Poll DM5 every 10 s

### ISSUE THREAD

**Issue by battjt** [Equipment-and-Tool-Institute/j1939-84#1222]
Use a global DM5 query for the heartbeat concept while the tool is idle (no queries pending) and waiting for a new part/query to start. The period shall be no less than every 10 seconds and no more than every 30 seconds.

The goal is to signal to other tools that the J1939-84 tool is using F9.

**Comment by ericthomasswenson** [comment]
Implement using 10 s after 3.1.14 release. (Was 10 ms)

**Comment by battjt** [comment]
"DM5 Heatbeat" added to the following steps:

| | ||
|--------|--------|--------|
| Part 01 |Step 01|Entire step
|Part 01 |Step 26|During "Second device using SA 0xF9" warning.
|Part 01 |Step 27|6.1.27.b.iii
|Part 02 |Step 17|During "Second device using SA 0xF9" warning.
|Part 02 |Step 18|Entire step
|Part 03 |Step 02|During "Do you wish to continue?" prompt
|Part 03 |Step 16|Entire step
|Part 04 |Step 15|Entire step
|Part 05 |Step 07|Entire step
|Part 06 |Step 11|Entire step
|Part 07 |Step 18|Entire step
|Part 08 |Step 16|Entire step
|Part 09 |Step 08|Entire step
|Part 09 |Step 25|Entire step
|Part 10 |Step 02|Entire step
|Part 10 |Step 05|Entire step
|Part 11 |Step 07|Entire step, but we could try to pause is during 5 minutes of periodic DM20 polling.
|Part 11 |Step 14|Entire step

**Comment by ericthomasswenson** [comment]
Works as expected… unfortunately extra queries are still observed.
