### ISSUE TITLE
Tool Issuing Failure for PG 65251 Updating Outside of 5000ms Cyclic Rate

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1223]
**Per the DA PG 65251 has a transmission rate of "Every 5 s and on change of torque/speed points of more than 10% since last transmission but no faster than every 500 ms" The tool doesn't take the on change into account when validating the cycle rate.**

PGN 65251 from Engine #1 (0)
17:43:54.4555 1CFEE300 [39] 00 13 C1 80 3B B9 20 1D E7 40 27 E9 60 31 E0 A0 3E FF FF 73 09 A0 4D 32 FF FF FF FF FF FF 3B 01 FF FF FF FF FF FF FF
17:43:59.4555 1CFEE300 [39] 00 13 C1 80 3B B9 20 1D E7 40 27 E9 60 31 E0 A0 3E FF FF 73 09 A0 4D 32 FF FF FF FF FF FF 3B 01 FF FF FF FF FF FF FF
17:44:01.4554 1CFEE300 [39] 80 11 BE 80 3B B9 00 1C E6 80 26 E9 00 31 E2 A0 3E FF FF 73 09 A0 4D 32 FF FF FF FF FF FF 3B 01 FF FF FF FF FF FF FF
FAIL: 6.1.26 - Broadcast period of PGN 65251 (1999 ms) by ECU Engine #1 (0) is less than 90% specified broadcast period of 5000 ms.

**Comment by ericthomasswenson** [comment]
@naroner how often is this observed?   Especially KOEO

**Comment by naroner** [comment]
@ericthomasswenson This is the only log I have seen it on.

**Comment by ericthomasswenson** [comment]
Consider lowering fail to warn or info.

**Comment by ericthomasswenson** [comment]
Add note to table A-1 regarding on-change v. Hard periodic rates.

**Comment by battjt** [comment]
Should be fixed with #1083 .

**Comment by ericthomasswenson** [comment]
Added text: Data that is broadcast on change like PG 65251(EC1) will appear more frequently than the expected broadcast period. 

Beneath Table A-1.
