### ISSUE TITLE
Active hour array sent as zero and failure message complains it isn’t zero

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1225]
Active hour array sent as zero and failure message complains it isn’t zero from 3.1.14

02:12.3207 Destination Specific GHGTTL Request to Engine #1 (0)
11:02:12.3241 18EA00F9 [3] 01 FB 00 (TX)
11:02:12.8968 1CFB0100 [72] [05 00 00 00 00 00 00](tel:05 00 00 00 00 00 00) [00 00 06 00 00 00 00](tel:00 00 06 00 00 00 00) [00 00 00 00 07 00 00](tel:00 00 00 00 07 00 00) [00 00 00 00 00 00](tel:00 00 00 00 00 00) F6 [00 00 00 00 00 00 00](tel:00 00 00 00 00 00 00) 00 F7 [00 00 00 00 00 00 00](tel:00 00 00 00 00 00 00) 00 F8 [00 00 00 00 00 00 00](tel:00 00 00 00 00 00 00) 00 F9 [00 00 00 00 00 00 00](tel:00 00 00 00 00 00 00) 00 FA [00 00 00 00 00 00 00](tel:00 00 00 00 00 00 00) 00
Green House Gas Lifetime Active Technology Tracking from Engine #1 (0): 
  Active Technology:  Vehicle Speed Limiting Technology (5), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Predictive Cruise Control (6), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Auto Neutral (7), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Mfg Defined Active Technology 5 (246), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Mfg Defined Active Technology 4 (247), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0.000 s, Vehicle Distance = 0.000 m

11:02:12.9160 Destination Specific GHGTTA Request to Engine #1 (0)
11:02:12.9199 18EA00F9 [3] 00 FB 00 (TX)
11:02:13.2373 1CFB0000 [40] [05 00 00 00 00 06 00](tel:05 00 00 00 00 06 00) [00 00 00 07 00 00 00](tel:00 00 00 07 00 00 00) 00 F6 [00 00 00 00](tel:00 00 00 00) F7 [00 00 00 00](tel:00 00 00 00) F8 [00 00 00 00](tel:00 00 00 00) F9 [00 00 00 00](tel:00 00 00 00) FA [00 00 00 00](tel:00 00 00 00)
Green House Gas Active 100 Hour Active Technology Tracking from Engine #1 (0): 
  Active Technology:  Vehicle Speed Limiting Technology (5), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Predictive Cruise Control (6), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Auto Neutral (7), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 5 (246), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 4 (247), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0.000 s, Vehicle Distance = 0.000 km

11:02:13.2393 Destination Specific GHGTTS Request to Engine #1 (0)
11:02:13.2418 18EA00F9 [3] FF FA 00 (TX)
11:02:13.5572 1CFAFF00 [40] [05 00 00 00 00 06 00](tel:05 00 00 00 00 06 00) [00 00 00 07 00 00 00](tel:00 00 00 07 00 00 00) 00 F6 [00 00 00 00](tel:00 00 00 00) F7 [00 00 00 00](tel:00 00 00 00) F8 [00 00 00 00](tel:00 00 00 00) F9 [00 00 00 00](tel:00 00 00 00) FA [00 00 00 00](tel:00 00 00 00)
Green House Gas Stored 100 Hour Active Technology Tracking from Engine #1 (0): 
  Active Technology:  Vehicle Speed Limiting Technology (5), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Predictive Cruise Control (6), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Auto Neutral (7), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 5 (246), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 4 (247), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0.000 s, Vehicle Distance = 0.000 km

11:02:13.5610 GHG Active Technology Arrays from Engine #1 (0)
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|
|                                     |    Active   |    Active   |    Stored   |    Stored   |             |             |
| Index                               |   100 Hour  |   100 Hour  |   100 Hour  |   100 Hour  |   Lifetime  |   Lifetime  |
| Description                         |    Time, m  |   Dist, km  |    Time, m  |   Dist, km  |    Time, m  |   Dist, km  |
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|
| Vehicle Speed Limiting Technology   |           0 |           0 |           0 |           0 |           0 |           0 |
| Predictive Cruise Control           |           0 |           0 |           0 |           0 |           0 |           0 |
| Auto Neutral                        |           0 |           0 |           0 |           0 |           0 |           0 |
| Mfg Defined Active Technology 5     |           0 |           0 |           0 |           0 |           0 |           0 |
| Mfg Defined Active Technology 4     |           0 |           0 |           0 |           0 |           0 |           0 |
| Mfg Defined Active Technology 3     |           0 |           0 |           0 |           0 |           0 |           0 |
| Mfg Defined Active Technology 2     |           0 |           0 |           0 |           0 |           0 |           0 |
| Mfg Defined Active Technology 1     |           0 |           0 |           0 |           0 |           0 |           0 |
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|

FAIL: 6.1.26.18.g - Active 100 hr array value received was greater than zero from Engine #1 (0) for SPN 12694, GHG Tracking Active 100 Hour Active Technology Index: Vehicle Speed Limiting Technology
/* questioned as a -84 problem, waiting for an answer */

**Comment by battjt** [comment]
Code was looking at all SPNs, including active technology index.
