### ISSUE TITLE
"Now reporting an initialize test" when test results have not changed

### ISSUE THREAD

**Issue by markmorrisoncummins** [Equipment-and-Tool-Institute/j1939-84#1226]
Maybe related to multiple test results being mapped to the same DTC? SLOT 256 and SLOT 12 never completed, SLOT 333 completed and did not clear.

6.4.12:
> 16:44:25.0736 Sending DM7 for DM30 to Engine #1 (0) for SPN 5024
16:44:25.0751 18E300F9 [8] F7 A0 13 1F FF FF FF FF (TX)
16:44:25.0856 1CA4F900 [36] F7 A0 13 0A 00 01 00 FB FF FF FF FF F7 A0 13 0A 0C 00 00 FB FF FF FF FF F7 A0 13 0A 4D 01 00 00 DE 2E 00 00
DM30 from 0: [
  SPN 5024 FMI 10 (SLOT 256) Result: Test Not Complete.
  SPN 5024 FMI 10 (SLOT 12) Result: Test Not Complete.
  SPN 5024 FMI 10 (SLOT 333) Result: Test Passed. Min: 0, Value: 0, Max: 119.98 s
]

6.4.14:
> 16:44:36.4979 Sending DM7 for DM30 to Engine #1 (0) for SPN 5024
16:44:36.5006 18E300F9 [8] FA A0 13 0A FF FF FF FF (TX)
16:44:36.5109 1CA4F900 [36] FA A0 13 0A 00 01 00 FB FF FF FF FF FA A0 13 0A 0C 00 00 FB FF FF FF FF FA A0 13 0A 4D 01 00 00 DE 2E 00 00
DM30 from 0: [
  SPN 5024 FMI 10 (SLOT 256) Result: Test Not Complete.
  SPN 5024 FMI 10 (SLOT 12) Result: Test Not Complete.
  SPN 5024 FMI 10 (SLOT 333) Result: Test Passed. Min: 0, Value: 0, Max: 119.98 s
]
FAIL: 6.4.14.2.a - Engine #1 (0) is now reporting an initialize test for SPN = 5024, FMI = 10
FAIL: 6.4.14.2.a - Engine #1 (0) is now reporting an initialize test for SPN = 5024, FMI = 10

Similar failures in 6.7.17, 6.8.14, and 6.9.6
> 16:58:07.3591 Sending DM7 for DM30 to Engine #1 (0) for SPN 5024
16:58:07.3629 18E300F9 [8] FA A0 13 0A FF FF FF FF (TX)
16:58:07.3712 1CA4F900 [36] FA A0 13 0A 00 01 00 FB FF FF FF FF FA A0 13 0A 0C 00 00 FB FF FF FF FF FA A0 13 0A 4D 01 00 00 DE 2E 00 00
DM30 from 0: [
  SPN 5024 FMI 10 (SLOT 256) Result: Test Not Complete.
  SPN 5024 FMI 10 (SLOT 12) Result: Test Not Complete.
  SPN 5024 FMI 10 (SLOT 333) Result: Test Passed. Min: 0, Value: 0, Max: 119.98 s
]
FAIL: 6.7.17.2.a - Engine #1 (0) is now reporting an initialize test for SPN = 5024, FMI = 10
FAIL: 6.7.17.2.a - Engine #1 (0) is now reporting an initialize test for SPN = 5024, FMI = 10

> 17:03:12.1105 Sending DM7 for DM30 to Engine #1 (0) for SPN 5024
17:03:12.1130 18E300F9 [8] FA A0 13 0A FF FF FF FF (TX)
17:03:12.1244 1CA4F900 [36] FA A0 13 0A 00 01 00 FB FF FF FF FF FA A0 13 0A 0C 00 00 FB FF FF FF FF FA A0 13 0A 4D 01 00 00 DE 2E 00 00
DM30 from 0: [
  SPN 5024 FMI 10 (SLOT 256) Result: Test Not Complete.
  SPN 5024 FMI 10 (SLOT 12) Result: Test Not Complete.
  SPN 5024 FMI 10 (SLOT 333) Result: Test Passed. Min: 0, Value: 0, Max: 119.98 s
]
FAIL: 6.8.14.2.a - Engine #1 (0) reported test result for SPN = 5024, FMI = 10 is now initialized
FAIL: 6.8.14.2.a - Engine #1 (0) reported test result for SPN = 5024, FMI = 10 is now initialized

> 17:04:47.0708 Sending DM7 for DM30 to Engine #1 (0) for SPN 5024
17:04:47.0749 18E300F9 [8] F7 A0 13 1F FF FF FF FF (TX)
17:04:47.0854 1CA4F900 [36] F7 A0 13 0A 00 01 00 FB FF FF FF FF F7 A0 13 0A 0C 00 00 FB FF FF FF FF F7 A0 13 0A 4D 01 00 00 DE 2E 00 00
DM30 from 0: [
  SPN 5024 FMI 10 (SLOT 256) Result: Test Not Complete.
  SPN 5024 FMI 10 (SLOT 12) Result: Test Not Complete.
  SPN 5024 FMI 10 (SLOT 333) Result: Test Passed. Min: 0, Value: 0, Max: 119.98 s
]
FAIL: 6.9.6.2.a - Engine #1 (0) reported test result for SPN = 5024, FMI = 10 is now initialized
FAIL: 6.9.6.2.a - Engine #1 (0) reported test result for SPN = 5024, FMI = 10 is now initialized

**Comment by ericthomasswenson** [comment]
Check 6.4 for collection of initialized test as part of #1130

**Comment by mmschaefer** [comment]
Dude if you need me, let me know!  Have an awesome daymmsOn Mar 3, 2023, at 1:15 PM, ericthomasswenson ***@***.***> wrote:﻿
Check 6.4 for collection of initialized test ad part of #1130

**Comment by ericthomasswenson** [comment]
This is a special case for #1039, the completed test measurements run fast.

Fix with #1039

**Comment by ericthomasswenson** [comment]
Eric to review #1039 texts in artifact to see if additional explanation is needed.

There is a footnote already to use counts of completed/initialized for SPN/FMIs returns when checking for erased/not erased test results, where multiple results are returned.

**Comment by ericthomasswenson** [comment]
Checking the counts of initialized tests as directed in the artifact footnotes is believed to be an effective strategy for this instance of #1130

**Comment by ericthomasswenson** [comment]
For example footnote 50 says:

[50] Since multiple test results can be provided for the same SPN and FMI, the number of initialized tests shall be counted for each SPN and FMI pair. Data has been observed where one or more sets of test results (measurements and limits) are observed to remain initialized throughout the set of test conditions offered in a stationary, low-load test. In these cases such tests were not erased: they never ran

**Comment by markmorrisoncummins** [comment]
This is still an issue in 3.1.24.
