### ISSUE TITLE
Add SPN 5600 to the supplemental scaling list

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1229]
SPN 5600 (J1939-31) is not included in the supplemental SPN scaling data base 

Values displayed in the freeze frame should display 0 to 255. 

6.3.13.1.c - Received from Engine #1 (0): 
  Freeze Frame: {
    Data Length: 114
    DTC 131075:27 - Unknown, Reserved For SAE Assignment - 3 times
    SPN Data: FA 00 00 00 00 01 00 00 00 4D C5 50 99 0F FA 00 63 23 96 26 00 00 C0 12 00 00 7D 7D 7D 40 38 C0 17 20 1C 60 22 40 1F AA C2 C7 DF E1 41 0A 64 3A 13 34 02 26 00 FF 63 FF 63 FF 63 FF 63 FF 63 FF 63 AE 63 DF 00 00 D3 26 A6 26 00 00 20 2C D6 26 01 00 00 00 40 9C 31 00 00 00 00 01 00 00 B6 26 A0 26 13 03 80 3E 00 00 00 00 00 00 04 DE 03 F7 03 **_27_**
...
    SPN  8619, Engine Exhaust Manifold Absolute Pressure 1: 99.000 kPa
    SPN  8620, Engine Exhaust Manifold Absolute Pressure 2: 101.500 kPa
    SPN  5600, Source Address (Network Message): **_Not Available_**             
  }

**Comment by battjt** [comment]
Displayed as not available, because there is no SLOT defined for SPN 5600, so the length is 0, so there is no attempt made to parse.  I added a SLOT definition for SPN 5600, but we should consider "guessing" a length of 1 byte or unknown SLOTs.
