### ISSUE TITLE
Big Endian Scaling used for SPN 918

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1230]
Revise to use little endian. 

PGN 65217 with Supported SPNs 917
11:01:37.2070 18FEC100 [8] FF FF FF FF 3B 6D 01 00
Found: High Resolution Vehicle Distance from Engine #1 (0): 
  SPN   917, Total Vehicle Distance (High Resolution): Not Available
  SPN   918, Trip Distance (High Resolution): 467495.000 m

00016D3Bh is 93499 or 93.499

**Comment by battjt** [comment]
00016D3Bh is 93,499 "5 m" (AKA scaling of "5 m per bit"), or 467,495 m.  Right?

**Comment by ericthomasswenson** [comment]
Not a tool issue
