### ISSUE TITLE
Eliminate excess NOx Binning and GHG Tracking queries when checking deleted data

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1232]
The text in A.5.3 intends that only the OBD ECUs that support NOx Binning and GHG Tracking should be queried.

The v 3.1.14 software queries all OBD ECUs for all GHG Tracking and NOx Binning PGNs.  Only the OBD ECUs that include the identified lead SPNs that define support for NOx binning and GHG tracking, and indicate their support should be queried. E.G.

B.	Stored 100-hour Accumulators.

The SPNs in the following PGs shall be greater than or equal the corresponding values observed in Part 2, after a DM11, or DM3 from a tool.

1.	**_Where SP 12675 for NOx Tracking Engine Activity Lifetime Fuel Consumption is supported in DM24._** (If supported)

The OBD ECUs that do not include SP 12675 in their DM24 responses need not be queried.

**Comment by battjt** [comment]
It is coded that way.  Is there a report that we can use to debug this with?
```
        if (getDataRepository().getObdModule(address).supportsSpn(12675)) {
            sectionA5NoxGhgVerifier.verifyDataSpn12675(listener,
                                                       getPartNumber(),
                                                       getStepNumber(),
                                                       packets,
                                                       isErased);
        }
```

**Comment by ericthomasswenson** [comment]
Use the data Bob sent for 2/14

Best Wishes,

Eric Swenson

**Comment by battjt** [comment]
It looks like the complaint is about this log entry 6.9.8.2.a.
```
15:36:25.9089 1CFB0200 [68] 5D 79 00 00 2F 05 00 00 F2 00 00 00 10 02 00 00 98 01 00 00 CE 06 00 00 B6 00 00 00 48 02 00 00 F0 01 00 00 E9 14 00 00 B8 00 00 00 F2 07 00 00 7A 09 00 00 CB 3C 00 00 08 01 00 00 13 03 00 00 CF 0E 00 00
NOx Tracking Engine Activity Lifetime Fuel Consumption Bins from Engine #1 (0): 
  SPN 12675, NOx Tracking Engine Activity Lifetime Fuel Consumption Bin 1 (Total): 1553,450 l
  SPN 12676, NOx Tracking Engine Activity Lifetime Fuel Consumption Bin 2 : 66,350 l
  SPN 12677, NOx Tracking Engine Activity Lifetime Fuel Consumption Bin 3 : 12,100 l
```

**Comment by ericthomasswenson** [comment]
And its buddies … for NOx binning and GHG tracking .. and observed for other deletion checks besides 6.9.8.2.a

Best Wishes,

Eric Swenson
