### ISSUE TITLE
Active Technology Displays and Outcomes incorrect in 6.11.13.12 for v3.1.14

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1233]
Tabular Display Contains NA

Outcomes are incorrect ... 

FAIL: 6.11.13.12.e - Number of active labels received differs from the number of lifetime labels
FAIL: 6.11.13.12.e - Number of stored labels received differs from the number of lifetime labels
FAIL: 6.11.13.12.f - Active labels received is not a subset of lifetime labels
FAIL: 6.11.13.12.f - Stored labels received is not a subset of lifetime labels

End Test 11.13 - NOx Binning and GHG tracking for MY2022+ Engines and Vehicles

**Comment by battjt** [comment]
See in "side by side" logs

**Comment by battjt** [comment]
@ericthomasswenson  I don't find this FAIL in any example logs that I have, including Halfman's v3114 log (which I thought was the "side-by-side" log).

**Comment by ericthomasswenson** [comment]
It would not be in the E39 side by side … as 

FAIL: 6.1.4.2.e - SP 12730 is not included in DM24 responses
WARN: 6.1.4.2.f - SP 12691 is not included in DM24 responses
Required Data Stream SPNs are not supported. SPNs: 96
Required Data Stream SPNs are not supported. SPNs: 5827
WARN: 6.1.4.3.a - SPN not supported in DM24


As the required SPs were not supported 

Best Wishes,

Eric Swenson

**Comment by ericthomasswenson** [comment]
Emailed log sent for 3.1.14

// Active Technology Tabular display missing 

// at End Test 1.26 - Data stream support verification

// and at End Test 2.17 - KOER Datastream verification

And at End Test 11.13 - NOx Binning and GHG tracking for MY2022+ Engines and Vehicles
