### ISSUE TITLE
Required Data Stream SPNs are not supported. SPNs: 12744 … Reported for CI engine.

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1234]
Required Data Stream SPNs are not supported. SPNs: 12744 

was observed on a CI engine. But, EVAP is SI only.

Please correct SP 12744, Evap. System Purge Pressure, to SI only.

Observed on 3.1.14.

**Comment by naroner** [comment]
**I'm still seeing this is 3.1.19:**

Required Data Stream SPNs are not supported. SPNs: 166
Required Data Stream SPNs are not supported. SPNs: 12748
Required Data Stream SPNs are not supported. SPNs: 3516, 3518, 7346
FAIL: 6.1.4.2.b - N.2 One or more SPNs for data stream is not supported
Required Data Stream SPNs are not supported. SPNs: 132
Required Data Stream SPNs are not supported. SPNs: 166
Required Data Stream SPNs are not supported. SPNs: 245, 917
Required Data Stream SPNs are not supported. SPNs: 4360
Required Data Stream SPNs are not supported. SPNs: **12744**
Required Data Stream SPNs are not supported. SPNs: 12750
Required Data Stream SPNs are not supported. SPNs: 12751
Required Data Stream SPNs are not supported. SPNs: 12752
Required Data Stream SPNs are not supported. SPNs: 12753
Required Data Stream SPNs are not supported. SPNs: 3516, 3518, 7346
WARN: 6.1.4.3.a - SPN not supported in DM24
Required Data Stream SPNs are not supported. SPNs: 74
Required Data Stream SPNs are not supported. SPNs: 101
INFO: 6.1.4.3.a - SPN not supported in DM24
More than one of the SPNs are reported as supported. SPNs: 110, 1637, 4076, 4193
INFO: 6.1.4.3.b - More than 1 SPN supported

**Comment by ericthomasswenson** [comment]
Still observed data to follow

**Comment by battjt** [comment]
The logic for 6.1.4.2.b is separate from the rest of the A1 table.  It was broken in multiple places.
