### ISSUE TITLE
No DM11 issued during Part 9 of the test in V3.1.16

### ISSUE THREAD

**Issue by anthonyhbest** [Equipment-and-Tool-Institute/j1939-84#1236]
See exceprt from test below showing time since code clear greater than 0 in part 9.  Looked through logs and cannot find a DM11 request from the tool in this part of the test.
![image](https://user-images.githubusercontent.com/94923793/226702536-65cfb99f-964e-41e8-aa28-17bb265018f5.png)

**Comment by ericthomasswenson** [comment]
This outcome was confirmed during a review of the log with the developer.

Start Test 9.8 - DM11: Diagnostic data clear/reset for active DTCs

// 6.8.9.1.a DS DM11 Query is correctly missing for the 1 OBD module case.
// NACK response from engine was observed on other occasions.
…
  EI-AECD Number = 47: Timer 1 = 0 minutes; Timer 2 = n/a
]

// Global DM11 from 6.9.8.5 was not observed.

End Test 9.8 - DM11: Diagnostic data clear/reset for active DTCs

Start Test 9.9 - DM21: Diagnostic readiness 2

… Also in Part 12, the global DM11 query appears to be missing.

  EI-AECD Number = 47: Timer 1 = 0 minutes; Timer 2 = n/a
]

FAIL: 6.12.10.2.b - Engine #1 (0) partially erased diagnostic information

// Global DM11 missing for 6.12.10.3

End Test 12.10 - DM11: Diagnostic data clear/reset for active DTCs

Start Test 12.11 - DM7/DM30: Command Non-Continuously Monitored Test/Scaled Test Results

**Comment by anthonyhbest** [comment]
DM11 still missing in V3.1.17.  Log shared with Joe via email.

**Comment by anthonyhbest** [comment]
Resolved with v3.1.19
