### ISSUE TITLE
Please omit DM5 bit state translation from DM5 heartbeat messages

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1237]
Please omit DM5 bit state translation from DM5 heartbeat message replies.
These are shown in the italicized text below. 
Translations for DM5 queries in test steps shall remain.

10:45:01.8170 Global DM5 **Heartbeat** Request
10:45:01.8200 18EAFFF9 [3] CE FE 00 (TX)
10:45:01.8285 18FECE03 [8] 00 00 05 00 00 00 00 00
DM5 from Transmission #1 (3): OBD Compliance: Not intended to meet OBD II requirements (5), Active Codes: 0, Previously Active Codes: 0
_Continuously Monitored System Support/Status:
    Comprehensive component    not supported,     complete
    Fuel System                not supported,     complete
    Misfire                    not supported,     complete
Non-continuously Monitored System Support/Status:
    A/C system refrigerant     not supported,     complete
    Boost pressure control sys not supported,     complete
    Catalyst                   not supported,     complete
    Cold start aid system      not supported,     complete
    Diesel Particulate Filter  not supported,     complete
    EGR/VVT system             not supported,     complete
    Evaporative system         not supported,     complete
    Exhaust Gas Sensor         not supported,     complete
    Exhaust Gas Sensor heater  not supported,     complete
    Heated catalyst            not supported,     complete
    NMHC converting catalyst   not supported,     complete
    NOx catalyst/adsorber      not supported,     complete
    Secondary air system       not supported,     complete_
// May the DM5 translations for heartbeat messages be skipped. They aren’t evaluated.
// The translations add dozens of pages to the length of the report.

**Comment by anthonyhbest** [comment]
The heartbeats are not translated in v3.1.19
