### ISSUE TITLE
Display grams, not seconds, for NOx Binning NOx Mass messages in 6.11.13.4.k.

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1239]
Display grams, not seconds, for NOx Binning NOx Mass messages in 6.11.13.4.k.

// grams not seconds for mass errors. Seconds works for engine run time.
INFO: 6.11.13.4.k - Active 100 hr system out Nox 12321 received is = 0 **_seconds_** from Engine #1 (0) for NOx Tracking Active 100 Hour System Out NOx MassBin 1 (Total)
INFO: 6.11.13.4.k - Active 100 hr system out Nox 12322 received is = 0 **_seconds_** from Engine #1 (0) for NOx Tracking Active 100 Hour System Out NOx Mass Bin 2 
INFO: 6.11.13.4.k - Active 100 hr system out Nox 12338 received is = 0 **_seconds_** from Engine #1 (0) for NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 1 (Total)
INFO: 6.11.13.4.k - Active 100 hr system out Nox 12339 received is = 0 **_seconds_** from Engine #1 (0) for NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 2

**Comment by anthonyhbest** [comment]
Correct in v3.1.19

INFO: 6.11.13.4.k - Active 100 hr system out Nox 12321 received is = 0 g from Engine #1 (0) for NOx Tracking Active 100 Hour System Out NOx Mass Bin 1 (Total)
INFO: 6.11.13.4.k - Active 100 hr system out Nox 12322 received is = 0 g from Engine #1 (0) for NOx Tracking Active 100 Hour System Out NOx Mass Bin 2 
INFO: 6.11.13.4.j - Active 100 hr system out Nox 12338 received is = 0 g from Engine #1 (0) for NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 1 (Total)
INFO: 6.11.13.4.j - Active 100 hr system out Nox 12339 received is = 0 g from Engine #1 (0) for NOx Tracking Active 100 Hour Engine Out NOx Mass Bin 2
