### ISSUE TITLE
Inconsistent "Warn"/"Info" for DM22 Response

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1242]
**Tool inconsistently applies warn/info to DM22 responses**

Start Test 9.3 - DM22: Individual clear/reset of active and previously active DTC
15:04:42.9941 Destination Specific DM22 Request to Engine #1 (0)
15:04:42.9961 18C300F9 [8] 11 FF FF FF FF FF FF FF (TX)
15:04:44.0186 Timeout - No Response
15:04:44.0186 Destination Specific DM22 Request to Engine #2 (1)
15:04:44.0221 18C301F9 [8] 11 FF FF FF FF FF FF FF (TX)
15:04:44.7671 Timeout - No Response
**WARN: 6.9.3.3.a - Engine #1 (0) did not provide DM22 CLR_PA_NACK or CLR_ACT_NACK with acknowledgement code of 0
WARN: 6.9.3.3.a - Engine #2 (1) did not provide DM22 CLR_PA_NACK or CLR_ACT_NACK with acknowledgement code of 0**
15:04:44.7725 Destination Specific DM22 Request to Exhaust Emission Controller (61)
15:04:44.7746 18C33DF9 [8] 01 FF FF FF FF 0B 11 04 (TX)
15:04:45.5211 Timeout - No Response
**INFO: 6.9.3.6.a - Exhaust Emission Controller (61) did not provide DM22 CLR_PA_NACK or CLR_ACT_NACK with acknowledgement code of 0**
15:04:45.5281 Global DM22 Request
15:04:45.5306 18C3FFF9 [8] 01 FF FF FF FF 0B 11 04 (TX)
15:04:46.2781 Timeout - No Response
15:04:46.2810 Global DM22 Request
15:04:46.2836 18C3FFF9 [8] 11 FF FF FF FF FF FF FF (TX)
15:04:47.0311 Timeout - No Response

**Comment by ericthomasswenson** [comment]
May be related to distributed effects.

 a. Info, ——  if DM22 (PG 49920) CLR_PA_NACK or CLR_ACT_NACK is not received with an acknowledgement code of 0.  b. Warn if J1939-21 NACK for PG 49920 is received.

**Comment by battjt** [comment]
It looks like the Sept 2022 edits were not applied correctly in the code.  I'll audit those.  I'm guessing it has to do with how the doc displays in google docs, sometimes to the left and sometimes to the right.
![image](https://user-images.githubusercontent.com/1972001/229166789-d0b4d132-5adb-4709-829b-45fce539233b.png)
![image](https://user-images.githubusercontent.com/1972001/229188177-f1b668bb-6579-4dab-909d-aa8e9f5c0d1d.png)

I'll audit all the changes in that batch and verify that they are applied correctly.

**Comment by battjt** [comment]
I audited other edits from Sept 19 and they have been correctly applied.  This appears to be and independent bug.
