### ISSUE TITLE
Tool Warns for Multiple ECUs Supporting the Same Monitored System

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1243]
**I propose that this is changed to an INFO instead of WARN**

14:42:49.0176 18FECE3D [8] 00 00 14 04 60 1C 60 1C
DM5 from Exhaust Emission Controller (61): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0
Continuously Monitored System Support/Status:
    Comprehensive component        supported,     complete
    Fuel System                not supported,     complete
    Misfire                    not supported,     complete
Non-continuously Monitored System Support/Status:
    A/C system refrigerant     not supported,     complete
    Boost pressure control sys not supported,     complete
    Catalyst                   not supported,     complete
    Cold start aid system      not supported,     complete
    Diesel Particulate Filter      supported, not complete
    EGR/VVT system             not supported,     complete
    Evaporative system         not supported,     complete
    Exhaust Gas Sensor             supported, not complete
    Exhaust Gas Sensor heater      supported, not complete
    Heated catalyst            not supported,     complete
    NMHC converting catalyst       supported, not complete
    NOx catalyst/adsorber          supported, not complete
    Secondary air system       not supported,     complete

14:42:49.1416 18FECE01 [8] 00 00 14 37 A0 02 A0 02
DM5 from Engine #2 (1): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0
Continuously Monitored System Support/Status:
    Comprehensive component        supported,     complete
    Fuel System                    supported, not complete
    Misfire                        supported, not complete
Non-continuously Monitored System Support/Status:
    A/C system refrigerant     not supported,     complete
    Boost pressure control sys     supported, not complete
    Catalyst                   not supported,     complete
    Cold start aid system      not supported,     complete
    Diesel Particulate Filter  not supported,     complete
    EGR/VVT system                 supported, not complete
    Evaporative system         not supported,     complete
    Exhaust Gas Sensor             supported, not complete
    Exhaust Gas Sensor heater  not supported,     complete
    Heated catalyst            not supported,     complete
    NMHC converting catalyst   not supported,     complete
    NOx catalyst/adsorber      not supported,     complete
    Secondary air system       not supported,     complete

Vehicle Composite of DM5:
    Comprehensive component        supported,     complete
    Fuel System                    supported, not complete
    Misfire                        supported, not complete
    EGR/VVT system                 supported, not complete
    Exhaust Gas Sensor heater      supported, not complete
    Exhaust Gas Sensor             supported, not complete
    A/C system refrigerant     not supported,     complete
    Secondary air system       not supported,     complete
    Evaporative system         not supported,     complete
    Heated catalyst            not supported,     complete
    Catalyst                   not supported,     complete
    NMHC converting catalyst       supported, not complete
    NOx catalyst/adsorber          supported, not complete
    Diesel Particulate Filter      supported, not complete
    Boost pressure control sys     supported, not complete
    Cold start aid system      not supported,     complete

WARN: 6.1.13.2.a (A6.2.d) - Exhaust Gas Sensor is supported by more than one OBD ECU

**Comment by ericthomasswenson** [comment]
Review with CARB. Detailed function allocation isn’t regulated.

**Comment by ericthomasswenson** [comment]
INFO accepted. Work in under current contract

**Comment by battjt** [comment]
Modify WARN to INFO in mtask8 artifact.

**Comment by ericthomasswenson** [comment]
… A.6.2.d

d. **_Info_** if any individual required monitor, except Continuous Component Monitoring (CCM) is supported by more than one OBD ECU.
