### ISSUE TITLE
CARB / EPA Check Box Missing From User Input Log Display

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1244]
CARB / EPA Check Box Missing From User Input Log Display

We added a check box to the data panel … but left the value selected out of log display 

User Data Entry: 

Engine Model Emissions Year: 2024
Number of Emissions ECUs Expected: 3
Number of CAL IDs Expected: 9
Fuel Type: Diesel vehicle
Ignition Type: Compression
Number of Trips for Fault B Implant: 1

**Comment by ericthomasswenson** [comment]
Check box display provided by IM

**Comment by battjt** [comment]
See #1107 for original request.

**Comment by ericthomasswenson** [comment]
“[Not] US/CARB” to appear after 

“Engine Model Emissions Year: 20XX”

**Comment by naroner** [comment]
@ericthomasswenson 

This appears in the logs from 3.1.22+, however it is inverted from what it should be. When the US/CARB box is checked the log file shows that it is not US/CARB:

Engine Model Emissions Year: 2024 **not US/CARB**
Number of Emissions ECUs Expected: 3
Number of CAL IDs Expected: 6
Fuel Type: Diesel vehicle
Ignition Type: Compression
Number of Trips for Fault B Implant: 1
