### ISSUE TITLE
Error status to A-1 note 1 reported as Warn instead of fail

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1251]
Error status to A-1 note 1 reported as Warn instead of fail 

Note 1 says supported data that is received in the error or not available should fail.

PGN 64501 with Supported SPNs **_8160, 8162_**
13:07:31.6569 18FBF53D [8] FF FF 00 00 FF FE 00 00
Found: AFT 1 Diesel Oxidation Catalyst 2 from Exhaust Emission Controller (61): 
  SPN  8160, AFT 1 Diesel Oxidation Catalyst Intake Pressure: Not Available
  SPN  8161, AFT 1 Diesel Oxidation Catalyst Outlet Pressure: 0.000 kPa
  SPN  8162, AFT 1 DOC Intake to DPF Outlet Delta Pressure: Error

FAIL: 6.2.17.3.a - N.1 SPN **_8160_** was received as NOT AVAILABLE from Exhaust Emission Controller (61)

WARN: 6.2.17.3.c - N.1 Exhaust Emission Controller (61) reported value for SPN **_8162_** (ERROR) is implausible

**Comment by ericthomasswenson** [comment]
Add W for warranty to 3.1.20 release issues … here and elsewhere.

**Comment by battjt** [comment]
Same reporting was used for N.1 and N.8.  I separated them making N.1 a FAIL and leaving N.8 a WARN.
