### ISSUE TITLE
FFh interpreted as greater than zero for all pending count

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1252]
FFh interpreted as greater than zero for all pending count

Start Test 3.4 - DM29: Regulated DTC counts
13:10:47.7949 Global DM29 Request
13:10:47.7969 18EAFFF9 [3] 00 9E 00 (TX)
13:10:47.8039 189EFF3D [8] 01 **_FF_** 00 00 00 FF FF FF
DM29 from Exhaust Emission Controller (61): 
Emission-Related Pending DTC Count                               1
All Pending DTC Count                                not available
Emission-Related MIL-On DTC Count                                0
Emission-Related Previously MIL-On DTC Count                     0
Emission-Related Permanent DTC Count                             0

13:10:47.8099 189EFF01 [8] 01 **_FF_** 00 00 00 FF FF FF
DM29 from Engine #2 (1): 
Emission-Related Pending DTC Count                               1
All Pending DTC Count                                not available
Emission-Related MIL-On DTC Count                                0
Emission-Related Previously MIL-On DTC Count                     0
Emission-Related Permanent DTC Count                             0

WARN: 6.3.4.3.a - Engine #2 (1) reported > 1 for **_all pending DTC count_**
WARN: 6.3.4.3.a - Exhaust Emission Controller (61) reported > 1 _**for all pending DTC count**_
WARN: 6.3.4.3.b - More than one ECU reported > 0 for pending DTC count
WARN: 6.3.4.3.b - More than one ECU reported > 0 **for all pending DTC count**

**Comment by ericthomasswenson** [comment]
Also no ecu reported an all pending count.

**Comment by battjt** [comment]
Is there action to take concerning this?
> Also no ecu reported an all pending count.

**Comment by battjt** [comment]
6.1.22.2.a,b (and 6.2.12.2.a,b) reference the value '0', but 6.1.22.2.c says "greater than 0'.  0xFF is not "greater than zero".  In this case should it be "not zero"?
> 6.1.22.2.c. For non-OBD ECUs, fail if any ECU reports pending, MIL-on, previously MIL-on or permanent DTC count greater than 0

[EDIT:] The artifact (and resulting implementation) is correct because:
>All Pending (DM27) is not required to be supported in the regulation.
> (DM6, DM12, DM23, DM28 are required)
