### ISSUE TITLE
If equipped, SPN 101 fails when modeled data is provided and not measured

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1254]
The engine is not equipped with a crankcase pressure sensor and is assessed a failure for not supporting SPN 101 in DM24.  Crankcase pressure is defined in the (if equipped) section in the regulation, thus failure to support data when not equipped seems harsh. Fail if provided when not supported should be Warn, instead. 

101 (24)	Engine Crankcase Pressure (CI)	65263	500 ms	No	Info	No	Fail	Fail	**_Fail_**	NA	NA

**Comment by ericthomasswenson** [comment]
Perhaps downgrade in conjunction with #1263

**Comment by ericthomasswenson** [comment]
Reconsider with DM24 SPN packing rules.

**Comment by battjt** [comment]
![image](https://github.com/Equipment-and-Tool-Institute/j1939-84/assets/1972001/29cd1e94-44ea-4f6f-9dfc-9fbdfc27684f)
Column 10, 
![image](https://github.com/Equipment-and-Tool-Institute/j1939-84/assets/1972001/2c5eba6c-e95c-401e-b3b7-d1c7d2e587cc)
,  should be WARN.
