### ISSUE TITLE
DM29 Erasure Detected yet the query matches the expected standard 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1258]
The queried data is 

08:01:22.4946 Destination Specific DM29 Request to Engine #1 (0)
08:01:22.4984 18EA00F9 [3] 00 9E 00 (TX)
08:01:22.5276 189EF900 [8] 00 00 00 00 00 FF FF FF
DM29 from Engine #1 (0): 
Emission-Related Pending DTC Count                               0
All Pending DTC Count                                            0
Emission-Related MIL-On DTC Count                                0
Emission-Related Previously MIL-On DTC Count                     0
Emission-Related Permanent DTC Count                             0
FAIL: 6.12.10.2.b - Engine #1 (0) erased DM29 data
// This is the expected state when there are no faults
// and matches the prior query data earlier in part 12 test 5. 
// SPN 629 FMI 22 is detected but its count doesn’t belong here.   
// One active DTC count shows up in the next query. 

The standard should be

Start Test 12.5 - DM29: Regulated DTC Counts
08:01:08.8510 Global DM29 Request
08:01:08.8541 18EAFFF9 [3] 00 9E 00 (TX)
08:01:08.8876 189EFF00 [8] 00 00 00 00 00 FF FF FF
DM29 from Engine #1 (0): 
Emission-Related Pending DTC Count                               0
All Pending DTC Count                                            0
Emission-Related MIL-On DTC Count                                0
Emission-Related Previously MIL-On DTC Count                     0
Emission-Related Permanent DTC Count                             0

End Test 12.5 - DM29: Regulated DTC Counts

**Comment by ericthomasswenson** [comment]
Start Test 11.4 - DM29: Regulated DTC counts
07:47:08.4613 Global DM29 Request
07:47:08.4646 18EAFFF9 [3] 00 9E 00 (TX)
07:47:09.2116 Timeout - No Response
FAIL: 6.11.4.2.b - No ECU reported > 0 for permanent DTC
// Global DM29 timed out … was generally reliable before. 

End Test 11.4 - DM29: Regulated DTC counts

**Comment by battjt** [comment]
Not reproducible.

July 23, 2023 "When the fault was implanted in the PIM instead of the engine...The DM29 erasure complaint didn’t recur."
