### ISSUE TITLE
DM5 Erasure Detected yet the response matches the expected standard.

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1259]
DM5 Erasure Detected yet the response matches the expected standard.

Detected Failure:

12:58:50.0106 Destination Specific DM5 Request to Engine #1 (0)
12:58:50.0137 18EA00F9 [3] CE FE 00 (TX)
12:58:50.0234 18FECE00 [8] 00 00 14 27 E0 0E E0 0E
DM5 from Engine #1 (0): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0
Continuously Monitored System Support/Status:
    Comprehensive component        supported,     complete
    Fuel System                    supported, not complete
    Misfire                        supported,     complete
Non-continuously Monitored System Support/Status:
    A/C system refrigerant     not supported,     complete
    Boost pressure control sys     supported, not complete
    Catalyst                   not supported,     complete
    Cold start aid system      not supported,     complete
    Diesel Particulate Filter      supported, not complete
    EGR/VVT system                 supported, not complete
    Evaporative system         not supported,     complete
    Exhaust Gas Sensor             supported, not complete
    Exhaust Gas Sensor heater      supported, not complete
    Heated catalyst            not supported,     complete
    NMHC converting catalyst   not supported,     complete
    NOx catalyst/adsorber          supported, not complete
    Secondary air system       not supported,     complete
FAIL: 6.7.16.2.a - Engine #1 (0) erased DM5 data

Candidate Standard:

Start Test 7.6 - DM5: Diagnostic readiness 1
12:58:34.1434 Global DM5 Request
12:58:34.1451 18EAFFF9 [3] CE FE 00 (TX)
12:58:34.1526 18FECE00 [8] 00 00 14 27 E0 0E E0 0E
DM5 from Engine #1 (0): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0
Continuously Monitored System Support/Status:
    Comprehensive component        supported,     complete
    Fuel System                    supported, not complete
    Misfire                        supported,     complete
Non-continuously Monitored System Support/Status:
    A/C system refrigerant     not supported,     complete
    Boost pressure control sys     supported, not complete
    Catalyst                   not supported,     complete
    Cold start aid system      not supported,     complete
    Diesel Particulate Filter      supported, not complete
    EGR/VVT system                 supported, not complete
    Evaporative system         not supported,     complete
    Exhaust Gas Sensor             supported, not complete
    Exhaust Gas Sensor heater      supported, not complete
    Heated catalyst            not supported,     complete
    NMHC converting catalyst   not supported,     complete
    NOx catalyst/adsorber          supported, not complete
    Secondary air system       not supported,     complete

See #1258 for DM29 example

**Comment by battjt** [comment]
Note for development: May have been fixed with commit [327c5147fa0ad543fb6948f0062cac9c931ab2ce](https://github.com/Equipment-and-Tool-Institute/j1939-84/commit/327c5147fa0ad543fb6948f0062cac9c931ab2ce)

**Comment by ericthomasswenson** [comment]
The complaint was observed on 3.1.20 … cannot say what version the commit string means.

Best Wishes,

Eric Swenson

**Comment by battjt** [comment]
In 3.1.20, the test for "was erased" didn't correctly include the "if engine model year less that 2019 ignore the misfire test".  So, the failure for "erased DM5 data" was incorrectly reported, even though the previous was erased (except for the misfire) and current was erased.

It was fixed as part of https://github.com/Equipment-and-Tool-Institute/j1939-84/issues/1246
