### ISSUE TITLE
Consider Switch to GRAAL-VM 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1262]
Incorporates 64_bit Java Virtual Machine into .exe

Avoids Java runtime environment installation 

Requires 64-bit adaptor .DLL

**Comment by ericthomasswenson** [comment]
Joe to confirm with additional adapters. (Vector next).

**Comment by battjt** [comment]
Vector does not support a 64 bit RP1210 adapter.

**Comment by ericthomasswenson** [comment]
Is there a 32-bit equivalent?

At this time, the opinion is to keep compatibility with Vector HW/SW.

**Comment by battjt** [comment]
There is no 32 bit equivalent.

**Comment by ericthomasswenson** [comment]
I guess we wait then, and ask Peter, when that might happen
