### ISSUE TITLE
Required Data Stream Info instead of Warn

### ISSUE THREAD

**Issue by anthonyhbest** [Equipment-and-Tool-Institute/j1939-84#1263]
@ericthomasswenson, is it possible to have some of the lesser supported SPNs changed from _Warn_ to _Info_ in the tool, for instance, SPN 12758 "Target Fresh Air Mass Flow"?
Some manufacturers may be utilizing this message, but it is not commonly utilized on CI engines.  This results in a _Warn_ from the tool, but since the regulations states "For all engines so equipped" at the beginning of section (h)4.2.3 would it be possible to adjust this to an _Info_?

**Comment by ericthomasswenson** [comment]
Eric will review v. Table A-1 and respond with a new comment.
No other participants object to this suggestion.

**Comment by battjt** [comment]
Waiting on verification from Halfman.

**Comment by ericthomasswenson** [comment]
13 CCR 1971.1 (h)(4.2.3) For all engines so equipped: 
(h)(4.2.3)(G) For _**2024**_ and subsequent model year engines, commanded DEF dosing, DEF dosing mode (A, B, C, etc.), DEF dosing rate, DEF usage for current driving cycle, target ammonia storage level on SCR, modeled actual ammonia storage level on SCR, SCR intake temperature, SCR outlet temperature, stability of NOx sensor reading, _**EGR mass flow rate,**_ engine fuel rate, vehicle fuel rate, hydrocarbon doser flow rate, hydrocarbon doser injector duty cycle, aftertreatment fuel pressure, charge air cooler outlet temperature, propulsion system active, chassis odometer reading, engine odometer reading (if available), hybrid/EV charging state, hybrid/EV battery system voltage, hybrid/EV battery system current, **_commanded/target fresh air flow_**, crankcase pressure sensor output, crankcase oil separator rotational speed, evaporative system purge pressure sensor output, and vehicle speed limiter speed limit.

**Comment by ericthomasswenson** [comment]
The subject line is marked CI and 2024.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40"><div align="center" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">
| 12758 (24) | Target Fresh Air Mass Flow (CI) | 61450 | 50 ms | No | Warn(CI) | No | Fail | Fail | Fail | NA | NA |

</div></html>


There is an argument whether SPN 12758 is or is not the best ‘lead’ SPN for PG 61450.
If not, then column 10 would be better coded as Warn instead of Fail, when PG 61450 is provided including SPN 12758.

**Comment by ericthomasswenson** [comment]
Other SPs included in PG 61450:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40"><div align="center" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">
| 2659 (24) | Engine Exhaust Gas Recirculation 1 Mass Flow Rate | 61450 | 50 ms | No | Warn | No | Fail | Fail | Fail | > 0 | NA |

</div></html>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40"><div align="center" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">
| 132 | Engine Intake Air Mass Flow Rate | 61450 | BC 50ms | No | Warn | Warn | Fail | Fail | Warn | > 0.20 kg/hr | <= 0 kg/hr |

</div></html>

**Comment by ericthomasswenson** [comment]
Of these, SPN 132 would appear to be the better lead SP when supported … followed by SPN 2659.

**Comment by ericthomasswenson** [comment]
Whereas logical alternatives to SPN 12758 as the lead SPN for PG 12758 exist, column 10 is better coded as Warn for SPN 12758. 

| 12758 (24) | Target Fresh Air Mass Flow (CI) | 61450 | 50 ms | No | Warn(CI) | No | Fail | Fail | **_Warn_** | NA | NA |

**Comment by ericthomasswenson** [comment]
Also change 2659 to warn.

| 2659 (24) | Engine Exhaust Gas Recirculation 1 Mass Flow Rate | 61450 | 50 ms | No | Warn | No | Fail | Fail | **_Warn_** | > 0 | NA |

**Comment by ericthomasswenson** [comment]
Also delete (CI) from 

| 12758 (24) | Target Fresh Air Mass Flow (CI) | 61450 | 50 ms | No | Warn(CI) | No | Fail | Fail | **_Warn_** | NA | NA |

in addition to changing Fail to Warn in ‘column 10’.
