### ISSUE TITLE
Hybrid System Controller not counted as OBD Module. 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1265]
Hybrid System Controller not counted as OBD Module. 

For 3.1.22 only the engine was counted.

**Comment by ericthomasswenson** [comment]
6.1.13 Responses.

Start Test 1.13 - DM5: Diagnostic Readiness 1: Monitor Readiness
17:37:55.1489 Global DM5 Request
17:37:55.1508 18EAFFF9 [3] CE FE 00 (TX)
17:37:55.1540 18FECE00 [8] 00 00 14 37 E0 1E E0 1E
DM5 from Engine #1 (0): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0

17:37:55.1685 18FECE5A [8] 00 FF 14 04 00 00 00 00
DM5 from Powertrain Control Module (90): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: not available

// Why isn't SA90 not counted as OBD device 2

17:37:55.9106 Destination Specific DM5 Request to Engine #1 (0)
17:37:55.9127 18EA00F9 [3] CE FE 00 (TX)
17:37:55.9194 18FECE00 [8] 00 00 14 37 E0 1E E0 1E
DM5 from Engine #1 (0): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes

... add DS query and display

**Comment by ericthomasswenson** [comment]
User Data Entry: 

Engine Model Emissions Year: 2023 not US/CARB
Number of Emissions ECUs Expected: 2
Number of CAL IDs Expected: 14
Fuel Type: Hybrid vehicle using diesel engine
Ignition Type: Compression
Number of Trips for Fault B Implant: 1

Vehicle Information:
VIN: 5FYH8YU08PB107655
Vehicle MY: 2023
Engine MY: 2023
Cert. Engine Family: ISL 2023MY Gen 2.5 Hybrid
**_Number of OBD ECUs Found: 1_**

**Comment by battjt** [comment]
The list of OBD modules is created in 6.1.3.1.  Any chance there was a failure during that step?  to diagnose, I'll need the section of the report that includes at least 6.1.3 and everything from the start to 6.1.13 would be helpful.

**Comment by battjt** [comment]
Before asking for a .ASC log, verify that the .ASC log contains the query used for "Number of OBD ECUs Found:".

**Comment by karysg** [comment]
I've confirmed that .ASC logging begins before the requests used for "Number of OBD ECUs Found:". I think the code is relying partly on Component ID responses to make the list, we might not be receiving one from the PCM.

I'll need the output and .ASC log from the the start of all tests through the end of 6.1.13 to confirm.
