### ISSUE TITLE
Address SA 90 display using N/A for DM26 where SA 0 provides the data

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1266]
Address SA 90 as Part of Centralized DTC Count Reporting 

Hybrid Controller SA 90 also swept up in this distributed system issue.

Here for DM26. See #1256 and #1257

**Comment by ericthomasswenson** [comment]
Start Test 1.14 - DM26: Diagnostic readiness 3
17:37:55.9395 Global DM26 Request
17:37:55.9410 18EAFFF9 [3] B8 FD 00 (TX)
17:37:55.9443 18FDB800 [8] 00 00 00 37 E0 1E E0 1E
DM26 from Engine #1 (0): Warm-ups: 0, Time Since Engine Start: 0 seconds

17:37:55.9588 18FDB85A [8] FF FF FF 04 00 00 00 00   
DM26 from Powertrain Control Module (90): Warm-ups: not available, Time Since Engine Start: not available

FAIL: 6.1.14.2.e - Powertrain Control Module (90) response indicates number of warm-ups since code clear is not zero
FAIL: 6.1.14.2.f - Powertrain Control Module (90) response indicates time since engine start is not zero
17:37:56.7017 Destination Specific DM26 Request to Engine #1 (0)
17:37:56.7055 18EA00F9 [3] B8 FD 00 (TX)
17:37:56.7090 18FDB800 [8] 00 00 00 37 E0 1E E0 1E
DM26 from Engine #1 (0): Warm-ups: 0, Time Since Engine Start: 0 seconds
17:37:56.7096 Destination Specific DM26 Request to Powertrain Control Module (90)
17:37:56.7126 18EA5AF9 [3] B8 FD 00 (TX)
17:37:56.7285 18FDB85A [8] FF FF FF 04 00 00 00 00
DM26 from Powertrain Control Module (90): Warm-ups: not available, Time Since Engine Start: not available

End Test 1.14 - DM26: Diagnostic readiness 3

**Comment by ericthomasswenson** [comment]
Greater than zero when referring to NOx Binning and GHG Tracking array values does not presume that unsupported using (FFFFh, FFFFFFFFh) will be provided.  For DM21, D26 and DM29, FFh, FFFFh, indicate that the value is not supported ... one device may provide a single answer for the system in such cases.

**Comment by ericthomasswenson** [comment]
Please correct FFFFFh observed for DM26 where it is believed this will not confound other centralized reporting work in Task 8.

**Comment by ericthomasswenson** [comment]
Needs work … any … v FFFFh

e.	Fail if any response indicates number of warm-ups since code clear (WU-SCC) (SP 3302) is not zero. 
f.	Fail if any response indicates time since engine start (SP 3301) is not zero.
g.	Fail if no OBD ECU provides DM26.
// SOW Confirmed existing criteria. Check Unit Tests vs. confirmation analysis in SOW.

**Comment by battjt** [comment]
proposed 6.1.14.2
e. Fail if any response indicates number of warm-ups since code clear (WU-SCC) (SP 3302) is not zero or FFh.
f. Fail if any response indicates time since engine start (SP 3301) is not zero or FFFFh.

**Comment by ericthomasswenson** [comment]
DM26 needed the same treatment as DM21 to ensure at both required counters were supported. This is shown below. Revised text is in bold italic.

6.1.14.2	Fail Criteria.    // C3
a.	Fail if any response for any monitor supported in DM5 by a given ECU is reported as “0=monitor complete this cycle or not supported” in SP 3303 bits 1-4 and SP 3305 [except comprehensive components monitor (CCM) and Misfire Monitoring for 2019+ MY engines].)].                         // #1205 and except misfire for MY 2019+ engines.
b.	Fail if any response for each monitor not supported in DM5 by a given ECU is also reported in DM26 as “1=monitor not complete this monitoring cycle” in SP 3303 bits 5-7.
c.	Fail if any response for each monitor not supported in DM5 by a given ECU is also reported in DM26 as “0=monitor enabled for this monitoring cycle” in SP 3303 bits 1 and 2 and SP 3304.
d.	Fail if any response from an ECU indicating support for CCM monitor in DM5 reports “0=monitor disabled for rest of this cycle or not supported” in SP 3303 bit 3. 
**_e.	Fail, if no response supports warm-ups since code clear (WU-SCC) (SP 3302).   // #1266
f.	Fail, if no response supports time since engine start (SP 3301)
g.	Fail if any response indicates number of warm-ups since code clear (WU-SCC) (SP 3302) is not zero. (if supported)
h.     Fail if any response indicates time since engine start (SP 3301) is not zero. (if supported)_**
i.	Fail if no OBD ECU provides DM26.

**Comment by ericthomasswenson** [comment]
The plurality of other DM26 criteria and actions added (where supported), which indicates that the action or criteria should ignore responses where the SPN listed is FFFFh. The new criteria in 6.1.14.2 ensures that the counters are supported.
