### ISSUE TITLE
Unsupported DM56 in MY2024

### ISSUE THREAD

**Issue by markmorrisoncummins** [Equipment-and-Tool-Institute/j1939-84#1271]
Unsupported DM56 does not fail for MY2024.

> Vehicle Information:
> VIN: 3HSPAAPR2NN233910
> Vehicle MY: 2022
> Engine MY: 2024

...
> Test 1.6 - DM56: Model year and certification engine family............(PASS)

...
> End Test 1.5 - PGN 65260 VIN verification
> 
> Start Test 1.6 - DM56: Model year and certification engine family
> 12:58:27.7622 Global DM56 Request
> 12:58:27.7649 18EAFFF9 [3] C7 FC 00 (TX)
> 12:58:28.5132 Timeout - No Response
> 6.1.6.1.a - DM56 is not supported
> 
> End Test 1.6 - DM56: Model year and certification engine family

I poked around the code a little bit, should this (in Part01Step06Controller.java) be "engineModelYear >= 2024" instead of strictly greater?

```
if (packets.isEmpty()) {
    if (engineModelYear > 2024) {
        addFailure("6.1.6.2.f - MY2024+ Engine does not support DM56");
    } else {
        getListener().onResult("6.1.6.1.a - DM56 is not supported");
    }
    return;
}
```

**Comment by ericthomasswenson** [comment]
Observed MY should exactly match user data entered.
Responses required of 2024, 2025, and so on engine model years.
