### ISSUE TITLE
Error in DM56 Check

### ISSUE THREAD

**Issue by markmorrisoncummins** [Equipment-and-Tool-Institute/j1939-84#1272]
We have a MY2024 engine that does not have DM56 configured yet, and instead of failing as expected, the tool seems to error out of all of the DM56 checks. In the summary, 1.6 gets marked as (PASS) even though it is clearly incorrectly formatted.

> Vehicle Information:
> VIN: 1NPBDH9X0FD256399
> Vehicle MY: 2015
> Engine MY: 2024

...
> Test 1.6 - DM56: Model year and certification engine family............(PASS)

...
> Start Test 1.6 - DM56: Model year and certification engine family
> 15:03:00.7998 Global DM56 Request
> 15:03:00.8020 18EAFFF9 [3] C7 FC 00 (TX)
> 15:03:00.9693 1CFCC700 [21] 4E 6F 74 5F 41 76 61 69 4E 6F 74 5F 41 76 61 69 6C 61 62 6C 65
> Model Year and Certification Engine Family from Engine #1 (0): 
> Model Year: Not_Avai
> Family Name: Not_Available
> 
> ERROR: Error: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.etools.j1939tools.j1939.packets.DM56EngineFamilyPacket.getEngineModelYear()" is null
> 
> End Test 1.6 - DM56: Model year and certification engine family

**Comment by ericthomasswenson** [comment]
e.g., “2013E-MY” is correct format so fail if doesn’t have xxxxE-MY with xxxx matching MY entered by user or any difference to “E-MY“
