### ISSUE TITLE
6.1.6 DM56 MY False Failure 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1298]
End Test 1.5 - PGN 65260 VIN verification

Log shows a 2024 MY engine was selected … yet a returns starting with 2024E- was not accepted.
Engine serial numbers do not have standardized MY prefixes, like VINs 

Start Test 1.6 - DM56: Model year and certification engine family
12:48:27.3332 Global DM56 Request
12:48:27.3340 18EAFFF9 [3] C7 FC 00 (TX)
12:48:27.4184 1CFCC700 [21] 32 30 32 34 45 2D 4D 59 52 4E 56 58 48 30 37 37 35 30 53 41 00
Model Year and Certification Engine Family from Engine #1 (0): 
Model Year: **_2024E_**-MY
Family Name: RNVXH07750SA

FAIL: 6.1.6.2.a - Engine **model year** does not match user input
FAIL: 6.1.6.2.d - MY designation in engine family (1st digit) does not match user MY input
/* these look like new -84 issues
End Test 1.6 - DM56: Model year and certification engine family

…

User Data Entry: 

Engine Model Emissions Year: **2024** not US/CARB
Number of Emissions ECUs Expected: 3
Number of CAL IDs Expected: 9
Fuel Type: Diesel vehicle
Ignition Type: Compression
Number of Trips for Fault B Implant: 1

Vehicle Information:
VIN: 3HSPCTZT6NN579683	/* JTC, DV22, black HX
Vehicle MY: 2022
Engine MY: 2024
Cert. Engine Family: E44 RC1 test with DrewLinQ
Number of OBD ECUs Found: 3
     Make: INT  , Model: 00101360N1, Serial: 
     Make: INT  , Model: 4269045C1 , Serial: XXXXXXXXXX
     Make: INT  , Model: 00106039N1, Serial: 
Number of CAL IDs Found: 9
     DM19 from Engine #1 (0): [
       CAL ID of 84m4422fBF01E and CVN of 0xFCE60102
       CAL ID of 5843S006.005 and CVN of 0x00006C3F
       CAL ID of SCANOxN-0440ATI2 and CVN of 0x8CDF2B15
       CAL ID of SCANOxN-0440ATO2 and CVN of 0xFBD45961
       CAL ID of SCANOxN-0440ATI2 and CVN of 0x8CDF2B15
       CAL ID of PMSP*12*350*A100 and CVN of 0x3790FC8A
       CAL ID of 018800610Q and CVN of 0xC44590C2
     ]
     DM19 from Management Computer #1 (39): CAL ID of SXXXBFKA and CVN of 0x858E76B8
     DM19 from Exhaust Emission Controller (61): CAL ID of 544416fXX01E and CVN of 0xEDB8F1E8

Addresses Claimed

…

Start Test 1.9 - Component ID: Make
12:48:29.7279 Destination Specific CI Request to Engine #1 (0)
12:48:29.7286 18EA00F9 [3] EB FE 00 (TX)
12:48:29.7511 1CFEEB00 [33] 49 4E 54 20 20 2A 30 30 31 30 31 33 36 30 4E 31 2A 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2A 2A
Component Identification from Engine #1 (0): {
  Make: INT
  Model: 00101360N1
  Serial: 
  Unit: 
}

12:48:29.7530 Destination Specific CI Request to Management Computer #1 (39)
12:48:29.7529 18EA27F9 [3] EB FE 00 (TX)
12:48:29.7820 1CFEEB27 [29] 49 4E 54 20 20 2A 34 32 36 39 30 34 35 43 31 20 2A 58 58 58 58 58 58 58 58 58 58 2A 2A
Component Identification from Management Computer #1 (39): {
  Make: INT
  Model: 4269045C1
  Serial: XXXXXXXXXX
  Unit: 
}

12:48:29.7838 Destination Specific CI Request to Exhaust Emission Controller (61)
12:48:29.7849 18EA3DF9 [3] EB FE 00 (TX)
12:48:29.8249 1CFEEB3D [33] 49 4E 54 20 20 2A 30 30 31 30 36 30 33 39 4E 31 2A 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2A 2A
Component Identification from Exhaust Emission Controller (61): {
  Make: INT
  Model: 00106039N1
  Serial: 
  Unit: 
}

Function 0 ECU is Unknown (-1)
FAIL: 6.1.9.2.b - None of the positive responses were provided by Unknown (-1)

 <<PAGE BREAK>>

**Comment by ericthomasswenson** [comment]
See #1272

**Comment by karysg** [comment]
This bug is likely fixed by commit 70c21306
