### ISSUE TITLE
List of Claimed Addresses is Missing from this log

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1299]
List of Claimed Addresses is Missing from this log

Summary of J1939-84 Tool Execution

J1939-84 Tool version 3.1.24 - 2023/11/10 09:11
Generated: 2023/12/21 13:37:27.7903
Log File Name: C:\CdriveSave\new j1939-84\E44 RC1 test v3124 DrewLinQ.txt

TEST SUMMARY REPORT
OUTCOME: 
Failures:    49
Warnings:    22
Information: 34
Incomplete:  0
Timing:      0
Passes:      141

User Data Entry: 

Engine Model Emissions Year: 2024 not US/CARB
Number of Emissions ECUs Expected: 3
Number of CAL IDs Expected: 9
Fuel Type: Diesel vehicle
Ignition Type: Compression
Number of Trips for Fault B Implant: 1

Vehicle Information:
VIN: 3HSPCTZT6NN579683	/* JTC, DV22, black HX
Vehicle MY: 2022
Engine MY: 2024
Cert. Engine Family: E44 RC1 test with DrewLinQ
Number of OBD ECUs Found: 3
     Make: INT  , Model: 00101360N1, Serial: 
     Make: INT  , Model: 4269045C1 , Serial: XXXXXXXXXX
     Make: INT  , Model: 00106039N1, Serial: 
Number of CAL IDs Found: 9
     DM19 from Engine #1 (0): [
       CAL ID of 84m4422fBF01E and CVN of 0xFCE60102
       CAL ID of 5843S006.005 and CVN of 0x00006C3F
       CAL ID of SCANOxN-0440ATI2 and CVN of 0x8CDF2B15
       CAL ID of SCANOxN-0440ATO2 and CVN of 0xFBD45961
       CAL ID of SCANOxN-0440ATI2 and CVN of 0x8CDF2B15
       CAL ID of PMSP*12*350*A100 and CVN of 0x3790FC8A
       CAL ID of 018800610Q and CVN of 0xC44590C2
     ]
     DM19 from Management Computer #1 (39): CAL ID of SXXXBFKA and CVN of 0x858E76B8
     DM19 from Exhaust Emission Controller (61): CAL ID of 544416fXX01E and CVN of 0xEDB8F1E8

Addresses Claimed

 <<PAGE BREAK>>

**Comment by ericthomasswenson** [comment]
Missing function may also explain the errors below.

Start Test 2.5 - DM19: Calibration information
12:50:28.6900 Destination Specific DM19 Request to Engine #1 (0)
12:50:28.6912 18EA00F9 [3] 00 D3 00 (TX)
12:50:28.7457 1CD3F900 [140] 02 01 E6 FC 38 34 6D 34 34 32 32 66 42 46 30 31 45 00 00 00 3F 6C 00 00 35 38 34 33 53 30 30 36 2E 30 30 35 00 00 00 00 15 2B DF 8C 53 43 41 4E 4F 78 4E 2D 30 34 34 30 41 54 49 32 61 59 D4 FB 53 43 41 4E 4F 78 4E 2D 30 34 34 30 41 54 4F 32 15 2B DF 8C 53 43 41 4E 4F 78 4E 2D 30 34 34 30 41 54 49 32 8A FC 90 37 50 4D 53 50 2A 31 32 2A 33 35 30 2A 41 31 30 30 C2 90 45 C4 30 31 38 38 30 30 36 31 30 51 20 20 20 20 20 00
DM19 from Engine #1 (0): [
  CAL ID of 84m4422fBF01E and CVN of 0xFCE60102
  CAL ID of 5843S006.005 and CVN of 0x00006C3F
  CAL ID of SCANOxN-0440ATI2 and CVN of 0x8CDF2B15
  CAL ID of SCANOxN-0440ATO2 and CVN of 0xFBD45961
  CAL ID of SCANOxN-0440ATI2 and CVN of 0x8CDF2B15
  CAL ID of PMSP*12*350*A100 and CVN of 0x3790FC8A
  CAL ID of 018800610Q and CVN of 0xC44590C2
]
12:50:28.7472 Destination Specific DM19 Request to Management Computer #1 (39)
12:50:28.7474 18EA27F9 [3] 00 D3 00 (TX)
12:50:28.7683 1CD3F927 [20] B8 76 8E 85 53 58 58 58 42 46 4B 41 00 00 00 00 00 00 00 00
DM19 from Management Computer #1 (39): CAL ID of SXXXBFKA and CVN of 0x858E76B8
12:50:28.7700 Destination Specific DM19 Request to Exhaust Emission Controller (61)
12:50:28.7701 18EA3DF9 [3] 00 D3 00 (TX)
12:50:28.8107 1CD3F93D [20] E8 F1 B8 ED 35 34 34 34 31 36 66 58 58 30 31 45 00 00 00 00
DM19 from Exhaust Emission Controller (61): CAL ID of 544416fXX01E and CVN of 0xEDB8F1E8

End Test 2.5 - DM19: Calibration information

Start Test 2.6 - DM56: Model year and certification engine family
12:50:28.8135 Destination Specific DM56 Request to Engine #1 (0)
12:50:28.8141 18EA00F9 [3] C7 FC 00 (TX)
12:50:28.8348 1CFCC700 [21] 32 30 32 34 45 2D 4D 59 52 4E 56 58 48 30 37 37 35 30 53 41 00
Model Year and Certification Engine Family from Engine #1 (0): 
Model Year: 2024E-MY
Family Name: RNVXH07750SA
12:50:28.8358 Destination Specific DM56 Request to Management Computer #1 (39)
12:50:28.8368 18EA27F9 [3] C7 FC 00 (TX)
12:50:28.8383 18E8FF27 [8] 01 FF FF FF F9 C7 FC 00
Acknowledgment from Management Computer #1 (39): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64711
12:50:28.8393 Destination Specific DM56 Request to Exhaust Emission Controller (61)
12:50:28.8391 18EA3DF9 [3] C7 FC 00 (TX)
12:50:28.8591 1CE8FF3D [8] 01 FF FF FF F9 C7 FC 00
Acknowledgment from Exhaust Emission Controller (61): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64711

End Test 2.6 - DM56: Model year and certification engine family

Start Test 2.7 - Component ID: Make
12:50:28.8639 Destination Specific CI Request to Engine #1 (0)
12:50:28.8652 18EA00F9 [3] EB FE 00 (TX)
12:50:28.8977 1CFEEB00 [33] 49 4E 54 20 20 2A 30 30 31 30 31 33 36 30 4E 31 2A 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2A 2A
Component Identification from Engine #1 (0): {
  Make: INT
  Model: 00101360N1
  Serial: 
  Unit: 
}

12:50:28.8981 Destination Specific CI Request to Management Computer #1 (39)
12:50:28.8990 18EA27F9 [3] EB FE 00 (TX)
12:50:28.9283 1CFEEB27 [29] 49 4E 54 20 20 2A [34 32 36 39 30 34 35](tel:34 32 36 39 30 34 35) 43 31 20 2A [58 58 58 58 58 58 58](tel:58 58 58 58 58 58 58) 58 58 58 2A 2A
Component Identification from Management Computer #1 (39): {
  Make: INT
  Model: 4269045C1
  Serial: XXXXXXXXXX
  Unit: 
}

12:50:28.9290 Destination Specific CI Request to Exhaust Emission Controller (61)
12:50:28.9298 18EA3DF9 [3] EB FE 00 (TX)
12:50:28.9704 1CFEEB3D [33] 49 4E 54 20 20 2A [30 30 31 30 36 30 33](tel:30 30 31 30 36 30 33) 39 4E 31 2A [00 00 00 00 00 00 00](tel:00 00 00 00 00 00 00) [00 00 00 00 00 00 00](tel:00 00 00 00 00 00 00) 2A 2A
Component Identification from Exhaust Emission Controller (61): {
  Make: INT
  Model: 00106039N1
  Serial: 
  Unit: 
}

FAIL: 6.2.7.2.d - No Function 0 device supports PG 65259 with the engine running
12:50:28.9740 Global Component Identification Request
12:50:28.9747 18EAFFF9 [3] EB FE 00 (TX)
12:50:29.2993 1CFEEB54 [37] 49 4E 54 20 20 2A [34 31 35 34 34 39 39](tel:34 31 35 34 34 39 39) 43 31 2A 42 4D 42 [58 30 38 41 36 32 33](tel:58 30 38 41 36 32 33) 41 48 4C [30 30 30 30 30 31](tel:30 30 30 30 30 31) 2A 2A
Component Identification from Cab Display #2 (84): {
  Make: INT
  Model: 4154499C1
  Serial: BMBX08A623AHL000001
  Unit: 
}


12:50:29.2151 1CFEEB0B [27] 42 4E 44 57 53 2A 45 43 38 30 45 53 50 20 2A 35 5A 34 38 32 30 30 30 36 33 2A 2A
Component Identification from Brakes - System Controller (11): {
  Make: BNDWS
  Model: EC80ESP
  Serial: 5Z48200063
  Unit: 
}

12:50:29.3555 1CFEEB4C [45] 49 4E 54 20 20 2A 34 31 35 34 34 39 30 43 31 2A 48 41 31 31 30 32 42 36 32 33 41 4A 46 30 35 34 33 36 37 2A 2A 00 00 00 00 00 00 00 00
Component Identification from Communications Unit, Radio (76): {
  Make: INT
  Model: 4154490C1
  Serial: HA1102B623AJF054367
  Unit: 
}

12:50:29.2541 1CFEEB27 [29] 49 4E 54 20 20 2A 34 32 36 39 30 34 35 43 31 20 2A 58 58 58 58 58 58 58 58 58 58 2A 2A
Component Identification from Management Computer #1 (39): {
  Make: INT
  Model: 4269045C1
  Serial: XXXXXXXXXX
  Unit: 
}

12:50:28.9893 1CE8FF3D [8] 03 FF FF FF FF EB FE 00
Acknowledgment from Exhaust Emission Controller (61): Response: Busy, Group Function: 255, Address Acknowledged: 255, PGN Requested: 65259

12:50:29.2904 1CFEEB2A [23] 42 4E 44 57 53 2A 46 4C 52 32 31 2A 32 30 34 33 30 37 30 30 39 2A 2A
Component Identification from Headway Controller (42): {
  Make: BNDWS
  Model: FLR21
  Serial: 204307009
  Unit: 
}

12:50:29.2789 1CFEEB05 [32] 49 4E 54 20 20 2A 52 4E 44 4D 4C 3B 20 4D 6F [64 65 50 65 72 73 69](tel:64 65 50 65 72 73 69) 73 74 3D 74 72 75 65 2A 2A 2A
Component Identification from Shift Console - Primary (5): {
  Make: INT
  Model: RNDML; ModePersist=true
  Serial: 
  Unit: 
}

12:50:29.2600 1CFEEB21 [29] 49 4E 54 20 20 2A 34 30 34 34 34 37 30 43 37 20 2A 30 32 31 32 32 38 30 32 33 39 2A 2A
Component Identification from Body Controller (33): {
  Make: INT
  Model: 4044470C7
  Serial: 0212280239
  Unit: 
}

12:50:29.2426 1CFEEB4A [29] 4E 41 56 20 20 2A 34 31 32 39 31 37 34 43 31 2A 32 32 30 35 30 35 2D 30 30 30 32 2A 2A
Component Identification from Communications Unit, Cellular (74): {
  Make: NAV
  Model: 4129174C1
  Serial: 220505-0002
  Unit: 
}

12:50:29.0934 1CFEEB00 [33] 49 4E 54 20 20 2A 30 30 31 30 31 33 36 30 4E 31 2A [00 00 00 00 00 00 00 00 00 00 00 00 00 00 2A 2A
Component Identification from Engine #1 (0): {
  Make: INT
  Model: 00101360N1
  Serial: 
  Unit: 
}


12:50:29.2268 1CFEEBED [24] 49 4E 54 20 20 2A [34 30 35 37 36 39 39](tel:34 30 35 37 36 39 39) 43 34 2A 41 30 36 37 34 36 2A 2A
Component Identification from Door Controller #2 (237): {
  Make: INT
  Model: 4057699C4
  Serial: A06746
  Unit: 
}

K
12:50:29.2475 1CFEEB03 [33] 49 4E 54 20 20 2A 30 30 30 30 30 30 30 30 43 30 2A 30 30 30 30 30 30 30 30 30 30 30 30 30 30 2A 2A
Component Identification from Transmission #1 (3): {
  Make: INT
  Model: 00000000C0
  Serial: 00000000000000
  Unit: 
}

12:50:29.2280 1CFEEB37 [27] 49 4E 54 20 20 2A 2A 4C 32 31 32 32 39 35 37 39 36 38 33 30 30 30 33 37 30 2A 2A
Component Identification from Lighting - Operator Controls (55): {
  Make: INT
  Model: 
  Serial: L21229579683000370
  Unit: 
}

12:50:29.2342 1CFEEBEC [24] 49 4E 54 20 20 2A 34 30 36 31 39 36 35 43 34 2A [42 33 39 36 31 31 2A 2A
Component Identification from Door Controller #1 (236): {
  Make: INT
  Model: 4061965C4
  Serial: B39611
  Unit: 
}


12:50:29.2919 1CFEEB19 [34] 49 4E 54 20 20 2A 34 31 30 30 30 37 33 43 33 2A 30 30 30 30 30 30 30 30 30 30 35 37 32 30 35 37 2A 2A
Component Identification from Passenger-Operator Climate Control #1 (25): {
  Make: INT
  Model: 4100073C3
  Serial: 0000000000572057
  Unit: 
}

12:50:29.3540 1CFEEB99 [36] 49 4E 54 20 20 2A 34 30 35 37 36 38 39 43 34 2A 4D 32 31 31 31 32 53 30 30 37 35 39 30 39 30 33 34 35 2A 2A
Component Identification from Reserved for future assignment 153 (153): {
  Make: INT
  Model: 4057689C4
  Serial: M21112S00759090345
  Unit: 
}

12:50:29.3522 1CFEEB9A [36] 49 4E 54 20 20 2A 34 30 35 37 36 38 39 43 34 2A 4D 32 31 32 32 39 35 37 39 36 38 33 30 33 30 34 37 36 2A 2A
Component Identification from Reserved for future assignment 154 (154): {
  Make: INT
  Model: 4057689C4
  Serial: M21229579683030476
  Unit: 
}

12:50:29.3561 1CFEEB97 [36] 49 4E 54 20 20 2A 34 30 35 37 36 38 39 43 34 2A 4D 32 31 32 32 39 35 37 39 36 38 33 30 31 30 34 37 34 2A 2A
Component Identification from Reserved for future assignment 151 (151): {
  Make: INT
  Model: 4057689C4
  Serial: M21229579683010474
  Unit: 
}

12:50:29.3572 1CFEEB98 [36] 49 4E 54 20 20 2A 34 30 35 37 36 38 39 43 34 2A 4D 32 31 32 32 39 35 37 39 36 38 33 30 32 30 34 37 35 2A 2A
Component Identification from Reserved for future assignment 152 (152): {
  Make: INT
  Model: 4057689C4
  Serial: M21229579683020475
  Unit: 
}

12:50:29.2019 1CFEEB43 [26] 49 4E 54 58 58 2A 43 43 41 20 43 43 41 31 00 00 2A 00 00 00 00 00 00 00 2A 2A
Component Identification from Clutch/Converter Unit (67): {
  Make: INTXX
  Model: CCA CCA1
  Serial: 
  Unit: 
}

12:50:29.2692 1CFEEB17 [31] 49 4E 54 2A 34 30 39 33 34 35 34 43 31 2A 35 37 39 36 38 33 31 36 38 31 31 31 33 35 35 2A 2A
Component Identification from Instrument Cluster #1 (23): {
  Make: INT
  Model: 4093454C1
  Serial: 579683168111355]
  Unit: 
}

12:50:29.7282 18EAFFF9 [3] EB FE 00 (TX)
12:50:30.0507 1CFEEB2A [23] 42 4E 44 57 53 2A 46 4C 52 32 31 2A 32 30 34 33 30 37 30 30 39 2A 2A
Component Identification from Headway Controller (42): {
  Make: BNDWS
  Model: FLR21
  Serial: 204307009
  Unit: 
}

12:50:30.0540 1CFEEB54 [37] 49 4E 54 20 20 2A 34 31 35 34 34 39 39 43 31 2A 42 4D 42 58 30 38 41 36 32 33 41 48 4C 30 30 30 30 30 31 2A 2A
Component Identification from Cab Display #2 (84): {
  Make: INT
  Model: 4154499C1
  Serial: BMBX08A623AHL000001
  Unit: 
}

12:50:30.0051 1CFEEB21 [29] 49 4E 54 20 20 2A 34 30 34 34 34 37 30 43 37 20 2A 30 32 31 32 32 38 30 32 33 39 2A 2A
Component Identification from Body Controller (33): {
  Make: INT
  Model: 4044470C7
  Serial: 0212280239
  Unit: 
}

12:50:30.1062 1CFEEB4C [45] 49 4E 54 20 20 2A 34 31 35 34 34 39 30 43 31 2A [48 41 31 31 30 32 42 36 32 33 41 4A 46 30 35 34 33 36 37 2A 2A 00 00 00 00 00 00 00 00
Component Identification from Communications Unit, Radio (76): {
  Make: INT
  Model: 4154490C1
  Serial: HA1102B623AJF054367
  Unit: 
}

12:50:29.9922 1CFEEB4A [29] 4E 41 56 20 20 2A 34 31 32 39 31 37 34 43 31 2A 32 32 30 35 30 35 2D 30 30 30 32 2A 2A
Component Identification from Communications Unit, Cellular (74): {
  Make: NAV
  Model: 4129174C1
  Serial: 220505-0002
  Unit: 
}

12:50:29.8443 1CFEEB00 [33] 49 4E 54 20 20 2A 30 30 31 30 31 33 36 30 4E 31 2A 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2A 2A
Component Identification from Engine #1 (0): {
  Make: INT
  Model: 00101360N1
  Serial: 
  Unit: 
}

12:50:30.0083 1CFEEB27 [29] 49 4E 54 20 20 2A 34 32 36 39 30 34 35 43 31 20 2A 58 58 58 58 58 58 58 58 58 58 2A 2A
Component Identification from Management Computer #1 (39): {
  Make: INT
  Model: 4269045C1
  Serial: XXXXXXXXXX
  Unit: 
}

12:50:29.9769 1CFEEB0B [27] 42 4E 44 57 53 2A 45 43 38 30 45 53 50 20 2A 35 5A 34 38 32 30 30 30 36 33 2A 2A
Component Identification from Brakes - System Controller (11): {
  Make: BNDWS
  Model: EC80ESP
  Serial: 5Z48200063
  Unit: 
}

12:50:29.9976 1CFEEB03 [33] 49 4E 54 20 20 2A 30 30 30 30 30 30 30 30 43 30 2A 30 30 30 30 30 30 30 30 30 30 30 30 30 30 2A 2A
Component Identification from Transmission #1 (3): {
  Make: INT
  Model: 00000000C0
  Serial: 00000000000000
  Unit: 
}

12:50:30.0383 1CFEEB05 [32] 49 4E 54 20 20 2A 52 4E 44 4D 4C 3B 20 4D 6F 64 65 50 65 72 73 69 73 74 3D 74 72 75 65 2A 2A 2A
Component Identification from Shift Console - Primary (5): {
  Make: INT
  Model: RNDML; ModePersist=true
  Serial: 
  Unit: 
}

12:50:29.9991 1CFEEB3D [33] 49 4E 54 20 20 2A 30 30 31 30 36 30 33 39 4E 31 2A 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2A 2A
Component Identification from Exhaust Emission Controller (61): {
  Make: INT
  Model: 00106039N1
  Serial: 
  Unit: 
}

12:50:29.9850 1CFEEBEC [24] 49 4E 54 20 20 2A 34 30 36 31 39 36 35 43 34 2A 42 33 39 36 31 31 2A 2A
Component Identification from Door Controller #1 (236): {
  Make: INT
  Model: 4061965C4
  Serial: B39611
  Unit: 
}

12:50:29.9894 1CFEEBED [24] 49 4E 54 20 20 2A 34 30 35 37 36 39 39 43 34 2A 41 30 36 37 34 36 2A 2A
Component Identification from Door Controller #2 (237): {
  Make: INT
  Model: 4057699C4
  Serial: A06746
  Unit: 
}

12:50:30.1021 1CFEEB99 [36] 49 4E 54 20 20 2A 34 30 35 37 36 38 39 43 34 2A 4D 32 31 31 31 32 53 30 30 37 35 39 30 39 30 33 34 35 2A 2A
Component Identification from Reserved for future assignment 153 (153): {
  Make: INT
  Model: 4057689C4
  Serial: M21112S00759090345
  Unit: 
}

12:50:30.1032 1CFEEB9A [36] 49 4E 54 20 20 2A 34 30 35 37 36 38 39 43 34 2A 4D 32 31 32 32 39 35 37 39 36 38 33 30 33 30 34 37 36 2A 2A
Component Identification from Reserved for future assignment 154 (154): {
  Make: INT
  Model: 4057689C4
  Serial: M21229579683030476
  Unit: 
}

12:50:30.1056 1CFEEB97 [36] 49 4E 54 20 20 2A 34 30 35 37 36 38 39 43 34 2A 4D 32 31 32 32 39 35 37 39 36 38 33 30 31 30 34 37 34 2A 2A
Component Identification from Reserved for future assignment 151 (151): {
  Make: INT
  Model: 4057689C4
  Serial: M21229579683010474
  Unit: 
}

12:50:30.0423 1CFEEB19 [34] 49 4E 54 20 20 2A [34 31 30 30 30 37 33](tel:34 31 30 30 30 37 33) 43 33 2A [30 30 30 30 30 30 30](tel:30 30 30 30 30 30 30) [30 30 30 35 37 32 30](tel:30 30 30 35 37 32 30) 35 37 2A 2A
Component Identification from Passenger-Operator Climate Control #1 (25): {
  Make: INT
  Model: 4100073C3
  Serial: 0000000000572057
  Unit: 
}

12:50:29.9885 1CFEEB37 [27] 49 4E 54 20 20 2A 2A 4C 32 31 32 32 39 35 37 39 36 38 33 30 30 30 33 37 30 2A 2A
Component Identification from Lighting - Operator Controls (55): {
  Make: INT
  Model: 
  Serial: L21229579683000370
  Unit: 
}

12:50:30.1079 1CFEEB98 [36] 49 4E 54 20 20 2A 34 30 35 37 36 38 39 43 34 2A 4D 32 31 32 32 39 35 37 39 36 38 33 30 32 30 34 37 35 2A 2A
Component Identification from Reserved for future assignment 152 (152): {
  Make: INT
  Model: 4057689C4
  Serial: M21229579683020475
  Unit: 
}

12:50:29.9523 1CFEEB43 [26] 49 4E 54 58 58 2A 43 43 41 20 43 43 41 31 00 00 2A 00 00 00 00 00 00 00 2A 2A
Component Identification from Clutch/Converter Unit (67): {
  Make: INTXX
  Model: CCA CCA1
  Serial: 
  Unit: 
}

12:50:30.0291 1CFEEB17 [31] 49 4E 54 2A 34 30 39 33 34 35 34 43 31 2A 35 37 39 36 38 33 31 36 38 31 31 31 33 35 35 2A 2A
Component Identification from Instrument Cluster #1 (23): {
  Make: INT
  Model: 4093454C1
  Serial: 579683168111355
  Unit: 
}

**_FAIL: 6.2.7.4.a - There is no positive response from function 0. (Global request not supported or timed out.)
ERROR: Error: Cannot invoke "org.etools.j1939tools.bus.BusResult.getPacket()" because "function0DSPacket" is null_**

End Test 2.7 - Component ID: Make

**Comment by ericthomasswenson** [comment]
See #1298 for related content

**Comment by battjt** [comment]
Missing Address Claim was related to DrewLink adapter.  Will not fix.

**Comment by ericthomasswenson** [comment]
Believed to be an adapter issue with Drew Technologies adapter where the adapter hides the address claim responses.
