### ISSUE TITLE
Initialized tests still fail in 3.1.24

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1300]
Initialized tests still fail in version 3.1.24.  See #1226. 

New Issue created to better track new release effected from @markamorrison remark therein.

Bob and Eric to assess their 3.1.24 outcomes. (complete)

**Comment by ericthomasswenson** [comment]
Mark, Jacob, please post the failure message(s). I didn’t see any problems in the 3.1.24 test Bob ran. The failure messages will provide the test step that failed.

**Comment by markmorrisoncummins** [comment]
I think the particular issue we are seeing is related to multiple test results being provided for the same SPN and FMI with differing completion status. We do not see these failures when all the tests for an SPN and FMI are initialized. The failure messages are unchanged from #1226, but here are some snips from a 3.1.24 log.

This is 6.4.12:

> 13:50:41.7991 Sending DM7 for DM30 to Engine #1 (0) for SPN 7329
> 13:50:41.7991 18E300F9 [8] F7 A1 1C 1F FF FF FF FF (TX)
> 13:50:41.8101 1CA4F900 [24] F7 A1 1C 02 32 01 80 7D 81 7D 80 7D F7 A1 1C 02 32 01 00 FB FF FF FF FF
> DM30 from Engine #1 (0): [
>   SPN 7329 FMI 2 (SLOT 306) Result: Test Passed. Min: 0, Value: 0, Max: 1 count
>   SPN 7329 FMI 2 (SLOT 306) Result: Test Not Complete.
> ]

And here are failure messages in 6.4.14:

> 13:50:53.4281 Sending DM7 for DM30 to Engine #1 (0) for SPN 7329
> 13:50:53.4311 18E300F9 [8] FA A1 1C 02 FF FF FF FF (TX)
> 13:50:53.4431 1CA4F900 [24] FA A1 1C 02 32 01 80 7D 81 7D 80 7D FA A1 1C 02 32 01 00 FB FF FF FF FF
> DM30 from Engine #1 (0): [
>   SPN 7329 FMI 2 (SLOT 306) Result: Test Passed. Min: 0, Value: 0, Max: 1 count
>   SPN 7329 FMI 2 (SLOT 306) Result: Test Not Complete.
> ]
> FAIL: 6.4.14.2.a - Engine #1 (0) is now reporting an initialize test for SPN = 7329, FMI = 2

6.7.17:

> 13:54:56.3561 Sending DM7 for DM30 to Engine #1 (0) for SPN 7329
> 13:54:56.3551 18E300F9 [8] FA A1 1C 02 FF FF FF FF (TX)
> 13:54:56.3691 1CA4F900 [24] FA A1 1C 02 32 01 80 7D 81 7D 80 7D FA A1 1C 02 32 01 00 FB FF FF FF FF
> DM30 from Engine #1 (0): [
>   SPN 7329 FMI 2 (SLOT 306) Result: Test Passed. Min: 0, Value: 0, Max: 1 count
>   SPN 7329 FMI 2 (SLOT 306) Result: Test Not Complete.
> ]
> FAIL: 6.7.17.2.a - Engine #1 (0) is now reporting an initialize test for SPN = 7329, FMI = 2

6.8.14:

> 13:57:26.8011 Sending DM7 for DM30 to Engine #1 (0) for SPN 7329
> 13:57:26.8011 18E300F9 [8] FA A1 1C 02 FF FF FF FF (TX)
> 13:57:26.8091 1CA4F900 [24] FA A1 1C 02 32 01 80 7D 81 7D 80 7D FA A1 1C 02 32 01 00 FB FF FF FF FF
> DM30 from Engine #1 (0): [
>   SPN 7329 FMI 2 (SLOT 306) Result: Test Passed. Min: 0, Value: 0, Max: 1 count
>   SPN 7329 FMI 2 (SLOT 306) Result: Test Not Complete.
> ]
> FAIL: 6.8.14.2.a - Engine #1 (0) reported test result for SPN = 7329, FMI = 2 is now initialized

and 6.9.6:

> 13:58:50.9211 Sending DM7 for DM30 to Engine #1 (0) for SPN 7329
> 13:58:50.9231 18E300F9 [8] F7 A1 1C 1F FF FF FF FF (TX)
> 13:58:50.9341 1CA4F900 [24] F7 A1 1C 02 32 01 80 7D 81 7D 80 7D F7 A1 1C 02 32 01 00 FB FF FF FF FF
> DM30 from Engine #1 (0): [
>   SPN 7329 FMI 2 (SLOT 306) Result: Test Passed. Min: 0, Value: 0, Max: 1 count
>   SPN 7329 FMI 2 (SLOT 306) Result: Test Not Complete.
> ]
> FAIL: 6.9.6.2.a - Engine #1 (0) reported test result for SPN = 7329, FMI = 2 is now initialized

**Comment by ericthomasswenson** [comment]
Present S13 engine software provides only one test result for each SPN and FMI combination and can’t reproduce this problem.

**Comment by markmorrisoncummins** [comment]
In version 3.1.27:

6.8.14 is still failing.
The other parts appear to be fixed. Skimming through the pull request, it looks like the logic might not have made it into the 8.14 controller?

**Comment by ericthomasswenson** [comment]
Mark thinks this was a simple omission, Joe

**Comment by ericthomasswenson** [comment]
Confirmed as corrected by Mark A
