### ISSUE TITLE
V3.1.25 will not progress beyond user input screen

### ISSUE THREAD

**Issue by anthonyhbest** [Equipment-and-Tool-Institute/j1939-84#1301]
When attempting to test V3.1.25, the test will not continue when "OK" is clicked at the bottom of the user input screen.  Clicking repeatedly, waiting, hitting the "enter" key all attempted with no success.

**Comment by jacobbosch-cummins** [comment]
I can second this.  I needed to close the window via the "X" in the title bar to continue.

**Comment by battjt** [comment]
We are able to reproduce this and will have a fixed version released very soon.
