### ISSUE TITLE
Info not provided for Non-OBD modules as defined for 6.1.3.3.c

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1308]
Info not provided for Non-OBD modules as defined for 6.1.3.3.c

6.1.3.3	Warn/Info Criteria
a.	Warn if more than one ECU responds with a value for OBD compliance where the values are not identical (e.g., if one ECU reports 13h and another reports 22h, if one reports 13h and another reports 11h, or if one ECU reports 00h and another reports 14h).
b.	Warn if any response received from a non-OBD ECU provides OBD Compliance values of 0, FBh, FCh, FDh, FEh, or FFh.
c.	Info for DM5 replies from non-OBD ECUs.
// The above changes incorporate #1099

Original request in #968

https://github.com/Equipment-and-Tool-Institute/j1939-84/assets/94923793/d77789b5-7253-40c8-b2d0-7fac36803097

**Comment by ericthomasswenson** [comment]
From 3.1.26

Vehicle Composite of DM5: Comprehensive component Fuel System
Misfire
EGR/VVT system
Exhaust Gas Sensor heater Exhaust Gas Sensor
…
supported, not complete
supported, not complete
supported, not complete
supported, not complete
not supported, complete

INFO: 6.1.3.3.c - Response received from a non-OBD ECU provided OBD Compliance values of 5h
INFO: 6.1.3.3.c - Response received from a non-OBD ECU provided OBD Compliance values of 5h 
INFO: 6.1.3.3.c - Response received from a non-OBD ECU provided OBD Compliance values of 5h

**Comment by ericthomasswenson** [comment]
Perhaps we add the SA to the info message

Joe, please respond with an estimate

**Comment by karysg** [comment]
If adding the SA is the only request, estimate is 2-4 hours.

**Comment by battjt** [comment]
I think the check is done in two different places.

- 6.1.13.2.a is a table A6.3.a check.
- 6.1.3.3.c is a 6.1.3.3.c check.

Both should be info.

**Comment by anthonyhbest** [comment]
@ericthomasswenson 
DM5 issue is still present in version 3.1.28
The following should be INFO not WARN per the agreed upon WARN/INFO criteria as mentioned above.

![image](https://github.com/Equipment-and-Tool-Institute/j1939-84/assets/94923793/6904732e-6021-4fe7-afc3-1e860d32cec3)
![image](https://github.com/Equipment-and-Tool-Institute/j1939-84/assets/94923793/1058edf7-3584-4018-82e9-45cfb982cf50)
