### ISSUE TITLE
Tool is issuing incorrect Timing: Late Responses

### ISSUE THREAD

**Issue by anthonyhbest** [Equipment-and-Tool-Institute/j1939-84#1314]
V3.1.20 of Tool is issuing timing late responses incorrectly:
![image](https://github.com/Equipment-and-Tool-Institute/j1939-84/assets/94923793/c372922a-ec50-4e9a-a953-e18fe7dc9792)
![image](https://github.com/Equipment-and-Tool-Institute/j1939-84/assets/94923793/862327a7-ebf3-4887-a1db-8172ea0ab2f6)

**Comment by anthonyhbest** [comment]
And again: 
![image](https://github.com/Equipment-and-Tool-Institute/j1939-84/assets/94923793/59a3ad07-7ce7-4150-9108-f0133f03053b)
![image](https://github.com/Equipment-and-Tool-Institute/j1939-84/assets/94923793/8eb34695-4bd5-4fd6-9c9a-598a8187890e)

**Comment by anthonyhbest** [comment]
And again:
![image](https://github.com/Equipment-and-Tool-Institute/j1939-84/assets/94923793/cf622e8b-a5b4-4b5c-af9f-518d2cf44165)

**Comment by ericthomasswenson** [comment]
I may have seen a similar complaint:

TIMING: Late response -  14:37:26.6447 18E8FF54 [8] 01 00 FF FF FF 82 FD 00
TIMING: Late response -  14:37:26.6461 18E8FF4C [8] 01 00 FF FF FF 82 FD 00
TIMING: Late response -  14:37:26.6506 18FD8200 [8] 43 FF 00 00 00 00 FF FF
TIMING: Late response -  14:37:26.6567 18FD8227 [8] 03 FF 00 00 00 00 FF FF
TIMING: Late response -  14:37:26.6616 18FD823D [8] 03 FF 00 00 00 00 FF FF

**Comment by battjt** [comment]
I think all of Anthony's late responses are related to conflicts between the DM5 heartbeat request and the report. That would make Eric's report a separate bug.  I will need a report and the .ASC file to diagnose that.

1. I am still investigating why the request time is after the response.
2. I will look into how to avoid conflicting DM5 requests and the DM5 heartbeat.

**Comment by battjt** [comment]
Looks like the DM5 heartbeat stop() wasn't waiting for the stop to complete.
