### ISSUE TITLE
Spurious Implausibility Warning message in 6.1.26.

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1316]
14:26:05.7337 18FD9400 [8] FF FF FF FF 00 00 11 03
Found: Electronic Engine Controller 7 from Engine #1 (0): 
  SPN    27, Engine EGR 1 Valve Position: Not Available
  SPN  3822, Engine EGR 1 Valve 2 Position: Not Available
  SPN  5444, Engine Crankcase Breather Oil Separator Speed: **_0.000_** rpm
  SPN  5312, Engine Intake Manifold Commanded Pressure: 98.125 kPa
[...]
WARN: 6.1.26.3.c - N.8 Engine #1 (0) reported value for **_SPN 5444 (7.0) is implausible_**

From 3.1.26

**Comment by ericthomasswenson** [comment]
PGN 64916 from Engine #1 (0)
14:26:05.7337 18FD9400 [8] FF FF FF FF 00 00 11 03
14:26:05.8337 18FD9400 [8] FF FF FF FF 00 00 11 03
14:26:05.9330 18FD9400 [8] FF FF FF FF 00 00 11 03

**Comment by battjt** [comment]
@ericthomasswenson The logs were lost.  Can we get  a new report with the corresponding .ASC file that has this issue?

We are at a loss, we can add debug information to the report indicating which packet the value was parsed from.
