### ISSUE TITLE
Add Adapter Selection to Report Heading

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1326]
Add “Adapter Selection:” to Report Heading

Insert “Adaptor Selection:” After Generated … and Before Log File Name

This is a conceptual error of omission from prior work. 

Please define a format that will be unambiguous… This may display content commonly found in an RP1210 .INI file and/or the file name and path. 

Current report displays…

Summary of J1939-84 Tool Execution

J1939-84 Tool version 3.1.26 - 2024/02/04 12:03
Generated: 2024/03/13 15:19:53.1072
Log File Name: C:\CdriveSave\new j1939-84\E44 RC2 ECM faults_13mar2024.txt

TEST SUMMARY REPORT
OUTCOME: 
Failures:    23
Warnings:    20
Information: 34
Incomplete:  0
Timing:      5
Passes:      154

User Data Entry:

**Comment by karysg** [comment]
Proposed format
Adapter Selection: DLL - ADAPTER NAME

J1939-84 Tool version 3.1.26 - 2024/02/04 12:03
Generated: 2024/03/13 15:19:53.1072
**Adapter Selection: NXULNK32 - NEXIQ Technologies USB-Link - USB-Link**
Log File Name: C:\CdriveSave\new j1939-84\E44 RC2 ECM faults_13mar2024.txt

**Comment by ericthomasswenson** [comment]
Looks nice … Please  implement this example (INI/DLL name || Dropdown menu string)  in both software sets.

**Comment by ericthomasswenson** [comment]
Confirmed observation in 3.1.28
