### ISSUE TITLE
Engine Revs Conversion Incorrect

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1329]
Engine Revs Conversation Incorrect 

0503CBh is 328651 decimal. Decimal point is in the wrong place.

14:29:13.3561 Destination Specific for PGN 65253 for SPNs  Request to Engine #1 (0) 
14:29:13.3577 18EA00F9 [3] E5 FE 00 (TX) 
14:29:13.3661 18FEE500 [8] A2 90 01 00 CB 03 05 00 
Engine Hours, Revolutions from Engine #1 (0): 
 SPN   247, Engine Total Hours of Operation: 5128.100 h 
 SPN   249, Engine Total Revolutions: 328651000.000 r

**Comment by mmschaefer** [comment]
I wish you cared…mmsOn Apr 29, 2024, at 4:14 PM, ericthomasswenson ***@***.***> wrote:﻿
Engine Revs Conversation Incorrect
0503CBh is 328651 decimal. Decimal point is in the wrong place.
14:29:13.3561 Destination Specific for PGN 65253 for SPNs  Request to Engine #1 (0)
14:29:13.3577 18EA00F9 [3] E5 FE 00 (TX)
14:29:13.3661 18FEE500 [8] A2 90 01 00 CB 03 05 00
Engine Hours, Revolutions from Engine #1 (0):
 SPN   247, Engine Total Hours of Operation: 5128.100 h
 SPN   249, Engine Total Revolutions: 328651000.000 r

**Comment by karysg** [comment]
The J1939DA SLOT (id 34) for SPN 249 has a scale factor of 1000, should this be changed?
@ericthomasswenson

**Comment by ericthomasswenson** [comment]
Correct … that’s a bit per minute at 1000 rpm … it just looked odd …

<img width="823" alt="image" src="https://github.com/Equipment-and-Tool-Institute/j1939-84/assets/78398059/1624b486-5a4a-4719-9da7-3fa14b113132">
