### ISSUE TITLE
Provide SPN and PGN Content from Table A.1 for Artifact Reconciliation 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1338]
Extract TableA1Repository.java into an excel spreadsheet to facilitate check for errors of omission.

Add SP Description and assigned PG to this table’s content.

Email spreadsheet for @ericthomasswenson to share with users.

**Comment by karysg** [comment]
Spreadsheet generated and sent.
