### ISSUE TITLE
Clicking "Read Vehicle Info" multiple times causes address conflict errors

### ISSUE THREAD

**Issue by markmorrisoncummins** [Equipment-and-Tool-Institute/j1939-84#1347]
Each time I click "Read Vehicle Info" after the first causes a new "RP1210 ERROR: Another ECU is using this address". It doesn't appear to matter whether reading the vehicle info is successful, as long as the software can communicate with the Nexiq hardware. When this happens, the error appears after every request from the -84 software throughout the entire test.

The .asc trace does not show any unexpected messages from source address 0xF9.

Here's a test where I clicked "Read Vehicle Info" three times:

> TEST LOG REPORT
> 
> RP1210 ERROR: Failed to read RP1210, restarting: Error (148): ERR_CLIENT_DISCONNECTED
> RP1210 ERROR: Another ECU is using this address: 18EAFFF9 [3] EC FE 00
> RP1210 ERROR: Another ECU is using this address: 18EAFFF9 [3] 00 D3 00
> RP1210 ERROR: Failed to read RP1210, restarting: Error (148): ERR_CLIENT_DISCONNECTED
> RP1210 ERROR: Another ECU is using this address: 18EEFFF9 [8] 00 00 E0 FF 00 81 00 00
> RP1210 ERROR: Another ECU is using this address: 18EEFFF9 [8] 00 00 E0 FF 00 81 00 00
> RP1210 ERROR: Another ECU is using this address: 18EAFFF9 [3] EC FE 00
> RP1210 ERROR: Another ECU is using this address: 18EAFFF9 [3] EC FE 00
> RP1210 ERROR: Another ECU is using this address: 18EAFFF9 [3] 00 D3 00
> RP1210 ERROR: Another ECU is using this address: 18EAFFF9 [3] 00 D3 00
> J1939-84 Tool version 3.1.28 - 2024/05/05 13:16
> 
> Start Part 1 - KOEO Data Collection

Here's the same place in the log with the same setup when I only clicked once:

> TEST LOG REPORT
> 
> J1939-84 Tool version 3.1.28 - 2024/05/05 13:16
> 
> Start Part 1 - KOEO Data Collection

**Comment by ericthomasswenson** [comment]
Suggestion:
Please disable and “grey” the button when data collection is underway.
Re-enable the button when complete… and avoid relaunching the tool for a blown fuse.

**Comment by battjt** [comment]
Also noticed while debugging that Thread.yield is in the wrong place and not effective.  Should be a Thread.sleep after read returns no packet.

**Comment by ericthomasswenson** [comment]
Bob Halfman will attempt to recreate similar circumstances.

**Comment by anthonyhbest** [comment]
We have seen similar issues as well in past releases.

**Comment by ericthomasswenson** [comment]
Bob Halfman reports that 3.2.0 addresses the observed behavior.
