### ISSUE TITLE
Null string provided for DM56 Engine Family did not fail.

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1352]
-84 doesn’t fail for no Engine Family value in DM56 reply. It may have been detected, but should say something like: 

FAIL: 6.1.6.2.x Engine Family Name missing from DM56.
 
Instead of Error: (which looks like a system failure)

2024E-MY comes from the regulation in 13 CCR 1971.1 (h). What follows matches the manufacturer’s emissions cert. application according to EPA’s rule (cited in an artifact footnote).

Start Test 1.6 - DM56: Model year and certification engine family
11:06:13.3182 Global DM56 Request
11:06:13.3206 18EAFFF9 [3] C7 FC 00 (TX)
11:06:13.3763 1CFCC700 [9] 32 30 32 34 45 2D 4D 59 **_00_**
Model Year and Certification Engine Family from Engine #1 (0):
Model Year: 2024E-MY
Family Name:
 
ERROR: Error: begin 0, end 1, length 0           /* -84 tool string
 
End Test 1.6 - DM56: Model year and certification engine family
 
 
This engine should send:               RNVXH07750SB

**Comment by karysg** [comment]
Fail should occur as part of step 6.1.6.2.e

e.	Fail if engine family has <> 12 characters before first asterisk character (ASCII 2Ah) or “null” character (ASCII 00h).

**Comment by ericthomasswenson** [comment]
Bob Halfman reports that failures are now observed for empty engine family strings.
EG.

Start Test 1.6 - DM56: Model year and certification engine family
11:08:47.3887 Global DM56 Request
11:08:47.3906 18EAFFF9 [3] C7 FC 00 (TX)
11:08:47.4474 1CFCC700 [9] 32 30 32 34 45 2D 4D 59 00
Model Year and Certification Engine Family from Engine #1 (0): 
Model Year: 2024E-MY
Family Name:
 
FAIL: 6.1.6.2.e - Engine family has 0 characters, which is not 12.
 
End Test 1.6 - DM56: Model year and certification engine family
