### ISSUE TITLE
Update Part1 Step07Controller with logic for missing verification specification

### ISSUE THREAD

**Issue by mmschaefer** [Equipment-and-Tool-Institute/j1939-84#156]
Per email:
Question on Step07  in the specification:
For obd module: 6.1.7.2.b.iv. Fail if CVN padded incorrectly (must use 0x00 in MSB for unused bytes) 
For non-obd module: 6.1.7.3.c.v. Warn if CVN padded incorrectly (must use 0x00 in MSB for unused bytes)

How do we determine if the CVN is less than 4 bytes?  The /73 project indicates this is determined by the length of the check sum but  how do we know the length of the check sum so we can determine if it has been padded?

Once clarification for this logic is recieved these step verification will need to be added to the controller and its unit tests.

**Comment by gumbelmj** [comment]
Eric to update Spec to indicate how this should handled.

**Comment by ericthomasswenson** [comment]
Proposed Resolution: 1/21/2021 email 

It would be ok to check all bytes for binary zeros.  It is highly unlikely to see 8 consecutive 0s in a completed CRC calculation. The probability of a false positive is guaranteed to be less than 1/256. This is not believed to be a pressing industry issue... let’s issue a warning message for excess zeros in any byte.  

The text would then read:

**_6.1.7.2.b.iv. Warn if CVN provides an implausible value of 00 in any byte.
6.1.7.3.c.v. Warn if CVN provides an implausible value of 00 in any byte._** 

Rationale:

It is not worth the effort to query users as to the actual lengths of multiple CVNs, as the plurality are expected to be 32-bit CVNs. Figuring out which lengths apply to which CVNs will also be problematic.

Note: A 16-bit CRC will have two bytes of trailing zeros in little endian notation.  If it wasn’t packed right, it will have 2 bytes of leading zeros.  If we check both the first and last bytes for zeros, we can screen likely suspects.  It seems just as easy to check all 4 bytes.

These examples show 00h is uncommon

**Comment by ericthomasswenson** [comment]
Was the proposal implemented?
or do I need to add 
6.1.7.2.b.iv. Warn if CVN provides an implausible value of 00 in any byte.
6.1.7.3.c.v. Warn if CVN provides an implausible value of 00 in any byte. 
to the draft 1st?

**Comment by gumbelmj** [comment]
We need to update to the documentation and note that this will be a future enhancement

**Comment by ericthomasswenson** [comment]
Alternatively, 

6.1.7.2 Fail Criteria
a. Fail if total number of reported CAL IDs is < user entered value for number of emission or diagnostic critical control units (test 6.1.2).  
b. For responses from OBD ECUs:
 i. Fail if <> 1 CVN for every CAL ID.  
ii. Fail if CAL ID not formatted correctly (printable ASCII, padded incorrectly, etc.).  
iii. Fail if any received CAL ID is all 0xFFh or any CVN is all 0x00h.  
**_iv. Fail if CVN padded with 16-binary zeros (where either the 1st two bytes are both 00h or the last two bytes both 00h).  Note HD OBD CVNs are required to be 32-bits._**
6.1.7.3 Warn Criteria 
a. Warn if total number of reported CAL IDs is > user entered value for number of emission or diagnostic critical control units (test 6.1.2). 
b. Warn if more than one CAL ID and CVN pair is provided in a single DM19 message.  
**_c. For responses from OBD ECUs, warn if 00h is observed in either the first or fourth bytes._**
d. For responses from non-OBD ECUs:
    i. Warn if any non-OBD ECU provides CAL ID.
   ii. Warn if <> 1 CVN for every CAL ID.  
  iii. Warn if CAL ID not formatted correctly (contains non-printable ASCII, padded incorrectly, etc.).
  iv. Warn if any received CAL ID is all 0xFFh or any CVN is all 0x00h. 
   v. Warn if CVN padded incorrectly (must use 0x00h in MSB for unused bytes).

**Comment by ericthomasswenson** [comment]
Omitted from 17 March 2021 as built draft.

**Comment by ericthomasswenson** [comment]
This proposal was not included in the 17 March 2021 as built draft

**Comment by ericthomasswenson** [comment]
Add to enhancement draft (as commented above) as below for 

6.1.7.2 Fail Criteria 
b. For responses from OBD ECUs:
**_iv. Fail if CVN padded with 16-binary zeros (where either the 1st two bytes are both 00h or the last two bytes both 00h). Note HD OBD CVNs are required to be 32-bits._**

6.1.7.3 Warn Criteria
**_c. For responses from OBD ECUs, warn if 00h is observed in either the first or fourth bytes._**

**Comment by ericthomasswenson** [comment]
To clarify, the methods to check for invalid CAL IDs was not directly defined in SAE J1939-84.
The padding checks proposed provide a heuristic approach for error detection 16-bit padding with zeros is compelling evidence as 16 consecutive zero bits in a CRC is highly unlikely.

**Comment by ericthomasswenson** [comment]
SOW Text see attachment for emphasis
[Future-Enhancement-Text-for-J1939-84 V-3-0-X Test-Software 6-7-2021.docx](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/8499213/Future-Enhancement-Text-for-J1939-84.V-3-0-X.Test-Software.6-7-2021.docx)


6.1.7.2 Fail Criteria
a. Fail if total number of reported CAL IDs is < user entered value for number of emission or diagnostic critical control units (test 6.1.2).
b. For responses from OBD ECUs:
i. Fail if <> 1 CVN for every CAL ID.
ii. Fail if CAL ID not formatted correctly (printable ASCII, padded incorrectly, etc.).
iii. Fail if any received CAL ID is all 0xFFh or any CVN is all 0x00h.
iv. Fail if any received CVN is all 0x00h
v. Fail if CVN padded with 16-binary zeros (where either the 1st two bytes are both 00h or the last two bytes both 00h). Note HD OBD CVNs are required to be 32-bits.

6.1.7.3 Warn Criteria
a. Warn if total number of reported CAL IDs is > user entered value for number of emission or diagnostic critical control units (test 6.1.2).
b. Warn if more than one CAL ID and CVN pair is provided in a single DM19 message.
c. For responses from OBD ECUs, warn if 00h is observed in either the first or fourth bytes.
d. For responses from non-OBD ECUs:
i. Warn if any non-OBD ECU provides CAL ID.
ii. Warn if <> 1 CVN for every CAL ID.
iii. Warn if CAL ID not formatted correctly (contains non-printable ASCII, padded incorrectly, etc.).
iv. Warn if any received CAL ID is all 0xFFh or any CVN is all 0x00h.
v. Warn if any received CVN is all 0x00h.
vi. Warn if CVN padded incorrectly (must use 0x00h in MSB for unused bytes).

**Comment by ericthomasswenson** [comment]
Duplicate suggested text found
