### ISSUE TITLE
Update SupportedSpnModuleTest to include all functions

### ISSUE THREAD

**Issue by mmschaefer** [Equipment-and-Tool-Institute/j1939-84#171]
SupportedSpnModuleTest is incomplete and needs to completed.

**Comment by ericthomasswenson** [comment]
This is too terse for a direct comment from me.  

The progress from October has been quite positive.

What enhancement is suggested?

**Comment by gumbelmj** [comment]
This actually a ticket for developers.  The Test class for the SupportedSpnModule isn't complete enough, in my opinion.  This task was created to remind me that it later needed to be done.

**Comment by ericthomasswenson** [comment]
Matt, Is this closed?

**Comment by ericthomasswenson** [comment]
Closed on developer recommendation.
