### ISSUE TITLE
6.I.D update DS retries

### ISSUE THREAD

**Issue by battjt** [Equipment-and-Tool-Institute/j1939-84#436]
Change
> 6.I.D Destination specific queries shall be accorded retries only when the acknowledgement control byte value of 3“Busy” is received.

to 

> 6.I.D Destination specific queries shall be accorded retries only when the acknowledgement control byte value of 3“Busy” is received or no response is detected.

This should result in an update to J1939 requestDS().

**Comment by ericthomasswenson** [comment]
Is this still relevant for 0.1.10?
A failure message is needed for no response, before the retry.
This seems to be the best approach for uncertain comm performance.
Let’s review after the 0.1.10 data comes in.

**Comment by ericthomasswenson** [comment]
The question seems to be now: Is this still relevant for 3.0.0.  Some queries require a failure message for a retry.  

The text says, ... Destination specific queries shall be accorded retries only when the acknowledgement  control  byte  value  of  3 “Busy”  is  received.  The  multiple  response  time  periods  for  the  RTS/CTS  transport protocol as shown in SAE J1939-21 Figure C1 shall  be individually observed. [2]
[2] Some global queries for multipacket  data  can exhaust  SAE

**Comment by ericthomasswenson** [comment]
We also need to address what appears to be a fixed time out of 200 ms vs. accepting late arrivals and marking them as late.  A source forge report showed a DM24 response that was received with RTS timing of 340 ms.  Matching this example would be preferred but not mandatory.

**Comment by battjt** [comment]
With a DS timeout of 600 ms and a warning at 200 ms, the following are example scenarios.  The response is the first response packet, either a :

Successful response (majority of requests)
```
   0: 18EA00F9 CD AB 00
  50: 18ABCD00 ....
```

Successful slow response
```
   0: 18EA00F9 CD AB 00
 599: WARN 18ABCD00 ....

   0: 18EA00F9 CD AB 00
 200: 18ABCD00 ....

   0: 18EA00F9 CD AB 00
 201: WARN 18ABCD00 ....
```


Give up with no response after 600 ms.
```
   0: 18EA00F9 CD AB 00
 600: GIVE UP (error reported by application layer)

```
Retry 200 ms after a BUSY up to 1.2s total time.
```
   0: 18EA00F9 xx xx xx
   1: 18E8F900 03 ....
 201: 18EA00F9 xx xx xx
 202: 18E8F900 03 ....
 402: 18EA00F9 xx xx xx
 403: 18E8F900 03 ....
 603: 18EA00F9 xx xx xx
 604: 18E8F900 03 ....
 804: 18EA00F9 xx xx xx
 805: 18E8F900 03 ....
1005: 18EA00F9 xx xx xx
1006: 18E8F900 03 ....
1200: GIVE UP (error reported by application layer)

```
Retry 200 ms after a BUSY up to 1.2s total time with slow responses.
```
   0: 18EA00F9 xx xx xx
 599: WARN 18E8F900 03 ....
 799: RETRY 18EA00F9 xx xx xx
1200: GIVE UP (error reported by application layer)

```

**Comment by gumbelmj** [comment]
Before you go through the effort of making any radical changes, we need to confirm with Eric about some of the steps which specifically call out when a retry is used and it provides scenarios where retries shouldn't be used.

**Comment by battjt** [comment]
The examples are here for discussion in Friday's meeting.Do you have something more specific about your retry concern?  The specification is extremely clear on DS retries.  Only retry in the case of a busy NACK.

**Comment by gumbelmj** [comment]
> 6.1.4.1.a. Destination Specific (DS) DM24 [send Request (PG 59904) for PG 64950 (SPs 3297, 4100-4103)] to each OBD ECU
6.1.4.1.b. If no response [transport protocol RTS or NACK(Busy) in 220 ms], then retry DS DM24 request to the OBD ECU. [Do not attempt retry for NACKs that indicate not supported]

same as 6.1.25.1 (DM20), 6.3.13.1 (DM25), and 6.11.8.1 (DM20)

The question is, do these step mesh with above requirements?

**Comment by ericthomasswenson** [comment]
The defaults in the front ... do not mean that specific instructions cannot be given.

The defaults can be harmonized with the exceptions, if the exceptions provide a consistent pattern.  (A goose and gander principle).

Mitigating factors may include anticipation of rts responses.

Specific instructions can be a form of relief... need to better understand the circumstances.  

In the case of DM24, it was a form of relief ... earlier software too often didn’t receive DM24 responses (which were judged to be compliant) ... so we choose not to rely on defaults, and write down the exact expectation. 220 ms is a direct reference to the 10% allowance in 6.I et.al.

**Comment by ericthomasswenson** [comment]
We agreed that the 22 March release would include 600 ms figure of merit for both BAM and DS responses.  

If that works as expected, 600ms will be sent to other users in the beta release, and the proffered document changes will be implemented, potentially with additional content on the context of our experience.

**Comment by ericthomasswenson** [comment]
Joe, I see a let it ride vibe here with no documentation proposal for the Jun24 as built.
The other 6.I-VII proposals were completed... 

I believe we agreed to let experience for the current implementation guide additional changes, with the possible exception of increasing the 600 ms timeout to 720 ms timeout based on the UR experiences for UR PGs that were sent on broadcast schedules, for the maintenance changes to test 1.26, and 2.17.

I’ll post an appropriate questions to remind us to revisit DS performance et.al and Response timeouts as a part of the maintenance contract effort
