### ISSUE TITLE
Part 1 Step 26 Needs to check for On-Request PGNs which are Not Supported

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/j1939-84#525]
From Eric:

> Please add a future enhancement issue for the detection of Table A-1 Note 7 omissions for SPs listed as UR.  This issue is not included in the detailed statement of work.  The Test 26 text does not provide for their detection today.  Today’s test text only provides for the detection of [broadcast] SPs that are not included in DM24 responses, for SPs that are received as part of the ECU’s broadcast data. It does not require queries for [UR] SPs that were not included in the DM24 response.  These SPs are commonly flagged with the note 2 failure message, so the lack of this functionality is not perceived to be a critical concern. ﻿
> This ignores the 2nd chance drawing for missed broadcast SPs, which is not directly relevant to this question about UR SPs, that are not supported in DM24.

**Comment by gumbelmj** [comment]
Currently, if the OBD Module doesn't indicate Support for an SP that is required per Table A-1 but is only sent upon request, the tool will query the OBD module for the information.  Thus it can't be determined if the module actually supports the SP or not.

**Comment by ericthomasswenson** [comment]
For test 6.1.26, clarify and enhance Actions1 et. al.

_6.1.26_ _Data stream support verification 
6.1.26.1 Actions: 
a. Create a list of expected SPNs and PGNs from the DM24 response, **where the data stream support bit defined in SAE J1939-73 5.7.24 is 0.**  **Add any omissions from Table A-1, excluding those SPNs noted (as CI or SI) for the opposite fuel type provided by the user.**  **Omit the the following SPNs (588, 1213, 1220, 12675, 12730, 12783, 12797) which are included in the list.  Display the completed list noting those omitted SPNs, supported SPNs as ‘broadcast’ or ‘upon request’, and additions from Table A-1.**
b. Gather broadcast data for all SPNs that are supported for data stream in the OBD ECU DM24 responses, **and the added SPNs from Table A-1.**_ _**This shall include the both SPNs that are expected to be queried with DS queries (in step 6.1.26.5 for SPNs supported in DM24) and SPNs that that are expected without queries.**_
_b. Gather/timestamp each parameter **that is observed** at least three times to be able to verify frequency of broadcast._ 

_6.1.26.3 Actions2 
a. Identify SPNs provided in the data stream that are listed in Table A-1, but are not supported by any OBD ECU in its DM24 response._  

_6.1.26.4 Fail/Warn Criteria2 
a. Fail/warn per Table A-1 column, “Action if SPN provided but not included in DM24”._

**Comment by ericthomasswenson** [comment]
For test 6.1.26, clarify/enhance Actions3 et. al.:

_6.1.26.5 Actions3: 
a. DS messages to ECU that indicated support in DM24 for upon request SPNs **and SPNs added from Table A-1**, **regardless of whether the SPNs were or were not** observed in step 1.  **[Where a PGN contains more than one SPN (to be queried), that PGN need only be queried one time].**
b. If no **response or NACK** for any SPN requested in 6.1.25.3.a, send global message to request that SPN(s)._ 

_6.1.26.6 Fail/warn criteria3:  [Refer to footnotes 23 and 24 for a and b, respectively].
a.  Fail if no response **or NACK** for any SPN indicated as supported by the OBD ECU in DM24. **Downgrade the failure to a warning where an upon request SPN was received in 6.1.26.1, and the request was not replied to with a NACK.  And, ignore NACK received for any SPN added from table A-1, whose PGN does not contain any SPNs listed as supported in DM24.**
b.  Fail if any parameter in a **fixed period message, upon request,** is not broadcast within ± 10% of the specified broadcast period. 
c.  Fail if any parameter in a variable period broadcast message exceeds 110% of its recommended broadcast period.26 
d. Fail/warn if any **data received (that is supported in DM24 by the subject OBD ECU)** is not valid for KOEO conditions as per section A.1Table A-1, Minimum Data Stream Support. 
e. Warn/info per Table A-1, if an expected SPN from the DM24 support list is provided by a non-OBD ECU. 
f. Fail/warn per Table A-1, if two or more ECUs provide an SPN listed in Table A-1._
**_g. Fail/warn per Table A-1 column, “Action if SPN provided but not included in DM24”._**

**Comment by ericthomasswenson** [comment]
Apply parallel construction to:

6.2.17 KOER  Data stream

**Comment by ericthomasswenson** [comment]
The proposed enhancement text for test 1.26 will need to be reviewed to consider inclusion of any SPs in Table A-1 that were potentially excluded by the multiple PG mapping exclusion. Presently, there are no known candidates in Table A-1 that would need to be added back. Such an add back could be implemented when the exception gets added into Table A-1.

**Comment by ericthomasswenson** [comment]
Improved proffer captured in #817.  This may be closed if no 3.0 development issue remains.

**Comment by battjt** [comment]
Consolidate test 26 suggestions for datastream into new ticket.

**Comment by ericthomasswenson** [comment]
The SOW text should define the current intention
