### ISSUE TITLE
BAM timeouts

### ISSUE THREAD

**Issue by battjt** [Equipment-and-Tool-Institute/j1939-84#545]
This ticket is to record the decision and to verify that -84 is updated.

> Dear Joe,

> 
> I believe it is best to provide relief for reception of BAM responses when the test vehicle condition presents contention between the engine’s DM1 length and (long) BAM responses, as has been observed in the data Bob Halfman has collected. This relief will better support engine development vehicles where the SAE J1934-84 test is used to provide an early warning for communications software issues. 
> 
> Please use a heuristic value of 600 ms timeout for global requests (only) as a substitute for the 200 ms + 10% value, which has been shown to be ineffective at the margins of the race condition created by longer DM1 messages.  The warning for late responses shall not be changed, it shall remain at 200 ms + 10%.
> 
> 200 ms will be exceeded by 4 DTCs where packets are throttled at 60 ms.  Over 240 ms for reception four messages can be expected, when temporary high bus loading conditions delay one or two of the packets.  Contention has been observed to be a recurring event, blocking multiple retry attempts for the DM19, DM20, and Component ID data.  Since there is no contention for RTS/CTS response resources, the 200 ms + 10% timeout need not be extended for responses to destination specific queries. 
> 
> 600 ms will support up to 13 DTCs at 60 ms. With over 13 DTCs the vehicle is not ready to test, as the DM1 displays consume over half the available time for BAM packets, and failures for missing global query responses is fair.  600 ms is 1/2 the overall 1.2 s network-wide timeout allowed by SAE J1939-21. This relief will also better account for additional delays that may be experienced by diagnostic gateways being introduced to address cybersecurity concerns expressed by NHTSA
> 
> As an alternative, the conversation of DM19, DM20, and Component ID from global queries to destination specific queries, was rejected.  It is believed these queries should still succeed during the overwhelming number of tests to be run with the software. When recommended test conditions are present, DM1 becomes a single frame display, and contention is not observed.  Also, DM1 is used as a heartbeat, and can convey safety-related information in its DTCs.  Thus, DM1 messages cannot be abandoned by the ECM in favor of service tool queries for these PGs.
> 
> The following will be added to the SAE J1934-84 draft that is tracking the new test software.
> ...
> 
> D. SAE J1939-21 defines query timeouts and provides for two retries of a given information request. Warnings may be provided for responses that exceed 200 ms, from the query to the first frame of the response, whether provided as a single frame response, BAM, RTS frame, or ACK(Busy). [XX] Globally addressed queries shall be accorded two retries. Destination specific queries shall be accorded retries only when the acknowledgement control byte value of 3 “Busy” is received. The multiple response time periods for the RTS/CTS transport protocol shown in SAE J1939-21 Figure C1 shall be individually observed.
> 
> [XX] Contention between long DM1 messages, which are sent with a fixed 1 Hz period, and Long BAM responses to global queries, including DM19, DM20, and component ID, have been observed.  This contention creates race conditions between the global query and the start of the DM1 broadcast (and its completion). Reception of replies sent by the ECM is expected of the test software, when contention occurs.
> 
> 
> Best Wishes,
> 
> Eric T. Swenson

**Comment by ericthomasswenson** [comment]
The specific additions are in bold italic font.

_D. SAE J1939-21 defines query timeouts and provides for two retries of a given information request. Warnings may be provided for responses that exceed 200 ms, **from the query to the first frame of the response, whether provided as a single frame response, BAM, RTS frame, or ACK(Busy). [XX]** Globally addressed queries shall be accorded two retries. Destination specific queries shall be accorded retries only when the acknowledgement control byte value of 3 “Busy” is received. The multiple response time periods for the RTS/CTS transport protocol shown in SAE J1939-21 Figure C1 shall be individually observed._

_**[XX] Contention between long DM1 messages, which are sent with a fixed 1 Hz period, and Long BAM responses to global queries, including DM19, DM20, and component ID, have been observed. This contention creates race conditions between the global query and the start of the DM1 broadcast (and its completion). Reception of replies sent by the ECM is expected of the test software, when contention occurs.**_

**Comment by ericthomasswenson** [comment]
Added text and inserted footnote 4 into 24June as built draft
