### ISSUE TITLE
No Failure/Warning for no response from DM7 request

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/j1939-84#569]
In Part 1 Step 12 (and others), there is no warning/failure if the module doesn't return a DM30 when receiving a DM7

**Comment by ericthomasswenson** [comment]
Examples where failures were issued have been observed (E39), in addition to examples where failures were not observed (3-BOX).

**Comment by ericthomasswenson** [comment]
Let's see what the next release does with some of the disparate vehicle architectures.

**Comment by ericthomasswenson** [comment]
Current performance for part 1 fails the engine for failure to respond.

Repeating this failure each time deletion of ‘diag. Info’ is checked is undesirable.
