### ISSUE TITLE
Part 7 Step 6 should indicate "OBD"

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/j1939-84#631]
>         6.7.6.2.b Fail if no ECU reports > 0 for previously active DTCs.
This should probably "Fail if no **_OBD_** ECU reports > 0 for previously active DTCs."

**Comment by ericthomasswenson** [comment]
Add OBD as recommended to 6.7.2.2.b, as shown below

_6.7.6.2 Fail  criteria: 
a. Fail  if  any  OBD  ECU  reports  >  0  for active  DTCs. 
b. Fail  if no  **OBD** ECU reports  >  0  for previously  active  DTCs. 
c. Fail  if  any  OBD  ECU  reports  a  different  number DM6:  emission  related  pending DTCs_

**Comment by ericthomasswenson** [comment]
Previously provided on 2/25
