### ISSUE TITLE
Titles should start with "Step" and not end with "."

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/j1939-84#652]
The messages in the progress bar as well as the step references in the report should be consistent format:
> Step 6.X.Y Action performing
> Start 6.X.Y Title

**Comment by gumbelmj** [comment]
Failure and warning messages should not include "Step"

**Comment by ericthomasswenson** [comment]
Bold, Italic  **_Test_** was incorrectly provided as Step in the examples below.
Section 6.I defines the enumeration as 6.X.Y.Z where X = Part; Y = Test; Z = Step. 

Desired changes will be provided via email directly.  Abridged examples are shown below.

From the detail report section 

Part 1 KOEO Data Collection............................................(FAIL)

**_Test_** 1.1. Test vehicle data collection.................................(PASS)
**_Test_** 1.2. Verify engine operation......................................(PASS)
**_Test_** 1.3. DM5: Diagnostic readiness 1..................................(PASS)
**_Test_** 1.4. DM24: SPN support............................................(PASS)

From the test log report

Start **_Test_** 1.1. Test vehicle data collection
...
End **_Test_** 1.1. Test vehicle data collection

Start **_Test_** 1.2. Verify engine operation
...
End **_Test_** 1.2. Verify engine operation

Start **_Test_** 1.3. DM5: Diagnostic readiness 1
...
End **_Test_** 1.3. DM5: Diagnostic readiness 1

Start _**Test**_ 1.4. DM24: SPN support
