### ISSUE TITLE
6.8.11.1.a. Needs updated

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/j1939-84#662]
> 6.8.11.1.a. DS DM7 with TID 247 + each DM24 SPN + FMI 31.

This should probably indicate that on the DM24 SPs which indicate they are supported as test results should be requested here.

**Comment by gumbelmj** [comment]
It should indicate it's to the given OBD Module.

**Comment by ericthomasswenson** [comment]
The following clarification is proposed.

_6.8.11 DM7/DM30: Command Non-Continuously Monitored Test/Scaled Test Results 
6.8.11.1 Actions
a. DS DM7 with TID 247 + each DM24 SPN + FMI 31 to **OBD** ECUs **for each SP that supports test results.**
b. Create list of any ECU address+SPN+FMI with non-initialized values.47_

**Comment by ericthomasswenson** [comment]
Updated 10 March Draft to say:

6.8.11.1	Actions

a.	_Iterate_ DS DM7 with TID 247 + SPN + FMI 31 _to OBD ECUs for each SP in the OBD ECU DM24 response that supports test results._
