### ISSUE TITLE
NOx Binning - GHG Tracking Display Example

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#667]
As an enhancement, tabular displays of the forthcoming NOX Binning and GHG Tracking Arrays are proposed. There will be approximately 75% reduction in printed lines, compared to a non-tabular approach.

With this enhancement, scaled data displays for individual PGs would not be provided after the PG in the log.

This example is outdated, and was deleted. See comment below for updated content.

**Comment by ericthomasswenson** [comment]
**SPs 12691, 12694, and 12697: Common Active Technology Key Table for SPN a**

The index numbers allowed for SPN a in each active technology tracking PG are described in the table below.

**Standardized GHG Active Technology Enumeration**
0, SAE/ISO Reserved
1, [Engine Controlled] Waste Heat Recovery 
2, Cylinder Deactivation
3, [Engine Controlled] Active Aerodynamics 
4, [Engine Participating] Intelligent Control
5, [Engine Controlled] Vehicle Speed Limiting Technology
6, [Engine Controlled] Predictive Cruise Control 
7, [Engine Controlled] Auto Neutral
8-242, SAE/ISO Reserved

**Manufacturer Defined GHG Active Technology Enumeration**
243, Manufacturer Defined Active Technology 8 
244, Manufacturer Defined Active Technology 7 
245, Manufacturer Defined Active Technology 6 
246, Manufacturer Defined Active Technology 5 
247, Manufacturer Defined Active Technology 4 
248, Manufacturer Defined Active Technology 3
249, Manufacturer Defined Active Technology 2
250 (FAh), Manufacturer Defined Active Technology 1 
251-255, SAE/ISO Reserved

Note: 251-255 (FBh, FCh, FDh, FEh and FFh) shall not be used as they convey special values according to SAE J1939- 71.
Note: Additional Standardized GHG Active Technology Enumerations may be assigned starting at the lowest value in the SAE/ISO Reserved range. Additional Manufacturer Defined GHG Active Technology Enumerations may be assigned starting at the highest value in the SAE/ISO Reserved range.

**Comment by ericthomasswenson** [comment]
Added Active Technology Legend. Need xEV examples.

Obsolete upload deleted...

**Comment by ericthomasswenson** [comment]
With xEV examples

obsolete link deleted use link below.

**Comment by mmschaefer** [comment]
[Example NOx Binning GHG Tabular Displays May12-2021.docx](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/6656444/Example.NOx.Binning.GHG.Tabular.Displays.May12-2021.docx)
This link works.  Use it.

**Comment by ericthomasswenson** [comment]
Statement of work artifact complete
