### ISSUE TITLE
Update Part09Step24 documentation

### ISSUE THREAD

**Issue by mmschaefer** [Equipment-and-Tool-Institute/j1939-84#711]
// 6.9.24.2.b. Compare to list of ECU address + EI-AECD number + actual time (for Timer 1 and/or Timer 2)
        // for any with non- zero timer values created earlier in step **6.9.6.1** and fail if any timer value is less
        // than the value it was earlier in this part.

NEEDS TO BE:

// 6.9.24.2.b. Compare to list of ECU address + EI-AECD number + actual time (for Timer 1 and/or Timer 2)
        // for any with non- zero timer values created earlier in step **6.9.7.1** and fail if any timer value is less
        // than the value it was earlier in this part.

**Comment by ericthomasswenson** [comment]
Marianne, Okay if I call the observed instead of created too?

**Comment by mmschaefer** [comment]
Yes, that would be more accurate, actually.

mms

**Comment by ericthomasswenson** [comment]
Updated in Draft SAE J1939-84 March 10, 2021 as: 
6.9.24.2...
_b.	Compare to list of ECU address + EI-AECD number + actual time (for Timer 1 and/or Timer 2) for any with non-zero timer values observed earlier in step 6.9.7.1 and fail if any timer value is less than the value it was earlier in this part._
