### ISSUE TITLE
Minor correction to Section A.5

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/j1939-84#742]
> Cumulative engine runtime [PG 65253 (SP 247)) and engine idle time (PG 65244 (SP 235)] shall not be reset/cleared for any non-zero values present before code clear.

Change some parentheses  to brackets:

"[PG 65253 (SP 247))" -> [PG 65253 (SP 247)]
"(PG 65244 (SP 235)]" -> [PG 65244 (SP 235)]

**Comment by gumbelmj** [comment]
While we are making updates, I've been breaking up statements like these into two different requirements in the code. Thus the tool can be explicit about which value caused the failure.

**Comment by ericthomasswenson** [comment]
How about leading with the SPNs too?

"[PG 65253 (SP 247))" -> [SP 247 (PG 65253)]
"(PG 65244 (SP 235)]" -> [SP 235 (PG 65244)]

Or use lead with SPNs and use commas?

"[PG 65253 (SP 247))" -> ,SP 247 (PG 65253),
"(PG 65244 (SP 235)]" -> ,SP 235 (PG 65244),

Cumulative engine runtime, SP 247 (PG 65253), and engine idle time, SP 235 (PG 65244), shall not be reset/cleared for any non-zero values present before code clear.

Commas look best to  me.  Separately, they would appear in A.5, p. 113, as

b. Cumulative engine runtime, SP 247 (PG 65253), shall not be reset/cleared for any non-zero values present before code clear.
c. (Cumulative) engine idle time, SP 235 (PG 65244), shall not be reset/cleared for any non-zero values present before code clear.

**Comment by gumbelmj** [comment]
I agree.  That reads much better.

**Comment by ericthomasswenson** [comment]
Updated as shown above in Draft SAE J1939-84 March 10, 2021
