### ISSUE TITLE
Part 5 Step 2 Document question

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/j1939-84#759]
@ericthomasswenson 

> 6.5.2.2.c Fail if DM12 DTC reported does not match the DM6 DTC SPN and FMI reported from step 6.4.2.

Test 6.4.2 is "DM12: Emissions Related Active DTCs"

Should Test 6.5.2. check the _DM12_ from Test 6.4.2 or should be checking the DM6 from _Test 6.4.8_?

(And pedantically , should the step read "... reported from _test_ 6.4.2"?)

**Comment by ericthomasswenson** [comment]
The correct standard for part 4 and all other expectations for fault A is the DM6 DTC from part 3 in test 6.3.2. Step 6.4.2 expects success, and would be better expressed as Test 6.3.2.

If the fault implant fails or is omitted, the DM6 tests in Part 3 will fail.

The DM12 tests in Part 4 will then subsequently fail.

If there isn’t a response in test 6.3.2, it’s fair for you to assume the DTC is null and fail all subsequent comparisons to a null standard.

Counting to two (and subsequently to three) is a key performance requirement.

We could try and create some kind of recovery heuristic... but I think you have better things to do

The technician today has the responsibility to correctly implant the fault.  Bob, I believe, accepts the current part 2 to Part 3 transition.  We can keep it that way.

**Comment by ericthomasswenson** [comment]
﻿Dear Matt, 

The correct standard for part 4 and all other expectations for fault A is the DM6 DTC from part 3 in test 6.3.2. Step 6.4.2 is expects success, and would be better expressed as Test 6.3.2.

If the fault implant fails or is omitted, the DM6 tests in Part 3 will fail.

The DM12 tests in Part 4 will then subsequently fail.

If there isn’t a response in test 6.3.2, it’s fair for you to assume the DTC is null and fail all subsequent comparisons to a null standard.

Counting to two (and subsequently to three) is a key performance requirement.

We could try and create some kind of recovery heuristic... but I think you have better things to do

The technician today has the responsibility to correctly implant the fault.  Bob, I believe, accepts the current part 2 to Part 3 transition.  We can keep it that way.

Best Wishes,

Eric Swenson

**Comment by gumbelmj** [comment]
So the document should read:
"6.5.2.2.c Fail if DM12 DTC reported does not match the DM6 DTC SPN and FMI reported from _test 6.3.2._" ?

**Comment by ericthomasswenson** [comment]
Yes, as shown below.

_6.5.2.2 Fail Criteria 
a. Fail if no OBD ECU reporting MIL on. See Section A.8 for allowed values.  
b. Fail if all OBD ECUs report no DM12 DTC set. 
c. Fail if DM12 DTC reported does not match the DM6 DTC SPN and FMI reported from **test 6.3.2.**
d. Fail if any ECU reporting MIL as ON, flashing. See Section A.8 for allowed values._

**Comment by ericthomasswenson** [comment]
Let’s also add a footnote to 6.3.2.

**_[xx] The DM6 response is expected to provide the Fault A DTC value to be used as the standard for subsequent responses, expecting the DTC value for fault A.  Should there be no value for fault A returned in test 6.3.2, the standard value for Fault A shall be considered to be null, and all subsequent comparisons to the null value shall fail._**

**Comment by ericthomasswenson** [comment]
Implemented in 17 March 2021 as-built draft

**Comment by ericthomasswenson** [comment]
Implemented in 17 March 2021 as built draft
