### ISSUE TITLE
Question about checking for erased data

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/j1939-84#763]
@ericthomasswenson,

Section A5:
>...when the specification for SAE J1939-84 indicates the test shall verify that diagnostic information is erased, the following content may be evaluated as defined by a given Section 6 test part:
1. Emission-related DTCs
a. DM6 pending shall report no DTCs and MIL off and not flashing.
...

So if I write the method to check for erased, I end up with
```
if (dm6Packet.hasDTCs()) {
    // Module did not erased data
}
```

and later in Section A5:
>... when the specification indicates that the test shall verify no diagnostic information was erased, none of the above shall occur. The occurrence of any of the items above shall be considered an indication of some diagnostic information having been erased.

Putting that into code, I end up with:
```
if (!dm6Packet.hasDTCs()) {
    // Module erased data
}
```

So if a module doesn't have a DM6 DTC, and didn't prior to code clear, then by strict reading of the document, it 'erased' when it shouldn't have.

**Comment by ericthomasswenson** [comment]
The following note is proposed for A.5, in line with the text shown:

* Diagnostic trouble codes for pending, active and previously active malfunctions
   * Emissions related pending DTCs (can be read with DM6) 
   * Active diagnostic trouble codes (can be read with DM1) 
   * Previously Active emissions related DTCs (can be read with DM23)
   **_Note: Simply checking fault displays for SPN 0, FMI 0 does not prove data was
               erased.  In many instances the display provided no faults (shown as SPN 0, FMI 0) prior to 
               the “false” deletion stimulus (e.g DM3 or DM22) being assessed, and there was no data
               to erase, in error._**

**Comment by ericthomasswenson** [comment]
Implemented in 17 March 2021 as built draft.

**Comment by ericthomasswenson** [comment]
Implemented in 17 March 2021 as built draft.

**Comment by gumbelmj** [comment]
@ericthomasswenson, adding a note to this criteria does not provide enough clarity to implement the intention.

If I'm understanding this correctly, 

The DM6 should be considered erased:
-  if it does not report a DTC _and it previously did_
- or if DM6 does not report MIL off _and it previously was off_

The DM6 should be considered not erased:
- if it reports a DTC
- or if it reports MIL on
- or it does not report a DTC and previously did not report a DTC _and_ it reports MIL off and it previously reported MIL off

Is this the correct logic?

**Comment by gumbelmj** [comment]
Email from @ericthomasswenson:

I’ve been thinking about it ... It’s clear that guidance is missing.

The coordination for MIL status is checked every time DM1,2,6,12,23,28 and 31 are queried. If we didn’t check at all, possibly with the exception of DM1. The likelihood of an overall false negative outcome is small.

The easiest thing to do may be to check DM1 for inappropriate changes, accept all matching lamp status values from all the other DMs, and fail the ones that don’t match DM1.  Then the SPN and FMI become the focus for DM6, 12, 23, 28 ...

We could then say:

Likewise, when the specification indicates that the test shall verify no diagnostic information was erased, none of the above shall occur.  The occurrence of any of the items above shall be considered an indication of some diagnostic information having been erased. 

Erasure for MIL status may checked for inappropriate changes in response to false erasure stimuli only in DM1, and the value received in DM1 can be used as the post-stimuli standard for the expected value of MIL Status in DM2, DM6, DM12, DM23, DM28, DM27 (if supported) and DM31 (if supported). Fault A and Fault B will provide the expected values for SPN and FMI when provided in a display instead of SPN 0, FMI 0.  Failure to properly display Fault A and Fault B to match the signal chart in Figure 2 is rigorously examined prior to checking for inappropriate deletion such that the potential for false negative outcomes for the ECU as a whole is minimal, as inappropriate responses will be detected when MIL status is checked in DM1.

**Comment by gumbelmj** [comment]
This method seemed to summarize the intent here:

```
 private static boolean shouldBeReported(boolean verifyIsErased,
                                            boolean wasPreviouslyErased,
                                            boolean isCurrentlyErased) {
        if (verifyIsErased) {
            // Report if the data is not erased
            return !wasPreviouslyErased && !isCurrentlyErased;
        } else {
            // Report if the data is erased
            return isCurrentlyErased && !wasPreviouslyErased;
        }
    }
```

It became clear that it needs to check for state changes between clear requests.  The state is clearly defined by the 'is erased' criteria.

**Comment by gumbelmj** [comment]
After discussing this IRL, we've decided to close this for now and reopen it if we have issues with the current implementation

**Comment by ericthomasswenson** [comment]
[erasure-checks-for-matt.docx](https://github.com/battjt/j1939-84/files/6174552/erasure-checks-for-matt.docx)

March 17, 2021 Text to remain.  

March 22, performance to be reviewed for excess false positives and negatives.

Uploaded example outcomes may be considered as an enhancement following this review.
