### ISSUE TITLE
Part 1 Step 7 needs to report 0x00 in any byte of CVN

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/j1939-84#766]
See #156 for details

**Comment by ericthomasswenson** [comment]
Alternatively,

6.1.7.2 Fail Criteria
a. Fail if total number of reported CAL IDs is < user entered value for number of emission or diagnostic critical control units (test 6.1.2).
b. For responses from OBD ECUs:
i. Fail if <> 1 CVN for every CAL ID.
ii. Fail if CAL ID not formatted correctly (printable ASCII, padded incorrectly, etc.).
iii. Fail if any received CAL ID is all 0xFFh or any CVN is all 0x00h.
**_iv. Fail if CVN padded with 16-binary zeros (where either the 1st two bytes are both 00h or the last two bytes both 00h). Note HD OBD CVNs are required to be 32-bits._**
6.1.7.3 Warn Criteria
a. Warn if total number of reported CAL IDs is > user entered value for number of emission or diagnostic critical control units (test 6.1.2).
b. Warn if more than one CAL ID and CVN pair is provided in a single DM19 message.
**_c. For responses from OBD ECUs, warn if 00h is observed in either the first or fourth bytes._**
d. For responses from non-OBD ECUs:
i. Warn if any non-OBD ECU provides CAL ID.
ii. Warn if <> 1 CVN for every CAL ID.
iii. Warn if CAL ID not formatted correctly (contains non-printable ASCII, padded incorrectly, etc.).
iv. Warn if any received CAL ID is all 0xFFh or any CVN is all 0x00h.
v. Warn if CVN padded incorrectly (must use 0x00h in MSB for unused bytes).

**Comment by gumbelmj** [comment]
In order keep track of all the moving parts on this project, I try to keep the changes to the 'document' in tickets which are separate from the 'code' tickets.  This is one such case. Currently the code matches the document as supplied "originally",   #156 is a ticket to update the document; this ticket is to update the source code (so we remember to do both)

At this time, I have this issue marked as "future enhancement" indicating that we are _not_ planning to implement this change in the current release of the software.  It's believe this can wait for the "NOx Binning" changes in V4 of the software.  

@ericthomasswenson, do you concur with that?

**Comment by ericthomasswenson** [comment]
The SOW text should define the current intent.

Revisit after the next release.

**Comment by ericthomasswenson** [comment]
The failure is detected… the warning message is garbled. See #1201

Close in favor of #1201 with the Task 5 artifact text for first or last byte.
