### ISSUE TITLE
Don't report overall failure for a module erasing data

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/j1939-84#767]
We already log the failure for the module erasing specific data; we don't need to also log that the module (overall) erased data.

**Comment by ericthomasswenson** [comment]
Yes, that does get tedious to read, and explain to CARB, that there is only one failure.

**Comment by ericthomasswenson** [comment]
The principal complaints with the old software were 
1. Not waiting at least 200 ms for a response, and submitting overlapping queries.
2. Omitting queries.
Just an extra warning message is refreshing, in comparison.
