### ISSUE TITLE
DM20's report as erased because the ignition cycles changed

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/j1939-84#770]
@ericthomasswenson ,

In developing the simulated engine, I discovered that a failure is present because the number of ignition cycles in DM20 has changed between the last requested DM 20 and request after the codes are cleared.

For instance, in Test 8.13 we request a DM20 to ascertain if the diagnostic information has been erased as part of Fail criteria 6.8.13.2.a "Fail if any diagnostic information erased"

Remembering that Section A.5 indicates "...when the specification for SAE J1939-84 indicates the test shall verify that diagnostic information is erased...7.a DM20 Monitor Performance Ratio data shall not be reset/shall stay the same as it was before code clear for all values including the number of ignition cycles..."

The previous request for DM20 occurred during Test 7.13.  During Test 7.18, several ignition cycles occurred.

Thus the tool will indicate that the ECU erased diagnostic information as the DM20 data is no longer the same as it was before code clear.

Is it expected that within any test indicating the tool should check for erased diagnostic information, the tool should request DM20 before requesting a code clear?

**Comment by ericthomasswenson** [comment]
I propose we add a note in A.5 after 9.

**_Whereas the baseline for monotonically increasing data items, that are not to be reset by a DM11 command may increase from the last known value, the monotonically increasing attribute of such data shall be used to check for erased data by affirming (as failure criteria) that the current value is less than the last known value for the indicated items (in 7 and 9)._**
﻿
﻿The number of ignition cycles is defined by the Figure in A.9.  These indications match 13 CCR 1971.1 which says:
“Ignition Cycle” means a driving cycle that begins with engine start, meets the engine start definition for at least two seconds plus or minus one second, and ends with engine shutoff. For hybrid vehicles, “ignition cycle” means a driving cycle that begins when the propulsion system active definition is met for at least two seconds plus or minus one second, and ends when the propulsion system active definition is no longer met.

**Comment by gumbelmj** [comment]
So in reality, the criteria for 7.a should read:
>DM20 Monitor Performance Ratio data shall not be reset/_decrement_ any values....

?

**Comment by ericthomasswenson** [comment]
Extending the example to the rest of the items in 7 and 9 provides: 

7.	Monitor performance data
a.	DM20 Monitor Performance Ratio data shall not be reset **_or display a value less than the prior value_** before code clear for all values including the number of ignition cycles, general denominators, monitor specific numerators, and monitor specific denominators.
8.	Permanent DTCs
a.	DM28 permanent DTCs shall not be erased **_and_** still report any permanent DTC that was present before code clear.
9.	Engine runtime information
a.	DM33 EI-AECD information shall not be reset **_or display a value less than the prior value_** /cleared for any non-zero values present before code clear.
b.	Cumulative engine runtime, SP 247 PG 65253), shall not be reset **_or display a value less than the prior value_** for any non-zero value present before code clear.
c.	(Cumulative) engine idle time, SP 235 (PG 65244) shall not be reset **_or display a value less than the prior value_** for any non-zero value present before code clear.

**_Whereas the baseline for monotonically increasing data items, that are not to be reset by a DM11 command may increase from the last known value, the monotonically increasing attribute of such data shall be used to check for erased data by affirming (as failure criteria) that the current value is less than the last known value for the indicated items (in 7 and 9)._**

**Comment by ericthomasswenson** [comment]
Implemented in 17 March as built draft
