### ISSUE TITLE
"Waiting" dialogs should include a timer so the operator knows how long they've waited

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/j1939-84#804]
In several places, the app needs to wait a "manufacturer's recommended interval"  To aid the operator in knowing how long that is, a timer can be displayed on the dialog

**Comment by mmschaefer** [comment]
@gumbelmj - Is this related to #984

**Comment by mmschaefer** [comment]
Closed accidentally.

**Comment by battjt** [comment]
Functionality was added.  We need feedback to know it is to intrusive or confusing.  Does it need a label?
