### ISSUE TITLE
Document enhancements for the info

### ISSUE THREAD

**Issue by mmschaefer** [Equipment-and-Tool-Institute/j1939-84#811]
Update the documentation of Part 01 Step 07 to use the word "info" instead of "warning".

**Comment by ericthomasswenson** [comment]
Correct error of omission in change pages to match SOW item as shown.

6.1.7.3 Warn Criteria 
a. Warn if total number of reported CAL IDs is > user entered value for number of emission or diagnostic critical control units (test 6.1.2). 
b. **_Info_** if more than one CAL ID and CVN pair is provided in a single DM19 message.

**Comment by ericthomasswenson** [comment]
Amend 6.8.12.3 as shown to provide correct enumerated values for DM22

6.8.12.3 Warn Criteria 
a. Info: if DM22 (PG 49920) **_CLR_**_PA_NACK or **_CLR_**_ACT_NACK is not received with an acknowledgement code of 0.[53]
b. Info: if J1939-21 NACK for PG 49920 is received.

**Comment by ericthomasswenson** [comment]
#813 is the fix ticket for both #811 (open) and #966 (closed, duplicate)

**Comment by mmschaefer** [comment]
Per @ericthomasswenson - closing ticket as correct ticket  [#813](https://github.com/Equipment-and-Tool-Institute/j1939-84/issues/813) will be used to track the work/fix.
