### ISSUE TITLE
Need launch strategy for collecting bugs

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#815]
We need to tell users what they should do to provide bugs during the support period.

For example, do we want to adapt the IUMPR form an attach them ...

**Comment by gumbelmj** [comment]
Personally, I'd like each bug report or enhancement request to be entered into the GitHub repo.  By doing so, we can be assured that everyone is aware of the issue and we capture the discussion around it.  Further, we can clearly indicate the version it was fixed in or note why we are not resolving it.

**Comment by gumbelmj** [comment]
Consider creating issue templates: https://docs.github.com/en/github/managing-your-work-on-github/creating-an-issue
and
https://github.blog/2018-01-25-multiple-issue-and-pull-request-templates/

**Comment by gumbelmj** [comment]
I'd like to propose we setup an anonymous bug reporting system found here: [https://gitreports.com/issue/battjt/j1939-84](https://gitreports.com/issue/battjt/j1939-84)

This will create an issue in the repo which can then be triaged by the team.  #878 is an example of an issue generated through this system.

Additionally, I'd like to put a link in the help which will link the user to the bug reporting system.

@ericthomasswenson , thoughts?

**Comment by gumbelmj** [comment]
Here's my proposed help text:

![Screen Shot 2021-03-23 at 9 29 53 PM](https://user-images.githubusercontent.com/7874086/112241018-d3c96c80-8c1f-11eb-84c7-0dd4cd8ca497.png)
