### ISSUE TITLE
Remove "Wait for manufacturer's interval" dialog box

### ISSUE THREAD

**Issue by mmschaefer** [Equipment-and-Tool-Institute/j1939-84#829]
To verify a KEY-OFF state, the software waits for the ECU to go to sleep (stop sending engine speed messages) which makes the wait for manufacturer's interval with the KEY-OFF redundant.  Can we remove the additional check after a KEY-OFF?  Need Eric's feedback on this one.  (I.E. 6.8.16.1)

**Comment by battjt** [comment]
Useful.
