### ISSUE TITLE
Freeze Frame Interpretation (correctly) missing for 6.3.13.1.c

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#835]
6.3.13.1.c requires interpretation of the FF content.

This could not be provided as FF length was mismatched.

FAIL: 6.3.13.2.c - Received data (164) does not match expected number of bytes (134) based on DM24 supported SPN list for Engine #1 (0)

6.3.13.1 Actions 
a. DS DM25 [(send Request (PGNPG 59904) for PGNPG 64951 (SPNSPs 3300, 1214-1215)]) to each OBD ECU.  
b. If no response [(transport protocol RTS or NACK(Busy) in 220 ms]), then retry DS DM25 request to the OBD ECU. ([Do not attempt retry for NACKS that indicate not supported.)] 
**_c. Translate and print in log file all received freeze frame data with data labels assuming data received in order expected by DM24 response for visual check by test log reviewer._**

**Comment by ericthomasswenson** [comment]
The displayed content is:

Start Test 3.13 - DM25: Expanded freeze frame

10:37:33.5970 Destination Specific DM25 Request to Engine #1 (0)
10:37:33.6049 18EA00F9 [3] B7 FD 00 (TX)
10:37:33.6160 18FDB700 [169] A8 83 10 07 01 01 01 C8 1C 07 4E 00 00 00 03 00 03 01 00 00 C6 2C 02 62 83 03 00 78 CB 26 43 01 1B 01 1A C6 11 6C 00 00 00 00 6B 24 0C 22 2B 8B 2A E8 28 00 00 31 90 E7 06 C7 1E 0F 58 03 24 00 F9 00 83 83 9E 09 A9 BE B5 D8 D7 10 3B 00 19 40 1F E0 2E 00 00 00 00 50 00 1E 27 CC 7B 0F 00 44 EA 06 4D AE 5B 2F 60 2F 60 2F 60 2F 60 2F 60 2F 60 FA 6C 45 01 00 00 04 00 0F 07 A0 0F A0 0F C1 00 00 79 28 46 29 36 25 00 26 00 00 FF 5A 8E 51 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3A 00 00 3A 00 00 00 00 00
DM25 from Engine #1 (0): 
Freeze Frames: [
Freeze Frame: {
DTC 4227:7 - Engine Crankcase Breather Oil Separator, Mechanical System Not Responding Or Out Of Adjustment - 1 times
SPN Data: 01 01 C8 1C 07 4E 00 00 00 03 00 03 01 00 00 C6 2C 02 62 83 03 00 78 CB 26 43 01 1B 01 1A C6 11 6C 00 00 00 00 6B 24 0C 22 2B 8B 2A E8 28 00 00 31 90 E7 06 C7 1E 0F 58 03 24 00 F9 00 83 83 9E 09 A9 BE B5 D8 D7 10 3B 00 19 40 1F E0 2E 00 00 00 00 50 00 1E 27 CC 7B 0F 00 44 EA 06 4D AE 5B 2F 60 2F 60 2F 60 2F 60 2F 60 2F 60 FA 6C 45 01 00 00 04 00 0F 07 A0 0F A0 0F C1 00 00 79 28 46 29 36 25 00 26 00 00 FF 5A 8E 51 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3A 00 00 3A 00 00 00 00 00
}
]

10:37:35.0606 Destination Specific DM25 Request to DPF Controller (85)
10:37:35.0725 18EA55F9 [3] B7 FD 00 (TX)
10:37:35.0733 18FDB755 [8] 00 00 00 00 00 FF FF FF
DM25 from DPF Controller (85): 
Freeze Frames: [
No Freeze Frames
]
6.3.13.1.c - Received from Engine #1 (0): 
Freeze Frame: {
DTC 4227:7 - Engine Crankcase Breather Oil Separator, Mechanical System Not Responding Or Out Of Adjustment - 1 times
SPN Data: 01 01 C8 1C 07 4E 00 00 00 03 00 03 01 00 00 C6 2C 02 62 83 03 00 78 CB 26 43 01 1B 01 1A C6 11 6C 00 00 00 00 6B 24 0C 22 2B 8B 2A E8 28 00 00 31 90 E7 06 C7 1E 0F 58 03 24 00 F9 00 83 83 9E 09 A9 BE B5 D8 D7 10 3B 00 19 40 1F E0 2E 00 00 00 00 50 00 1E 27 CC 7B 0F 00 44 EA 06 4D AE 5B 2F 60 2F 60 2F 60 2F 60 2F 60 2F 60 FA 6C 45 01 00 00 04 00 0F 07 A0 0F A0 0F C1 00 00 79 28 46 29 36 25 00 26 00 00 FF 5A 8E 51 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3A 00 00 3A 00 00 00 00 00
}

Unable to confirm engine speed
FAIL: 6.3.13.2.c - Received data (164) does not match expected number of bytes (134) based on DM24 supported SPN list for Engine #1 (0)

End Test 3.13 - DM25: Expanded freeze frame

**Comment by ericthomasswenson** [comment]
PGN 61444 with Supported SPNs 190, 512, 513
10:34:59.3111 0CF00400 [8] F0 7D 80 C4 12 00 F3 80
Found: Engine Speed from Engine #1 (0): 
  SPN   899, Engine Torque Mode: 0000
  SPN  4154, Actual Engine - Percent Torque (Fractional): 1.875000 %
  SPN   512, Driver's Demand Engine - Percent Torque: 0.000000 %
  SPN   513, Actual Engine - Percent Torque: 3.000000 %
  SPN   190, Engine Speed: 600.500000 rpm
  SPN  1483, Source Address of Controlling Device for Engine Control: 0.000000 source address
  SPN  1675, Engine Starter Mode: 0011
  SPN  2432, Engine Demand - Percent Torque: 3.000000 %

**Comment by ericthomasswenson** [comment]
Let’s improve 

Unable to confirm engine speed

to

Unable to confirm engine speed **_in freeze frame data._**

**Comment by gumbelmj** [comment]
#825 was created to improve the engine speed message.  We're going to make it a warning.  Should we add that to the specification?

**Comment by ericthomasswenson** [comment]
6.3.13.2.e. Fail/warn per Section A.2, Criteria for Freeze Frame Evaluation. 

Table A.2 Says [Warn If] SP 190 is not supported in DM24

Add **_Or, if Engine Speed cannot be determined in FF data._** behind quoted entry.
