### ISSUE TITLE
Add Offset to table A-1 for SP 91 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#858]
Add Offset to table A-1 for SP 91. 0.4 % is close enough to 0, just like 99% is close enough to 100.

PGN 61443 with Supported SPNs 91, 92
09:55:06.4505 0CF00300 [8] D1 01 08 FF FF FF 6E FF
Found: Electronic Engine Controller 2 from Engine #1 (0): 
  SPN   558, Accelerator Pedal 1 Low Idle Switch: 01
  SPN   559, Accelerator Pedal Kickdown Switch: 00
  SPN  1437, Road Speed Limit Status: 01
  SPN  2970, Accelerator Pedal 2 Low Idle Switch: 11
  SPN    91, Accelerator Pedal Position 1: 0.400000 %
  SPN    92, Engine Percent Load At Current Speed: 8.000000 %
  SPN   974, Remote Accelerator Pedal Position: Not Available
  SPN    29, Accelerator Pedal 2 Position: Not Available
  SPN  2979, Vehicle Acceleration Rate Limit Status: 11
  SPN  5021, Momentary Engine Maximum Power Enable Feedback: 11
  SPN  5399, DPF Thermal Management Active: 11
  SPN  5400, SCR Thermal Management Active: 11
  SPN  3357, Actual Maximum Available Engine - Percent Torque: 44.000000 %
  SPN  5398, Estimated Pumping - Percent Torque: Not Available

WARN: 6.11.7.3.a - N.8 Engine #1 (0) reported value for SPN 91 (0.4) is implausible

**Comment by gumbelmj** [comment]
Duplicate
