### ISSUE TITLE
Doc - Examples for DM26 enable bit review

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#861]
Review the following enable bit messages for enable bit criteria enhancement.
Note DM5 content for issue #860 

Start Test 1.13 - DM5: Diagnostic Readiness 1: Monitor Readiness

10:32:51.3757 Global DM5 Request
10:32:51.3795 18EAFFF9 [3] CE FE 00 (TX)
10:32:51.3821 18FECE55 [8] FF FF 14 00 00 00 00 00
DM5 from DPF Controller (85): OBD Compliance: HD OBD (20), Active Codes: not available, Previously Active Codes: not available
10:32:51.3842 18FECE00 [8] 00 00 14 37 E0 1E A0 1E
DM5 from Engine #1 (0): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0
...
10:32:51.3946 18FECEA7 [8] 00 01 FF 00 00 00 00 00
DM5 from Instrument Cluster #2 (167): OBD Compliance: Not available (255), Active Codes: 0, Previously Active Codes: 1

Vehicle Composite of DM5:
    A/C system refrigerant     not supported,     complete
    **_Boost pressure control sys     supported, not complete_**
    Catalyst                   not supported,     complete
    Cold start aid system      not supported,     complete
    Comprehensive component        supported,     complete
    Diesel Particulate Filter      supported, not complete
    EGR/VVT system                 supported, not complete
    Evaporative system         not supported,     complete
    Exhaust Gas Sensor             supported, not complete
    **_Exhaust Gas Sensor heater      supported,     complete_**
    Fuel System                    supported, not complete
    Heated catalyst            not supported,     complete
    Misfire                        supported, not complete
    NMHC converting catalyst       supported, not complete
    NOx catalyst/adsorber          supported, not complete
    Secondary air system       not supported,     complete

FAIL: 6.1.13.2.a (A6.2.c) - Composite vehicle readiness for Exhaust Gas Sensor heater did not meet the criteria of Table A4
_**This outcome is correct, but should not define the standard for part 12 when the failure message in part 12 references part 11.**_

Start Test 1.14 - DM26: Diagnostic readiness 3

10:32:52.0271 Global DM26 Request
10:32:52.0368 18EAFFF9 [3] B8 FD 00 (TX)
10:32:52.0442 18FDB800 [8] 00 00 05 37 40 14 E0 1E
DM26 from Engine #1 (0): Warm-ups: 5, Time Since Engine Start: 0 seconds

Vehicle Composite of DM26:
    A/C system refrigerant     not enabled,     complete
    **_Boost pressure control sys not enabled, not complete_**
    Catalyst                   not enabled,     complete
    Cold start aid system      not enabled,     complete
    Comprehensive component        enabled,     complete
    Diesel Particulate Filter      enabled, not complete
    EGR/VVT system             not enabled, not complete
    Evaporative system         not enabled,     complete
    Exhaust Gas Sensor         not enabled, not complete
    **_Exhaust Gas Sensor heater      enabled, not complete_**
    Fuel System                    enabled, not complete
    Heated catalyst            not enabled,     complete
    Misfire                        enabled, not complete
    NMHC converting catalyst       enabled, not complete
    NOx catalyst/adsorber      not enabled, not complete
    Secondary air system       not enabled,     complete

FAIL: 6.1.14.2.a - Engine #1 (0) response for a monitor Boost pressure control sys in DM5 is reported as supported and is reported as not enabled by DM26 response
FAIL: 6.1.14.2.a - Engine #1 (0) response for a monitor EGR/VVT system in DM5 is reported as supported and is reported as not enabled by DM26 response
FAIL: 6.1.14.2.a - Engine #1 (0) response for a monitor Exhaust Gas Sensor in DM5 is reported as supported and is reported as not enabled by DM26 response
FAIL: 6.1.14.2.a - Engine #1 (0) response for a monitor NOx catalyst/adsorber in DM5 is reported as supported and is reported as not enabled by DM26 response
FAIL: 6.1.14.2.d - Engine #1 (0) response indicates number of warm-ups since code clear is not zero

**Comment by ericthomasswenson** [comment]
Start Test 11.11 - DM26: Diagnostic Readiness 3

09:26:23.3172 Destination Specific DM26 Request to Engine #1 (0)
08:14:48.3877 18EA00F9 [3] B8 FD 00 (TX)
08:14:48.3978 18FDB800 [8] 6F 02 00 27 C0 16 E0 1E
DM26 from Engine #1 (0): Warm-ups: 0, Time Since Engine Start: 623 seconds

End Test 11.11 - DM26: Diagnostic Readiness 3


End Test 12.1 - Verify engine operation

Start Test 12.2 - DM26: Diagnostic readiness 3

09:30:02.8123 Destination Specific DM26 Request to Engine #1 (0)
08:18:27.8825 18EA00F9 [3] B8 FD 00 (TX)
08:18:27.8890 18FDB800 [8] 00 00 00 37 C0 16 E0 1E
DM26 from Engine #1 (0): Warm-ups: 0, Time Since Engine Start: 0 seconds
FAIL: 6.12.2.2.a - Engine #1 (0) reported Misfire as 'not complete this cycle' when it reported it as 'complete this cycle' in part 11
// DM26 bits cited for enhancement… this is one reason why.

**Comment by ericthomasswenson** [comment]
6.1.14.2 Fail Criteria 
a. Fail if any response for any monitor supported in DM5 by a given ECU is reported as “'0=monitor complete this cycle or not supported”' in SP 3303 bits 1-4 and SP 3305 [except comprehensive components monitor (CCM)].  
b. Fail if any response for each monitor not supported in DM5 by a given ECU is not also reported in DM26 as “'0=monitor complete this cycle or not supported”' in SP 3303 bits 5 to -7 and “'0=monitor disabled for rest of this cycle or not supported”' in SP 3303 bits 1- and 2 and SP 3304.23 
c. Fail if any response from an ECU indicating support for CCM monitor in DM5 reports “'0=monitor disabled for rest of this cycle or not supported'” in SP 3303 bit 3.  
d. Fail if any response indicates number of warm-ups since code clear (WU-SCC) (SP 3302) is not zero.  
e. Fail if any response indicates time since engine start (SP 3301) is not zero. 
f. Fail if no OBD ECU provides DM26. 
6.1.14.3 Warn Criteria 
a. Warn if any individual required monitor, except Continuous Component Monitoring (CCM) is supported by more than one OBD ECU.

**Comment by ericthomasswenson** [comment]
Add misfire to a.
6.12.2.2 Fail Criteria 
a. Fail if any supported monitor (except CCM **_or misfire_**) that was “0 = complete this cycle” in part 11 is not reporting “1 = not complete this cycle.”. 
b. Fail if NACK not received from OBD ECUs that did not provide a DM26 message.

**Comment by ericthomasswenson** [comment]
See #745 for prior part 2 discussion.

Test Conditions for Enable/Disable status bits are not adequately controlled to predict values without creating false positive outcomes. Cold soaks, cold ambient conditions, and engine running have been observed to present false positive outcomes.  The text below removes the criteria that have been observed present the false positive outcomes for enabled/disabled bits.

6.1.14.1 Actions 
a. Global DM26 [(send Request (PG 59904) for PG 64952 (SPs 3301-3305)]). 
i. Create list by OBD ECU address of all data and current status for use later in the test.  
b. Display monitor readiness composite value in log for OBD ECU replies only.  
6.1.14.2 Fail Criteria 
a. Fail if any response for any monitor supported in DM5 by a given ECU is reported as “'0=monitor complete this cycle or not supported”' in SP 3303 bits 1-4 and SP 3305 [except comprehensive components monitor (CCM)].  
b. Fail if any response for each monitor not supported in DM5 by a given ECU is not also reported in DM26 as “'0=monitor complete this cycle or not supported”' in SP 3303 bits 5 to 7 and “'0=monitor disabled for rest of this cycle or not supported”' in SP 3303 bits 1 and 2 and SP 3304.[23] 
 **// delete c. Fail if any response from an ECU indicating support for CCM monitor in DM5 reports “'0=monitor disabled for rest of this cycle or not supported'” in SP 3303 bit 3.  //** 
**_c_**. Fail if any response indicates number of warm-ups since code clear (WU-SCC) (SP 3302) is not zero.  
**_d_**. Fail if any response indicates time since engine start (SP 3301) is not zero. 
_**e**_. Fail if no OBD ECU provides DM26. 
6.1.14.3 Warn Criteria 
a. Warn if any individual required monitor, except Continuous Component Monitoring (CCM) is supported by more than one OBD ECU. 

6.2.8.1 Actions 
a. DS DM26 [(send Request (PG 59904) for PG 64952 (SPNs 3301-3305)]) to each OBD ECU. 
i. Record time since engine start (SP 3301) from each ECU and timestamp of when message was received. 
b. Display monitor readiness composite value in log for OBD ECU replies only.  
6.2.8.2 Fail Criteria 
a. Fail if any difference in any ECUs **_monitor support bits_** compared to responses in part 1 after DM11. 
b. Fail if any ECU reports number of warm-ups SCC (SP 3302) greater than zero.[33]
c. Fail if NACK not received from OBD ECUs that did not provide a DM26 response.  
6.2.8.3 Warn Criteria 
a. Warn if any individual required monitor, except Continuous Component Monitoring (CCM) is supported by more than one OBD ECU. 

6.9.16 DM26: Diagnostic Readiness 3 
6.9.16.1 Actions 
a. DS DM26 [(send Request (PG 59904) for PG 64952 (SP 3302)]) to each OBD ECU. 
6.9.16.2 Fail Criteria 
a. Fail if any ECU that was reporting a non-zero value of number of WU-SCC (SP 3302) in test 6.8.16.1.a is still reporting > 0. 
b. Fail if NACK not received from OBD ECUs that did not provide a DM26 message. 

6.11.2.1 Actions 
a. Global DM26 ([send Request (PG 59904) for PG 64952 (SP 3301)]). 
i. Record time since engine start. 
ii. Separately start tracking time in software to compare to reported values later in part 11. 
6.11.2.2 Fail Criteria 
a. If more than one ECU responds, fail if times (since engine start) differ by > 2 seconds. 
b. Fail if no OBD ECU provides a DM26 message.  

6.11.11.1 Actions 
a. DS DM26 [(send Request (PG 59904) for PG 64952 (SPs 3301-3305)]) to each OBD ECU.  
b. Record all monitor readiness this trip data (i.e., which supported monitors are complete this trip or supported and not complete this trip). 
**_c. Display composite status for support and enable bits for responses received from OBD ECUs._**
6.11.11.2 Fail Criteria 
a. Fail if response indicates time since engine start (SP 3301) differs by more than ±10 seconds from expected value (calculated by software using original DM26 response in this part plus accumulated time since then).
i.e., Fail if ABS[(Time Since Engine StartB - Time Since Engine StartA) - Delta Time] > 10 seconds.  
b. Fail if NACK not received from OBD ECUs that did not provide a DM26 message. 

6.12.2.1 Actions 
a. DS DM26 [(send Request (PG 59904) for PG 64952 (SPs 3303-3305)]) to each OBD ECU. 
6.12.2.2 Fail Criteria 
a. Fail if any supported monitor (except CCM **_and Misfire_**) that was “0 = complete this cycle” in part 11 is not reporting “1 = not complete this cycle.”
b. Fail if NACK not received from OBD ECUs that did not provide a DM26 message.

**Comment by ericthomasswenson** [comment]
Let’s try and do this with the discovered user issues.  Vimal complained about this as part of his back to back changes. Carb has been informed of the decision. The most practical approach seems to be to delete the criteria creating the false positive outcomes.

**Comment by vmuthu2** [comment]
Start Test 2.8 - DM26: Diagnostic readiness 3

12:05:16.5114 Destination Specific DM26 Request to Engine #1 (0)
12:05:16.5144 18EA00F9 [3] B8 FD 00 (TX)
12:05:16.5229 18FDB800 [8] 43 00 00 37 60 1C E0 1E
DM26 from Engine #1 (0): Warm-ups: 0, Time Since Engine Start: 67 seconds
FAIL: 6.2.8.2.a - Difference from Engine #1 (0) monitor support bits this cycle compared to responses in part 1 after DM11

The EGR and boost (enable/disable) bits for the two monitor groups disable for some time before they are enabled. 
As it is mentioned, every manufacturer have the enabled/disable bits configured differently. Suggest removing 6.2.8.2a check for failure evaluation.

6.2.8.1 Actions
a. DS DM26 [(send Request (PG 59904) for PG 64952 (SPNs 3301-3305)]) to each OBD ECU.
i. Record time since engine start (SP 3301) from each ECU and timestamp of when message was received.
b. Display monitor readiness composite value in log for OBD ECU replies only.
6.2.8.2 Fail Criteria
a. Fail if any difference in any ECUs monitor support bits compared to responses in part 1 after DM11. --- **Delete this check!!**
b. Fail if any ECU reports number of warm-ups SCC (SP 3302) greater than zero.[33]
c. Fail if NACK not received from OBD ECUs that did not provide a DM26 response.
6.2.8.3 Warn Criteria
a. Warn if any individual required monitor, except Continuous Component Monitoring (CCM) is supported by more than one OBD ECU.

Below from J1939-73:
![image](https://user-images.githubusercontent.com/46825003/116628734-9e8df980-a904-11eb-955d-f603883aa88e.png)

**Comment by ericthomasswenson** [comment]
Continuous misfire status defined to be complete in 2019 reg. change my contribute to this observation.

**Comment by ericthomasswenson** [comment]
SOW Defined Criteria: See SOW artifact for bold italic emphasis
[Future-Enhancement-Text-for-J1939-84 V-3-0-X Test-Software 6-7-2021.docx](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/8499204/Future-Enhancement-Text-for-J1939-84.V-3-0-X.Test-Software.6-7-2021.docx)


Proposed text.         6.1.14 is the as built text for v.3.0.9.

6.1.14 DM26: Diagnostic Readiness 3  
6.1.14.1 Actions 
a. Global DM26 [send Request (PG 59904) for PG 64952 (SPs 3301-3305)]. 
    i. Create list by OBD ECU address of all data and current status for use later in the test.  
b. Display monitor readiness composite value in log for OBD ECU replies only.  

6.1.14.2 Fail Criteria 
a. Fail if any response for any monitor supported in DM5 by a given ECU is reported as “0=monitor complete this cycle or not supported” in SP 3303 bits 1-4 and SP 3305 [except comprehensive components monitor (CCM)].  
// After a reset (here DM11), all completed monitors are reset to not complete.

b. Fail if any response for each monitor not supported in DM5 by a given ECU is 
also reported in DM26 as “1=monitor not complete this monitoring cycle” in SP 3303 bits 5-7.
// Unsupported monitors will never need to run and are ‘de facto’ complete.

c. Fail if any response for each monitor not supported in DM5 by a given ECU is 
also reported in DM26 as “0=monitor enabled for this monitoring cycle” in SP 3303 bits 1 and 2 and SP 3304. [23]  
// Unsupported monitors will never run and cannot be enabled.

d. Fail if any response from an ECU indicating support for CCM monitor in DM5 reports “0=monitor disabled for rest of this cycle or not supported” in SP 3303 bit 3.  

e. Fail if any response indicates number of warm-ups since code clear (WU-SCC) (SP 3302) is not zero.  
f. Fail if any response indicates time since engine start (SP 3301) is not zero. 
g. Fail if no OBD ECU provides DM26. 

6.1.14.3 Warn Criteria 
a. Warn if any individual required monitor, except Continuous Component Monitoring (CCM) is supported by more than one OBD ECU. 

6.1.14.4 Actions 
a. DS DM26 to each OBD ECU. 

6.1.14.5 Fail Criteria 
a. Fail if any difference compared to data received during global request. 
b. Fail if NACK not received from OBD ECUs that did not respond to global query.

6.2.8 DM26: Diagnostic Readiness 3            6.2.8+ text is proposed for the maintenance contract 
6.2.8.1 Actions 
a. DS DM26 [send Request (PG 59904) for PG 64952 (SPs 3301-3305)] to each OBD ECU. 
    i. Record time since engine start (SP 3301) from each ECU and timestamp of when message was received. 
b. Display monitor readiness composite value in log for OBD ECU replies only.  

// In KOER mode, checking for differences in a KOEO Part 1 response is a conceptual error.
// Invariant conditions from Part 1 still apply and can be checked, except for monitors that may complete KOER.

6.2.8.2 Fail Criteria 
a. Fail if any response for each monitor not supported in DM5 by a given ECU is 
also reported in DM26 as “1=monitor not complete this monitoring cycle” in SP 3303 bits 5-7.
// Unsupported monitors will never need to run and are ‘de facto’ complete.

b. Fail if any response for each monitor not supported in DM5 by a given ECU is 
also reported in DM26 as “0=monitor enabled for this monitoring cycle” in SP 3303 bits 1 and 2 and SP 3304. [
// Unsupported monitors will never run and cannot be enabled.

c. Fail if any response from an ECU indicating support for CCM monitor in DM5 reports “0=monitor disabled for rest of this cycle or not supported” in SP 3303 bit 3. 

d. Fail if any ECU reports number of warm-ups SCC (SP 3302) greater than zero. [33] 
e. Fail if NACK not received from OBD ECUs that did not provide a DM26 response to global query.

6.2.8.3 Warn Criteria
a. Warn, if any individual required monitor, except Continuous Component Monitoring (CCM) is supported by more than one OBD ECU.
b. Info, if any response for any monitor supported in DM5 by a given ECU is reported as “0=monitor complete this cycle or not supported” in SP 3303 bits 1-4 and SP 3305 [except comprehensive components monitor (CCM)].  
// After a reset (here engine start), all completed monitors are reset to not complete.  Some may complete under KOEO conditions.

6.11.2.1 Actions
a. Global DM26 ([send Request (PG 59904) for PG 64952 (SP 3301)]).
i. Record time since engine start.
ii. Separately start tracking time in software to compare to reported values later in part 11.

6.11.2.2 Fail Criteria
a. If more than one ECU responds, fail if times (since engine start) differ by > 2 seconds.
b. Fail if no OBD ECU provides a DM26 message.
 
6.11.11.1 Actions
a. DS DM26 [(send Request (PG 59904) for PG 64952 (SPs 3301-3305)]) to each OBD ECU.
b. Record all monitor readiness this trip data (i.e., which supported monitors are complete this trip or supported and not complete this trip).
c. Display composite status for support and enable bits for responses received from OBD ECUs.

6.12.2 DM26: Diagnostic Readiness 3 
6.12.2.1 Actions 
a. DS DM26 [(send Request (PGNPG 59904) for PGNPG 64952 (SPNSPs 3303-3305)]) to each OBD ECU.
6.12.2.2 Fail Criteria 
a. Warn, if any individual required monitor, except Continuous Component Monitoring (CCM) is supported by more than one OBD ECU.
b. Info, if any response for any monitor supported in DM5 by a given ECU is reported as “0=monitor complete this cycle or not supported” in SP 3303 bits 1-4 and SP 3305 [except comprehensive components monitor (CCM)].  
c. Fail if NACK not received from OBD ECUs that did not provide a DM26 message

**Comment by ericthomasswenson** [comment]
DM26 criteria may be completed before Table A-6-1, 2 are updated for monitor changes.

**Comment by ericthomasswenson** [comment]
DM26 criteria in consolidated text.

**Comment by ericthomasswenson** [comment]
A-6 documentation complete in task 5 artifact
