### ISSUE TITLE
Table A-1 Entry for SP 168 N.7 is incorrect 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#863]
PGN 65271 with Supported SPNs 
10:33:01.6419 18FEF755 [8] FF FF FF FF F8 00 FF FF
Found: Vehicle Electrical Power 1 from DPF Controller (85): 
  SPN   114, SLI Battery 1 Net Current: Not Available
  SPN   115, Alternator Current: Not Available
  SPN   167, Charging System Potential (Voltage): Not Available
  SPN   168, Battery Potential / Power Input 1: 12.400000 V
  SPN   158, Key Switch Battery Potential: Not Available

WARN: 6.1.26.4.a - N.7 Provided SPN 168 is not indicated as supported by DPF Controller (85)
// The entry for SP 168 says none.  Check the rest of this row too.

**Comment by gumbelmj** [comment]
@mmschaefer, there should be no warning message for this SP.
