### ISSUE TITLE
Logic reversed for 6.7.15.2.b, should be NACK received.

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#868]
Logic should be if NACK received, not if NACK _**NOT**_ received for 

10:49:08.2636 Sending DM7 for DM30 to Engine #1 (0) for SPN 1322
10:49:08.2681 18E300F9 [8] F7 2A 05 1F FF FF FF FF (TX)
10:49:08.8640 Timeout - No Response
10:49:08.8685 18E300F9 [8] F7 2A 05 1F FF FF FF FF (TX)
10:49:09.4643 Timeout - No Response
10:49:09.4688 18E300F9 [8] F7 2A 05 1F FF FF FF FF (TX)
10:49:10.0661 Timeout - No Response
FAIL: 6.7.15.2.b - NACK **_not_** received from Engine #1 (0) which did not support an SPN (1322) listed in its DM24 response

6.7.15.2 Fail Criteria 
a. Fail if any difference in the ECU address+SPN+FMI combinations that report test results compared to list created in part 1.  
b. Fail if NACK received from OBD ECUs that did not support an SP listed in its DM24 response.

Fail: noted in part 1 for failure to respond

**Comment by ericthomasswenson** [comment]
The list of supported SPs for test results is iterated. NACK says the bit was wrong.
No response may infer the bit was wrong... but timeout is the better description of the error for no response.

**Comment by gumbelmj** [comment]
If I'm reading the intent here, 6.7.15.2.b is meant to detect the ECU failed to support the request. It could be the module didn't respond (timed-out) or NACK'ed the request (What happens if the ECU ACK's the request?)

The description added to the criteria actually seems to confuse the issue.  

I believe it should read: 
> 6.7.15.2.b Fail if NACK received from any OBD ECU

Perhaps we should add to that:
> 6.7.15.2.c Fail if no response from any OBD ECU

**Comment by ericthomasswenson** [comment]
Also observed at:

FAIL: 6.7.15.2.b - NACK not received from Engine #1 (0) which did not support an SPN (1659) listed in its DM24 response
