### ISSUE TITLE
Omit excess DM31 query 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#870]
When DM31 is not supported and this may be omitted ... and, It should not create failures

Start Test 8.9 - DM31: DTC to lamp association

10:52:36.2079 Global DM31 Request
10:52:36.2143 18EAFFF9 [3] 00 A3 00 (TX)
10:52:36.8076 Timeout - No Response
FAIL: 6.8.9.2.a - No ECU reported same DTC as MIL on as reported in DM12 earlier in this part
FAIL: 6.8.9.2.c - No ECU reported same DTC as MIL off as reported in DM23 earlier in this part

**Comment by ericthomasswenson** [comment]
>6.8.9 DM31: DTC to Lamp Association 
6.8.9.1 Actions 
a. Global DM31 [(send Request (PGNPG 59904) for PGNPG 41728 (SPNSPs 1214, 1215, 4113, 4117)]). 
6.8.9.2 Fail Criteria **_(if supported)_** 
a. Fail if no ECU reports same DTC as MIL on for as was reported in DM12 earlier in this part. See Section A.8 for allowed values of SPNSP 4113 and 4117.  
b. Fail if any ECU reports additional or fewer DTCs than those reported in DM12 and DM23 responses earlier in this part. 
c. Fail if no ECU reports the same DTC as MIL off for the previous active DTC reported in DM23 earlier in this part.

**Comment by ericthomasswenson** [comment]
_III. Assessment of optional diagnostic messages – Several query evaluation criteria are marked with the term “(if supported).”. The criteria listed for these queries represent optional content that is at the discretion of the manufacturer to provide, as shown in SAE J1939-73 Tables 1 and 2. Vehicles and engines shall pass a test when there are no responses provided for queries marked as “(if supported).”._  

_Footnote 12 “If supported” is used for DMs and SPNs that are not required to be implemented but are tested for accurate information only if they are supported/implemented by one or more ECUs. When used, this indicates that it is acceptable for all, one or more than one OBD ECUs to not support this DM (i.e., to NACK for destination specific requests and no response for global requests). But for ECUs that do respond, the fail and warn criteria should be applied._ 

_6.1.23.1 Actions 
a. Global DM31 [(send Request (PGNPG 59904) for PG 41728 (SPNSPs 1214-1215, 4113, 4117)]).  6.1.23.2 Fail Criteria (**_if supported_**)
 a. Fail if any received ECU response does not report MIL off._ 

This is a false positive outcome.

**Comment by gumbelmj** [comment]
I missed the "if supported" in the specification.  I'll get that fixed.

**Comment by gumbelmj** [comment]
Given the specification doesn't indicate the request is optional, I'll leave the request in, but I'll eliminate the false failure.
