### ISSUE TITLE
Doc - Only One OBD ECU needs to provide FF for 6.8.10.2

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#873]
SA does not provide the Freeze Frame ... SA 0 does ... SA 85 is not required to duplicate the SA 0 FF.
... intended performance is ... by all OBD ECUs

10:52:39.7216 Destination Specific DM25 Request to DPF Controller (85)
10:52:39.7291 18EA55F9 [3] B7 FD 00 (TX)
10:52:39.7334 18FDB755 [8] 00 00 00 00 00 FF FF FF
DM25 from DPF Controller (85): 
Freeze Frames: [
No Freeze Frames
]
FAIL: 6.8.10.2.b - DPF Controller (85) provided no freeze frame data

6.8.10.2 Fail Criteria 
a. Fail if DTC(s) reported in the freeze frame does not include either the DTC reported in DM12 or the DTC reported in DM23 earlier in this part 
b. Fail if no freeze frame data (i.e. an empty freeze frame) is provided, _**by all OBD ECUs**_
c. Fail if NACK not received from OBD that did not provide an DM25 message.

**Comment by gumbelmj** [comment]
To be consistent with the rest of the specification, the criteria should read:
>b. Fail if no ECU provides freeze frame data (i.e. an empty freeze frame is provided by all modules).

**Comment by gumbelmj** [comment]
Since I think this will cause customer complaints, I'm going to split this ticket and implement the new criteria.  I'll switch this ticket to a documentation ticket so the as-built spec can be updated.

**Comment by ericthomasswenson** [comment]
add to 24 June as built draft as 
b.   Fail if no OBD ECU provides freeze frame data (i.e. an empty freeze frame is provided by all OBD modules).
