### ISSUE TITLE
Doubled query to SA 85 for SP 7330 Test results 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#876]
Several occasions were observed where the same test results were queried consecutively.  In this example it may be the case that the second query should have been for SP 7993.

10:49:35.8743 Sending DM7 for DM30 to DPF Controller (85) for SPN 7330
10:49:35.8798 18E355F9 [8] FA A2 1C 02 FF FF FF FF (TX)
10:49:35.8873 18A4F955 [24] FA A2 1C 02 20 00 00 00 E8 03 00 00 FA A2 1C 02 20 00 8B 08 EA 0D DC 05
DM30 from 85: [
  SPN 7330 FMI 2 (SLOT 32) Result: Test Passed. Min: 0, Value: 0, Max: 1
  SPN 7330 FMI 2 (SLOT 32) Result: Test Passed. Min: 1.5, Value: 2.187, Max: 3.562
]

10:49:35.9022 Sending DM7 for DM30 to DPF Controller (85) for SPN 7330
10:49:35.9077 18E355F9 [8] FA A2 1C 02 FF FF FF FF (TX)
10:49:35.9082 18A4F955 [24] FA A2 1C 02 20 00 00 00 E8 03 00 00 FA A2 1C 02 20 00 8B 08 EA 0D DC 05
DM30 from 85: [
  SPN 7330 FMI 2 (SLOT 32) Result: Test Passed. Min: 0, Value: 0, Max: 1
  SPN 7330 FMI 2 (SLOT 32) Result: Test Passed. Min: 1.5, Value: 2.187, Max: 3.562
] // baseline result

End Test 7.17 - DM7/DM30: Command non-continuously monitored test/scaled test results

**Comment by gumbelmj** [comment]
This is resolved with #833

**Comment by ericthomasswenson** [comment]
10:55:40.8898 Sending DM7 for DM30 to DPF Controller (85) for SPN 7330
10:55:40.8933 18E355F9 [8] FA A2 1C 02 FF FF FF FF (TX)
10:55:40.8977 18A4F955 [24] FA A2 1C 02 20 00 00 00 E8 03 00 00 FA A2 1C 02 20 00 00 FB FF FF FF FF
DM30 from 85: [
  SPN 7330 FMI 2 (SLOT 32) Result: Test Passed. Min: 0, Value: 0, Max: 1
  SPN 7330 FMI 2 (SLOT 32) Result: Test Not Complete.
]

10:55:40.9087 Sending DM7 for DM30 to DPF Controller (85) for SPN 7393
10:55:40.9134 18E355F9 [8] FA E1 1C 0A FF FF FF FF (TX)
10:55:40.9177 18A4F955 [12] FA E1 1C 0A D0 00 00 FB FF FF FF FF
DM30 from 85: SPN 7393 FMI 10 (SLOT 208) Result: Test Not Complete.

10:55:40.9287 Sending DM7 for DM30 to DPF Controller (85) for SPN 7393
10:55:40.9341 18E355F9 [8] FA E1 1C 01 FF FF FF FF (TX)
10:55:40.9436 18A4F955 [12] FA E1 1C 01 20 00 00 FB FF FF FF FF
DM30 from 85: SPN 7393 FMI 1 (SLOT 32) Result: Test Not Complete.
FAIL: 6.9.10.2.a - DPF Controller (85) reported test result for SPN = 7330, FMI = 2 is not initialized
// Juxtaposition reported for improvement 

End Test 9.10 - DM7/DM30: Command non-continuously monitored test/scaled test results

**Comment by ericthomasswenson** [comment]
Added 2nd half of example. Showing sp 7993.
