### ISSUE TITLE
Failure Message for SA 85 Erasing Data for DS DM11

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#877]
End Test 9.7 - DM33: Emission increasing AECD active time

Start Test 9.8 - DM11: Diagnostic data clear/reset for active DTCs

10:54:56.6602 Destination Specific DM11 Request to DPF Controller (85)
10:54:56.6645 18EA55F9 [3] D3 FE 00 (TX)
10:54:56.6693 18E8FF55 [8] 00 FF FF FF FF D3 FE 00
Acknowledgment from DPF Controller (85): Response: ACK, Group Function: 255, Address Acknowledged: 255, PGN Requested: 65235
// Issue raised to fail all DS 11 ACKs from OBD ECUs.

6.9.8.2.a - Checking for erased diagnostic information

...

10:55:07.2208 Sending DM7 for DM30 to DPF Controller (85) for SPN 6774
10:55:07.2302 18E355F9 [8] F7 76 1A 1F FF FF FF FF (TX)
10:55:07.2378 18A4F955 [12] F7 76 1A 07 D0 00 00 FB FF FF FF FF
DM30 from 85: SPN 6774 FMI 7 (SLOT 208) Result: Test Not Complete.

10:55:07.2547 Sending DM7 for DM30 to DPF Controller (85) for SPN 6780
10:55:07.2601 18E355F9 [8] F7 7C 1A 1F FF FF FF FF (TX)
10:55:07.2657 18A4F955 [12] F7 7C 1A 02 32 01 00 FB FF FF FF FF
DM30 from 85: SPN 6780 FMI 2 (SLOT 306) Result: Test Not Complete.

10:55:07.2777 Sending DM7 for DM30 to DPF Controller (85) for SPN 7330
10:55:07.2842 18E355F9 [8] F7 A2 1C 1F FF FF FF FF (TX)
10:55:07.2856 18A4F955 [24] F7 A2 1C 02 20 00 00 00 E8 03 00 00 F7 A2 1C 02 20 **_00 00 FB FF FF FF FF_**
DM30 from 85: [
  SPN 7330 FMI 2 (SLOT 32) Result: Test Passed. Min: 0, Value: 0, Max: 1
  SPN 7330 FMI 2 (SLOT 32) Result: Test Not Complete.
] // Failure message missing for DS DM11 to SA 85

10:55:07.2986 Destination Specific DM11 Request to Engine #1 (0)
10:55:07.3021 18EA00F9 [3] D3 FE 00 (TX)
10:55:07.3094 18E8FF00 [8] 00 FF FF FF F9 D3 FE 00
Acknowledgment from Engine #1 (0): Response: ACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 65235

6.9.8.4.a - Checking for erased diagnostic information

**Comment by ericthomasswenson** [comment]
10:55:22.2369 Sending DM7 for DM30 to DPF Controller (85) for SPN 7330
10:55:22.2513 18E355F9 [8] F7 A2 1C 1F FF FF FF FF (TX)
10:55:22.2559 18A4F955 [24] F7 A2 1C 02 20 00 00 00 E8 03 00 00 F7 A2 1C 02 20 00 00 FB FF FF FF FF
DM30 from 85: [
  SPN 7330 FMI 2 (SLOT 32) Result: Test Passed. Min: 0, Value: 0, Max: 1
  SPN 7330 FMI 2 (SLOT 32) Result: Test Not Complete.
]
FAIL: 6.9.8.4.b - One or more than one ECU erased diagnostic information and one or more other ECUs did not erase diagnostic information

Where is failure message for 6.9.8.2.b?

One failure message for each DS DM11 ACK
And One failure message for erased data for each ECU is ok ... didn’t get one (erasure failure data) for DS DM11 to SA 85

**Comment by gumbelmj** [comment]
The problem is:
> SPN 7330 FMI 2 (SLOT 32) Result: Test Passed. Min: 0, Value: 0, Max: 1

The definition of erased for test results is 
>DM7/DM30 Test Results shall report all test results with initialized results and limits (all 0x00 or 0xFB00 for results and 0xFFFF for limits)

The ECU appears to NACK most DMs which would be checked to determine if the diagnostic information was erased.  So none of those consider into the determination of erasure.

Thus, this one test result indicates the ECU didn't erase data. 

In 6.9.8.2, ECU 0 is not erased and ECU 85 is not erased because of the test result above.

In 6.9.8.4, ECU 0 _is_ erased with ECU 85 still indicating that it's not erased.  This generates the failure.

**Comment by ericthomasswenson** [comment]
No specific recommendation for as built draft
