### ISSUE TITLE
Scaling in MPa in for SP 157 is believed to be incorrect.

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#883]
Scaling in MPa in for SP 157 is believed to be incorrect.

14:44:45.1788 Sending DM7 for DM30 to Engine #1 (0) for SPN 157
13:33:10.2471 18E300F9 [8] FA 9D 00 10 FF FF FF FF (TX)
14:44:45.2117 18A4F900 [12] FA 9D 00 10 89 01 BF 70 FF FF 12 5B
DM30 from 0: SPN 157 FMI 16 (SLOT 393) Result: Test Passed. Min: -20.001, Value: -0.482, Max: N/A MPa
// Scaled data in conflict with units for SP 157. 
// Negative 20 MPa is not believed for a positive pressure value. (Deep Space is 0 kPa absolute).

**Comment by gumbelmj** [comment]
```
14:44:45.2117 18A4F900 [12] FA 9D 00 10 89 01 BF 70 FF FF 12 5B

FA -> Test Identifier = 250
9D 00 10  -> SPN & FMI = 157:16
89 01 -> SLOT = 393
BF 70 -> Test Value = 28863 (not scaled)
FF FF -> Test Maximum = N/A
12 5B -> Test Minimum  = 23314 (not scaled)
```

The ECU indicated that SLOT 393 was to be used to interpret this test result data.

SLOT 393 is defined [here](https://github.com/battjt/j1939-84/blob/trunk/src/org/etools/j1939_84/resources/j1939da-slots.csv#L271).

The scaling factor is 0.0035176 MPa/bit with an offset of -102.0104 MPa. (I've confirmed these values with J1939-DA)

Test value: `28863 * 0.0035176 + (-102.0104) = -0.4819112 MPa`

Test minimum: `23314 * 0.0035176 + (-102.0104) = -20.0010736 MPa`
