### ISSUE TITLE
Refine Criteria for NTE SPs vs. Practical Discussion Below

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#889]
Review Criteria with CARB — Current Criteria is underperforming 

Start Test 2.16 - DM34: NTE status

08:45:07.2173 Global DM34 Request
08:45:07.2428 18EAFFF9 [3] 00 A0 00 (TX)
08:45:07.2456 18A0FF00 [8] 13 13 FF FF FF FF FF FF
DM34 NTE Status from Engine #1 (0):  {
                          NOx NTE Control Area Status = Outside Area (0)
  Manufacturer-specific NOx NTE Carve-out Area Status = Inside Area (1)
                       NOx NTE Deficiency Area Status = Outside Area (0)
                           PM NTE Control Area Status = Outside Area (0)
   Manufacturer-specific PM NTE Carve-out Area Status = Inside Area (1)
                        PM NTE Deficiency Area Status = Outside Area (0)
}

FAIL: 6.2.16.2.c - Engine #1 (0) reported NOx carve-out area != 0b00 or 0b11
FAIL: 6.2.16.2.c - Engine #1 (0) reported PM carve-out area != 0b00 or 0b11
// This could be a problem in the criteria off is outside the area
// And I can argue idle is outside the area too, despite the NTE idle test point.
// but since all carve outs have expired … it may be the case everything should be inside the area.

End Test 2.16 - DM34: NTE status

**Comment by ericthomasswenson** [comment]
6.2.16 DM34: NTE Status 
6.2.16.1 Actions 
a. Global DM34 [(send Request (PGNPG 59904) for PGNPG 40960 (SPNSPs 4127-4132)]). 
6.2.16.2 Fail Criteria 
a. Fail if no ECU responds, unless the user selected SI technology.  
b. Fail if any ECU response is not = 00b or 01b (Outside Control Area) for NOx and PM control areas (byte 1 bits 7-8, byte 2 bits 7-8). 
c. Fail if any ECU response is not = 00b (Outside Area), **_01b (Inside Area)_** or 0b11b (not available) for NOx/PM carve-out/deficiency areas (byte 1 bits 5-6 and byte 2 bits 5-6). 
d. Fail if any ECU response is not = 0b 11b for byte 1 bits 1-2 and for byte 2 bits 1-2. 
e. Fail if any reserved bytes 3-8 are not = 0xFFh.  
6.2.16.3 Actions 
a. DS DM34 to each OBD ECU which responded to the DM34 global request in step 1. 
6.2.16.4 Fail Criteria 
a. Fail if any difference compared to data received from global request. 
b. Fail if NACK received from OBD ECUs that responded to the global query in part 1.

**Comment by ericthomasswenson** [comment]
6.2.16 DM34: NTE Status
6.2.16.1 Actions
a. Global DM34 [send Request (PG 59904) for PG 40960 (SPs 4127-4132)].
6.2.16.2 Fail Criteria
a. Fail if no ECU responds, unless the user selected SI technology.
b. Fail if any ECU response is not = 00b **_(Outside Control Area)_** or 01b (**_Inside_** Control Area) for NOx and PM control areas (byte 1 bits 7-8, byte 2 bits 7-8).
**_c. Fail if any ECU response is 10b (Error) for NOx/PM carve-out/deficiency areas (byte 1 bits_** **_5-6 and byte 2 bits 5-6)._**
d. Fail if any ECU response is not = 00b or 11b for byte 1 bits 1-2 and for byte 2 bits 1-2.
e. Fail if any reserved bytes 3-8 are not = 0xFFh.
6.2.16.3 Actions
a. DS DM34 to each OBD ECU which responded to the DM34 global request in step 1.
6.2.16.4 Fail Criteria
a. Fail if any difference compared to data received from global request.
b. Fail if NACK received from OBD ECUs that responded to the global query in part 1.

**Comment by ericthomasswenson** [comment]
Document changes complete.,

**Comment by battjt** [comment]
6.2.16.2.b doesn't match VERSION 8: J1939-84-61113-6217-A4-A7-Task5.  Otherwise, complete.

**Comment by ericthomasswenson** [comment]
Improved text provided in Task 5 artifact
