### ISSUE TITLE
FB00h is status and not scalable to Engineering Value 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#891]
Please display FB00h when observed instead of Scaled Value

FB00h is not ready, and not 3012.800000 ppm
FB00h is an allowed value in Table A-1

Scaled value is misleading... 
and suggests technicians should wear gas masks when working on the truck

PGN 61454 with Supported SPNs 3216, 3217
08:45:07.8759 18F00E00 [8] 00 FB FE FA FF FF FF FF
Found: AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 3012.800000 ppm
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: 21.026556 %
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: 11
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000000 

PGN 61455 with Supported SPNs 3226
08:45:07.8762 18F00F00 [8] 00 FB FF FF FF FF FF FF
Found: AFT 1 Outlet Gas 1 from Engine #1 (0): 
  SPN  3226, AFT 1 Outlet NOx 1: 3012.800000 ppm
  SPN  3227, AFT 1 Outlet Percent Oxygen 1: Not Available
  SPN  3228, AFT 1 Outlet Gas Sensor 1 Power In Range: 11
  SPN  3229, AFT 1 Outlet Gas Sensor 1 at Temperature: 11
  SPN  3230, AFT 1 Outlet NOx 1 Reading Stable: 11
  SPN  3231, AFT 1 Outlet Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3232, AFT 1 Outlet Gas Sensor 1 Heater Preliminary FMI: 31.000000 
  SPN  3233, AFT 1 Outlet Gas Sensor 1 Heater Control: 11
  SPN  3234, AFT 1 Outlet NOx Sensor 1 Preliminary FMI: 31.000000 
  SPN  5713, AFT 1 Outlet NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3235, AFT 1 Outlet Oxygen Sensor 1 Preliminary FMI: 31.000000

**Comment by battjt** [comment]
![image](https://user-images.githubusercontent.com/1972001/112469705-2b5ef980-8d40-11eb-98b3-2873efd5e1da.png)
