### ISSUE TITLE
Doc - Ignore unsupported IUMPR monitors sent as FFFF / FFFFh

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#902]
Unsupported monitors will never be incremented, but must be reported as FFFF / FFFFh.

Skip DM20 Denominators/ Numerator numeric checks for monitor labels with unsupported counts.

PACCAR engines do not support the groups that report 65535 in numerator and denominator. Below screenshot from CCR 1971.1,

**Comment by ericthomasswenson** [comment]
PACCAR side-by-side issue 19.	See #914 for 6.11.8.3.a NMHC warning message bug.

WARN: 6.11.8.3.a - Engine #1 (0) response indicates denominator for monitor SPN 5308 AFT 1 NOx Adsorber Catalyst System Monitor has not incremented by one

Explanation – Tool Issue 

SPN 5308 AFT 1 NOx Adsorber Catalyst System Monitor                    65,535 / 65,535
PACCAR Engines do not support NOx adsorber and hence denominator will never increment by 1.

PACCAR side-by-side issue 20

WARN: 6.11.8.3.b.i - Engine #1 (0) response shows denominator for monitor SPN 3306 Variable Valve Timing and/or Control is greater than the general denominator
WARN: 6.11.8.3.b.i - Engine #1 (0) response shows denominator for monitor SPN 3054 Secondary Air System Monitor is greater than the general denominator
WARN: 6.11.8.3.b.i - Engine #1 (0) response shows denominator for monitor SPN 5308 AFT 1 NOx Adsorber Catalyst System Monitor is greater than the general denominator
WARN: 6.11.8.3.b.i - Engine #1 (0) response shows denominator for monitor SPN 3050 Catalyst Bank 1 System Monitor is greater than the general denominator
WARN: 6.11.8.3.b.i - Engine #1 (0) response shows denominator for monitor SPN 3053 Engine Evaporative System Monitor is greater than the general denominator
WARN: 6.11.8.3.b.i - Engine #1 (0) response shows denominator for monitor SPN 3052 Engine Misfire System Monitor is greater than the general denominator
WARN: 6.11.8.3.b.i - Engine #1 (0) response shows denominator for monitor SPN 3059 Engine Positive Crankcase Ventilation System Monitor is greater than the general denominator
WARN: 6.11.8.3.b.i - Engine #1 (0) response shows denominator for monitor SPN 3060 Engine Cooling System Monitor is greater than the general denominator
WARN: 6.11.8.3.b.i - Engine #1 (0) response shows denominator for monitor SPN 3061 Engine Cold Start Emission Reduction Strategy System Monitor is greater than the general denominator
WARN: 6.11.8.3.b.i - Engine #1 (0) response shows denominator for monitor SPN 3062 Air Conditioning System Component Monitor is greater than the general denominator
WARN: 6.11.8.3.b.i - Engine #1 (0) response shows denominator for monitor SPN 3063 Direct Ozone Reduction Monitor is greater than the general denominator
WARN: 6.11.8.3.b.iii - Engine #1 (0) response shows numerator for monitor SPN 3306 Variable Valve Timing and/or Control is greater than the ignition cycle counter
WARN: 6.11.8.3.b.iii - Engine #1 (0) response shows numerator for monitor SPN 3054 Secondary Air System Monitor is greater than the ignition cycle counter
WARN: 6.11.8.3.b.iii - Engine #1 (0) response shows numerator for monitor SPN 5308 AFT 1 NOx Adsorber Catalyst System Monitor is greater than the ignition cycle counter
WARN: 6.11.8.3.b.iii - Engine #1 (0) response shows numerator for monitor SPN 3050 Catalyst Bank 1 System Monitor is greater than the ignition cycle counter
WARN: 6.11.8.3.b.iii - Engine #1 (0) response shows numerator for monitor SPN 3053 Engine Evaporative System Monitor is greater than the ignition cycle counter
WARN: 6.11.8.3.b.iii - Engine #1 (0) response shows numerator for monitor SPN 3052 Engine Misfire System Monitor is greater than the ignition cycle counter
WARN: 6.11.8.3.b.iii - Engine #1 (0) response shows numerator for monitor SPN 3059 Engine Positive Crankcase Ventilation System Monitor is greater than the ignition cycle counter
WARN: 6.11.8.3.b.iii - Engine #1 (0) response shows numerator for monitor SPN 3060 Engine Cooling System Monitor is greater than the ignition cycle counter
WARN: 6.11.8.3.b.iii - Engine #1 (0) response shows numerator for monitor SPN 3061 Engine Cold Start Emission Reduction Strategy System Monitor is greater than the ignition cycle counter
WARN: 6.11.8.3.b.iii - Engine #1 (0) response shows numerator for monitor SPN 3062 Air Conditioning System Component Monitor is greater than the ignition cycle counter
WARN: 6.11.8.3.b.iii - Engine #1 (0) response shows numerator for monitor SPN 3063 Direct Ozone Reduction Monitor is greater than the ignition cycle counter

**Comment by ericthomasswenson** [comment]
6.11.8.3 Warn Criteria, **_for monitor labels with numerators and denominators not broadcast as FFFFh / FFFFh (unsupported)_**
a. Warn if any response indicates **_a supported_** denominator for SCR **_(SP 4792, 4364, or 5308), Catalyst  (SP 3050),_** EGR _**(SP 3058)**_ NOx sensor **_(SP 5318)_**, boost **_(SP 5321)_** and fuel system **_(SP 3055)_** have not incremented by one. 
b. Warn if any ECU response shows: 
i. any monitor denominator greater than the general denominator;  
ii. general denominator greater than the ignition cycle counter (SPNSP 3048); or 
iii. if any numerator greater than the ignition cycle counter. 
c. Compare all values to values recorded in part 1. 
i. Warn if any value (numerator, denominator, or ignition cycle counter) is less than their corresponding value in part 1. 
d. If more than one ECU reports DM20 data, warn if general denominators or ignition cycle counts do not match from all ECUs.

**Comment by ericthomasswenson** [comment]
WARN: 6.11.8.3.a - Engine #1 (0) response indicates denominator for monitor SPN 5308 AFT 1 NOx Adsorber Catalyst System Monitor has not incremented by one

is created by
_a. Warn if any response indicates denominator for SCR, EGR, NOx sensor, boost, and fuel system have not incremented by one._

The warning is not expected as another SP was provided for the NOx conversion monitor requirement among the three allowed alternatives in Table A-4-1.

_NOx Catalyst Bank 1 **4792**  SP 4792, Aftertreatment 1 SCR Catalyst System Monitor OR
NOx Catalyst Bank 1 **_4364_** SP 4364, Aftertreatment 1 SCR Conversion Efficiency (Warning) OR
NOx Adsorber **_5308_**, SP 5308, Aftertreatment 1 NOx Adsorbing Catalyst System Monitor_ 

The other monitors checked are not listed with alternatives in Table A-4-1.

_Exhaust Gas Sensor **5318** Aftertreatment Exhaust Gas Sensor System Monitor 
EGR System **3058** EGR System Monitor 
Boost Pressure Control System **5321** Engine Intake Manifold Pressure System Monitor 
Fuel system **3055** Engine Fuel System Monitor_ 


This warning Is never expected for the DPF monitor, which has an 800 minute requirement and the NMHC Catalyst monitor which were both excluded from the enumeration in 6.11.k8.3.a. 
See #914 for incorrect NMHC Catalyst warning to 6.11.k8.3.a. 

PM Filter **3064** Aftertreatment Diesel Particulate Filter System Monitor 
NMHC Converting Catalyst 5322 Aftertreatment NMHC Converting Catalyst System Monitor

**Comment by ericthomasswenson** [comment]
Providing FFFFh is a Diagnostic Executive Reuse Strategy that provides coverage for SI alternative fuel calibrations, and alternant diesel emissions control selections in a fixed layout for DM20.  To achieve this, the unused labels are sent as FFFFh / FFFFh.

**Comment by ericthomasswenson** [comment]
Minimum monitor support to Table A-4 is performed in Part 1. 
We can disclose the convention in the regulation here.

6.1.8 DM20: Monitor Performance Ratio 
6.1.8.1 Actions 
a. Global DM20 (send Request (PG 59904) for PG 49664 (SPs 3048, 3049, 3066-3068). 
i. Create list by ECU address of all data for use later in the test. 
6.1.8.2 Fail Criteria 
a. Fail if minimum expected SPs are not supported (in the aggregate response for the vehicle) per Section A.4, Criteria for Monitor Performance Ratio Evaluation. **_When  a numerator and denominator are provided as FFFFh and FFFFh, the monitor identified in the label SPN shall be considered to be unsupported_**

**Comment by gumbelmj** [comment]
In addition to adding a notation of "not available", can we identify the SPNs of interest?

"SCR, EGR, NOx sensor, boost, and fuel system" is vague.  I thought "AFT NMHC Converting Catalyst" was part of the "SCR" criteria.

**Comment by gumbelmj** [comment]
From @ericthomasswenson  via email:

I think this should do ... as shown in #902

6.11.8.3 Warn Criteria, for monitor labels with numerators and denominators not broadcast as FFFFh / FFFFh (unsupported)
a. Warn if any response indicates a supported denominator for SCR (SP 4792, 4364, or 5308), EGR (SP 4364) NOx sensor (SP 5318), boost (SP 5321) and fuel system (SP 3055) have not incremented by one.

**Comment by gumbelmj** [comment]
Shouldn't the EGR SP be 3058 "EGR System Monitor"?

**Comment by gumbelmj** [comment]
Are the same SPs used for Spark Ignition engines as well?

**Comment by gumbelmj** [comment]
in Email from @ericthomasswenson:

They are except for Catalyst (SP 3050), which is the SI 3-way catalyst, and O2 sensor (3058).  Which results in:

6.11.8.3 Warn Criteria, for monitor labels with numerators and denominators not broadcast as FFFFh / FFFFh (unsupported)
a. Warn if any response indicates a supported denominator for SCR (SP 4792, 4364, or 5308), Catalyst (SP 3050), EGR (SP 3058) NOx sensor (SP 5318), O2 sensor (3056), boost (SP 5321) and fuel system (SP 3055) have not incremented by one.

Good catch on 3058.

**Comment by ericthomasswenson** [comment]
Updated 6.11.8.3 as SCR (SP 4792, 4364, or 5308), Catalyst (SP 3050), EGR (SP 3058) NOx sensor (SP 5318), O2 sensor (3056), boost (SP 5321) and fuel system (SP 3055) have not incremented by one.

Updated 6.1.8.2 to add When a numerator and denominator are provided as FFFFh and FFFFh, the monitor identified in the label SPN shall be considered to be unsupported.
