### ISSUE TITLE
Excess Failures Observed for Non-OBD ECUs in 6.8.6.2.a

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#912]
Excess Failures were observed for Non-OBD ECUs observed for step 8.6.2.a.
Criteria cites only OBD ECUs, making the non-OBD failure messages excess.

6.8.6 DM5: Diagnostic Readiness 1 
6.8.6.1 Actions 
a. Global DM5 [(send Request (PG 59904) for PG 65230 (SPs 1218-1223)]). 
6.8.6.2 Fail Criteria 
a. Fail if any **OBD ECU** reports different number of DTCs than corresponding DM1 or DM2 response earlier this part. 
6.8.6.3 Actions2 
a. DS DM5 to each OBD ECU. 
6.8.6.4 Fail Criteria2 
a. Fail if any difference in data compared to global response.

**Comment by ericthomasswenson** [comment]
Start Test 8.6 - DM5: Diagnostic readiness 1
 
14:04:43.8567 Global DM5 Request
14:04:43.8735 18EAFFF9 [3] CE FE 00 (TX)
14:04:43.8760 18FECE55 [8] FF FF 14 00 00 00 00 00
DM5 from DPF Controller (85): OBD Compliance: HD OBD (20), Active Codes: not available, Previously Active Codes: not available
14:04:43.8802 18FECE00 [8] 01 01 14 37 E0 1E E0 1E
DM5 from Engine #1 (0): OBD Compliance: HD OBD (20), Active Codes: 1, Previously Active Codes: 1
14:04:43.8825 18FECE05 [8] 00 00 00 00 00 00 00 00
DM5 from Shift Console - Primary (5): OBD Compliance: Reserved for SAE/Unknown (0), Active Codes: 0, Previously Active Codes: 0
14:04:43.8828 18FECE03 [8] 00 00 05 00 00 00 00 00
DM5 from Transmission #1 (3): OBD Compliance: Not intended to meet OBD II requirements (5), Active Codes: 0, Previously Active Codes: 0
14:04:43.9183 18FECEA7 [8] 00 00 FF 00 00 00 00 00
DM5 from Instrument Cluster #2 (167): OBD Compliance: Not available (255), Active Codes: 0, Previously Active Codes: 0
**FAIL: 6.8.6.2.a - Transmission #1 (3) reported different number of DTCs than correspond DM1 response earlier in this part
FAIL: 6.8.6.2.a - Shift Console - Primary (5) reported different number of DTCs than correspond DM1 response earlier in this part
FAIL: 6.8.6.2.a - Instrument Cluster #2 (167) reported different number of DTCs than correspond DM1 response earlier in this part
FAIL: 6.8.6.2.a - Transmission #1 (3) reported different number of DTCs than correspond DM2 response earlier in this part
FAIL: 6.8.6.2.a - Shift Console - Primary (5) reported different number of DTCs than correspond DM2 response earlier in this part
FAIL: 6.8.6.2.a - Instrument Cluster #2 (167) reported different number of DTCs than correspond DM2 response earlier in this part**

**Comment by ericthomasswenson** [comment]
Start Test 8.5 - DM2: Previously active DTCs
 
14:04:43.2518 Global DM2 Request
14:04:43.2692 18EAFFF9 [3] CB FE 00 (TX)
14:04:43.2702 18FECB00 [8] 40 FF 83 10 07 01 FF FF
DM2 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: off
DTC 4227:7 - Engine Crankcase Breather Oil Separator, Mechanical System Not Responding Or Out Of Adjustment - 1 times
14:04:43.3800 18FECB21 [10] 00 FF 19 F3 EE 09 15 F3 EE 12
DM2 from Body Controller (33): MIL: off, RSL: off, AWL: off, PL: off
DTC 520985:14 - Manufacturer Assignable SPN, Special Instructions - 9 times
DTC 520981:14 - Manufacturer Assignable SPN, Special Instructions - 18 times
14:04:43.2732 18FECB03 [8] 00 FF 00 00 00 00 FF FF
DM2 from Transmission #1 (3): MIL: off, RSL: off, AWL: off, PL: off, No DTCs
14:04:43.2749 18FECB0B [8] 00 FF 00 00 00 00 FF FF
DM2 from Brakes - System Controller (11): MIL: off, RSL: off, AWL: off, PL: off, No DTCs
14:04:43.2773 18FECB05 [8] FF FF 00 00 00 7F FF FF
DM2 from Shift Console - Primary (5): MIL: not supported, RSL: not supported, AWL: not supported, PL: not supported, No DTCs
14:04:43.2813 18FECBA7 [8] 00 FF 00 00 00 00 FF FF
DM2 from Instrument Cluster #2 (167): MIL: off, RSL: off, AWL: off, PL: off, No DTCs
14:04:43.2878 18FECB17 [8] 00 FF 00 00 00 00 FF FF
DM2 from Instrument Cluster #1 (23): MIL: off, RSL: off, AWL: off, PL: off, No DTCs
 
End Test 8.5 - DM2: Previously active DTCs

**Comment by ericthomasswenson** [comment]
Summary of J1939-84 Tool Execution
J1939-84 Tool version 3.0.3 - 2021/03/25 10:58
Generated: 2021/03/26 14:34:55.7241
Log File Name: C:\CdriveSave\new j1939-84\303 MY16 745 ECM ACM Link2.j1939-84

Vehicle Information:
VIN: 3HSDJSNR8HN447736
Vehicle MY: 2017
Engine MY: 2016
Cert. Engine Family: MY2016 745 12.4L ECM/ACM
Number of OBD ECUs Found: 2
    Make: INT  , Model: 7571031515, Serial: 124KM2Y4411888
    Make: , Model: 6X2u07D1500000000, Serial: 00000000
Number of CAL IDs Found: 6
    DM19 from Engine #1 (0): CAL ID of M133XXM_B282NE06 and CVN of 0xCB465A72
    DM19 from DPF Controller (85): [
      CAL ID of OYANDXC and CVN of 0xC5E134EB
      CAL ID of NOx-SAE14a ATI1 and CVN of 0x138973A8
      CAL ID of NOx-SAE14a ATO1 and CVN of 0xC9F94B8C
      CAL ID of 0201010002 and CVN of 0x0033FFAC
      CAL ID of PMS12341A101 and CVN of 0xA90FBFD2
    ]

**Comment by gumbelmj** [comment]
This will be resolved with Pull Request #911
