### ISSUE TITLE
Need DM58 support and Freeze Frame Offset added to DM24 Tabular Display.

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#913]
Need DM58 support and Freeze Frame Offset added to DM24 Tabular Display.

Congrats on saving dozens of pages with the tabular display.  Bob and I liked it.

We will need to add DM58 support and freeze frame offset to the existing tabular display as part of the maintenance enhancements as shown by the attachment in #666.

A second display for all SPs with non-zero FFrame lengths, in the same order as received in DM24, showing the offsets is desired.  The 1st SP with non-zero FF length is the fifth byte of DM25.

  DM24 from Engine #1 (0): [
  D F T F
  a r e F
  t F s l
  a r t n  SPN — SP Name
 ————————————-
  D F   2  SPN 27 - Engine EGR 1 Valve Position
  D F   1  SPN 51 - Engine Throttle Valve 1 Position 1
  D F   2  SPN 84 - Wheel-Based Vehicle Speed
  D F   1  SPN 91 - Accelerator Pedal Position 1
  D F   1  SPN 92 - Engine Percent Load At Current Speed
  D F   1  SPN 94 - Engine Fuel Delivery Pressure
        1  SPN 96 - Fuel Level 1
    F   1  SPN 100 - Engine Oil Pressure 1
  D F T 1  SPN 102 - Engine Intake Manifold #1 Pressure
  D F   1  SPN 105 - Engine Intake Manifold 1 Temperature
  D F   1  SPN 108 - Barometric Pressure
  D F T 1  SPN 110 - Engine Coolant Temperature
  D F   2  SPN 157 - Engine Fuel 1 Injector Metering Rail 1 Pressure
  D F   2  SPN 158 - Key Switch Battery Potential
  D F   2  SPN 171 - Ambient Air Temperature

[TabularDM24displayEnhancementExample.docx](https://github.com/Equipment-and-Tool-Institute/j1939-84/files/7938479/TabularDM24displayEnhancementExample.docx)

(Fixed link 1/25/2022)

**Comment by mmschaefer** [comment]
![Example Output Table](https://user-images.githubusercontent.com/7682306/151380188-a2754c78-a79f-4c6b-acea-c7171e52aede.png)

**Comment by ericthomasswenson** [comment]
Observed in 3.1.0 / 3.1.1.
