### ISSUE TITLE
Accept Completed DM5 Monitors in Part 2

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#927]
Accept Completed DM5 Monitors in Part 2, as the engine is running 
Monitor completion for DM5 misfire monitor bit in Part 2 is a good thing.
1000 revs is less than 2 mins, creating a race condition that the engine won, and then failed.

May the outcome below say 

**_INFO_**: 6.2.2.2.a (A6.2.c) - Composite vehicle readiness for Misfire observed as complete, was not complete in part 1 test 13 did not meet the criteria of Table A4

Start Test 2.2 - DM5: Diagnostic readiness 1

13:51:37.2434 Global DM5 Request
13:51:37.2510 18EAFFF9 [3] CE FE 00 (TX)
13:51:37.2516 18FECE00 [8] 00 00 14 27 E0 1E E0 1E
DM5 from Engine #1 (0): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0
13:51:37.2556 18FECE03 [8] 00 00 05 00 00 00 00 00
DM5 from Transmission #1 (3): OBD Compliance: Not intended to meet OBD II requirements (5), Active Codes: 0, Previously Active Codes: 0
13:51:37.2635 18FECE17 [8] 00 00 05 00 00 00 00 00
DM5 from Instrument Cluster #1 (23): OBD Compliance: Not intended to meet OBD II requirements (5), Active Codes: 0, Previously Active Codes: 0
13:51:37.2740 18FECE19 [8] 00 00 05 00 00 00 00 00
DM5 from Passenger-Operator Climate Control #1 (25): OBD Compliance: Not intended to meet OBD II requirements (5), Active Codes: 0, Previously Active Codes: 0

Vehicle Composite of DM5:
    A/C system refrigerant     not supported,     complete
    Boost pressure control sys     supported, not complete
    Catalyst                   not supported,     complete
    Cold start aid system      not supported,     complete
    Comprehensive component        supported,     complete
    Diesel Particulate Filter      supported, not complete
    EGR/VVT system                 supported, not complete
    Evaporative system         not supported,     complete
    Exhaust Gas Sensor             supported, not complete
    Exhaust Gas Sensor heater      supported, not complete
    Fuel System                    supported, not complete
    Heated catalyst            not supported,     complete
    Misfire                        supported,     complete
    NMHC converting catalyst       supported, not complete
    NOx catalyst/adsorber          supported, not complete
    Secondary air system       not supported,     complete

**_FAIL: 6.2.2.2.a (A6.2.c) - Composite vehicle readiness for Misfire did not meet the criteria of Table A4_**
WARN: 6.2.2.2.a (A6.3.a) - Non-OBD ECU Transmission #1 (3) responded
WARN: 6.2.2.2.a (A6.3.a) - Non-OBD ECU Instrument Cluster #1 (23) responded
WARN: 6.2.2.2.a (A6.3.a) - Non-OBD ECU Passenger-Operator Climate Control #1 (25) responded

13:51:37.8647 Destination Specific DM5 Request to Engine #1 (0)
13:51:37.8821 18EA00F9 [3] CE FE 00 (TX)
13:51:37.8920 18FECE00 [8] 00 00 14 27 E0 1E E0 1E
DM5 from Engine #1 (0): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0

End Test 2.2 - DM5: Diagnostic readiness 1

**Comment by ericthomasswenson** [comment]
_6.2.2 DM5: Diagnostic Readiness 1 
6.2.2.1 Actions 
a. Global DM5 [send Request (PG 59904) for PG 65230 (SPs 1218-1223)]. 
b. Display monitor readiness composite value in log for OBD ECU replies only.  
6.2.2.2 Fail/Warn Criteria 
a. Fail/warn per the Section A.6 Criteria for Readiness 1 Evaluation,_ **_except that monitor completion bits which transition from not complete to complete shall be prefixed with INFO: instead of FAIL: or WARN:_** [30]
_b. Fail if no OBD ECU reports active/previously active fault DTC count not = 0/0. 
c. Warn if any individual required monitor, except Continuous Component Monitoring (CCM) is supported by more than one OBD ECU.  
6.2.2.3 Actions2 
a. DS DM5 to each OBD ECU. 
6.2.2.4 Fail Criteria2 
a. Fail if any difference compared to data received during global request_.
### [30] Engine operation (even for 1 minute) before this data is collected can result in completed monitors, especially those that are intended to be continuous. Thus, monitor transitions from incomplete to complete must be allowed with the engine running. Section A.6 discusses the resulting engine running evaluation further.

**Comment by ericthomasswenson** [comment]
From A.6.
Specific implementations may require the immediate setting of the misfire monitor status bit to zero (complete). Refer to 13 CCR 1971.1 for such conditions. Observation of a zero (complete) for a misfire monitor status bit after fault codes have been cleared will be marked with a warning message.  
...
_Note that cold start aid monitoring results, where equipped, will depend on cold soak or hot soak condition and ambient air temperature when an engine is started. Items listed as (after code clear) change from not complete (1) to complete (0) as the engine runs. Required monitors, except Continuous Component Monitoring (CCM), are expected to be supported by only one OBD ECU. While monitor support bit content in DM26 shall match the support bit content in DM5, the inhibited status data bits in DM26 are not guaranteed to match the status bits in DM5._  

**_Engine operation in part 2 can result in a completed monitor. In particular, Misfire has been observed to be complete after 1000 revs of operation. Transitions from not complete to complete shall be accepted, and not flagged as a failure in test 2.2._**

**Comment by gumbelmj** [comment]
Though I understand the intent, I don't think adding a few paragraphs to the document clearly defines that intent.  Table A-4 needs updated to indicate when FAIL, WARN and INFO should be reported.

**Comment by ericthomasswenson** [comment]
Revised Table A-6-1 Note Text Proposal 
**_Note monitor status bits marked with (after code clear) change from not complete (1) to complete (0) as the engine runs.  Engine operation in part 2 can result in a completed monitor. In particular, Misfire has been observed to be complete after 1000 revs of operation. Transitions from not complete to complete shall be accepted, and not flagged as a failure in test 2.2, and subsequent tests. Transitioned status bits, observed in test 2.2 shall be identified with an informative message._**

Status bit transitions for cold start aid monitoring results, where equipped, will depend on cold soak or hot soak condition and ambient air temperature when an engine is started. 

Required monitors, except Continuous Component Monitoring (CCM), are expected to be supported by only one OBD ECU. While monitor support bit content in DM26 shall match the support bit content in DM5, the inhibited status data bits in DM26 are not guaranteed to match the status bits in DM5.

**Comment by gumbelmj** [comment]
Footnote 30 completely invalidates the checking of the status bits in Table A4.  If the table indicates that the value must be 1 but footnote 30 then indicates the value is allowed to be 0, then either value is acceptable.  The only bits that need checked are the supported bits.

Or am I missing something?

**Comment by gumbelmj** [comment]
Ah!  I think I get it.  

For misfire:
must=1 after code clear, warn if 0

So if it's 1, that's acceptable, if it's 0, then just INFO, correct?

**Comment by gumbelmj** [comment]
In email from @ericthomasswenson:

Yes, You’re getting much closer. Table A-4 doesn’t say after code clear like Table A-6.

And I see your confusion here too.

must = 1 after code clear, warn if 0 

As the text stood this warning was intended for part 1 KOEO.
Info is needed for KOER, I could add a line like this

Part 1: must = 1 after code clear, warn if 0 
Part 2: must = 1 after code clear, info if 0

Misfire is the category that broke the rule for expecting the status bits to remain the same as in part 1, which was already noted in the text ... just not as clearly noted in the test steps.  We’ve also seen exhaust sensor heater fail, and it is possible for cold start to complete after a cold soak too.

Providing relief from false FAIL: messages is the intent here.  Monitors with event based tests, like a DPF regen will never show complete in test 2.2. Warning or failure is more is appropriate for them, than info.  We could bifurcate the rule.

Misfire, Exhaust Sensor Heater, cold start (if supported)
Part 1: must = 1 after code clear, warn if 0 
Part 2: must = 1 after code clear, info if 0

Fuel System, EGR/VVT, Boost, 
Part 1 must = 1 (after code clear), Fail if 0.
Part 2 must = 1 (after code clear), Warn if 0

NMHC Catalyst, DPF, NOX Converting Catalyst, Exhaust Sensor
must = 1 (after code clear), Fail if 0.    
Both Part 1 and Part 2 are expected to show not complete 

6.2.2.2
a. Fail/warn per the Section A.6 Criteria for Readiness 1 Evaluation.  Monitor completion bits which transition from not complete to complete shall use alternate criteria for part 2, where designated in Table A-6. [30]

Revised Table A-6-1 Note Text Proposal
Note monitor status bits marked with (after code clear) change from not complete (1) to complete (0) as the engine runs. Engine operation in part 2 can result in a completed monitor. In particular, Misfire has been observed to be complete after 1000 revs of operation. Transitions from not complete to complete are accommodated in Table A-6-1 by specific outcomes for part 2, and are not flagged as a failure in test 2.2. Event driven monitors like NMHC Catalyst or DPF, are clearly not expected to be completed and do not have an alternate criteria.

Status bit transitions for cold start aid monitoring results, where equipped, will depend on cold soak or hot soak condition and ambient air temperature when an engine is started.

Required monitors, except Continuous Component Monitoring (CCM), are expected to be supported by only one OBD ECU. While monitor support bit content in DM26 shall match the support bit content in DM5, the inhibited status data bits in DM26 are not guaranteed to match the status bits in DM5.

**Comment by gumbelmj** [comment]
"after code clear" is redundant and doesn't make any sense.  A global DM 11 request is sent in Test 1.10. The monitors are supported in Test 1.13 and Test 2.2, both of which are obviously after the codes have been cleared.

**Comment by ericthomasswenson** [comment]
Yes Matt, (after code clear) is redundant in a way.
Yet, it provides a context cue that results are transient, which is explained in the notes.

Are you in favor of the Part 1/Part 2 approach for Table A-6-1.?

**Comment by gumbelmj** [comment]
Yes, it would be more clear if the table outlined the values expected in each part.
