### ISSUE TITLE
Are two failures for one action appropriate 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#929]
Double failure message outcome can this be reduced to one?

Start Test 10.4 - DM28: Permanent DTCs

14:24:49.8393 Destination Specific DM28 Request to Engine #1 (0)
14:24:50.4640 18EA00F9 [3] 80 FD 00 (TX)
14:24:50.4506 Timeout - No Response
FAIL: 6.10.4.2.a - No ECU reported a permanent DTC
FAIL: 6.10.4.2.c - OBD ECU Engine #1 (0) did not provide a NACK for the DS query

**Comment by gumbelmj** [comment]
It is completely possible to avoid redundant failures.  However, by a strict reading of the document, both failures are required. 

If the desired behavior is not report redundant failures, I think it's best handled as an enhancement in V3.1. As such, the documentation needs updated to indicate that failure 6.10.4.2.a (not DTCs) should be reported if DM28(s) is(are) received but does no module reports a DTC.  That would prevent that failure from being reported when no packets are received and allow the singular failure 6.10.4.2.c (no NACK) to indicate the undesired behavior.

This might also need to apply to all the places where such logic exists.

**Comment by ericthomasswenson** [comment]
That’s why it’s a question and nothing more.

In terms of priorities it ranks below white space cleanup, but I thought it was worth recording.

**Comment by battjt** [comment]
Not an error.
