### ISSUE TITLE
Investigate Address claim late response vs J1939-81

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#946]
The timing rules for address claim may not meet the 220 ms model at the beginning of section 6.

Investigate timing complaint vs. J1939-81 ... the single segment assumption may be incorrect.

Here SA 4C is isolated on a disparate segment

13:22:10.8789 Global Request for Address Claim
13:22:10.8857 18EAFFF9 [3] 00 EE 00 (TX)
13:22:10.8873 18EEFF03 [8] 00 00 40 02 00 03 00 00
Transmission #1 (3) reported as: {
  Industry Group: Global
  Vehicle System: Non-specific System, System Instance: 0
  Function: Transmission, Functional Instance: 0, ECU Instance: 0
  Manufactured by: Eaton Corp, Transmission Div., Identity Number: 0
  Is not arbitrary address capable.
...

13:22:11.1406 18EEFF4C [8] 38 32 A0 01 00 38 00 00
Communications Unit, Radio (76) reported as: {
  Industry Group: Global
  Vehicle System: Non-specific System, System Instance: 0
  Function: Communications Unit, Radio, Functional Instance: 0, ECU Instance: 0
  Manufactured by: Delco Electronics, Identity Number: 12856
  Is not arbitrary address capable.
}
**_TIMING: Late response -  13:22:11.1406 18EEFF4C [8] 38 32 A0 01 00 38 00 00
                          
11.1406 Less 10.8857 is  0.2549_**

**Comment by ericthomasswenson** [comment]
4C answered twice here

Log File Name: C:\CdriveSave\new j1939-84\v307 786 Samsara Link2.j1939-84

TEST LOG REPORT

J1939-84 Tool version 3.0.7 - 2021/04/12 08:26

Start Part 1 - KOEO Data Collection

Start Test 1.1 - Test vehicle data collection
Initial Engine Speed = 0.0 RPMs
Final Engine Speed = 0.0 RPMs

12:06:49.7146 Global Request for Address Claim
12:06:49.7178 18EAFFF9 [3] 00 EE 00 (TX)
12:06:49.7209 18EEFF4C [8] 38 32 A0 01 00 38 00 00
Communications Unit, Radio (76) reported as: {
  Industry Group: Global
  Vehicle System: Non-specific System, System Instance: 0
  Function: Communications Unit, Radio, Functional Instance: 0, ECU Instance: 0
  Manufactured by: Delco Electronics, Identity Number: 12856
  Is not arbitrary address capable.
}
...
12:06:49.9744 18EEFF4C [8] 38 32 A0 01 00 38 00 00
Communications Unit, Radio (76) reported as: {
  Industry Group: Global
  Vehicle System: Non-specific System, System Instance: 0
  Function: Communications Unit, Radio, Functional Instance: 0, ECU Instance: 0
  Manufactured by: Delco Electronics, Identity Number: 12856
  Is not arbitrary address capable.
}
TIMING: Late response -  12:06:49.9744 18EEFF4C [8] 38 32 A0 01 00 38 00 00
                                              Less 49.7178
                                                         0.2566

**Comment by battjt** [comment]
Addressed with previous TP and application tuning.
