### ISSUE TITLE
Timing Error Count is incorrect 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#947]
Timing Error Count is incorrect 

The correct count is 2; count for “TIMING: Late” instead of “timing:”

Log File Name: C:\CdriveSave\new j1939-84\v307 786b Link2.j1939-84

TEST SUMMARY REPORT
OUTCOME: 
Failures:    10	// I think this is the best current 786 can do? ETS looks that way to me too, Bob
Warnings:    29	// I didn’t look at these. ETS: No false failures were perceived 
Information: 0
Incomplete:  0
Timing:      15	// This count is wrong; it is counting DA text along with late responses
Passes:      168	// The correct count is 2; look for “TIMING: Late” instead of “timing:”

**Comment by battjt** [comment]
"Timing" was counting all J1939 TP errors, but apparently not reporting them in the report.

Should these be reported and/or counted?

1. Receiving BAM:
  * warn("BAM canceled or aborted: " + bam + " -> " + p);
  * warn("BAM missing DT %d != %d", received.cardinality(), numberOfPackets);
2. Receiving DS:
  * Canceled DS TP session.
3. Most of the TP errors that we catch are sending DS, which I don't expect that this tool does:
  * warn("TP.CM_CTS bytes 4-5 should be FFFF: %04X  %s", cts.get16(3), cts.toString());
  * warn("TP.CM_CTS bytes 6-8 should be the PGN: %04X  %s", cts.get24(5), cts.toString());
  * warn("Abort received: " + getAbortError(ctsOptional.get().get(1)));
  * DS CTS or EOM missing

**Comment by ericthomasswenson** [comment]
How about we let this ride and select from among the enhancement suggestions later.
All of these seem closer to nice to have than must have.

We can choose to reconcile the count in the header later as well

**Comment by battjt** [comment]
The count should only count timing errors.  TP aborts are not timing errors.
