### ISSUE TITLE
Global response to DM6 not observed in Test 7.7

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#950]
Global response to DM6 not observed in Test 7.7.  See #949 for parallel example in DM2.
... 
Both the Global and DS Queries were Supported... in Part 3.  Yet a failure was in Part 7.

Start Test 7.7 - DM6: emission related pending DTCs

12:26:57.8366 Global DM6 Request
12:26:57.8407 18EAFFF9 [3] CF FE 00 (TX)
12:26:57.8435 18FECF17 [8] 00 FF 00 00 00 00 FF FF
DM6 from Instrument Cluster #1 (23): MIL: off, RSL: off, AWL: off, PL: off, No DTCs

12:26:58.4419 Destination Specific DM6 Request to Engine #1 (0)
12:26:58.4468 18EA00F9 [3] CF FE 00 (TX)
12:26:58.4482 18FECF00 [8] 00 FF 00 00 00 00 FF FF
DM6 from Engine #1 (0): MIL: off, RSL: off, AWL: off, PL: off, No DTCs
FAIL: 6.7.7.4.b - OBD ECU Engine #1 (0) did not provide a response to Global query and did not provide a NACK for the DS query

End Test 7.7 - DM6: emission related pending DTCs

Start Test 3.2 - DM6: Emission related pending DTCs

Attempt 1

12:13:37.0502 Global DM6 Request
12:13:37.0546 18EAFFF9 [3] CF FE 00 (TX)
12:13:37.0553 18FECF17 [8] 00 FF 00 00 00 00 FF FF
DM6 from Instrument Cluster #1 (23): MIL: off, RSL: off, AWL: off, PL: off, No DTCs
**_12:13:37.0648 18FECF00 [8] 00 FF 83 10 01 00 FF FF
DM6 from Engine #1 (0): MIL: off, RSL: off, AWL: off, PL: off_**
DTC 4227:1 - Engine Crankcase Breather Oil Separator, Data Valid But Below Normal Operational Range - Most Severe Level - 0 times

12:13:37.6554 Destination Specific DM6 Request to Engine #1 (0)
12:13:37.6619 18EA00F9 [3] CF FE 00 (TX)
12:13:37.6648 18FECF00 [8] 00 FF 83 10 01 00 FF FF
DM6 from Engine #1 (0): MIL: off, RSL: off, AWL: off, PL: off
DTC 4227:1 - Engine Crankcase Breather Oil Separator, Data Valid But Below Normal Operational Range - Most Severe Level - 0 times

End Test 3.2 - DM6: Emission related pending DTCs

Start Test 3.3 - DM27: All pending DTCs

12:13:37.6687 Global DM27 Request
12:13:37.6718 18EAFFF9 [3] 82 FD 00 (TX)
12:13:37.6748 18FD8200 [8] 00 FF 83 10 01 00 FF FF
DM27 from Engine #1 (0): MIL: off, RSL: off, AWL: off, PL: off
DTC 4227:1 - Engine Crankcase Breather Oil Separator, Data Valid But Below Normal Operational Range - Most Severe Level - 0 times

12:13:38.2707 Destination Specific DM27 Request to Engine #1 (0)
12:13:38.2743 18EA00F9 [3] 82 FD 00 (TX)
12:13:38.2748 18FD8200 [8] 00 FF 83 10 01 00 FF FF
DM27 from Engine #1 (0): MIL: off, RSL: off, AWL: off, PL: off
DTC 4227:1 - Engine Crankcase Breather Oil Separator, Data Valid But Below Normal Operational Range - Most Severe Level - 0 times

End Test 3.3 - DM27: All pending DTCs

**Comment by battjt** [comment]
Looks to me like the lack of a response was due to some other module requesting FEEB and that response still being in progress.  The following is filtered:

```
12:26:57.5150 18EAFFFE [3] EB FE 00
12:26:57.5182 18ECFF00 [8] 20 3F 00 09 FF EB FE 00
12:26:57.5782 18EBFF00 [8] 01 49 4E 54 20 20 2A 37
12:26:57.6382 18EBFF00 [8] 02 35 37 31 30 33 31 37
12:26:57.6983 18EBFF00 [8] 03 31 37 2A 31 32 34 4B
12:26:57.7584 18EBFF00 [8] 04 4D 32 59 34 35 30 33
12:26:57.8182 18EBFF00 [8] 05 32 39 37 00 00 00 2A
12:26:57.8407 18EAFFF9 [3] CF FE 00 (TX)
12:26:57.8435 18FECF17 [8] 00 FF 00 00 00 00 FF FF
12:26:57.8784 18EBFF00 [8] 06 30 30 30 30 30 30 30
12:26:57.9382 18EBFF00 [8] 07 30 30 30 2A 19 19 19
12:26:57.9985 18EBFF00 [8] 08 19 19 19 19 19 19 19
12:26:58.0581 18EBFF00 [8] 09 19 19 19 19 19 19 00
12:26:58.4468 18EA00F9 [3] CF FE 00 (TX)
12:26:58.4482 18FECF00 [8] 00 FF 00 00 00 00 FF FF

```
There was no BUSY NACK.

**Comment by mmschaefer** [comment]
Application behaves as expected.  There was no BUSY NACK and reporting was handled correctly.
