### ISSUE TITLE
Alternate off MIL status should pass for NON OBD ECU DM1 in 6.1.15.2.c

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#957]
Alternate off MIL status should pass for NON OBD ECU DM1 in 6.1.15.2.c

13:42:52.8882 18FECA2F [8] 00 00 00 00 00 00 00 00
DM1 from Suspension - System Controller #1 (47): MIL: alternate off, RSL: alternate off, AWL: alternate off, PL: alternate off, No DTCs

FAIL: 6.1.15.2.c - Non-OBD ECU Suspension - System Controller #1 (47) did not report MIL off or not supported, need not change

6.1.15.2.c - Fail if any non-OBD ECU does not report MIL off or not supported MIL status (per SAE J1939-73 Table 5), could be written better.

**Comment by ericthomasswenson** [comment]
Proposed text

6.1.15.2.c - Fail if any non-OBD ECU does not report MIL Status **_as_** MIL off **_(preferred or alternate)_** or not supported (per SAE J1939-73 Table 5).

**Comment by vmuthu2** [comment]
PACCAR vehicles also have a similar issue. 
FAIL: 6.1.15.2.c - Non-OBD ECU Instrument Cluster #1 (23) did not report MIL off or not supported
FAIL: 6.3.6.2.d - Non-OBD ECU Instrument Cluster #1 (23) did not report MIL off or not supported
FAIL: 6.9.22.2.a - ECU Instrument Cluster #1 (23) reported MIL status of alternate off
WARN: A.8 - Alternate coding for off (0b00, 0b00) has been accepted

There are 4 FAILURES for the same issue in 4 different parts of the test.

**Comment by ericthomasswenson** [comment]
#1186 adds observation from 3rd participant.

**Comment by battjt** [comment]
This ticket only addresses 6.1.15.2.c.  If needed, please make tickets for the following (not currently included in doc):
- FAIL: 6.3.6.2.d - Non-OBD ECU Instrument Cluster https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (23) did not report MIL off or not supported
- FAIL: 6.9.22.2.a - ECU Instrument Cluster https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (23) reported MIL status of alternate off
- WARN: A.8 - Alternate coding for off (0b00, 0b00) has been accepted
