### ISSUE TITLE
False FAIL for VIN in 6.1.5.2e - TOOL Issue

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#964]
12:03:09.1071 Global VIN Request
12:03:09.1103 18EAFFF9 [3] EC FE 00 (TX)
12:03:09.2952 18FEEC00 [18] 31 58 50 42 44 4B 39 58 31 4C 44 37 30 38 31 39 35 2A
Vehicle Identification from Engine #1 (0): 1XPBDK9X1LD708195
FAIL: 6.1.5.2.e - VIN is not valid (not 17 legal chars, incorrect checksum, or non-numeric sequence

Version detected in - J1939-84 Tool version 3.0.7

The VIN is reported correctly and the checksum is also correct. Why is there a FAIL VIN not valid?

**Comment by gumbelmj** [comment]
@vmuthu2 , that VIN is invalid.  The checksum is not correct.

![Screen Shot 2021-04-29 at 9 00 37 PM](https://user-images.githubusercontent.com/7874086/116635928-0d337d00-a92e-11eb-8902-67d99d48d4ee.png)

**Comment by gumbelmj** [comment]
The source of truth can be found at [govinfo.gov](https://www.govinfo.gov/content/pkg/CFR-2011-title49-vol6/pdf/CFR-2011-title49-vol6-part565.pdf)

**Comment by ericthomasswenson** [comment]
Vimal, I don’t see a need for a change, do you have a rebuttal argument?

**Comment by gumbelmj** [comment]
@ericthomasswenson , I have a rebuttal.  It _is_ a valid bug.  The fractional remainder is "0.091" which should be '1' not 'X'.  I mis-read the spec.

**Comment by ericthomasswenson** [comment]
Might explain the problem with the brand F Vin early too

**Comment by ericthomasswenson** [comment]
2. Fail if the check digit (ninth character) does not match the expected check digit as calculated by the test software per §565.15(c).

**Comment by ericthomasswenson** [comment]
Glad to see this resolved.
