### ISSUE TITLE
Timing - Test Summary Report Outcome

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#965]
![image](https://user-images.githubusercontent.com/46825003/116625941-56200d00-a8ff-11eb-8e0a-8ad85a14d9cb.png)

Timing : 6??

How does the tool evaluate it? What must the user be looking for?

Version detected - J1939-84 Tool version 3.0.7

**Comment by ericthomasswenson** [comment]
See #947 for prior discussion on this question.  This was deemed low priority compared to false failures for 3.0.7., but is appropriate for correction under the current contract.

**Comment by battjt** [comment]
Closing as duplicate of #947
