### ISSUE TITLE
Multiple CAL-ID/CVNs in a single DM19

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#966]
WARN: 6.1.7.3.b - Engine #1 (0) provided more than one CAL ID and CVN pair in a single DM19 message

Specification issue

Most engine manufacturers report multiple CAL-Ids and CVNs in a single DM19. Why cannot this be changed to an INFO?

**Comment by gumbelmj** [comment]
This appears to be a duplicate of #811

**Comment by ericthomasswenson** [comment]
And #813

Proposed text is documented in #811

**Comment by battjt** [comment]
Duplicate of #813 and #811.
