### ISSUE TITLE
Engine Serial Number - Specification Issue

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#967]
WARN: 6.1.9.3.a - Serial number field (SPN 588) from Engine #1 (0) is less than 8 characters long

![image](https://user-images.githubusercontent.com/46825003/116629687-a0f15300-a906-11eb-9846-666fe0be0b00.png)

This issue was supposed to be fixed with the new tool. The issue is still not fixed.

**Comment by ericthomasswenson** [comment]
Did 5 numeric digits pass or fail? 

Yes, there is an error of omission compared to the statement of work and the table of ESN archetypes in Appendix A-1 for SP 588. The real omission is in 6.1.9.2.c which says.

c. Fail if the serial number field (SP 588) from any function 0 device does not end in 6 numeric characters (ASCII 0 through ASCII 9).  
... Which should say 5 numeric digits to match the entries for archetypes.

The plurality of engines provide a model character, an engine model year character and six numeric digits.  I think there is a clear case to downgrade from warning to info ... as there are no regulations as to format, just a convention that numeric decimal digits are used.

**Comment by ericthomasswenson** [comment]
Proposed J1939-84 text 
6.1.9.2.c Fail if the serial number field (SP 588) from any function 0 device does not end in **_5_** numeric characters (ASCII 0 through ASCII 9).

6.1.9.3.a. **_INFO_** if the serial number field (SPNSP 588) from any function 0 device is less than eight characters long.

**Comment by ericthomasswenson** [comment]
There is also an omission in Appendix A

Add

| aa * b * A12345  | Unit number field and delimiter not provided for six character serial number | Pass |

**Comment by ericthomasswenson** [comment]
6 is now 5 and  
aa * b * A12345 -- Unit number field and delimiter not provided for six character serial number | Pass
added to serial number examples in Appendix A ESN Example table in 24 June as built draft.
