### ISSUE TITLE
Non-OBD ECU responses for DM5 - Spec Issue

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#968]
12:03:26.1374 Global DM5 Request
12:03:26.1399 18EAFFF9 [3] CE FE 00 (TX)
12:03:26.1439 18FECE03 [8] 00 00 05 00 00 00 00 00
DM5 from Transmission #1 (3): OBD Compliance: Not intended to meet OBD II requirements (5), Active Codes: 0, Previously Active Codes: 0

WARN: 6.1.13.2.a (A6.3.a) - Non-OBD ECU Transmission #1 (3) responded
WARN: 6.2.2.2.a (A6.3.a) - Non-OBD ECU Transmission #1 (3) responded

There is no reason for this WARNING. The DM5 content clearly mentions that it is “Not intended to meet OBD II requirements (5)”. Why WARN?

Suggest an INFO or nothing as there is nothing wrong here.

**Comment by ericthomasswenson** [comment]
Consolidate in #1099

**Comment by ericthomasswenson** [comment]
Consolidation proposal #1099 ready for review.

**Comment by ericthomasswenson** [comment]
Superseded by #1099
