### ISSUE TITLE
Incorrect SPN 3217 evaluation for plausibility - Spec Issue

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#969]
PGN 61454 with Supported SPNs 3216, 3217
12:03:35.6165 18F00E00 [8] 00 FB FF FE FF FF FF FF
Found: AFT 1 Intake Gas 1 from Engine #1 (0): 
  SPN  3216, Engine Exhaust 1 NOx 1: 0xFB00
  SPN  3217, Engine Exhaust 1 Percent Oxygen 1: Error
  SPN  3218, Engine Exhaust 1 Gas Sensor 1 Power In Range: 11
  SPN  3219, AFT 1 Intake Gas Sensor 1 at Temperature: 11
  SPN  3220, Engine Exhaust 1 NOx 1 Reading Stable: 11
  SPN  3221, AFT 1 Intake Wide-Range Percent Oxygen 1 Reading Stable: 11
  SPN  3222, AFT 1 Intake Gas Sensor 1 Heater Preliminary FMI: 31.000000 
  SPN  3223, AFT 1 Intake Gas Sensor 1 Heater Control: 11
  SPN  3224, Engine Exhaust 1 NOx Sensor 1 Preliminary FMI: 31.000000 
  SPN  5714, Engine Exhaust 1 NOx Sensor 1 Self-diagnosis Status: 111
  SPN  3225, AFT 1 Intake Oxygen  Sensor 1 Preliminary FMI: 31.000000 

WARN: 6.1.26.2.d - N.8 Engine #1 (0) reported value for SPN 3217 (ERROR) is implausible
WARN: 6.2.17.2.b - N.8 Engine #1 (0) reported value for SPN 3217 (ERROR) is implausible
WARN: 6.11.7.3.a - N.8 Engine #1 (0) reported value for SPN 3217 (ERROR) is implausible

![image](https://user-images.githubusercontent.com/46825003/116630664-7bfddf80-a908-11eb-946a-e656bda57795.png)

SPN 3217 must be evaluated only on SI engines. Why is it being evaluated here for plausibility?

**Comment by gumbelmj** [comment]
SP 3217 is supported by the ECU.  However, the ECU reported the value as "ERROR".  As such, the value is implausible per footnote 28:

![Screen Shot 2021-04-29 at 9 14 22 PM](https://user-images.githubusercontent.com/7874086/116636758-10c80380-a930-11eb-8b1b-3cf953efd832.png)

"Received values of the error indicator... shall be considered a plausibility failure..."

**Comment by ericthomasswenson** [comment]
Vimal, my expectation is that were SP 3217 not included in your DM24 response, the value for SP 3217 would have been ignored.  Under the current conventions, there should be a DM1/DM12 DTC for SP 3217, given the broadcast value of FEFFh. Oxygen sensor values of FB00/FBXXh can be accepted, but we would add the same notes in Table A-1 and J1939DA.

**Comment by vmuthu2** [comment]
Agreed with the addition Eric. But until the sensor is ready for measurement, it has to report something on the bus and since there is no definition/guidance in any documents, not really sure what can be done for it as it stands. So until the sensor warms up, it reports FEFF and finally once the sensor is online, it reports the correct values. Suggestion here is to add some exceptions.
I would not categorize this as "INVALID" bug.

**Comment by gumbelmj** [comment]
I change this from a Tool Issue to a Spec Issue and remove the Invalid flag

Matt

On Apr 30, 2021, at 15:50, vmuthu2 ***@***.***> wrote:

﻿
Agreed with the addition Eric. But until the sensor is ready for measurement, it has to report something on the bus and since there is no definition/guidance in any documents, not really sure what can be done for it as it stands. So until the sensor warms up, it reports FEFF and finally once the sensor is online, it reports the correct values. Suggestion here is to add some exceptions.
I would not categorize this as "INVALID" bug.

**Comment by ericthomasswenson** [comment]
Dear Vimal,

Accepting error (FEFFh) anyway is anathetical.  ...  The agreed convention (model) is to provide FBXXh until the sensor is ready. I think you need to work toward that model.

**Comment by ericthomasswenson** [comment]
Advertised data stream SPs, that are sent and received as FEFF (error), is defined to fail as a general matter of course.

**Comment by ericthomasswenson** [comment]
Proposed Table A-1 text change accepts FBh for all SPs, as provided for the maintenance SOW.

**Comment by ericthomasswenson** [comment]
Documented maintenance contract proposed resolution.

[J1939-84-Table-A-1-MY24 May-21-2021 .docx](https://github.com/battjt/j1939-84/files/6593273/J1939-84-Table-A-1-MY24.May-21-2021.docx)
