### ISSUE TITLE
SPN 3609, 3610 and 3251 plausibility check incorrect values - Spec Issue

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#970]
PGN 64908 with Supported SPNs 3609, 3610
12:03:36.0769 18FD8C00 [8] 0E 00 00 00 FF FF FF FF
Found: AFT 1 Gas Parameters from Engine #1 (0): 
  SPN  3609, AFT 1 DPF Intake Pressure: 1.400000 kPa
  SPN  3610, AFT 1 DPF Outlet Pressure: 0.000000 kPa

WARN: 6.1.26.2.d - N.8 Engine #1 (0) reported value for SPN 3609 (1.4000000000000001) is implausible

Sensor tolerances are not taken into account for plausibility check with Key On Engine Off.

Propose a spec change.

![image](https://user-images.githubusercontent.com/46825003/116631273-94222e80-a909-11eb-9c10-569829bc9fc4.png)

This issue again was supposed to be fixed in the statement of work for the new tool.

**Comment by vmuthu2** [comment]
It will be great if this one can be fixed within the warranty period. This must have been included in the original scope request/statement of work. Kindly review and do the needful to get this bug rectified.

**Comment by ericthomasswenson** [comment]
Fixing table A-1 values beyond the values noted in the J1939-84 change pages is not in the detailed statement of work.  I think this is clear in the task 1 text which says:

> _Task 1 Data Stream Issue Cluster.  Improve processing for DM24 responses and Table A-1 as amended to support the following improvements. Reorganize the data structures used to capture table A-1 to better reflect the existence of distributed systems and contributions from Non OBD modules particularly for Fuel Level, Battery and Ignition Voltage.  Reorganize the data structures to incorporate the additional “Info” outcomes.  [**The plurality of the improvements are captured in the revised table A-1.**  Please identify any inconsistencies.  See SAE J1939-84 section A.10 for principles that apply to asymmetric distributed systems.  See Task 6 for SI technology additions]._ 

Omissions from the “revised Table A-1” and new Table A-1 insights (like info for SP 96) are not the provider’s responsibility.  A similar request, #859, already has a future enhancement label.

I’m willing to lead a new set of Table A-1 improvements with all contributors and ask.  
(A weighted voting scheme could be used to prioritize improvements, should they become numerous).
But I don’t believe ETI (industry) can compel new Table A-1 content as part of the existing contract.

[StatementOfWorkCheckoff-84-3-0.docx](https://github.com/battjt/j1939-84/files/6408360/StatementOfWorkCheckoff-84-3-0.docx)

**Comment by ericthomasswenson** [comment]
https://github.com/Equipment-and-Tool-Institute/j1939-84/files/7171010/J1939-84-Table-A-1-MY24.15Sept2021.docx 

Provides enhanced plausibility criteria that may be enough.

**Comment by ericthomasswenson** [comment]
Table 1 changes implemented.

**Comment by ericthomasswenson** [comment]
Table 1 Documentation complete for Task 1

**Comment by ericthomasswenson** [comment]
Plausibility value improvements released in 3.1.3 to Table 1 artifact.
