### ISSUE TITLE
SPN 96 available from two ECU - Spec Issue

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#971]
WARN: 6.1.26.2.f - N.5 SPN 96 provided by more than one ECU
WARN: 6.2.17.2.d - N.5 SPN 96 provided by more than one ECU

There is nothing wrong here when two ECU's report SPN 96. The OBD ECU (Engine Controller) reports SPN 96 correctly as per the regulation. All the required datastream is provided by the engine controller.

![image](https://user-images.githubusercontent.com/46825003/116631904-c1bba780-a90a-11eb-9931-344713b20fbc.png)

**Comment by ericthomasswenson** [comment]
I’ve seen circumstances where the engine supports SP 96 in DM24, and then provides the value FF.
This results in a Fail message that cannot be excused.

Changing “Action if Two or More ECUs Respond” to info I believe can be accommodated in the maintenance contract.

**Comment by mmschaefer** [comment]
@ericthomasswenson - the reverence above is to 6.1.26.2.(f?). The latest copy of the spec only goes to 6.1.26.2.e.  Code change ticket?

**Comment by mmschaefer** [comment]
This is actually referring to 6.1.26.2.e. - will also require a code change if doing.

**Comment by ericthomasswenson** [comment]
We can fix providing f instead of e during maintenance contract fixes for test 1.26.
Doing it now, for inclusion in the first maintenance release, would avoid a potential error of omission.
Your choice, add a maintenance issue to track it separately from this issue.
This issue is about what the -84 document should say in table A-1 for the future test 1.26 performance.

**Comment by ericthomasswenson** [comment]
Table A-1 Revisions should address this

96 (16) | Fuel Level 1 | 65276 | BC 1000 ms | No | Warn | No | **_Info_** | Info | Info | N/A | N/A
38 (16) | Fuel Level 2 | 65276 | BC 1000 ms |   “”   | No |  “”   | **_Info_** | Info | Info | N/A | N/A

https://github.com/Equipment-and-Tool-Institute/j1939-84/files/7171010/J1939-84-Table-A-1-MY24.15Sept2021.docx

**Comment by ericthomasswenson** [comment]
Table A-1 Changes implemented. This is believed to be resolved.
