### ISSUE TITLE
SPN 2978 incorrect plausibility check - Spec Issue

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#972]
WARN: 6.2.17.2.b - N.8 Engine #1 (0) reported value for SPN 2978 (0.0) is implausible
WARN: 6.11.7.3.a - N.8 Engine #1 (0) reported value for SPN 2978 (0.0) is implausible

On PACCAR's engines, SPN 2978 (Estimated Engine Parasitic Losses - Percent Torque) is a sum of parasitic torque from the coolant pump and cooling fan. Some trucks are equipped with a variable speed fan and hence when the cooling fan is not operating SPN 2978 is less than 1% (< 1%) at idle speed (500 to 700 rpm). Also the resolution of this SPN is 1%/bit. So there is no option of reporting it in decimal. Too restrictive.

![image](https://user-images.githubusercontent.com/46825003/116632392-f5e39800-a90b-11eb-85ac-6b3d4f8aa25b.png)
 

Instead of <=0% for Engine On. Kindly request it be changed to <0% or N/A.

**Comment by ericthomasswenson** [comment]
Perhaps the better concept would defining a maximum parasitic loss > x%

Would 8% do?

**Comment by ericthomasswenson** [comment]
Hi Eric,
...
As far as the parasitic load (SPN 2978), would propose the following improvement for plausibility:
Engine Off >0% (no changes here)
Engine On (low idle)  >5% (can be 5% or 8% like you have suggested)
...

Thank you,
Vimal

**Comment by ericthomasswenson** [comment]
Revised Table A-1 Row for 2978 says

2978 (16) | Estimated Engine Parasitic Losses - Percent Torque | 65247 | BC 250 ms or RPM Dependent | Yes | No | No | None | Fail | Fail | >0% | > 8%, < 0

https://github.com/Equipment-and-Tool-Institute/j1939-84/files/7171010/J1939-84-Table-A-1-MY24.15Sept2021.docx

**Comment by ericthomasswenson** [comment]
Closed in favor of text provided for Table A-1 in #1094
