### ISSUE TITLE
WARN for DM22 - Spec Issue

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#973]
WARN: 6.8.12.6.a - Engine #1 (0) did not provide DM22 CLR_PA_NACK or CLR_ACT_NACK with acknowledgement code of 0
WARN: 6.9.3.6.a - Engine #1 (0) did not provide DM22 CLR_PA_NACK or CLR_ACT_NACK with acknowledgement code of 0

There is no requirement from any legislation to support DM22. PACCAR’s engines do not support DM22. “Table 1 - Emission-related component PGN and SPN support” in J1939-73 does not require DM22 to be supported as well.

The old CT-84 tool did not evaluate this. Also the below is mentioned very clearly in J1939-73,
![image](https://user-images.githubusercontent.com/46825003/116633438-5247b700-a90e-11eb-9f20-c1123ba4931b.png)

**Comment by ericthomasswenson** [comment]
There is a prohibition (not) to support DM22, the warning text in J1939-84 was agreed upon a long time ago. (Led by Bill Chittick).
The suggestion I have is to change from warning to info.

**Comment by ericthomasswenson** [comment]
See #771 for Correction of garbled text in J1939-84

**Comment by ericthomasswenson** [comment]
5.7.22 Individual Clear/Reset of Active and Previously Active DTC (DM22)

All of the diagnostic information pertaining to the specified diagnostic trouble code should be erased when the CLR_PA_REQ or CLR_ACT_REQ action of this PG is requested. This PGN is used to provide the DTC clear/reset services offered with DM3 and DM11, but for individual DTCs. When the individual clear of a previously active DTC is performed, the diagnostic data associated with active trouble codes will not be affected. Upon the completion of a requested clear/reset operation, a positive acknowledgement using CLR_PA_ACK or CLR_ACT_ACK, respectively, is required.

DM22 is a command-type message. It is not queried using SAE J1939-21 request (PGN EA00), and use of the SAE J1939-21 acknowledgement PGN (PGN E800) is not expected for replies to DM22. Instead, devices that support DM22 should send a DM22 response. Devices that don’t support DM22 (at all) are not required to provide a response using DM22. As a result, responses to DM22 queries may time out, according to SAE J1939-21 rules for response time (Tr). Similarly, retries for DM22 shall be limited to the three-attempt convention that may be inferred from SAE J1939-21.

**_NOTE: A DM22 CLR_PA_REQ or CLR_ACT_REQ may or may not generate a response from the target device. No response would be expected if the target node does not support the PGN._** The target node might filter out the message at the hardware level to reduce CPU utilization or the target node may have no receive handler for this message effectively discarding the DM22 with no action. A DM22 response (DM22 CLR_PA_ACK, CLR_PA_NACK, CLR_ACT_ACK, or CLR_ACT_NACK) is only expected if the target device supports this PGN.
NOTE: A response to a DM 22 CLR_PA_REQ or CLR_ACT_REQ will be one of a DM22 CLR_PA_ACK, CLR_PA_NACK, CLR_ACT_ACK, or CLR_ACT_NACK. The response should not be an acknowledge PGN (E800).
Devices that comply with HD OBD or OBD II shall not clear any individual HD OBD defined DTC.

**Comment by ericthomasswenson** [comment]
Proposed Text

6.8.12.4 Actions2 
a. DS DM22 to OBD ECU with a DM12 MIL on DTC stored using the DM12 MIL On DTC SPN and FMI and control byte = 1, Request to Clear/Reset Previously Active DTC. 

6.8.12.5 Fail Criteria2 
a. Fail if the ECU provides DM22 with CLR_PA_ACK or CLR_ACT_ACK.  
b. Fail if the ECU provides J1939-21 ACK for PG 49920. 
c. Fail if the ECU provides CLR_ACT_NACK with an acknowledgement code greater than 0.  

6.8.12.6 Warn Criteria2 
a. **_Info_**, if DM22 (PG 49920) **_CLR_**_PA_NACK or **_CLR_**_ACT_NACK is not received with an acknowledgement code of 0. 
b. Warn if J1939-21 NACK for PG 49920 is received.

**Comment by ericthomasswenson** [comment]
No response at all is anticipated in SAE J1939-73

**Comment by ericthomasswenson** [comment]
Proposal Matches

6.8.12.3 Warn Criteria 
a. Info: if DM22 (PG 49920) **_CLR_**_PA_NACK or **_CLR_**_ACT_NACK is not received with an acknowledgement code of 0.[53]

**Comment by ericthomasswenson** [comment]
6.9.3.6 documentation incomplete added to artifact errata.

**Comment by anthonyhbest** [comment]
6.9.3.6.a WARN still being issued by release 3.1.6 but 6.8.12.6.a appears to be correct now.

**Comment by ericthomasswenson** [comment]
This will be one of the observations where warn adds no value when copied into the reporting  template.

**Comment by anthonyhbest** [comment]
Resolved in V3.1.7
