### ISSUE TITLE
Incorrect plausibility check in Part 11 Test 7 - Tool Issue

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#974]
The tool is incorrectly executing a plausibility check when the engine speed is being increased from idle (650rpm) to 1200rpm. Below are the three WARNINGs due to that,
WARN: 6.11.7.3.a - N.8 Engine #1 (0) reported value for SPN 183 (6.25) is implausible
WARN: 6.11.7.3.a - N.8 Engine #1 (0) reported value for SPN 1600 (5.472) is implausible
WARN: 6.11.7.3.a - N.8 Engine #1 (0) reported value for SPN 512 (1.0) is implausible

Using the idle control button in the cab, the idle is being increased from 650rpm to 1200rpm. During that process, plausibility check is executed causing FALSE fails in the test.

12:33:04.1753 Test Update:
          Engine Speed: 650.25 RPM
      WMA Engine Speed: 650.25 RPM
     Idle Engine Speed: 600.0 RPM
        Pedal Position: 0.0 %
  Run Time >= 1150 RPM: 0 seconds
      Run Time at Idle: 0 seconds
        Total Run Time: 3 seconds

12:34:04.1822 Test Update:
          Engine Speed: 650.0 RPM
      WMA Engine Speed: 649.8177456483442 RPM
     Idle Engine Speed: 650.0 RPM
        Pedal Position: 0.0 %
  Run Time >= 1150 RPM: 0 seconds
      Run Time at Idle: 57 seconds
        Total Run Time: 63 seconds

12:35:04.1842 Test Update:
          Engine Speed: 650.25 RPM
      WMA Engine Speed: 650.1699007084301 RPM
     Idle Engine Speed: 650.0 RPM
        Pedal Position: 0.0 %
  Run Time >= 1150 RPM: 0 seconds
      Run Time at Idle: 114 seconds
        Total Run Time: 123 seconds

12:36:04.1830 Test Update:
          Engine Speed: 648.0 RPM
      WMA Engine Speed: 649.9371163443017 RPM
     Idle Engine Speed: 650.0 RPM
        Pedal Position: 0.0 %
  Run Time >= 1150 RPM: 0 seconds
      Run Time at Idle: 170 seconds
        Total Run Time: 183 seconds

PGN 65266 with Supported SPNs 183
12:36:26.2027 18FEF200 [8] 7D 00 00 00 55 06 00 FF
Found: Fuel Economy (Liquid) from Engine #1 (0): 
  SPN   183, Engine Fuel Rate: 6.250000 l/h
  SPN   184, Engine Instantaneous Fuel Economy: 0.000000 km/L
  SPN   185, Engine Average Fuel Economy: 3.166016 km/L
  SPN    51, Engine Throttle Valve 1 Position 1: 0.000000 %
  SPN  3673, Engine Throttle Valve 2 Position: Not Available

WARN: 6.11.7.3.a - N.8 Engine #1 (0) reported value for SPN 183 (6.25) is implausible
PGN 64737 with Supported SPNs 1600
12:36:26.2120 18FCE100 [8] 60 15 00 00 FF FF FF FF
Found: Fuel Economy 2 (Liquid) from Engine #1 (0): 
  SPN  1600, Engine Fuel Rate (High Resolution): 5.472000 l/h
  SPN  7596, Engine Diesel Fuel Demand Rate: Not Available

WARN: 6.11.7.3.a - N.8 Engine #1 (0) reported value for SPN 1600 (5.472) is implausible
PGN 61444 with Supported SPNs 190, 512, 513, 4154
12:36:26.2902 0CF00400 [8] 1E 7E 89 02 16 00 F0 86
Found: Engine Speed from Engine #1 (0): 
  SPN   899, Engine Torque Mode: 1110
  SPN  4154, Actual Engine - Percent Torque (Fractional): 0.125000 %
  SPN   512, Driver's Demand Engine - Percent Torque: 1.000000 %
  SPN   513, Actual Engine - Percent Torque: 12.000000 %
  SPN   190, Engine Speed: 704.250000 rpm
  SPN  1483, Source Address of Controlling Device for Engine Control: 0.000000 source address
  SPN  1675, Engine Starter Mode: 0000
  SPN  2432, Engine Demand - Percent Torque: 9.000000 %

WARN: 6.11.7.3.a - N.8 Engine #1 (0) reported value for SPN 512 (1.0) is implausible

**Comment by ericthomasswenson** [comment]
Matt, there are two contributing approaches to reducing the number of Warns in part 11.
 -1. Increase allowed idle engine values in Table A-1 to account for transients 
 -2. Wait until all the time for engine operation above 1150 has been collected to minimize exposure to transient engine operation.
I suggest we do both.

 -2. Can be justified by observed performance of the Table A-1 values in Part 11, and need not be reviewed with the agency.  We’ve seen this happen on multiple engine makes. It was also suggested before as what the ControlTech software did.
 -1. Will need to be reviewed with the agency, but should not be controversial.  We just need to gather all the examples where the current values don’t work.

 -1. Should be combined with the offset adjustments desired for engine off operation.
 -2. Needs a note in Part 11 directing the timing desired.

**Comment by ericthomasswenson** [comment]
-1. Should include value improvements for #972 and #970 
      And May address SP 91 comment in #858.
      This change may be considered a future enhancement as the software matches the specification.

 -2. Waiting until all time above 1150 RPM has elapsed to match current software and minimize warnings is recommended for the current contract.

**Comment by ericthomasswenson** [comment]
A consolidated list of proposal was set out for review:

Dear Vimal,

Overall, we are starting to approach 10% of the plausibility value lines.
Any additional requests (not already in GitHub).

Bob, Joseph, and Dan,

Do you have any additional plausible value limits suggestions.
The concept is to address low value added plausible value warnings, especially during engine transient operation during General Denominator Demonstration in Part 11.

These values intend to eliminate known sensor offsets and account for boost pressure that had not finished bleeding off before data is checked.

There is also a list of MY22 and MY24 additions for table A-1, that will need to be modeled for the maintenance contract statement of work.

Best Wishes,

Eric Swenson

[J1939-84-Table-A-1-enhancements.docx](https://github.com/battjt/j1939-84/files/6408694/J1939-84-Table-A-1-enhancements.docx)

**Comment by battjt** [comment]
@gumbelmj split this into 3 issues:
1. plausibility numbers
2. routine (delay start of check)
3. document routine (delay start of check)

**Comment by gumbelmj** [comment]
The tool will now wait until 1150 time has expired then check values once the engine speed settles.
