### ISSUE TITLE
Spec: Correct Test 1.14 DM26 Enable Bit Outcomes

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/j1939-84#980]
From j1939-84 created by [ericthomasswenson](https://github.com/ericthomasswenson): battjt/j1939-84#977  

Correct Test 1.14 DM26 Enable Bit Outcomes 

Enable status settings are incorrectly identified as errors in part 1 test 14.  

Details provided below in explanation to CARB.

**Comment by gumbelmj** [comment]
The existing text is technically correct, but too hard to read.

**Comment by gumbelmj** [comment]
Correct Test 1.14 DM26 Enable Bit Outcomes 

<div dir="ltr" style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(255, 255, 255); color: rgb(255, 255, 255); font-family: UICTFontTextStyleTallBody; font-size: 19px;"><div>Dear Dan and Paul,</div><div><br></div><div>One of the reasons I’ve been struggling with DM26 is the overly complex language in Part 1 Test 14. This was complicated by incorrect outcomes, which I identified to the software developer yesterday as shown below.  </div><div><br></div><div>My conclusion is that the text for unsupported monitors, as identified in DM5, needed to be simplified.  The revised text will provide the same outcomes intended by the current language, which Allen Lyons and I wrote about 8 years ago.  The current language for part 1 test 14 does not evaluate enabled bit content.  This I believe to be correct.  The examples for enable bit values, given in J1939-73 5.7.29, illustrate test conditions driven by manufacturers’ implementations that cannot be reasonably controlled in the J1939-84 text.</div><div><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-size: 10pt; font-family: Arial, sans-serif;"> </span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"></p><blockquote type="cite"><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;"><i><font size="4">1. Monitor enable status for the current driving cycle. This bit shall indicate when a monitor is disabled in a manner such that there is no likely or reasonable way for the driver to operate the vehicle to allow the monitor run. Typical examples are:<o:p></o:p></font></i></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><b><span style="font-family: Arial, sans-serif;"><i><font size="4">• Engine-off soak not long enough (e.g., cold start temperature conditions not satisfied)<o:p></o:p></font></i></span></b></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><b><span style="font-family: Arial, sans-serif;"><i><font size="4">• Monitor maximum time limit or number of attempts/aborts exceeded<o:p></o:p></font></i></span></b></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><b><span style="font-family: Arial, sans-serif;"><i><font size="4">• Ambient air temperature too low or too high<o:p></o:p></font></i></span></b></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><b><span style="font-family: Arial, sans-serif;"><i><font size="4">• BARO too low (high altitude)<o:p></o:p></font></i></span></b></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><b><span style="font-family: Arial, sans-serif;"><i><font size="4">The monitor shall not indicate “disabled” for operator-controlled conditions such as rpm, load, accelerator position, minimum time limit not exceeded, etc.<o:p></o:p></font></i></span></b></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;"><i><font size="4"> </font></i></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;"><i><font size="4">2. Monitor completion status for the current driving/monitoring cycle. Status shall be reset to “not complete” upon starting a new monitoring cycle. Note that some monitoring cycles can include various engine-operating conditions; other monitoring cycles begin after the ignition key is turned off. Some status bits on a given vehicle can utilize engine-running monitoring cycles while others can utilize engine-off monitoring cycles. Resetting the bits to “not complete” upon starting the engine will accommodate most engine-running and engine-off monitoring cycles; however, manufacturers are free to define their own monitoring cycles.<o:p></o:p></font></i></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;"><i><font size="4"> </font></i></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;"><i><font size="4">NOTE: DM26 bits shall be utilized for all non-continuous monitors which are supported, and change completion status in DM5. If a non-continuous monitor is not supported or always shows “complete,” the corresponding DM26 bits shall indicate disabled and complete. DM26 bits may be utilized at the vehicle manufacturer’s discretion for all continuous monitors which are supported with the exception of the bit that shall always show CCM (comprehensive component monitoring) as enabled for spark ignition and compression ignition engines.</font><o:p></o:p></i></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;"><i> </i></span></p></blockquote></div><div>I’ll see if I can’t detangle the part 2 DM29 language soon.</div><div><br></div><div>Sincerely Yours,</div><div><br></div><div>Eric Swenson </div><div><br></div><div>————— Text to software developer below.</div><div><br></div><div>Dear ...,</div><div><br></div><div>When I read this, I believe that the enable bit for a monitor supported in DM5 is permitted to say disabled or enabled for the current cycle in DM26. The failure criteria for unsupported monitors, does prohibit the enabled setting. Disable is prohibited for the CCM enable bit (bit 3 of SP 3303).</div><div><br></div><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"></p><blockquote type="cite"><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;">6.1.14.2 Fail Criteria <o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;">a. Fail if any response for any monitor <b><i>supported in DM5 </i></b>by a given ECU is <b><i>reported</i></b> as “0=monitor <b>complete</b> this cycle or not supported” in SP 3303 bits 1-4 and SP 3305 [except comprehensive components monitor (CCM)].  <o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;">b. Fail if any response for each monitor <b><i>not supported in DM5</i></b> by a given ECU is <b><i>not also reported</i></b> in DM26 as “0=monitor complete this cycle or not supported” in SP 3303 bits 5-7 and [also reported in DM26 as] “0=monitor disabled for rest of this cycle or not supported” in SP 3303 bits 1 and 2 and SP 3304. [23]<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;">c. Fail if any response from an ECU <b><i>indicating support for CCM</i></b> monitor in DM5 reports “0=monitor disabled for rest of this cycle or not supported” in SP 3303 bit 3.  <o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;">d. Fail if any response indicates number of warm-ups since code clear (WU-SCC) (SP 3302) is not zero.  <o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;">e. Fail if any response indicates time since engine start (SP 3301) is not zero. <o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;">f. Fail if no OBD ECU provides DM26. <font size="2"><o:p></o:p></font></span></p></blockquote><div><br></div>a-c are summarized below</div><div dir="ltr" style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(255, 255, 255); color: rgb(255, 255, 255); font-family: UICTFontTextStyleTallBody; font-size: 19px;"><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;"> </span></p>

  | DM5 Support | DM26 Enable | DM26 Complete | Outcome
-- | -- | -- | -- | --
6.1.14.2.a | Supported | Any | Complete | Fail
6.1.14.2.b | Not Supported | Any | Not Complete | Fail
6.1.14.2.b | Not Supported | Enabled | Any | Fail
6.1.14.2.c | CCM Supported | Disabled | Any | Fail

<p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;"> </span></p></div><div dir="ltr" style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(255, 255, 255); color: rgb(255, 255, 255); font-family: UICTFontTextStyleTallBody; font-size: 19px;">So when I look at <div><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3"> <o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">07:17:42.1013 Global DM26 Request<o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">07:17:42.1088 18EAFFF9 [3] B8 FD 00 (TX)<o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><b><font size="3"><span style="font-family: &quot;Courier New&quot;;">07:17:42.1111 18FDB800 [8] </span><a><span style="font-family: &quot;Courier New&quot;; color: black;">00 00 00 37 80 12</span></a><span style="font-family: &quot;Courier New&quot;;"> E0 1E<o:p></o:p></span></font></b></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">DM26 from Engine #1 (0): Warm-ups: 0, Time Since Engine Start: 0 seconds<o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3"> <o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">Vehicle Composite of DM26:<o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">    A/C system refrigerant     not enabled,     complete<o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">    Boost pressure control sys     enabled, not complete<o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">    Catalyst                   not enabled,     complete<o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">    Cold start aid system      not enabled,     complete<o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">    Comprehensive component        enabled,     complete<o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">    <i>Diesel Particulate Filter  not enabled, not complete</i><o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">    EGR/VVT system                 enabled, not complete<o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">    Evaporative system         not enabled,     complete<o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">    <i>Exhaust Gas Sensor         not enabled, not complete</i><o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><b><font size="3"><i><span style="font-family: &quot;Courier New&quot;;">    Exhaust Gas Sensor heater  not enabled, not complete</span></i><span style="font-family: &quot;Courier New&quot;;"><o:p></o:p></span></font></b></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">    Fuel System                    enabled, not complete<o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">    Heated catalyst            not enabled,     complete<o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">    Misfire                        enabled, not complete<o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">   <i> </i>NMHC converting catalyst       enabled, not complete<o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><b><font size="3"><i><span style="font-family: &quot;Courier New&quot;;">    NOx catalyst/adsorber      not enabled, not complete</span></i><span style="font-family: &quot;Courier New&quot;;"><o:p></o:p></span></font></b></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3">    Secondary air system       not enabled,     complete<o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: &quot;Courier New&quot;;"><b><font size="3"> <o:p></o:p></font></b></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><b><font size="3"><i><span style="font-family: &quot;Courier New&quot;;">FAIL: 6.1.14.2.a - Engine #1 (0) response for a monitor Diesel Particulate Filter in DM5 is reported as supported and is reported as not enabled by DM26 response</span></i><span style="font-family: &quot;Courier New&quot;;"><o:p></o:p></span></font></b></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><b><font size="3"><i><span style="font-family: &quot;Courier New&quot;;">FAIL: 6.1.14.2.a - Engine #1 (0) response for a monitor Exhaust Gas Sensor in DM5 is reported as supported and is reported as not enabled by DM26 response</span></i><span style="font-family: &quot;Courier New&quot;;"><o:p></o:p></span></font></b></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><b><font size="3"><i><span style="font-family: &quot;Courier New&quot;;">FAIL: 6.1.14.2.a - Engine #1 (0) response for a monitor Exhaust Gas Sensor heater in DM5 is reported as supported and is reported as not enabled by DM26 response</span></i><span style="font-family: &quot;Courier New&quot;;"><o:p></o:p></span></font></b></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><b><i><span style="font-family: &quot;Courier New&quot;;"><font size="3">FAIL: 6.1.14.2.a - Engine #1 (0) response for a monitor NOx catalyst/adsorber in DM5 is reported as supported</font></span></i></b></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><b><i><span style="font-size: 10pt; font-family: &quot;Courier New&quot;;"><br></span></i></b></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><br></p><div dir="ltr">I’ve come to the conclusion that the disabled prohibition was applied in a. to the supported monitors (as defined in DM5) in error. Here the cited supported monitors properly show ‘not complete’ for a.</div></div><div dir="ltr"><br></div><div dir="ltr">I find that my prior acceptance of these and similar error messages was a mistake.</div><div><br></div><div>Do you agree?</div><div><br></div><div>My recommendation is to rewrite a-c as a-d by splitting and simplifying the word salad in b.</div><div><br></div><div><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;">6.1.14.2 Fail Criteria <o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;">a. Fail if any response for any monitor <b><i>supported in DM5 </i></b>by a given ECU is <b><i>reported</i></b> as “0=monitor <b>complete</b> this cycle or not supported” in SP 3303 bits 1-4 and SP 3305 [except comprehensive components monitor (CCM)].  <o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;">// After a reset (here DM11), all completed monitors are reset to not complete.</span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;"><br></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;">b. Fail if any response for each monitor </span><b style="font-family: Arial, sans-serif;"><i>not supported in DM5</i></b><span style="font-family: Arial, sans-serif;"> by a given ECU is </span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><b style="font-family: Arial, sans-serif;"><i>also reported</i></b><span style="font-family: Arial, sans-serif;"> in DM26 as “1=monitor <b><i>not complete </i></b>this monitoring cycle” in SP 3303 bits 5-7.</span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;">// Unsupported monitors will never need to run and are ‘de facto’ complete.</span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;"><br></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;"><b><i>c.</i></b> Fail if any response for each monitor <b><i>not supported in DM5</i></b> by a given ECU is </span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;"><b><i>also reported</i></b> in DM26 as “0=monitor <b><i>enabled</i></b> for this monitoring cycle” in SP 3303 bits 1 and 2 and SP 3304. [23]  </span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;">// Unsupported monitors will never run and cannot be enabled.</span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;"><br></span></p><p class="MsoNormal" style="margin: 0in; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-family: Arial, sans-serif;"><b><i>d</i></b>. Fail if any response from an ECU <b><i>indicating support for CCM</i></b> monitor in DM5 reports “0=monitor disabled for rest of this cycle or not supported” in SP 3303 bit 3.  </span></p></div><div>// For now, CCM is always to be shown as complete.</div><div><br></div><div>I think you will agree these are easier to read.</div><div><br></div><div>Best Wishes,</div><div><br></div><div>Eric</div></div>

**Comment by ericthomasswenson** [comment]
Added to 24June As built draft.
