### ISSUE TITLE
Accommodate FBxx for additional Exhaust Sensors 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#989]
Accommodate FBxx for additional NOx Sensors.

In anticipation of request 21200507WW, https://www.sae.org/servlets/works/postDiscussion.do?comtID=TETES7Z&docID=&resourceID=840863&inputPage=showAll 

Required to meet expectations of J1939-84 compliance test tool. 
Applies to SPNs 3217, 3227, 3256, 3266, 7650, 7661, 7672, 7683

J1939DA will add the text below for the subject SPs
value of FB00h shall be provided when ambient or engine operating conditions do not permit the sensor to operate in data collection mode.

This may need to wait for the August committee meeting

**Comment by ericthomasswenson** [comment]
The notes for Table A-1 are proposed to say:  (As shown in table A1 proposed additions draft)

| Note | Table A1 Column Title | Comments |
|-- | -- | --|
| 1 | SPN (MY) | Entries in Table A1 represent a subset of those SPs which are expected in a DM24 message from an HD OBD ECU. Additional SPs from those listed here are expected in DM24 responses. Query support for individual SPs provided in a DM24 response that are not shown in Table&nbsp;A1 shall be assessed, but plausible values are not defined for the data returned. SPs which appear in DM24 and that indicate data stream support shall not provide FFh&nbsp;(not available/not supported) or FEh&nbsp;(error) indicators. **They may provide FBh (special conditions) indicators.** &nbsp;The SPN column also identifies alternative content.&nbsp;Model years other than 2013 are shown in parentheses following SPN values.|

**Comment by ericthomasswenson** [comment]
Add

**_SP Data displays sent with the Special Conditions (FBh) indicators shall be accepted._**

at the end of footnote [26]

[26] Missing SPN support, as compared to Table A1, shall be determined for the data presented by DM24 in test 6.1.4. Here only SPNs provided in the DM24 data from test 6.1.4 need be evaluated. As given in (d) data from non-OBD ECUs may be flagged with a warning or an informational message. Data that does not meet Table A1 plausibility limits, or that does not meet broadcast period requirements, may be counted as present (passing), without additional warning or failure messages than those generated for the plausibility limits, provided that it is not sent using the SAE J1939-71 Error (FEh) or Not Available (FFh) Indicators.

**Comment by vmuthu2** [comment]
Please add PM sensor SPNs to it. SPN 7393 and SPN 5835 need to be added to this list.

**Comment by ericthomasswenson** [comment]
As written it’s a general principle…. And should be accepted for any SP including the omitted PM mass sensors, SPN 7393 and SPN 5835.

If Needed, we can add fail if FBh in Table A-1 Entries.  

It’s not worth the groups’ time to chase FBh sensor by sensor.  

There are more important issues for our limited funds.

The recommendation provided to Greg Gillham for J1939DA:

Please add the following note to the descriptions of SP 3217, 3227, 3256, 3266, 5835, 7393 7650, 7661, 7672, and 7683.  Replace any existing note with the same effect to reflect a common text.

When operating conditions do not permit physical measurement of the parameter, the value provided shall reflect the parameter specific indicator (i.e. FBh et. al.) defined in Table 1 of SAE J1939-71.  The not available or not requested indicator (i.e. FFh et. al.) shall not be used for temporary conditions like high humidity. The not available or not requested indicator (i.e. FFh et. al) indicates the SP is not supported.

**Comment by ericthomasswenson** [comment]
A more extensive list could include:
3216 3217 3221 3225 3226 3227 3231 3235
3255 3256 3260 3264 3265 3266 3270 3274
7649 7660 7661 7665 7670 7671 7682 7650
7654 7659 7672 7676 7681 7683 7687 7692
9177 9178
12754 12755 12750 12751

**Comment by ericthomasswenson** [comment]
This was expected for inclusion with Table A-1 changes.

**Comment by ericthomasswenson** [comment]
Implemented with Table A-1 content in 3.1.1.
