### ISSUE TITLE
Investigate Unknown Publisher notice in installer

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#991]
The installer provides an unknown publisher message.

keep anyway May work 

Investigate what may be done to define ETI as publisher.

**Comment by battjt** [comment]
Initial investigation shows that it's about $500/year to maintain a certificate.  We would need the certificate when we make a release.  The certificate would not need to be maintained if there are no releases being made.  Search for "EV Code Signing Certificates" for more information.

**Comment by ericthomasswenson** [comment]
Defer for next contract
