### ISSUE TITLE
Address DM21 mismatch: accept 1 minute difference between queries

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#992]
Address DM21 mismatch: accept 1 minute (1 bit state) difference between queries

14:07:00.8905 Destination Specific DM21 Request to Engine #1 (0) 
14:07:00.8951 18EA00F9 [3] 00 C1 00 (TX) 
14:07:00.8981 18C1F900 [8] 00 00 00 00 00 00 02 00 
DM21 from Engine #1 (0): [ 
 Distance Traveled While MIL is Activated:     0 km (0 mi) 
 Time Run by Engine While MIL is Activated:    0 minutes 
 Distance Since DTCs Cleared:                  0 km (0 mi) 
 Time Since DTCs Cleared:                      **_2 minutes_** 
] 
FAIL: 6.2.9.4.a - Difference compared to data received during global request from Engine #1 (0)

**Comment by ericthomasswenson** [comment]
Still … Need text proposal

**Comment by ericthomasswenson** [comment]
Work with #1257

**Comment by ericthomasswenson** [comment]
6.2.9.3	Actions2.	
a.	DS DM21 to each OBD ECU.
6.2.9.4	Fail Criteria2
a.	Fail if any difference compared to data received from global request.
i.	Allow 1 minute difference between responses for SPN 3296

**Comment by ericthomasswenson** [comment]
This may be worked prior to implementation in an MTask8 artifact.

**Comment by battjt** [comment]
Comment made on wrong issue.  disregard:
>PgnDefinition already has a isVariableBroadcast flag.  Development, verify that this flag is correctly intergpretted for the SPNs in question.  No DA parsing changes should be needed.

**Comment by ericthomasswenson** [comment]
The interpretation (implementation) will change as timing is to be ignored.
 
Best Wishes,

Eric Swenson
