### ISSUE TITLE
Failure and warning counts incorrect in 3.0.8

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#993]
Looks like when we fixed the timing count..
Failures:    81 
Warnings:    84 
Information: 0 
Incomplete:  0 
Timing:      2 
Passes:      167 
We broke the fail and warnings counts ...

Search for FAIL: says 27 found.
Joe reports 3 * 27 were in the log.

**Comment by vmuthu2** [comment]
J1939-84 Tool version 3.0.8 - 2021/05/10 10:33
Generated: 2021/05/10 16:04:35.9885
Log File Name: C:\Users\Vimal.Muthukumar\Desktop\Back_up\Working_Files\J1939-84\Official_PVE_1_Testing\MY2021\NewTool-P1286seq-132\Truck_2060_-84_May10.j1939-84

TEST SUMMARY REPORT
OUTCOME: 
Failures:    114
Warnings:    54
Information: 9
Incomplete:  0
Timing:      0
Passes:      1

Observed the same issue
