### ISSUE TITLE
Incorrect FAIL assessment for DM21 - SPN 3069, 3294, 3296

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#998]
New issue introduced with v 3.0.8.. Issue was not present in v3.0.7

DM21 reports correctly and all the SPNs are supported as expected.

15:22:51.5449 DS Request for PGN 49408 to Engine #1 (0) for SPNs 3069, 3294, 3296
15:22:51.5472 18EA00F9 [3] 00 C1 00 (TX)
15:22:51.5515 18C1F900 [8] 00 00 00 00 00 00 00 00
DM21 from Engine #1 (0): [
  Distance Traveled While MIL is Activated:     0 km (0 mi)
  Time Run by Engine While MIL is Activated:    0 minutes
  Distance Since DTCs Cleared:                  0 km (0 mi)
  Time Since DTCs Cleared:                      0 minutes
]
PGN 49408 with Supported SPNs 3069, 3294, 3296
15:22:51.5515 18C1F900 [8] 00 00 00 00 00 00 00 00
Found: DM21 from Engine #1 (0): [
  Distance Traveled While MIL is Activated:     0 km (0 mi)
  Time Run by Engine While MIL is Activated:    0 minutes
  Distance Since DTCs Cleared:                  0 km (0 mi)
  Time Since DTCs Cleared:                      0 minutes
]
FAIL: 6.1.26.6.a - SPN 3069 was received as NOT AVAILABLE from Engine #1 (0)

FAIL: 6.1.26.6.a - SPN 3294 was received as NOT AVAILABLE from Engine #1 (0)

FAIL: 6.1.26.6.a - SPN 3296 was received as NOT AVAILABLE from Engine #1 (0)

15:24:43.3463 DS Request for PGN 49408 to Engine #1 (0) for SPNs 3069, 3294, 3296
15:24:43.3504 18EA00F9 [3] 00 C1 00 (TX)
15:24:43.3586 18C1F900 [8] 00 00 00 00 00 00 01 00
DM21 from Engine #1 (0): [
  Distance Traveled While MIL is Activated:     0 km (0 mi)
  Time Run by Engine While MIL is Activated:    0 minutes
  Distance Since DTCs Cleared:                  0 km (0 mi)
  Time Since DTCs Cleared:                      1 minutes
]
PGN 49408 with Supported SPNs 3069, 3294, 3296
15:24:43.3586 18C1F900 [8] 00 00 00 00 00 00 01 00
Found: DM21 from Engine #1 (0): [
  Distance Traveled While MIL is Activated:     0 km (0 mi)
  Time Run by Engine While MIL is Activated:    0 minutes
  Distance Since DTCs Cleared:                  0 km (0 mi)
  Time Since DTCs Cleared:                      1 minutes
]
FAIL: 6.2.17.6.a - SPN 3069 was received as NOT AVAILABLE from Engine #1 (0)

FAIL: 6.2.17.6.a - SPN 3294 was received as NOT AVAILABLE from Engine #1 (0)

FAIL: 6.2.17.6.a - SPN 3296 was received as NOT AVAILABLE from Engine #1 (0)

**Comment by ericthomasswenson** [comment]
PGN 49408 with Supported SPNs 3069, 3294
14:04:45.5743 18C1F900 [8] 00 00 00 00 00 00 00 00
Found: DM21 from Engine #1 (0): [
  Distance Traveled While MIL is Activated:     0 km (0 mi)
  Time Run by Engine While MIL is Activated:    0 minutes
  Distance Since DTCs Cleared:                  0 km (0 mi)
  Time Since DTCs Cleared:                      0 minutes
]
FAIL: 6.1.26.6.a - SPN 3069 was received as NOT AVAILABLE from Engine #1 (0)

FAIL: 6.1.26.6.a - SPN 3294 was received as NOT AVAILABLE from Engine #1 (0)
